### ISSUE TITLE
Create a setting menu to enable the retroarch rewind feature on supported cores

### ISSUE THREAD

**Issue by nekomania** [recalbox/recalbox-os#100]
/recalbox/configs/retroarch/retroarchcustom.cfg
;rewind_enable = true

For example, the below settings is good for an overclocked RPi1. 
Peoples have a faster RPi2 might want to try turn on rewind on SNES or GBA.

REWIND
-----------------
NES           ON
SNES         OFF
GB/GBC     ON
GBA           OFF
SG1000     ON
SMS	          ON
GG             ON
Genesis      ON
PCEngine   ON

**Comment by hstampfl** [comment]
hmmm.. regarding the hotkey mapping, there is a free slot too.
Hotkey + LEFT is not used until yet

**Comment by substring** [comment]
done in 4.0.0
https://github.com/recalbox/recalbox-configgen/commit/ac288363786dfabb7867481ddf97b0cd5f2fdf7c
