### ISSUE TITLE
[4.0.0-beta3][FR] Impossibilité modifications de touche

### ISSUE THREAD

**Issue by Ozakiii** [recalbox/recalbox-os#1002]
Salut tout le monde ! 

Cela fait maintenant une semaine que je posede mon Raspberry Pi 3 couplé avec Recalbox et j'en suis assez satisfait de l'OS qui est tres bon que ce soit les menu et les fonctionalités de ce dernier. Cependant je rencontre un probleme assez contraignant au niveau des boutons sur la manette. En effet, je suis dans l'incapacité de modifié mes boutons sur ma manette Xbox 360 (Filaire) MAIS aussi sur ma manette PS4 (Dont je n'ai toujours pas trouvé comment il fallait faire pour la faire fonctionné en Bluethooth (Bien qu'il est un menu dédiée...)). Bien que je réalise la configuration en réasignant tout les boutons, ce dernier se bloque sur la configuration de base ! 

J'ai retenté plusieurs fois, mit ma manette en profil sur joueur 1 mais rien n'y fait, les boutons reste toujours sur la même configuration de base. (Qui est tres contraignante vu que le bouton pour quitté et sur le clavier...)

Es ce que quelqu'un aurais une solution à ce probleme ? Une configuration spécifique à faire au sein même de la configuration ? Ou un probleme du à la BETA ? 

Merci de vos réponse.

**Comment by paradadf** [comment]
S'il vous plaît, utilisez le forum pour les questions de soutien.
[Recalbox Forum](https://forum.recalbox.com/)
