### ISSUE TITLE
[4.0.0-beta1-4] Wifi cant connect, very slow or disconnects if USB Bluetooth dongle is present

### ISSUE THREAD

**Issue by Duglim** [recalbox/recalbox-os#1003]
I had Wifi connectivity issues since month, when Wifi was not able to connect or disconnects after a few slow minutes of data transfer.

I now figured out, all issues are gone, if I unplug my external USB Bluetooth dongle (normally used to connect two SFC30 gamepads) and restart the Recalbox. 

This happens on two Raspberry 3 boards with internal Wifi and external Bluetooth 4.0 dongles.

Potential causes I can imagine:
- USB dongle has software conflicts with RPi3 Wifi module
- USB dongles wireless signal disturbs the RPi3s Wifi signal

Any idea how to get both working simultaineous?

Thx and greetings, 
Dan

**Comment by Murphyprecht** [comment]
Hey Dan, just throwing it out there.
What kinda charge is your supply capable of delivering as a BT dongle and WiFi dongle consume more power than just one ;)

**Comment by Duglim** [comment]
Hi, it's a 3A supply.

Von meinem iPhone gesendet

**Comment by sechsbug** [comment]
This happens because Bluetooth and WiFi send on the same frequency. 
Set up a second WiFi-Network in the 5GHz-frequency and it should work.

**Comment by substring** [comment]
May i suggest that this is no recalbox issue as itself, and therefore may be closed ? Please join the forum if you'd like to discuss more about this topic :)

**Comment by Duglim** [comment]
Sure. If this is natural behaviour of BT/Wifi frequency disturbing each other, lets close this one.
