### ISSUE TITLE
[4.0.0-beta4][CORE] No NDS or PSP support

### ISSUE THREAD

**Issue by willstdueswissen** [recalbox/recalbox-os#1004]
### What happened
    - no core avaible for nds or psp in the gui
### What should have happened
    - it should be avaible :D
### Enumerate your devices
    - rpi2
### How to reproduce the bug
    - simple boot your recalbox rpi

### NDS
    - i don't know how to support
### PSP
    - should work

~~### List of roms not auto update in the gui~~
    ~~- also no update button avaible?~~

**Comment by substring** [comment]
Expect psp for release 4.1

NDS is sluggish on pi, it won't happen
