### ISSUE TITLE
[4.1] Add a checksum process on .tar.xz files before upgrading system

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-os#1015]

**Comment by digitalLumberjack** [comment]
I'm on it

**Comment by nadenislamarre** [comment]
are you sure that xz has not already an internal checksum like gzip ?

**Comment by nadenislamarre** [comment]
if the tarball is wrong, then unxz will fail.

not that .tar itself doesn't include any check.


http://tukaani.org/xz/xz-file-format.txt

3.1.7. CRC32

        The CRC32 is calculated over everything in the Block Header
        field except the CRC32 field itself. It is stored as an
        unsigned 32-bit little endian integer. If the calculated
        value does not match the stored one, the decoder MUST indicate
        an error.


2016-08-14 9:35 GMT+02:00 Nicolas Adenis-Lamarre <
nicolas.adenis.lamarre@gmail.com>:

> are you sure that xz has not already an internal checksum like gzip ?
>

**Comment by digitalLumberjack** [comment]
yep but we need logs about that, informations in the user interface, and space left check.

**Comment by nadenislamarre** [comment]
@digitalLumberjack is it done or to do ?
squashfs will remove the need for that.

**Comment by substring** [comment]
done in https://github.com/recalbox/recalbox-buildroot/pull/634
