### ISSUE TITLE
GLupeN64: mupen64plus + RSP-HLE + GLideN64 + libretro

### ISSUE THREAD

**Issue by paradadf** [recalbox/recalbox-os#1017]
If you haven't read about it, I would like to bring it to your attention. This might be an interesting core to add, much more updated than de mupen64plus libretro core, and still a libretro port!
But better information can be found here:
https://github.com/loganmc10/GLupeN64

**Comment by rockaddicted** [comment]
Yep I'm following this repository since his creation. I'll test it in the next weeks and add it to 4.1 if tests are ok.

**Comment by paradadf** [comment]
Closing because of https://github.com/recalbox/recalbox-buildroot/pull/442
Thanks!
