### ISSUE TITLE
Downloadable file hash

### ISSUE THREAD

**Issue by auzias** [recalbox/recalbox-os#1023]
It would be great if you could add md5 or sha*  hash of the downloadable files, a.k.a. releases file.

**Comment by digitalLumberjack** [comment]
I can add it but as zip contains checksums of each files internally, if you can unzip, you are all good :)

Is it for an other reason ?

**Comment by auzias** [comment]
Yes: I'ld rather check the `.zip`̀ file once-for-all-files rather than write a loop to check each files. Adding it to the released posts would be great so I don't have to unzip an _untrustable_ file.

What do you think @rockaddicted?

**Comment by digitalLumberjack** [comment]
The https of github adds the "trusted" part of the file, as you are sur it cames from our github. 
So if you unzip the file just after you will be sure to have the good file from the good place with the good content. Effectivly the issue can be if you move the file or give it to someone you could do your own checksum to be sure the file is still the same.

What do you think @rockaddicted?

**Comment by digitalLumberjack** [comment]
I've added the sha1sum in the release process as i was migrating the servers. Will be available in the next release.

**Comment by auzias** [comment]
Great! Thanks! :)
