### ISSUE TITLE
4.1.0 Recalbox Cannot scrap Sega SG-1000 and Dreamcast 

### ISSUE THREAD

**Issue by sylvain-perez** [recalbox/recalbox-os#1024]
What happened

Cannot scrap for Sega SG-1000 and Dreamcast systems.
Even if systems appears in the main menu and we can play games of the two systems, they don't show up in the Scrap menu.

What should have happened

SG-1000 and Dreamcast must appear in the System selection menu under the Scrap menu.

Enumerate your devices

Odroid XU4

How to reproduce the bug

Add an SG -1000 rom or Dreamcast rom, update gamelist then go to Scrap menu and see that neither SG-1000 nor Dreamcast appears in the list of System to scrap.

Needs to be tested on 4.0.0 beta4.
 @sylvain-perez

**Comment by Supernature2k** [comment]
So as I am working on platform currently, I checked and found:

`<platform>ignore</platform>`

For Dreamcast and SG-1000 in es_systems.cfg

This tag tells ES that these platform should not appear in Scrapper.

https://github.com/recalbox/recalbox-buildroot/blob/rb-4.1.X/board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_systems.cfg#L187

Problem is there for SG-1000 in 4.0

@digitalLumberjack @rockaddicted @substring: I will fix this by puting the correct platform according to my PR for emulationstation but should I do 2 PR? 1 for 4.0 with SG-1000 and 1 for 4.1 with SG-1000 and Dreamcast?

**Comment by digitalLumberjack** [comment]
You can do 1 or 2 pr it's as you want.

**Comment by substring** [comment]
fixer with https://github.com/recalbox/recalbox-buildroot/commit/b3cda3009e80b2194158c50bcf890ed9d45782f5
