### ISSUE TITLE
[Feature Request] Please add suport for Streets of Rage Remake

### ISSUE THREAD

**Issue by silvio-giuliani** [recalbox/recalbox-os#1035]
A while ago a user ported the excelent Streets of Rage Remake to a retropie build.
I would really appreciate to able to play it on recalbox.
Links for further reading:

Official Streets of Rage Remake website:
https://street-rage-remake.en.uptodown.com/windows

Blog + Github:
https://blog.adafruit.com/2016/04/08/how-to-run-streets-of-rage-remake-on-raspberry-pi-piday-raspberrypi-raspberry_pi/

Tks again

**Comment by rockaddicted** [comment]
Hi, can you check this issue, and if this game is not mentioned in, you can add it.
https://github.com/recalbox/recalbox-os/issues/358
Ports native games / game engine in recalbox will be done in a next release.
So I close this one.
