### ISSUE TITLE
[?.?][KODI] KODI stops reading or jumps in time in files

### ISSUE THREAD

**Issue by hugoheitz** [recalbox/recalbox-os#1038]
### What happened

When I watch an episode or a movie, sometimes KODI stops reading or jumps in time while reading files.
### What should have happened

KODI should read files normally.
### Enumerate your devices

2 USB controllers
1 remote video USB controller
1 USB keyboard
### How to reproduce the bug

Play video files on kodi.
Sometimes everything is OK. sometimes not.

**Comment by nadenislamarre** [comment]
@hugoheitz is it local files or streamed files ?
never got that issue on any architecture.
is there some other feedback ?
i suggest to close this issue while it's not a recalbox issue and seems to be specific to a source.

**Comment by hugoheitz** [comment]
Hi,
It is not local files, it is files streamed through dlna from a nas device. I did not test recently if things have improved since the upgrader to à newer version of kodi ( isengard ).

**Comment by nadenislamarre** [comment]
ok. it's too specific so that we check the bugs on that on recalbox.
however, you should retest with recalbox 4.1 while kodi was upgraded to the last version.
