### ISSUE TITLE
4.0.0-beta5 GPIO issue with special commands

### ISSUE THREAD

**Issue by agli14** [recalbox/recalbox-os#1039]
I'm not able to execute any special commands like HK + Start or HK + B or Select + Start ....
It seems that with GPIO each command works alone but it's not possible to make any combination with multiple.
I have no problem with a USB controller.
Is someone have the same issue ?

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
