### ISSUE TITLE
Error compiling xboxdrv

### ISSUE THREAD

**Issue by Gamephantom** [recalbox/recalbox-os#1042]
### What happened
Error with xboxdrv

### What should have happened
It should have compiled xboxdrv

### How to reproduce the bug
Activate xboxdrv

### Error
src/dbus_subsystem.cpp: In member function »void DBusSubsystem::register_controller_slots(const std::vector<boost::shared_ptr<ControllerSlot> >&)«:
src/dbus_subsystem.cpp:98:65: Error: »dbus_glib_xboxdrv_controller_object_info« is not declared in this scope.
     dbus_g_object_type_install_info(XBOXDRV_TYPE_G_CONTROLLER, &dbus_glib_xboxdrv_controller_object_info);
                                                                 ^
scons: *** [src/dbus_subsystem.o] Error 1
scons: building terminated because of errors.

**Comment by substring** [comment]
hey @Gamephantom 
I compiled a full recalbox 2 days ago, the build bot is working well and doesn't report any sort of compilation problem. So I guess the problem is on your side.

**Comment by MikaXII** [comment]
Did you install xboxdrv on your host ?
