### ISSUE TITLE
[4.1][S12Populateshare] Make sure all new folders from 4.1 are created during a 4.0 -> 4.1 upgrade

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-os#1043]
Here are the folders that change :
- [ ] roms (added a few systems)
- [ ] ~/configs
- [ ] new lr-mame2003 folders
- [ ] overlays folder (simply needs to be of the roms/\* subfolders, even if it's just for retroarch ?)

For those who have the right, edit my post and add folders

**Comment by substring** [comment]
Looks like this is working :
```shell
for DIR in roms roms/mame/mame2003
do
    [ ! -e "$OUT""/""$DIR" ] && mkdir "$OUT""/""$DIR"
    find "$IN""/""$DIR" -mindepth 1 -maxdepth 1 -type d |
        while read SUBDIR
        do
            BNAME=$(basename "$SUBDIR")
            TDIR="$OUT""/""$DIR""/""$BNAME"
            if test ! -e "$TDIR" # ASSUME THAT PARENTS ARE LISTED BEFORE CHILDREN
            then
                cp -r "$SUBDIR" "$TDIR"
            fi
        done
done
```

**Comment by substring** [comment]
@nadenislamarre @rockaddicted @digitalLumberjack your opinion is welcome
@digitalLumberjack knowing that overlays need the same tree structure as roms, but are only handled by retroarch, do you prefer :
- a full blind software clone of the roms subfolder (just the systems, don't need what's inside), so even non retraorch systems have a folder
- add every overlay-able system in fsoverlay ? which means upgrade this one too when a new retroarch core is added
- any other idea ?

**Comment by benutzer193** [comment]
Why do you add new folders manually, is there a problem populating all available folder found in share_init?

something like:
    
    for DIR in find $IN -type d #optional: -not -path "/path/to/directory/that/has/to/be/excluded"
    do
        [[ ! -d $OUT/$DIR ]] && mkdir $OUT/$DIR
    done

**Comment by substring** [comment]
@benutzer193 I guess you're missing a few points :
- it's not only about creating a folder, it's also copying it's content (roms -> system with the readme's, eventually some subfolders), hence `cp -r` and not only `mkdir`
- your method works for only one path at once, whereas with a for, we can specify several paths
- sometimes we don't want to copy some parts. Don't ask me why, it's what the comments say
- we don't want some trees to be copied. Ok we can exclude some parts with your method
- your method just checks the existence of folders, not files inside, nor the subfolders structure

Have you read the full S12 ? :)

**Comment by benutzer193** [comment]
yeah I read the full S12, but haven't found a comment saying not all directories are allowed to be in share.

My question wasn't directed only at your suggestion, but at S12 in general.
My idea was to handle folders the way I suggested at the beginning of S12 and then automate the process for files in folders where there are no exceptions, meaning just copy them if not available.
After that handle the remaining files manually.

**Comment by substring** [comment]
@benutzer193 just remembered : we don't copy the .emulationstation folder, it would make upgrades a real mess + wasted space

**Comment by benutzer193** [comment]
Ah okay, that makes sense of course.

**Comment by substring** [comment]
```
for DIR in roms roms/mame/mame2003 system/configs
do
    [ ! -e "$OUT""/""$DIR" ] && mkdir "$OUT""/""$DIR"
    find "$IN""/""$DIR" -mindepth 1 -maxdepth 1 -type d |
        while read SUBDIR
        do
            BNAME=$(basename "$SUBDIR")
            TDIR="$OUT""/""$DIR""/""$BNAME"
            if test ! -e "$TDIR" # ASSUME THAT PARENTS ARE LISTED BEFORE CHILDREN
            then
                cp -r "$SUBDIR" "$TDIR"
            fi
        done
done
```

**Comment by nadenislamarre** [comment]
@substring can we close ? or what is to do ?

**Comment by substring** [comment]
@nadenislamarre we don't close as no one even discussed it

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0
