### ISSUE TITLE
[4.0.0-build-170][ES] Cannot use 2 wii classic controllers with mayflash usb adapter

### ISSUE THREAD

**Issue by sinedied** [recalbox/recalbox-os#1044]
### What happened

When trying to use 2 wii classic controllers on 1 mayflash usb adapter, recalbox only detect 1 gamepad, with buttons from both controllers.

### What should have happened

2 gamepads should be detected and configurable individually.

### Enumerate your devices

- rPI 3
- Mayflash wii classic usb adapter
- 2x Wii classic controller

### How to reproduce the bug

Connect 2 wii classic controllers on 1 mayflash usb adapter and try to use them as 2 separate controllers

**Comment by Laddyacris** [comment]
Hello
can you post a link to mayflash wii ?
Connect your gamepads.
and can you upload archive with this command line in ssh : `/recalbox/scripts/recalbox-support.sh`

**Comment by sinedied** [comment]
It's this one: http://www.mayflash.com/products/pcusb/pc045.html
I'll upload the archive asap, I'm not at home until monday.

**Comment by substring** [comment]
doh ... looks like some usb_quirks stuff
@sinedied please do what acris suggested so that we can try a fix

**Comment by sinedied** [comment]
Here we go, sorry for the delay:

[recalbox-support-20160918195523.tar.gz](https://github.com/recalbox/recalbox-os/files/478874/recalbox-support-20160918195523.tar.gz)

**Comment by sinedied** [comment]
Do you need more info to investigate the issue?
Can I provide additional help in any way?

**Comment by substring** [comment]
oooops looks like we forgot you.

You need to `mount -o remount, rw /boot` then add `usbhid.quirks=0x925:0x3E8:0x040` to `cmdline.txt`

**Comment by sinedied** [comment]
@substring It works! Thanks a lot! Just out of curiosity, how did you find the fix?
I plan to buy a 2nd adapter to get 4 pads working, will this fix also work with the 2nd adapter?

**Comment by substring** [comment]
I guess it should work, yes.

How do i know ? Rule of thumb : 2 pads on 1 single usb ports usually requires such trick. It works, we will add it natively on 4.1
