### ISSUE TITLE
[4.0.0-beta5][ES] Screen gets cut off in games with 1366x768 resolution TV's and monitors.

### ISSUE THREAD

**Issue by gsjkly123** [recalbox/recalbox-os#1048]
When launching/playing a game the top and bottom of the screen get cut off a little on 1366x768 resolution TV's and monitors.

It should fit or a least be a little smaller so you can see the entire game.

I'm using a 32 in. 1366x768 resolution flat screen TV, with a wired keyboard, wireless mouse, and a Wired Xbox One controller.

To see the bug simply launch a game on a 1366x768 resolution TV or monitor, the screen should cut off.

**Comment by Voljega** [comment]
Please use the forum if you need help with a configuration problem, this is not a bug at all.

Now you can either :
- configure your tv correctly to display the whole image (usually a parameter like zoom 1:1)
- use the overscan parameters in Recalbox, see the wiki on this github

**Comment by substring** [comment]
As kindly asked, please make a forum thread. Issues are for development bugs tracking
