### ISSUE TITLE
Gasia PS3 bluetooth controller problem in Recalbox 4.0.0

### ISSUE THREAD

**Issue by richi115** [recalbox/recalbox-os#1050]
Hi,
I'm testing 4.0.0-beta5 and PS3 bluetooth controller using gasia drivers and doesn't seem to work, this is the log I'm getting. I've made a fresh install two times and only changed recalbox.conf:

controllers.ps3.driver=gasia

this worked correctly in the version 3.3.0-beta17 making this same procedure (fresh install and only chaning that recalbox.conf line)

Sep 10 19:04:11 RECALBOX user.info kernel: [  476.582146] usb 1-1.4: new full-speed USB device number 5 using dwc_otg
Sep 10 19:04:12 RECALBOX user.info kernel: [  476.685100] usb 1-1.4: New USB device found, idVendor=054c, idProduct=0268
Sep 10 19:04:12 RECALBOX user.info kernel: [  476.685124] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 10 19:04:12 RECALBOX user.info kernel: [  476.685138] usb 1-1.4: Product: PS(R) Gamepad
Sep 10 19:04:12 RECALBOX user.info kernel: [  476.685149] usb 1-1.4: Manufacturer: Gasia Co.,Ltd
Sep 10 19:06:41 RECALBOX user.info kernel: [  626.122692] usb 1-1.4: USB disconnect, device number 5
Sep 10 19:07:07 RECALBOX daemon.err bluetoothd[283]: Refusing input device connect: No such file or directory (2)
Sep 10 19:07:07 RECALBOX daemon.warn bluetoothd[283]: Can't find device agent
Sep 10 19:07:07 RECALBOX daemon.err bluetoothd[283]: input: authorization for 00:1A:7D:DA:71:07 failed: Operation not permitted (-1)
Sep 10 19:09:42 RECALBOX daemon.err bluetoothd[283]: Refusing input device connect: No such file or directory (2)
Sep 10 19:09:42 RECALBOX daemon.warn bluetoothd[283]: Can't find device agent
Sep 10 19:09:42 RECALBOX daemon.err bluetoothd[283]: input: authorization for 00:1A:7D:DA:71:07 failed: Operation not permitted (-1)

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
