### ISSUE TITLE
[4.0.0-beta5][moonlight] Logitech F710 mapped incorrectly (with proposed fix!)

### ISSUE THREAD

**Issue by adamries** [recalbox/recalbox-os#1051]
I have two Logitech F710 but mostly use only the first one.
I mapped the F710 completely and correctly using recalbox's built-in controller setup.
Result: when using moonlight, the right analog stick doesn't work correctly: only the vertical axis can be used, the horizontal axis is ignored. This happened in both games that I tried: Tomb Raider (2013) and Half-Life 2.

Here's the original share/system/configs/moonlight/mappingP1.conf as generated by recalbox:
```
# Device name = Logitech Gamepad F710
# SDL2 GUID   = 030000006d0400001fc2000005030000
# Event path  = /dev/input/event0
btn_west = 307
btn_east = 305
abs_dpad_y = 17
abs_dpad_x = 16
reverse_dpad_y = false
reverse_dpad_x = false
abs_ry = 4
abs_deadzone = 4
btn_south = 304
btn_start = 315
reverse_ry = true
reverse_rx = false
btn_mode = 316
abs_x = 0
abs_y = 1
reverse_x = false
reverse_y = true
btn_select = 314
btn_thumbl = 317
btn_tr = 311
btn_north = 308
btn_tl = 310
btn_thumbr = 318
abs_rz = 5
abs_z = 2
```

Here's a fix: I replaced all the configuration directives by the ones found in https://github.com/irtimmer/moonlight-embedded/blob/master/mappings/xbox360.conf
Do note that the xbox360.conf has more configuration directives than the one generated by recalbox, this could explain why at least one axis isn't working as it should.

That's it. As far as I can tell, the controls now work just fine and I can control the camera in TR and HL2.

**Comment by substring** [comment]
I saw you made a forum topic, i'm closing and answering you there

**Comment by substring** [comment]
typo in configen on joystick2left
Solved via https://github.com/recalbox/recalbox-configgen/pull/86
