### ISSUE TITLE
[4.0.0-beta5][Gamecon Driver] Upgrade from 1.0 to 1.2

### ISSUE THREAD

**Issue by widgetfonda** [recalbox/recalbox-os#1057]
Hi !

I have some issues with 2 PSX controllers wired on GPIO with Gamecon Driver v1.0.

The v1.2 of the Gamecon driver is out, and it seems to fix psx controller issues.

Can you upgrade to 1.2 in the next beta or in the next 4.1 experimental build ?

Thanks

[Forum topic link](https://forum.recalbox.com/topic/4034/gpio-power-led-ps1-controller)

**Comment by substring** [comment]
Just read your topic on the forum.  Could you provide a link to the source code please ?

**Comment by widgetfonda** [comment]
Thank you ! 
https://www.niksula.hut.fi/~mhiienka/Rpi/ 

But I don't know if the source code is there...

**Comment by substring** [comment]
the source in in the .deb
