### ISSUE TITLE
New chinese ps3 controller issues

### ISSUE THREAD

**Issue by globalgvl** [recalbox/recalbox-os#1060]
hello everybody !

I get some troubles with controller setup ! Help me :) thank you
---
Please fill the following form :

### What happened
I have 2 chinese BT clone controller identified as Shanwan from Recalbox and I have 4 issues with them.
1. I did not success to pair them with BT but this is not an emergency atm.

2. When i plug them with usb they are permanently vibrating. A bit boring when you play... I would like to make it stop.

3. I can pair each of these but not at the same time (each time I plug a second one, the first controller is disabled) they are both identifier as js0 whatever the usb slot.

4. The detection work only the first time so if I plug controller 1, I can use it, when I plug controller 2, I can use c2 but not c1 anymore. If I deplug and replug c2 or c1 I can't use any of these anymore and need to restart my rasp.

### Enumerate your Devices 
2 redgo wireless ps3 controller 
Rasp3 model b

**Comment by Laddyacris** [comment]
Hello
do you modify recalbox.conf to use shanwan driver ?
https://github.com/recalbox/recalbox-os/wiki/recalbox.conf-%28EN%29
```
## Please enable only one of these
# -------------- D1 - PS3 Controllers ------------ #
##Enable PS3 controllers support
controllers.ps3.enabled=1
## Choose an driver between official, shanwan and gasia if you have dualshock clones (official,shanwan,gasia)
controllers.ps3.driver=shanwan
```

**Comment by substring** [comment]
Hey @globalgvl 
We use github to trak issues, that's a dev tool. Could you please join the forum (you can use your github account) to ask for support ?
