### ISSUE TITLE
If possible add support for a Commodore C16 Plus4 emulator such as YAPE or VICE 

### ISSUE THREAD

**Issue by Schattenreich** [recalbox/recalbox-os#1063]
I know in 4.1.0 support for Commodore C64 will come - very nice!!!
After that:
If possible (please) add support for a Commodore C16 Plus4 emulator such as YAPE or VICE
Thank you...

**Comment by Nokturn** [comment]
I think they will use vice.

**Comment by substring** [comment]
It's vice, yes

**Comment by substring** [comment]
#452
