### ISSUE TITLE
[4.0.0 Beta 170][ES] Scraping titles with punctuation doesn't work

### ISSUE THREAD

**Issue by Dagnillo** [recalbox/recalbox-os#1072]
Scraping games like B.O.B., Eek! The Cat, and F-Zero (to name a few) brings up no results even though the titles are an exact match to their TGDB counterparts.  I can find no way to bring up a match.

**Comment by rockaddicted** [comment]
added a scraper using screenscraper DB, this kind of games, if are correctly named (based on romset no-intro) are now scrapped.

https://github.com/recalbox/recalbox-emulationstation/pull/159
