### ISSUE TITLE
Access to other GNU/Linux computer from recalbox

### ISSUE THREAD

**Issue by cpcbegin** [recalbox/recalbox-os#1073]
Would be possible add some icon to open another GNU/Linux computer via ssh, p.e.:
ssh -XC miuser@mipowerfullpc.local gnome-flashback
Or open a Terminal 
Or use VNC

**Comment by substring** [comment]
This is not the aim of recalbox, nor does it have X + a window manager. So that won't happen :)

**Comment by cpcbegin** [comment]
At least one Terminal?

**Comment by digitalLumberjack** [comment]
ssh is not enough ?

**Comment by cpcbegin** [comment]
But I'd like to connect via ssh from recalbox raspberry to another PC Linux...

**Comment by substring** [comment]
You can do it ! Genuine ssh text mode !
