### ISSUE TITLE
[4.0.0-beta5][ES] Xarcade tankstick stops working after first boot

### ISSUE THREAD

**Issue by BestUsername** [recalbox/recalbox-os#1075]
### What happened
On first boot, the xarcade tank stick worked perfectly. Including the trackball in some mame games!!!
After rebooting, the buttons had a bad mapping. It's the same result as if I disable the xarcade setting in the configuration file.

### What should have happened
I would hope that the controller would have the same mappings after the first boot.

### Enumerate your devices:
Raspberry pi 3
A usb dongle for a rii keyboard/mouse  controller (backup for when tankstick isn't usable)
Keyboard and mouse usb connectors for an x-arcade tankstick (two players with centre trackball)

When unplugging and plugging the keyboard connector, this is the tail of dmesg:

usb 1-1.3: USB disconnect, device number 7
usb 1-1.3: new low-speed USB device number 8 using dwc_otg
usb 1-1.3: New USB device found, idVendor=aa55, idProduct=0101
usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
usb 1-1.3: Product: X-Arcade
usb 1-1.3: Manufacturer: XGaming
input: XGaming X-Arcade as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:AA55:0101.0008/input/input7
hid-generic 0003:AA55:0101.0008: input,hidraw3: USB HID v1.10 Keyboard [XGaming X-Arcade] on usb-3f980000.usb-1.3/input0
input: XGaming X-Arcade as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:AA55:0101.0009/input/input8
hid-generic 0003:AA55:0101.0009: input,hidraw4: USB HID v1.10 Keyboard [XGaming X-Arcade] on usb-3f980000.usb-1.3/input1

So it's being detected properly.

**Comment by substring** [comment]
Hi,

The tankstick is somehow quite bothering as it takes about 7s for it to "boot". One solution is to create a `~/custom.sh`, start xarcade2joystick from there. Make sure your file is chmoded 744

**Comment by BestUsername** [comment]
That worked perfectly! Thanks!!!

**Comment by Thesundreamer** [comment]
substring, I am not able to make the tankstick to be rocognized.  I am new to recalbox can you pleade jhelp me ?
