### ISSUE TITLE
Road of the sword(mame) seems available in the recalbox excel file however I always jump to main menu once launge the game.

### ISSUE THREAD

**Issue by dmsbfamily** [recalbox/recalbox-os#1077]
### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

**Comment by Voljega** [comment]
Please don't you use the github bug tracker to ask for support, especially in such a poor form.
If you have any question use the forum

**Comment by dmsbfamily** [comment]
well noted
