### ISSUE TITLE
[New Core] Minibrowser

### ISSUE THREAD

**Issue by paradadf** [recalbox/recalbox-os#1078]
Hi, I'm opening this issue to suggest this web browser to be added. Maybe it is something you think that shouldn't be part of recalbox, and then it is just a reference discussion for the future. I know, I'd like to have it :D

https://github.com/libretro/minibrowser

**Comment by cpcbegin** [comment]
A web browser would be very useful.

**Comment by nadenislamarre** [comment]
a browser is not compatible with the release frequency of recalbox.
moreover, i see no browser package in buildroot.
i suggest to close this issue.
