### ISSUE TITLE
[4.0.0-beta5] Ultra slim Rii not detected

### ISSUE THREAD

**Issue by aranud87** [recalbox/recalbox-os#1079]
Hi,

In first sorry for bad english (i am french).
i have buy this keyboard : http://www.kubii.fr/peripheriques-usb-rapsberry-pi/681-mini-clavier-ultra-slim-rii-6952917712009.html

I have a Raspberry 3 andrecalboxOS 4.0.0-beta5
The keyboard (i know bluetooth is not supported yet) not detected with the linnk too :/

Thank you

**Comment by substring** [comment]
Hey !

Please mke a forum post for support requests. But i think this keyboard may just not work with linux

**Comment by Laddyacris** [comment]
Les claviers ont leur propre dongle livré, Il faut l'utiliser.
