### ISSUE TITLE
Outdated changelog in RECOVERY filesystem.

### ISSUE THREAD

**Issue by Yamakaky** [recalbox/recalbox-os#108]
Last reported release is in 2014.

**Comment by nadenislamarre** [comment]
@substring can i close ?

**Comment by Yamakaky** [comment]
I don't know, is it solved? I haven't used recalbox in a while.

**Comment by nadenislamarre** [comment]
but what is supposed to be fixed ? i dont understand the object of the issue

**Comment by substring** [comment]
Me neither. But the issue looks even more oitdated than any changelog ;)
