### ISSUE TITLE
[4.0.0] 5Moonlight black screen

### ISSUE THREAD

**Issue by Stormbring3r** [recalbox/recalbox-os#1080]
I've got an issue with the moonlight streaming.
The sound and the inputs are streamed well, but there is no image, just a black screen with the recalbox logo

Everything work well on the computer

RPI3
Computer with GTX 780  - GEforce experience V3.0

**Comment by Laddyacris** [comment]
Hello
do you have geforce 3.0.7 ?

**Comment by Stormbring3r** [comment]
Yes Geforce3.0.7 . Thank you.
 So, my setting is clean :D.

**Comment by substring** [comment]
solved by now on the unstable branch

**Comment by noxx2015** [comment]
Habe the same Problem
Herr the sound a See a black screen with a recalbox Logo in the upper side.
Usw RB 4.0 final

**Comment by noxx2015** [comment]
Use RB 4.00 final

**Comment by noxx2015** [comment]
Moonlight on Android Works

**Comment by Laddyacris** [comment]
You need to downgrade geforce experience.
