### ISSUE TITLE
[4.1][libretro cores] Change the platform to rpi3 when existing ...

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-os#1081]
and eventually bump to a more recent commit :
- blueMSX : https://github.com/libretro/blueMSX-libretro/blob/e9b81fd80c4857936efc4e0599d49759d804c9b0/Makefile.libretro#L65
- gambatte : https://github.com/libretro/gambatte-libretro/blob/d5af1d7c4b339deab9e9f6fa999b5af3a96ca842/Makefile.libretro#L191
- prosystems : https://github.com/libretro/prosystem-libretro/blob/feda5b4c529c6efd6093afcafe8c99aac9c6db62/Makefile#L163
- stella : https://github.com/libretro/stella-libretro/blob/82d6e59c4dc49128a68bde6393874862dbc741f1/Makefile#L178
- nxengine https://github.com/libretro/nxengine-libretro/blob/0b36ae33e2a789036eb836b581296e1d7d5d7fa6/Makefile#L188
- fuse : https://github.com/libretro/fuse-libretro/blob/a5b53624993ee549343378cd56a2fee64fbe2d19/Makefile.libretro#L119
  beetle-lynx : https://github.com/libretro/beetle-lynx-libretro/blob/c2cc95ebf8166ef087361445fadeafbacc0df1a5/Makefile#L173
- mame2003 : https://github.com/libretro/mame2003-libretro/blob/dbf150383654c7852c5687333a94cd6c591c5272/Makefile#L113
- mupen64 (even if we don't use it yet) : https://github.com/libretro/mupen64plus-libretro/blob/c4833685a100c99a7a9c54cf199be24fded46ef1/Makefile#L122
- fba : https://github.com/libretro/fbalpha/blob/cd04ce06635c46146863c1f718ffe2c2c56a3ea2/makefile.libretro#L205

**Comment by paradadf** [comment]
*SNES9x Next is now called SNES9x 2010:
https://github.com/libretro/snes9x2010/blob/master/Makefile.libretro#L244
