### ISSUE TITLE
[Feature Request][ES] Option to Input TheGamesDB Game ID #

### ISSUE THREAD

**Issue by Dagnillo** [recalbox/recalbox-os#1082]
With the various issues that exist with the scraper (and scraper utilities) it would be greatly beneficial to add this option for those truly stubborn games.  Inputting the game ID points the Scraper directly to the appropriate game and leaves no room for error.

**Comment by paradadf** [comment]
You might want to take a look at my previous post: https://github.com/recalbox/recalbox-os/issues/938

**Comment by Dagnillo** [comment]
Ahh I see why I didn't find it, with the abbreviations.  My apologies. 

However I disagree with the assessment. Existing methods of IDing games are incomplete and imperfect.  There will always be games that slip through.  I'd much rather type a number in than have to download the artwork, resize it, then cut and paste game info for every instance.  I know someone who has implemented this into their front end, maybe I will consult with them on the issue.

**Comment by substring** [comment]
@rockaddicted is this one still needed as we've added a new scrapper in 4.1 ?

**Comment by rockaddicted** [comment]
This new scraper, base on screenscraper DB is using the game's name to find it.

But the DB is very clean, so from the moment that the game is correctly named (using a no-intro roms's name), and the game is present in the DB (if don't, screenscraper is a community database, so everyone can add informations), scraper won't return wrong positives results.

So for me, can be closed.

Next step ... a scraper based on rom's hashing
