### ISSUE TITLE
我的recalbox  树莓派3 接入1440的thinkvision 没有图像显示，但是可以显示引导画面

### ISSUE THREAD

**Issue by leonda2008** [recalbox/recalbox-os#1083]
### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

**Comment by substring** [comment]
Hi

Could you speak english ? We can't help you otherwise

**Comment by leonda2008** [comment]
My raspberry pie 3 installed recalbox does not display images, but can display the screen when pressing shift. The display is 1440 resolution, 1080 at home can be normal display, but in my office 1440 resolution is not displayed.

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)

Please read first https://github.com/recalbox/recalbox-os/wiki/Video-configuration-detailled-%28EN%29
