### ISSUE TITLE
 [4.0.0-beta5][FR] mapping touches n64 & power switch

### ISSUE THREAD

**Issue by Moutonlucide** [recalbox/recalbox-os#1092]
Bonjour et félicitations pour ce projet excellent.
C'est la première fois que je poste ici pour apporter ma contribution, je ne sais pas si je suis au bon endroit.

Pour signaler que le mapping des touches ne fonctionne pas avec les jeux n64
Et aussi pour prévenir quand on utilise le switch sur les GPIO 5&6 pour arrêter via un bouton, cela ne sauvegarde pas (favoris, touches etc)) comme si on atteignait via le menu.

Voila, espérant apporter mon aide, et en espérant voir une release bientôt. hehe. bye et bon courage

**Comment by Moutonlucide** [comment]
je précise que les touches n64 fonctionnent pas une manette, mais pas si on utilise les boutons dans une borne d'arcade branchés en usb. ça fonctionne pas tous les jeux, sauf n64

**Comment by substring** [comment]
du mal à comprendre ce que tu dis ...

le mapping de la N64 marche. Le seul truc qui ne marche pas avec c'est avoir les pads dans le meme ordre que sur ES.
