### ISSUE TITLE
PI 3 Freeze error with a GBA game

### ISSUE THREAD

**Issue by Arno77du42** [recalbox/recalbox-os#1093]
Hello,

Kuru kuru kururin, a GBA Game, freeze the system after 2 minutes of playing.
The game should have continued but it stop and it need to shut down the systhem to restart.
The problem is the same whatever the rom of kuru kuru kurin is with or without libreto.

In order to verify the bug problem, you just have to launch this gba game and wait 2 minutes of playing before it freeze   

Sorry for my bad English, i'm french

**Comment by Laddyacris** [comment]
Bonjour
tu peux aussi parler français, recalbox est dev par les français.
https://forum.recalbox.com/topic/4464/probl%C3%A8me-de-freeze-avec-kuru-kuru-kururin

**Comment by substring** [comment]
Judging from the posts in the forum, looks like a rom dump problem.

Anyway, that's a support question, i'm closing
