### ISSUE TITLE
virtual gamepad buttons should be labeled

### ISSUE THREAD

**Issue by cpcbegin** [recalbox/recalbox-os#1094]
Virtual gamepad, we see in recalbox.local:8080, should be all the buttons labeled.
It's confused if you don't know the name of each button in original snes gamepad.

**Comment by Laddyacris** [comment]
Hello @cpcbegin 
Information : https://github.com/recalbox/recalbox-os/wiki/Manual-%28EN%29#8---virtual-gamepads
Open issue on virtual gamepad : https://github.com/miroof/node-virtual-gamepads

**Comment by cpcbegin** [comment]
But why not label the buttons in the same image? Something similar to the [image in the wiki](https://github.com/digitalLumberjack/recalbox-os/raw/master/wiki/images/virutalgamepad_touch_zones-350px.png).

**Comment by cpcbegin** [comment]
I open issue on virtual gamepad, and they solved changing flow text objects to path in svg files:
https://github.com/miroof/node-virtual-gamepads/issues/20

**Comment by substring** [comment]
Should close once we update virtual gamepad
