### ISSUE TITLE
fstab cifs mount not working

### ISSUE THREAD

**Issue by cr4nk89** [recalbox/recalbox-os#1095]
Hi, 
Im using a Pi3 with the newest unstable update.
I edited fstab with cifs mounts on roms. 
On reboot it should automount, but it doesn't. 
If I type mount -a it mounts everything fine.... 
seems like network isn't ready when fstab tries to mount?!

**Comment by nadenislamarre** [comment]
supported in recalbox 4.1
see recalbox.remix.free.fr at the bottom of the page

**Comment by cr4nk89** [comment]
Thanks. So more or less solved :)
