### ISSUE TITLE
Bluetooth speakers support

### ISSUE THREAD

**Issue by cpcbegin** [recalbox/recalbox-os#1096]
Do you consider support bluetooth speakers in future?

**Comment by substring** [comment]
well ... not yet. 4.1 doesn't have yet the support for bt speakers. That could be added, but that's not our main focus right now

**Comment by paradadf** [comment]
duplicate https://github.com/recalbox/recalbox-os/issues/556

**Comment by rockaddicted** [comment]
Thx I close this one
