### ISSUE TITLE
Weird Characters in Game Metadata Freeze Emustation

### ISSUE THREAD

**Issue by styper** [recalbox/recalbox-os#1097]
If you have a game that has weird characters in the metadata Emulastation freezes as soon as you try to select the game in the interface.

The game that was breaking for me was this one: http://thegamesdb.net/game/4723/
The developer's name is "Br**ø**derbund Software", taking that _crossed O_ from Br**ø**derbund fixed it for me.

**Comment by rockaddicted** [comment]
So ... don't play to games with weird characters =)

**Comment by paradadf** [comment]
related to: https://github.com/recalbox/recalbox-os/issues/935

**Comment by rockaddicted** [comment]
ok so let's continue on this issue

**Comment by nadenislamarre** [comment]
why to close ?
it's a locale issue i think. probably the same problem as uppercase of é in
es. It must be fixed.

**Comment by rockaddicted** [comment]
continue to talk about this issue here : https://github.com/recalbox/recalbox-os/issues/935
