### ISSUE TITLE
Can't launch some games in Steam

### ISSUE THREAD

**Issue by Phil5004** [recalbox/recalbox-os#1102]
Hello, 
If I wan't to use Moonlight to stream some Steam games to my TV, I can't stream every game..
For example Rocket League won't launch if I click to play (Steam shows the animation to boot up the game, but after this I'll go back to the Steam Big Picture menu

**Comment by substring** [comment]
Hi

I'm afraid we can't help much as this is either a gamestream problem, either a moonlight problem. Recalbox is just a "container", not the dev. 

Do you own a NVidia Shield ? does Rocket League work on it ? Or have you tried Moonlight on your phone/tablet ? Does Rocket League work there ?

**Comment by substring** [comment]
And please, support questions should be asked ni the forum, that's clearly stated in the template of an issue :)
