### ISSUE TITLE
Can't download because freeze

### ISSUE THREAD

**Issue by pierrepier5** [recalbox/recalbox-os#1104]
Hi, trying to play retrogames,
I've already formated the sd card in FAT32
I've already extracted the file on the sd root

I've connected my rasberry 3 on my tv, 1 keyboard, a ethernet cable to my router.

BUT it freeze when downloading files, and i have to reboot it.
After, i have to do (ENTER + I + ENTER) to redownloading files, but it freeze again.

Sorry for my bad english,
Thanks, Pierre

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)

Et tu pourras parler en français sur le forum :)

**Comment by pierrepier5** [comment]
J'arrive pas a y aller:

> Ce  site est inaccessible
> Impossible de trouver l'adresse DNS du serveur forum.recalbox.com.
> ERR_NAME_NOT_RESOLVED

**Comment by substring** [comment]
Moi si : https://forum.recalbox.com/

On a eu des sushis avec free dernièrement, j'espère que ca ne recommence pas
