### ISSUE TITLE
Wii U Adapter

### ISSUE THREAD

**Issue by Minimarko32** [recalbox/recalbox-os#1107]
Hi I have a problem: I have a Wii Gamecube Controller Adapter, which is still intact, only RecalBoxOS not recognize him.
I have also tried if it works with a Linux program, it just tells me that it is not executable!
I can not convert it.

Message:
wiiu-gc-adapter : Unrecognized Exec format

[Program.zip](https://github.com/recalbox/recalbox-os/files/589860/Program.zip)

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
