### ISSUE TITLE
Can't connect in SSH or can't enter directly with login/password in the terminal

### ISSUE THREAD

**Issue by Valadone** [recalbox/recalbox-os#1108]
Hi,

I have an issue on my RP1 B model and the version of RecalBox is 4.0.0-Beta5

I can't see the rpi on my network, can't access to it with ssh and no more with login and password(root, recalboxroot) when i do F4 and Alt + F2.

And my Ip adress is in Ipv6...

Is this normal on my model or not and there is a way to resolve it ?

Thanks

**Comment by rockaddicted** [comment]
Hi, as said in the message you have deleted to write yours. This place is to track dev issues, not to provides support. So please use the forum or irc channel to have help.
Thank you.
