### ISSUE TITLE
N64 Emulator Controller issue (Xbox 360 with wireless dongle)

### ISSUE THREAD

**Issue by slippytoad1** [recalbox/recalbox-os#1110]
Once in game the Start button doesn't register. HotKey+Start still exits game but no other keys work.

**Comment by rockaddicted** [comment]
As said in the text that you have delete to write your issue, this place is to track development issues.
It is not a place to provide an user support.
So please, use our [forum](https://forum.recalbox.com/) or irc chan to ask your question.

Thx, see you soon there.
