### ISSUE TITLE
[4.0.0-build-195 2016/08/13 08:38][RasPi2] Update Does not Apply

### ISSUE THREAD

**Issue by nWoJester** [recalbox/recalbox-os#1112]
### What happened
Turned on Recalbox, msg popped up stating a new update is available.  Went into system\updates and selected Start Update.  Confirmed Yes to Really Update, then OK to reboot.

OS cycled twice, with one screen Upgrading... then the next back into the Recalbox.

Keeps showing An update is available msg.  Checked version, still on old.

Checked for the /root/updates.log, but doesn't exist.

After login in through SSH went to the Upgrade directory and found update.err.log file
 - xz:  (Stdin): File format not recognized
 -tar: Short Read

### What should have happened
System upgrade to new version.

### How to reproduce the bug
Same as description.

**Comment by substring** [comment]
Are you sure you had enough space on your share partition ?

**Comment by nWoJester** [comment]
Yes.  4GB give or take

**Comment by nWoJester** [comment]
Where is the Update being downloaded to?  Is there a log for the extraction process?

**Comment by substring** [comment]
To ~/upgrade

**Comment by nWoJester** [comment]
I think the Download did not complete properly.  The two files in upgrade (boot.tar.xz and root.tar.xz) are only 87K each.  Seems small.

**Comment by substring** [comment]
damn too small, if you want my opinion ;)

**Comment by nWoJester** [comment]
Found the log that shows the download process and it was being blocked, but still creating the file which made it believe the DL was done to advise of a reset.  Connected to a different network and worked fine.  Sorry for the inconvenience.  However, knowing this it should verify the download after it completes it to be sure it finished.

**Comment by substring** [comment]
yeah, eventually :)
