### ISSUE TITLE
[4.0.0-beta6] Some PGM and CPS3 game doesn't work properly when Rewind is activated

### ISSUE THREAD

**Issue by Gromak123** [recalbox/recalbox-os#1113]
Some games like : _Demont Front, All CPS3 Games  (JoJo's Venture,JoJo's Bizarre Adventure: Heritage for the Future,Red Earth,Street Fighter III: New Generation,Street Fighter III: 2nd Impact - Giant Attack,Street Fighter III: 3rd Strike - Fight for the Future)_ doesn't work fine (crash or lag) when the advanced option "**Rewind**" is activated.

**Temporary solution** : 

- Put your CPS3 and PGM roms (and BIOS) in the "Fba" directory.
- In game settings/advanced/fba change the  emulator in libretro and the core in FBA.
- Turn the Rewind off

And enjoy your games.

**Comment by paradadf** [comment]
I'd recommend to turn rewind off by default on all arcades, at least on fba_libretro. It causes more harm than good.
And I don't think it is in the scope of Recalbox to fix this (if even possible). IMO you should open an issue upstream: https://github.com/libretro/fbalpha/issues

**Comment by Gromak123** [comment]
Yeah i know, but Recalbox (in next release) could probably turn off rewind by default on all arcade ? 
It would help a lot off user.

Thx i would report this to fba too.

**Comment by paradadf** [comment]
That is what I suggested :D

**Comment by Gromak123** [comment]
Yes, I hope this will be heard :)

**Comment by paradadf** [comment]
I took a look and actually, the rewind for fba_libretro and mame should be disabled by default with this line:
https://github.com/recalbox/recalbox-configgen/blob/4.1.X/configgen/generators/libretro/libretroConfig.py#L39

What am I missing?

**Comment by Gromak123** [comment]
It's actually a bit weird because on a fresh install the Rewind is activate by default on Fba libretro.

Why this doesn't work ?

**Comment by paradadf** [comment]
That's what I asked... XD

**Comment by substring** [comment]
@paradadf because https://github.com/recalbox/recalbox-configgen/blob/4.0.0/configgen/emulatorlauncher.py#L54 and https://github.com/recalbox/recalbox-configgen/blob/4.1.X/configgen/emulatorlauncher.py#L68

One underscore differs ... and changes the whole world ... So it's already solved in 4.1 since we unified the 
the name of fba_libretro through months  (it used to be named fbalibretro and fba_libretro ... what a mess ...)

**Comment by paradadf** [comment]
Good to know! I wasn't aware of that technicality ;)

**Comment by Gromak123** [comment]
Thank's for the answer.
