### ISSUE TITLE
[4.0.0] Can't scrape short titles?

### ISSUE THREAD

**Issue by sibob** [recalbox/recalbox-os#1117]
### What happened

Can't scrape a game called 'Oh No!' for PSX, which is in thegamesdb. I'm assuming it's the shortness of the two words in the title? All my other games scraped fine. Is this known? Is there a way around this?

**Comment by rockaddicted** [comment]
A known problem, and should be fixed with this PR https://github.com/recalbox/recalbox-emulationstation/pull/159
