### ISSUE TITLE
System setting doesn't opening

### ISSUE THREAD

**Issue by marcos1500** [recalbox/recalbox-os#1118]
every time that i try to open the system setting, crash.

**Comment by rockaddicted** [comment]
Recalbox version ? Platform/board?
We need more details if you want support...

**Comment by marcos1500** [comment]
sorry, recalbox 4.0.0, raspberry pi3

**Comment by RupertAvery** [comment]
Do you have a USB drive attached? Any other system settings that might cause this? Does it still happen with a fresh install of recalbox 4.0.0?

**Comment by marcos1500** [comment]
Only xbox controll.. But i fixed the problem., i installed the recalbox version 4.0.0 beta 5. And after i searched for new update this fixed the problem.. Now i can select the menu system settings
