### ISSUE TITLE
[Resquest] steam controller driver

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-os#1121]
Hello

Steam controller driver : https://github.com/ynsta/steamcontroller

peut être intéressant de l'ajouter :D

**Comment by rockaddicted** [comment]
Yop, on a déjà une issue ouverte sur ce sujet. https://github.com/recalbox/recalbox-os/issues/466
Je ferme celle issue et on continuera dans l'autre.
As tu ce gamepad @Laddyacris ?

**Comment by Laddyacris** [comment]
Nop j'ai pas ce stick mais j'accepte les dons :P mdr
