### ISSUE TITLE
[4.0.0 - Final]Configure the RT button Xbox360 Controller Wireless Official by Receiver

### ISSUE THREAD

**Issue by langelotti** [recalbox/recalbox-os#1125]
### What happened
(Sorry about my english)
When I configure the controller by the contreller menu, I put the LT (L2) and its save as axis+2, but when I release the button, the system skips the R2 and go to R3 without give me the chance to configure the R2.
I gave up to use the xboxdrv because when i activate it on, the N64 games does not work the buttons anymore    
### What should have happened
I need the R2 button to Tomb Raider, Resident Evil and Driver PSX games
### Enumerate your devices
Raspberry Pi 3 
Xbox 360 Controller
Xbox 360 Receiver

**Comment by substring** [comment]
Once you defined hotkey, don't validate but scroll back to R2 and set it again.

**Comment by langelotti** [comment]
Sorry, I didn't understand what to do
