### ISSUE TITLE
[4.0.0-final][ES] Waveshare 5 inch HDMI not working

### ISSUE THREAD

**Issue by pardo** [recalbox/recalbox-os#1126]
### What happened

I've got a 5 inch display and set the proper configuration files, screen works fine until the emulationstation window is open which makes the screen turn white gradually.

If I hit F4 and switch to a terminal the display works fine.

http://www.waveshare.com/wiki/5inch_HDMI_LCD_(B)

My settings

config.txt
```
max_usb_current=1
hdmi_cvt=800 480 60 6
hdmi_group=2
hdmi_mode=87
hdmi_ignore_edid=0xa5000080
```

recalbox.conf
```
global.videomode=default
```

### What should have happened
Emulationstation should have appeared on screen.

Tried to run emulationstation manually in a smaller resolution and windowed but it doesn't work.
```
HOME=/recalbox/share/system LC_ALL=\"${settings_lang}.UTF-8\" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation --windowed --resolution 800 480 --vsync 0
```

Also played around with the 
```tvservice```

### starting an emulator
this produces the same result on the screen
```
retroarch -L /usr/lib/libretro/pcsx_rearmed_libretro.so --config /recalbox/share/system/configs/retroarch/retroarchcustom.cfg /recalbox/share/roms/psx/Spider-Man.bin
```

### Hardware
Raspberry Pi 3 Model B
Raspberry Pi 2 Model B

my thoughts are that is an issue related to OpenGL ES

Not sure on how to debug this.

**Comment by Laddyacris** [comment]
Hello 

may be help
https://github.com/recalbox/recalbox-os/wiki/TFT5-Screen-HDMI-%28EN%29

>The line max_usb_current=1 increases the Pi max USB output current. This way your pi will supply enough power to your screen. Be sure that the main power supply is powerful enough for all your devices

https://forum.recalbox.com/topic/4539/how-to-config-portable-5-inch-screen-pics-inside

**Comment by pardo** [comment]
Reading a little bit more on the forums just found that you must disable sound on this kind of screens

so my final configuration file looks like

config.txt
```
# Remove audio support
#hdmi_drive=2

max_usb_current=1
hdmi_cvt=800 480 60 6
hdmi_group=2
hdmi_mode=87
hdmi_ignore_edid=0xa5000080
```
