### ISSUE TITLE
[4.1.0-alpha][XU4][ES-RA] Screen blanking at random times during game play

### ISSUE THREAD

**Issue by ShockwaveTheFallen** [recalbox/recalbox-os#1127]
[4.1.0-alpha][XU4][ES-RA] Screen blanks during game play

What happened: while in game play mode, the screen will go black, and then reappear during game play. This happens regardless of which game or core is selected during the time which this occurs. The game does not lock up, pause or stop, but the screen goes completely black. There is no loss of audio or distortion of sound. The length of time the screen can go black for is approximately 2 seconds. It happens randomly at random times during game play, but it DOES always happen over time. 

What should happen: the screen not go dark during game play at random times!

Devices:
Hardkernel Odroid XU4
Dual Shock 3
Odroid Wifi USB Adapter 0 (Wifi Enabled)
Sandisk 200 GB Micro SD card

How to reproduce the bug: For this instance: PocketSNES core, Street Fighter 2 Turbo, 20-25 minutes into game play was when it occurred. I notice it usually happens about 30 minutes into game play and it becomes random after that with occurrence time.

**Comment by grgohr** [comment]
I think this is related to that fix https://github.com/recalbox/recalbox-buildroot/pull/521/files
simply make sure that line looks like the following in your boot.ini :
setenv console "console=ttySAC2,115200n8 consoleblank=0 vt.global_cursor_default=0"

**Comment by ShockwaveTheFallen** [comment]
Yup, that would be the one. Thank you kindly! Closing this out.
