### ISSUE TITLE
"Cannot Display this Video Mode" after starting a game

### ISSUE THREAD

**Issue by ak-media** [recalbox/recalbox-os#1128]
My installation of Recalbox works fine. Audio analog output works. Kodi works. 
But: When I start a game, I ca hear the music or sound effects of the game, but the Monitor turns black and shows only "Cannot Display this Video Mode".

I use an Dell 15" TFT (device_name=DEL-DELL_1503FP). 

In config.txt I entered: 
hdmi_group=2
hdmi_mode=16

I hane no idea how to fix this.
With Retropie the Monitor works fine with my games.

Any suggestions?

Cheers
Andi

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-os/wiki/Video-configuration-detailled-(EN)#global-video-mode-for-emulators global.videmode=default

**Comment by digitalLumberjack** [comment]
Please use the forum for support next time.

**Comment by ak-media** [comment]
Thanks Mate, you made my day. It works!
