### ISSUE TITLE
Add regular SNES9x core for RPi 3

### ISSUE THREAD

**Issue by Pat86** [recalbox/recalbox-os#1129]
Hello there,

is it planned to add the regular (and more accurate) snes9x core (https://github.com/libretro/snes9x) or is even the RPi 3 too weak to handle it?

**Comment by substring** [comment]
hi,

Your message is way to short. Core name ? core link ? If you mean bsnes, even a PS3 can't handle it at 100%

**Comment by Pat86** [comment]
I've put a link to it in my post

**Comment by rockaddicted** [comment]
This core will needs some tests.

**Comment by substring** [comment]
What's the diff between nthis one and the 2010 version ?

**Comment by Pat86** [comment]
Its based on the latest official version 1.54.
2010 is is a hybrid from 1.52 and 1.53 with specific hacks for performance improvements.

**Comment by rockaddicted** [comment]
And this core support msu audio. So I planned since a moment to test it.

**Comment by rtissera** [comment]
I have added libretro-snes9x package to my own fork.
Feel free to cherry pick these commits: 
https://github.com/rtissera/batocera.linux/commit/ad9478600f5d43d35be8e08021e69b09f13c84f8
https://github.com/rtissera/batocera.linux/commit/e47f1afdc7ce88296f9e158c7cabd0ce92749c8a

**Comment by rockaddicted** [comment]
Thank you, dis you test it ? How does it run on rpi3 ?

**Comment by rtissera** [comment]
Untested so far, I do not have any rpi3 but I will test tonight on Odroid
XU4.

Le 12 janv. 2017 3:53 PM, "rockaddicted" <notifications@github.com> a
écrit :

**Comment by rockaddicted** [comment]
@rtissera ok, so I'll wait your feedback :wink: 
The last time I tested this core on rpi3, I had exactly the same issue that https://github.com/libretro/snes9x/issues/14

**Comment by rtissera** [comment]
@rockaddicted Ok do you remember when (approximately) was thelast time you gave it a try ?

**Comment by rtissera** [comment]
Gave it a try on my XU4 and the issue you referenced.
I can confirm is not occurring for me. Worth a look on rpi3, but I don't have any one.

**Comment by rockaddicted** [comment]
Ok, so I built your package for rpi3, started a game with this command line : 
`/usr/bin/retroarch -L /usr/lib/libretro/snes9x_libretro.so --config /recalbox/share/system/configs/retroarch/retroarchcustom.cfg /recalbox/share/roms/snes/ActRaiser\ \(France\).zip`

And I have a `Segmentation fault`.

Did you updated your retroarch version ? I'm still on 1.36 version.

**Comment by rtissera** [comment]
I am using 31bcb3d6f84b99c93844bde70251bcf3dec9ce7b commit of RetroArch, seems to match this commit : https://github.com/recalbox/recalbox-buildroot/pull/421/files

**Comment by rockaddicted** [comment]
OK so we are using  the same retroarch version.

**Comment by rtissera** [comment]
Can you try to rebuild as debug maybe ?
FYI I'm building on Ubuntu 16.04.4 with gcc 5.4.

**Comment by rtissera** [comment]
Spotted some interesting differences between snes9x_next and snes9x makefiles

https://github.com/libretro/snes9x2010/blob/master/Makefile.libretro
-> This one has some specific rpi2 and rpi3 sections with CPU tweaking (-mcpu)

https://github.com/libretro/snes9x/blob/master/libretro/Makefile
-> This one does not.

Could you try to add the rpi3 section to snes9x Makefile and rebuild ?

**Comment by rockaddicted** [comment]
Same configuration, ubuntu&gss version on my pc.
I'll try to patch the makefile this weekend, and comment this issue once done.

**Comment by rockaddicted** [comment]
@rtissera Ok, so I've done some building tests and the makefile needs to be patched to works on rpi3.
In ARM section : 
```
 # ARM
 else ifneq (,$(findstring armv,$(platform)))
 	TARGET := $(TARGET_NAME)_libretro.so
-	SHARED := -shared -Wl,--no-undefined
+	SHARED := -shared -Wl,--version-script=link.T -Wl,--no-undefined
```

**Comment by rtissera** [comment]
Ok perfect then.
Can you send a pull request to libretro ?
How does it run on rpi3 ?

**Comment by rockaddicted** [comment]
Didn't have time to really test it. Started a game then shut it down.
We'll test that during the next unstable release.
