### ISSUE TITLE
[4.0.0] USB key is mounted as readonly

### ISSUE THREAD

**Issue by renebigot** [recalbox/recalbox-os#1135]
### What happened

I've told EmulationStation to use my USB key as /recalbox/share (using ES GUI).
Once done, I can see my games lists, but no game can be played. After some research, I've found that /dev/sda1 is mounted as "vfat ro". 
If I remount it as a rw filesystem (mount -o remount,rw /dev/sda1), I can play with my games. Unfortunately, after a reboot, I always have to remount sda1 as in rw mode.
I've try to reinstall the OS through noobs and I've also try to completely reinstall the OS on a brand new SD card, but the problem persists 

### What should have happened

/ is ro since 4.0 but /dev/sdX should be rw

### Enumerate your devices

Raspberry Pi 3, both 4GB or 8GB SD Card, 128GB USB key

### How to reproduce the bug

Recalbox clean install
External drive as data source

**Comment by substring** [comment]
Hi

You just need to fsck (linux)/chkdsk (windows) your key. It must have been not correctly unmounted once, so linux remounts it as read-only.

This is no issue but support, please use the forum next time :)

**Comment by renebigot** [comment]
Wow... never thought that was the problem. It's fixed now thank you and sorry for the issue. I'll use the forum next time ;)
