### ISSUE TITLE
[4.1] Suggest adding more native Linux game ports (along the lines of PrBoom)

### ISSUE THREAD

**Issue by Insidious611** [recalbox/recalbox-os#1137]
I think RecalBox should add in support for some other retroy Linux ports of games. The one that comes immediately to mind is OpenTyrian, a linux port of the good old DOS game "Tyrian". Another is EDuke32, the port of Duke Nukem 3D. A third is Descent and Descent 2 via the DXX-Rebirth project. All three should run on ARM, afaik (I know OpenTyrian does as it has android ports).

**Comment by substring** [comment]
I guess you forgot to do a search, so you couldn't stumble unpon https://github.com/recalbox/recalbox-os/issues/358 :)

Please feel free to add any missing game over there, i'm closing this issue.
