### ISSUE TITLE
moonlight problem whit command ''init''

### ISSUE THREAD

**Issue by tocco93** [recalbox/recalbox-os#1138]
hi i pair my pi2 with my pc to play moonlight but when i use the command init for scratch games from pc it say that the command is invalid. why?

**Comment by substring** [comment]
Hi

There is a template to fill when reporting issues.
You're asking for support, so you should ask on the forum.
There is not even your recalbox version (and it DOES matter concerning Moonlight).

Please join the forum and ask over there :)

**Comment by tocco93** [comment]
sorry is the first time i write on github and my english is too bad. my recalbox version is the final 4.0 and moonlight is 2.2.2 . it give me 'init is not a valid command' . what forum did you say?

**Comment by substring** [comment]
https://forum.recalbox.com
Give also the full commands you're typing to help solving your problem

**Comment by tocco93** [comment]
thank you.
