### ISSUE TITLE
recalboxOS 4.0.0 Black Screen right after setup

### ISSUE THREAD

**Issue by 7brunner** [recalbox/recalbox-os#1143]
I just started the setup on a RPi 2 B+ with a 16GB Sandisk Ultra SD formatted with SDFormatter, connected a USB keyboard and an HDMI cable with DVI adapter. The screen goes black right after the setup finishes at 100% and doesn't recover (waited about 15min). Tried on a TV with HDMI connection as well, got no signal. Tried the process described above twice now and still doesn't work.

**Comment by rockaddicted** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
