### ISSUE TITLE
Psx won't load/play rom game

### ISSUE THREAD

**Issue by MarceloFabricio** [recalbox/recalbox-os#1146]
Hi
I download some ps2 roms and put on recalbox/roms/psx
But when I try to play game, the same dont open/load/play rom
The screen fade to black and return to games list
I tryied everything... I installed BIOS from playstation... I try to convert .bin to .iso and nothing
Does anybody have the same problem?

**Comment by rockaddicted** [comment]
> I download some ps2 roms
Where did you see that we are emulating the PS2 ?

**Comment by MarceloFabricio** [comment]
I was think the Recalbox with Pi 3 run ps2 roms, that's right?

**Comment by rockaddicted** [comment]
nope ps1 (first gen) only.

**Comment by MarceloFabricio** [comment]
ok, I was breking my mind since yesterday triyng to emulate ps2... sorry!

**Comment by MarceloFabricio** [comment]
thanks
