### ISSUE TITLE
[4.0.x] [ES] scraper.py is missing (at least) one module

### ISSUE THREAD

**Issue by piso77** [recalbox/recalbox-os#1148]
# python /usr/lib/python2.7/site-packages/scraper.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scraper.py", line 5, in <module>
    import Image
ImportError: No module named Image

I don't know if, other than Image, other modules are missing, whoever takes care of this bug should *at least* try to run the scraper.py script himself before closing this.

**Comment by substring** [comment]
Hi

Cpuld you fill the expeted fields from the issue template so that we know which steps are required to reproduce the bug ?

**Comment by piso77** [comment]
Steps to reproduce it:

Ssh into the board and try to execute the script:

$ ssh root@recalbox
# python /usr/lib/python2.7/site-packages/scraper.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scraper.py", line 5, in <module>
    import Image
ImportError: No module named Image

**Comment by substring** [comment]
why would you execute that script ?

**Comment by piso77** [comment]
Because that's a command line scraper that is shipped with the system - the one embedded in the GUI simply doesn't cut it in so many ways.

**Comment by substring** [comment]
obviously it's not embedded ^^

**Comment by piso77** [comment]
And what does your smart comment add to this bug?

**Comment by substring** [comment]
That you try to run something that doesn't exist and is not meant to exist inside recalbox ? My previous smart comment kindly explained that any scrapper might not be embedded that way, and that there are numerous better scrapers out there : Universal XML scrapper, fullscrape, fastscrape.

Furthermore, non one ever tried usong scraper.py, i dont even know where you read it is supposed to be shipped with recalbox

**Comment by piso77** [comment]
No, your comment didn't say anything like that, and besides...

"you try to run something that doesn't exist and is not meant to exist inside recalbox ?"

Are you serious or what? Do you actually know what comes with the image you are shipping?

$ md5sum recalboxOS-4.0.0.zip 
95d03e9c163c5c7d28f42305d6600c71  recalboxOS-4.0.0.zip
$ unzip -q recalboxOS-4.0.0.zip  -d foobar
$ tar tvf foobar/os/recalboxOS-rpi3/root.tar.xz | grep scraper.py
-rw-r--r-- 0/0           28714 2015-05-19 21:53 ./usr/lib/python2.7/site-packages/scraper.py
-rw-r--r-- 0/0           29062 2016-11-01 00:23 ./usr/lib/python2.7/site-packages/scraper.pyc

That scraper script is there, and you ship it with every image you deliver to the people - so, either it's a mistake (and whoever did the integration didn't try to run that script) so it should be removed, or you fix it - and if you have nothing useful to say, or you don't want to spend 5 minutes of your life checking what's going on, please refrain from any other comments because you are just wasting my time.

Thank you.

**Comment by substring** [comment]
Nobody would want to spend 5 minutes in his life for someone who can't behave.

So, i do admit i was wrong about the script. But your behaviour is despising. Period, end of the issue. Learn to behave and talk to people in a proper manner. Until then, issue closed.

And merry christams !
