### ISSUE TITLE
[KODI] Allow it to be updated separately

### ISSUE THREAD

**Issue by hannesgod** [recalbox/recalbox-os#1150]
I'm completely new to the world of Recalbox and tried to find for an answer before posting, but I couldn't.
The closest idea was given in #429, but I acknowledge the advantages of a single-boot, so this is different.

Kodi v17 Krypton is about to be released and Recalbox is still on v15 Jarvis. Looking into yout buildroot files (not a programmer) I saw that 4.1 should come out with v16, though an outdated version. Kodi v17 has, of course, many improvements and I can't stop feeling a bit left behind. Kodi v15 works, no doubt, but it would be nicer to use a version not so far from "the state of the art".

I don't know if such feature would be possible without destroying the harmonious coexistence that you currently offer between Kodi and RecalboxOS, if you allow me to consider them as separate unities. But maybe it is something you also would like to have a this "issue" serves for showing interest.

Without further ado, I say goodbye with great appreciation and gratitude.

**Comment by substring** [comment]
Hi,

I'm afraid this can't be done for many reasons :
- we patch kodi for a much better joypad support (yes, KODI ootb is pretty lame with pads)
- would need to have write access to / which is not the case
- I have no idea what kodi built are worth
- I'm also pretty sure it wouldn't work that easily on recalbox

So we prefer sticking to the buildroot version of Kodi which is "maintained" by buildroot

**Comment by hannesgod** [comment]
Thank you for the fast answer. Without trying to be insistent, my considerations:
- Kodi has sice v17 embed [controller support](http://kodi.wiki/view/HOW-TO:Configure_controllers)
- I believe a distribution like [LibreELEC](https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages) is based on buildroot and heavily optimized for low-end devices

But you posted other points which I don't understand and even less I would be able to achieve.
Please, feel free to close this issue if this is not a feasible option.

**Comment by substring** [comment]
Thank you very much for mentionning the v17 controllers support ! That's something that does sound "recalbox-like" and it would mean we should write a configuration generator once we release Kodi17.

Buildroot is still on Kodi 16.1 which is the version we will ship with Recalbox 16.1

**Comment by rockaddicted** [comment]
recalbox 16.1 ? in 2075 ? :wink:

**Comment by substring** [comment]
recalbox 4.1 :stuck_out_tongue_closed_eyes:

**Comment by substring** [comment]
I'm closing as this won't happen ...
