### ISSUE TITLE
[4.0.0-final][ES] N64 game return to ES

### ISSUE THREAD

**Issue by Nogue** [recalbox/recalbox-os#1151]
### What happened
When i try to launch a n64's game i return to ES
### What should have happened
I should start the game
### Enumerate your devices
Raspberry pi3 with keyboard and QUMOX n64 Controller
### How to reproduce the bug
Launching the n64 game

PD: I try to do https://github.com/recalbox/recalbox-os/wiki/N64-%3A-return-to-ES-%28EN%29 but doesn't work.

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
