### ISSUE TITLE
network connection issues ethernet and wifi

### ISSUE THREAD

**Issue by t1980** [recalbox/recalbox-os#1152]
hi there, i'm having connection issues, but I can access recalbox through my pc like putty, browser and network as well as kodi addons are working perfectly fine. but that is only when my Ethernet cable is connected; through wifi it wont connect at all. And yes I did configure my wifi ssid and key with no luck, I reinstall recalbox from scratch several with 2 different class 10 sd card still no luck, at the moment I wont be able to update recalbox in the future. On emulationstation statue says not connected please see attach
![capture](https://cloud.githubusercontent.com/assets/24740146/21464097/afb52ee0-c96b-11e6-855c-640427f3571d.PNG)

**Comment by substring** [comment]
@t1980 
edit `~/.emulationstation/es_settings.cfg` and replace `<string name="UpdateServer" value="recalbox.com" />` with `<string name="UpdateServer" value="archive.recalbox.com" />`

**Comment by t1980** [comment]
just received an email with edit text in es_settings to replace and it works. thank you guys.
for anybody having the same issue please see below:
edit ~/.emulationstation/es_settings.cfg and replace <string name="UpdateServer" value="recalbox.com" /> with <string name="UpdateServer" value="archive.recalbox.com" />

**Comment by randroid88** [comment]
> edit ~/.emulationstation/es_settings.cfg and replace with

Your line is cut off. What was the solution?

**Comment by randroid88** [comment]
I believe this is the full line:

> edit ~/.emulationstation/es_settings.cfg and replace <string name="UpdateServer" value="recalbox.com" /> with <string name="UpdateServer" value="archive.recalbox.com" />


From: [https://forum.recalbox.com/topic/5039/can-t-connect/31](url)

**Comment by t1980** [comment]
edit ~/.emulationstation/es_settings.cfg and replace <string name="UpdateServer" value="recalbox.com" /> with <string name="UpdateServer" value="archive.recalbox.com" />
sorry my bad!!!

**Comment by t1980** [comment]
edit ~/.emulationstation/es_settings.cfg and replace 
<string name="UpdateServer" value="recalbox.com" /> 
with <string name="UpdateServer" value="archive.recalbox.com" />

**Comment by t1980** [comment]
wont let me copy and paste properly. anyway you've got it..... this the one

**Comment by randroid88** [comment]
No worries and thanks, this worked. I was able to update.
