### ISSUE TITLE
 4.0.0 X-arcade not recognised despite settings to 1 

### ISSUE THREAD

**Issue by Thesundreamer** [recalbox/recalbox-os#1153]
### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

**Comment by Thesundreamer** [comment]
hello I am new to recalbox.  Only at first boot I was able to see xarcade tankstick, since it is recognized as keyboard.  It does not show in controllers.  Can someone please help with that thanks

**Comment by Laddyacris** [comment]
Hello @Thesundreamer 
this request is not an issue problem. Please read wiki : https://github.com/recalbox/recalbox-os/wiki/XArcade-configuration-%28EN%29
and post your request on forum.

**Comment by Thesundreamer** [comment]
Isn't it an issue when most people say it does not work ?


Having the xarcade recognized for only first boot seems to me like it's an issue

Best regards and merry christmass


Criss

Envoy? de mon iPhone

Le 25 d?c. 2016 ? 10:11, Laddyacris <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Hello @Thesundreamer<https://github.com/Thesundreamer>
this request is not an issue problem. Please read wiki : https://github.com/recalbox/recalbox-os/wiki/XArcade-configuration-%28EN%29
and post your request on forum.

-

**Comment by substring** [comment]
As you must have read in the issue, it takes a very long time for the XArcade to be recognised by the OS. It seems plugging both USB cables makes it better.

A suggestion has already been made on how to solve the issue and it works. Just `echo "/usr/bin/xarcade2jstick" > ~/custom.sh && chmod u+x ~/custom.sh`

**Comment by Thesundreamer** [comment]
Merci on à testé et on y arrive pas, on à utilisé putty créé le custom.sh avec /usr/bin/xarcade2jstick

Au boot toujours pareil, le xarcade n'est pas reconnu :-(

**Comment by Laddyacris** [comment]
poste l archive demandé dans ce sujet en ayant brancher le xarcade : 
https://github.com/recalbox/recalbox-os/wiki/Recalbox-support--%28FR%29

**Comment by Thesundreamer** [comment]
Voila l'archive après mes premiers pas avec Winscp et putty

http://www64.zippyshare.com/v/PKUObVip/file.html

English or french for me as people who can help want :-)
