### ISSUE TITLE
4.0.0 ES | Freeze when deleting last rom from rom options

### ISSUE THREAD

**Issue by robindevouge** [recalbox/recalbox-os#1154]
### What happened
As I deleted the last snes ROM from the ROM options (select button > edit game data > delete) ES freezed while displaying options menu from the next game in the list, but since there was none, freezes

### What should have happened
ES should have come back to the systems menu I suppose

### How to reproduce the bug
While in a system's ROM list, press select, edit game data then delete, repeat until all system's ROM have been deleted

**Comment by paradadf** [comment]
one more dupe to the list: https://github.com/recalbox/recalbox-os/issues/1139
