### ISSUE TITLE
[4.0.0-final] Custom cheats not showing up

### ISSUE THREAD

**Issue by uniQ168** [recalbox/recalbox-os#1156]
### What happened
So I made a custom .cht file for a Playstation game and saved it in \\recalbox\share\cheats.
I started up the game and could not see the custom folder when loading cheat files.

### What should have happened
I expected the custom folder to show up to load my custom made cheat files.

### Enumerate your devices
RPi 3 Model B, 64GB SanDisk mSD, Xbox360 Gamepad

### How to reproduce the bug
Place custom .cht file in \\recalbox\share\cheats and check if it's visible ingame.

**Comment by rockaddicted** [comment]
The cheats folder defined in the system is `/recalbox/share_init/cheats/cht`
So you have to mount `/` partition on rw with : `mount -o remount, rw /` then add your cheat file inside this folder.
The next time, please use the forum to ask support.
Github issues are only used for dev problems.

**Comment by Nintendoguy88** [comment]
Well yeah what is rw exactly no cheats work for any emulator om pretty upset over this to be honest
