### ISSUE TITLE
Audio issues and menu issues

### ISSUE THREAD

**Issue by kryptalivian** [recalbox/recalbox-os#1158]
I have a pi 3 and pi zero and cannot get audio to come through my ks8000 Samsung TV. I'll get audio on pi zero every once in a while, but when I do, my Bluetooth controller won't work and I'm forced to unplug and plug in the Bluetooth dongle.. Also the pi 3 always goes to start menu when exiting a game. I'm running the stable 4.0 system

**Comment by kryptalivian** [comment]
I may have solved the issue. I changed the volume from 100 to 80-90s and sound came back upon reboot.

**Comment by kryptalivian** [comment]
Turns out that didn't solve the issue :-(

**Comment by LipkeGu** [comment]
It seems the dongle has the ability to act a a audio device. so when you put in the dongle it switches to the dongle. you should explicit set the audio device instead o using AUTO

**Comment by kryptalivian** [comment]
That would explain alot. I'll try that when I get home. Thanks!

**Comment by kryptalivian** [comment]
This solved the issue. I'll close the thread. Thanks!
