### ISSUE TITLE
Archive.recalbox.com - Offline

### ISSUE THREAD

**Issue by elizeufreitas** [recalbox/recalbox-os#1162]
Friends, there are 3 days in which the site is in the forum, I want to test the 4.1 beta and I have been waiting for 3 days. -benzoic acid.

Are you aware of the problem?

**Comment by digitalLumberjack** [comment]
http://archive.recalbox.com is up, it just returns a 403 to me. Do you have a host not found or connection refused ?

**Comment by elizeufreitas** [comment]
yes, error 403 .

**Comment by digitalLumberjack** [comment]
yep so it's only, the file browsing is disabled.

**Comment by elizeufreitas** [comment]
Got it, but can someone re-enable it? Or could I pass the direct links to the files?

After all, what is the reason for the deactivation? Safety ?

**Comment by digitalLumberjack** [comment]
It's the default config of the file server. Files on this server are used for internal testing or update of 4.0. I don't see the case where browsing is enabled. Sorry but you'll have to wait for 4.1 official beta.

**Comment by elizeufreitas** [comment]
I did not understand, because I downloaded it several times through http://archive.recalbox.com the problem is that I deleted the files, because they were previous versions.

Could you send the link from the last 2 versions only? Please.

**Comment by Laddyacris** [comment]
Sorry but you'll have to wait for 4.1 official beta.

**Comment by digitalLumberjack** [comment]
We are working on it, please let us finish the 4.1 beta and tools that comes with as we want before testing it.
