### ISSUE TITLE
Buildroot: Retroarch doesnt compile on MUSL

### ISSUE THREAD

**Issue by LipkeGu** [recalbox/recalbox-os#1165]
### What happened
Compiling fails on MUSL

### What should have happened
The Compiling should gets done
### Enumerate your devices
RPI1: recalbox-Buildroot -> Package retroarch
### How to reproduce the bug
build retroarch with MUSL

**Comment by substring** [comment]
Hi !

What's the point of using musl ?

**Comment by LipkeGu** [comment]
They already has the fix

**Comment by LipkeGu** [comment]
fixed and superssed by: https://github.com/recalbox/recalbox-os/issues/1170
