### ISSUE TITLE
[4.0.0-beta5][GPIO] Escape button on GPIO

### ISSUE THREAD

**Issue by bboybboy** [recalbox/recalbox-os#1167]
Hi. How can I bind GPIO button to ESC keyboard key? I have hardware button and want to be able exit from retroarch just pressing on it and don't use gamepad for it. (This is like reset button in NES).

I've created own script in **/etc/init.d** but my script running in python and using **uinput** library, which is not included in recalbox. 

Thanks

**Comment by substring** [comment]
That's something we will try to release with 4.1 as some steps have been made in this way.

If you're familiar with python, the best is to kill the retroarch process. You should rather check the forum about that, there have been 2 or 3 threads concerning this topic

**Comment by bboybboy** [comment]
This is script which I want to exec

`
import uinput
import time
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BOARD)

pin_esc = 3

GPIO.setup(pin_esc, GPIO.IN, pull_up_down=GPIO.PUD_UP)

events = (uinput.KEY_ESC)
device = uinput.Device(events)

key_esc = False

while True:
	if (not key_esc) and (not GPIO.input(pin_esc)): 
		key_esc = True
		device.emit(uinput.KEY_ESC, 1)
	if key_esc and GPIO.input(pin_esc):
		key_esc = False
		device.emit(uinput.KEY_ESC, 0) 
	time.sleep(.05) 
`

**Comment by substring** [comment]
instead of sending ESC, they way we've been working on is just a kill of the running process

**Comment by bboybboy** [comment]
@substring looks like idea. Thx

**Comment by bboybboy** [comment]
It's works

Here is python script

```
import time
import os
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BOARD)

pin_esc = 3

GPIO.setup(pin_esc, GPIO.IN, pull_up_down=GPIO.PUD_UP)

key_esc = False

while True:
	if (not key_esc) and (not GPIO.input(pin_esc)): 
		os.system("killall -9 retroarch")
		key_esc = True
	if key_esc and GPIO.input(pin_esc):
		key_esc = False

	time.sleep(.05)
```

And video preview
https://www.youtube.com/watch?v=hxvhXi_p76U
