### ISSUE TITLE
[4.0.0][ES] video smoothing turns off when it shouldn't

### ISSUE THREAD

**Issue by rsn8887** [recalbox/recalbox-os#1172]
### What happened
video smoothing is turned off when shader is specified in recalbox.conf even though in recalbox.conf and in ES Menu it is listed still as "ON"

### What should have happened
video smoothing should be on if the user selects it to be on. Fix: remove line in libretro configgen pythoon script. Some shaders, most notably shaders_glsl/retro/sharp-bilinear.glslp depend on this being on to give the intended result. E.g. sharp-bilinear with a pre-scale of "2" would give sharp pixels with minimum blurring and zero pixel wobble if this problem could be fixed. Currently it gives pixel wobble, unless the user goes in and switches HW bilinear filtering back on manually in the retroarch video menu. In addition, linear_filter0=true has NO effect when smoothing is off, in ANY glslp file. This potentially causes many shaders to give wrong results that rely on such filtering, not just the sharp-bilinear.glslp preset.  

The fix is to remove one line in recalbox-configgen/configgen/generators/libretro/libretroConfig.py :

    if defined('shaders', recalboxConfig):
        retroarchConfig['video_shader'] = recalboxConfig['shaders']
        retroarchConfig['video_shader_enable'] = 'true'
        retroarchConfig['video_smooth'] = 'false'
^^^^^^^^^^^^^^^ this last line here should be removed.

### How to reproduce the bug
Turn video smoothing on. change 
global.shaders= 
in recalbox.conf to 
global.shaders=/recalbox/share_init/shaders/shaders_glsl/retro/sharp-bilinear.glslp
start a libretro game
press hotkey + B to bring up retroarch menu
select quick_menu->shaders
change sharp-bilinear shader preset to "Linear Filtering" and "1x" scaling and apply shader changes.
The image should now be blurry because there is a pre-scale of only 1x so the whole image should be stretched using linear filtering. But it isn't blurry because the "Linear filtering" choice has NO EFFECT, and the image is stretched using nearest neighbour filtering resulting in distorted pixels and pixelwobble.

If above is repeated with an empty global.shaders= string in recalbox.conf, the image becomes blurry as expected. Note that a prescale factor of 2 in this case already gives a very nice and sharp image without any distortion. Sharp-bilinear is the best filter for pixel enthusiasts.

**Comment by dankcushions** [comment]
`filter_linear0 = "true"` in a glslp will turn on bilinear filter for that shader. it doesn't matter what the user has set for video_smooth. eg, i have it off but https://github.com/RetroPie/common-shaders/blob/rpi/crt-pi.glslp#L3 turns it on.

**Comment by rsn8887** [comment]
Hmm you are right and according to the glslp specs the filtering when scaling the final shader is implementation dependent. So a simple workaround is to use a two-pass glslp to make sharp-bilinear work perfectly, and leave everything else as it is!!! Awesome.
