### ISSUE TITLE
[4.0.0-beta1][ES] optimization configuration for n64 games 

### ISSUE THREAD

**Issue by sinmartz** [recalbox/recalbox-os#1178]
I´m currently running recalbox with the default configuration, i have read also the gamelist compatibility for n64 games, but is there any optimization in order to get properly work the other games? i mean there is the known issue on mario party games that the characters are not visible, in perfect dark there are some textures missing etc, is there any configuration in the code to fix this little problems? i have tried also to overclocking my rpi3 model b at arm_freq = 1350 (thats the only optimizatin i have made so far), im not an expert in the matter but i have read some issues in this forum but it seems that there is no information on how to optimize the configuration on n64 games, does anyone have tried anything that have worked properly in order to optimize n64 performance in recalbox? i would really apreccciate that you can share your configurations.

thanks

**Comment by paradadf** [comment]
Please, use the forum for support questions.
Also, I recommend you to read about n64 emulation in general ;)
