### ISSUE TITLE
add dreamcast emulator

### ISSUE THREAD

**Issue by Energizing** [recalbox/recalbox-os#118]
i suppose there is no retroarch core for reicast though?

**Comment by digitalLumberjack** [comment]
No there is no core for reicast :)
But i would love to play crazi taxi on my recalbox !
The longest thing in adding a standalone emulator is the mapping of the
controls (/recalbox/scripts/generateEmuConfigs/*)

**Comment by Energizing** [comment]
damn, i hope someone programs a core for it in the near future! (or maybe it doesn't work like that)

**Comment by NerosTie** [comment]
There is this tweet from reicast team: https://twitter.com/reicastdc/status/562207033794265089

**Comment by Energizing** [comment]
yeah that's why ^^ but it works full speed for a few games apparently, i did not try it but some people gave feedback on raspberry forums

**Comment by C-Fu** [comment]
I tried reicast on RPi2, and it works, in spite of its very very alpha stage.

- Some games work
- Some slowdowns, but many games run at full speed
- Joystick buttons are mapped automatically (can't change them), but some games doesn't respond on button presses
- No sound by default (have to use hacks)

Would love to have reicast on recalbox, but at the current state, it's gonna be some time though.

**Comment by brisssou** [comment]
not much love for this one :'(

**Comment by mchtt** [comment]
any news about the reicast stability ?
the compatibilty list is getting better : [Compability List](https://docs.google.com/spreadsheets/d/1AD91IcudqHP7dDmEXLO25Pzb85uUgAy4chU2QxlZBQk/edit?usp=sharing)
All the following games are fully playable, maybe it's time to include it ?

4 Wheel Thunder
AeroWings
AeroWings 2: Air Strike
Alone in the Dark: The New Nightmare
Aqua GT
Blue Stinger
Capcom vs. SNK
Carrier
CART Flag To Flag
Charge 'N Blast
Chicken Run
ChuChu Rocket!
Coaster Works
Confidential Mission
Cosmic Smash
Disney's Donald Duck: Goin' Quackers
Disney/Pixar Buzz Lightyear of Star Command
Evolution
Fighting Force 2
Fighting Vipers 2
Fur Fighters
Giga Wing
Grand Theft Auto 2
The Grinch
Gunbird 2
Headhunter
Heavy Metal: Geomatrix
Incoming
Jet Grind Radio
Jojo's Bizarre Adventure
Kao the Kangaroo
Legacy of Kain: Soul Reaver
Mag Force Racing
Marvel vs. Capcom: Clash of Super Heroes
Marvel vs. Capcom 2
MDK2
Metropolis Street Racer
Mortal Kombat Gold
Namco Museum
Outtrigger
Pen Pen TriIcelon
Power Stone
Power Stone 2
Project Justice
Revive... Sosei
Re-Volt
Ready 2 Rumble Boxing
Roadsters
Samba de Amigo
San Francisco Rush 2049
Sega GT
Shadow Man
Silver
Snow
Soul Fighter
Speed Devils
Spider-Man
Star Wars Episode I Racer
Sword of the Berserk: Guts' Rage
Tech Romancer
Time Stalkers
Tony Hawk's Pro Skater 2
Toy Commander
Under Defeat
Virtua Fighter 3tb
Virtua Striker 2
Walt Disney World Quest: Magical Racing Tour
Wetrix+
Zombie Revenge
