### ISSUE TITLE
Moonlight - Black Screen

### ISSUE THREAD

**Issue by noxx2015** [recalbox/recalbox-os#1180]
hello

ihad installed Recabox 4.0 Final and the latest GeForce Experience (3.2.2.49). 

Moonlight on my AmazonFireTV works fine, but if i start Moonlight with
Recalbox i get a black screen (with Recalbox Logo on the buttom side)
i here only the sound of the game.

**Comment by Tyrix** [comment]
The current implementation of moonlight in recalbox is "too old" for GeForce Experience 3.2. So, the moonlight binary has to be updated in recalbox. You could also downgrade GeForce Experience to 3.07 or 3.1x, I think.

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
