### ISSUE TITLE
[ES][Enhancement] Vastly improve loading time of EmulationStation #59

### ISSUE THREAD

**Issue by Supernature2k** [recalbox/recalbox-os#1182]
Hi,

Retropie team added [this PR](https://github.com/RetroPie/EmulationStation/pull/59) to improve ES loading time.

I tried to add it in Recalbox ES, compiled with success but crashes when launched.

Could you take a look at it and see if it could be added to recalbox ES?

**Comment by paradadf** [comment]
Duplicate: https://github.com/recalbox/recalbox-os/issues/848

PR already referenced there.
