### ISSUE TITLE
Moonlight - Disable Steam Games

### ISSUE THREAD

**Issue by noxx2015** [recalbox/recalbox-os#1186]
Hello

in my GFE Settings are only manualy added links to my Games. But 
Moonlight show also Games of Steam. How can i disable Steam Games?

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
