### ISSUE TITLE
add PSP emulator?

### ISSUE THREAD

**Issue by Energizing** [recalbox/recalbox-os#119]
damn i didn't know it was working so well!

https://www.youtube.com/watch?v=qwtffTKyG1o

**Comment by RomainOdeval** [comment]
Well, this will help @digitalLumberjack a lot ...

https://github.com/libretro/libretro-ppsspp

**Comment by Energizing** [comment]
no worries he already knows all of this

**Comment by rockaddicted** [comment]
A way to build it?
If someone want to try ... he is welcome

https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=99806

**Comment by digitalLumberjack** [comment]
Not in 3.3.0, unstable, unbuildable for now.

**Comment by SandroBR** [comment]
+1

**Comment by mchtt** [comment]
+1 what about the actual ppsspp builds ?

**Comment by substring** [comment]
done ^^

**Comment by MarcDK** [comment]
Hi!

What does this mean: "done"? So it is commited but recal box had its last release a while back. Is this project still actively maintained?

**Comment by substring** [comment]
@MarcDK i guess you are not familiar either with github, either with how recalbox is moving, but https://github.com/recalbox/recalbox-buildroot/blob/rb-4.1.X/CHANGELOG.md
It means PPSSPP has been added to recalbox4.1. You can track recalbox-buildroot's commits to see our activity

**Comment by MarcDK** [comment]
Hi! 

Ok, thanks. I did not know that you are one the main developers. I thought this was just a commit from someone which will never get merged into the master branch. Good to see that two new emulators are on its way! 

Thank you and cheers!
