### ISSUE TITLE
EN: any prediction of adding the Nintendo DS emulator (DraStic) in the next Builds?

### ISSUE THREAD

**Issue by lfrgames** [recalbox/recalbox-os#1192]
### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

**Comment by substring** [comment]
Hi,

Drastic runs at 10-15 fps on a pi3, we won't add it

**Comment by substring** [comment]
Well my bad seems i made a mistake with Desmune.

Drastic is closed source, we can't include it.
