### ISSUE TITLE
[4.1] Test new bluetooth improvements

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-os#1199]
Hi @recalbox/recalbox-testers !

Before pushing a major enhancement concerning bluetooth to the unstable branch, i do need as much feedback as possible on some changes.

**You must :**
- have a pi3
- understand this is for testing purpose only, so i expect some feedbacks, you should expect some bugs/failures/apocalypse
- have already upgraded to 4.1

**Devices not concerned :**
- anything related to Dualshock 3 (they don't follow the standard bt pairing protocol)
- own a deboard other than a pi3 (just because i only built for pi3 for now)
- any BT audio device (this won't be supported in recalbox)

**Devices concerned :**
- any bluetooth pad, including DualShock 4
- any keyboard

**What you should do:**
1. preliminary
    - have a 4.1 recalbox on pi3
    - edit recalbox.conf and change `updates.type=gitlab/30-make-bluetooth-more-reliable` and update
    - if you own a DualShock 4, edit recalbox.conf and set `controllers.ps3.driver=bluez`
    - delete paired devices in ES
2. the real deal
    - scan for BT devices
    - pair your pad(s)
    - make sure your pad is properly configured in ES
    - test in games
    - test reconnection once the pad went to sleep mode
    - poweroff recalbox, turn it on, turn on your pads, make sure they reconnect

**Expected feedback:**
- pad name + firmware version if you ever know it
- if it worked or not
- what BT dongle you have

**Known bugs:**
- my 8bitdo Zero would not automatically connect if I turn it on before recalbox. In that case, power cycle, and it's good
- recalbox will only use the HCI0 bt device. If you're unsure if you're using the internal BT or your dongle, `hciconfig`may help you. The device on a /dev/tty is the internal BT. If you want to disable the Pi3 internal BT, edit `/boot/config.txt` and add `dtoverlay=pi3-disable-bt`

I hope i've said it all, now your turn, merry recalboxers :)

**Comment by substring** [comment]
@recalbox/recalbox-testers please also mention if you still want to be part of the recalbox-testers team or not

**Comment by benutzer193** [comment]
If there is a test I can participate, I do. So I'd stay in the testers team.
As I don't own a rpi3 I can't help with this test.

**Comment by substring** [comment]
Anyway it has been merged to the unstable branch now, so testing is not required anymire except for unstable feedback (including bluetooth)
