### ISSUE TITLE
Support controllers in kodi

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#12]
Kodi blocks the special file /dev/input/jsX when launched. jstest does not report any event when kodi is on...
The configure.in file of kodi disable joystick if building for arm, even with --enable-joystick

**Comment by musyne** [comment]
That _might_ help:
http://www.griffinscs.com/blog/?p=493

**Comment by digitalLumberjack** [comment]
Thanks for the link, i'll take a look ;)

**Comment by mgoulartBR** [comment]
I think that it can help you!

http://kodi.wiki/view/Keymap#Gamepads

**Comment by digitalLumberjack** [comment]
Yeah i tried to compile kodi with this patch. That unlock the input file, which is nice. But then i did not managed to make the controller work with SDL...

**Comment by digitalLumberjack** [comment]
I will need some help on that one...

**Comment by mgoulartBR** [comment]
http://kodi.wiki/view/HOW-TO:Set_up_PS3_BD_Remote

There is a lot of stuff to make it work! I don't know if it will work on any other controller.

**Comment by agenttank** [comment]
seems like emulating a keyboard seems to be a way of making gamepads work...
http://openelec.tv/forum/124-raspberry-pi/74287-xbox360-wireless-gamepad-support

quote "lrusak"
------
Joystick requires SDL, SDL requires xorg (in Kodi at least).

 It was never available on the RPi (or any arm builds) with OpenELEC.

 If you want to use joystick support either use OpenELEC on an x86 computer, or use Raspbian (or arch linux) on your RPi.

 Here you can see the joystick, SDL, xorg combo hardcoded in Kodi, https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/WinEventsSDL.cpp#L43
----------

xbian also supports gamepads by emulating mouse/keyboard (i'd prefer a keyboard-only emulation over a mouse emulation)

**Comment by agenttank** [comment]
hey, i'm just looking at the manual of the nes30 controller... 
it says it's working as a bluetooth keyboard when you power it on by pressing start+B! does this work for you? mine isn't here yet.
http://www.nes30.com/download/Manual/NES30-Manual-v1.0.pdf

also i found this video tutorial of how to make a xbox controller work in kodi on retropie (raspbian i think). maybe this one might help? https://www.youtube.com/watch?v=beBGRwjJI60

**Comment by PreferLurking** [comment]
What about trying to get sixad to translate the joystick events into keystrokes from input.h? I use this on an nvidia ion pc to map PS key to the escape key.  Only the escape key works though.I have tried other mappings and they do not work, including one from the web for Gnome that seems to be made by qtsixa's author.

I am building a minibian system with sixad rithg now to see if the escape key works on the Pi.

**Comment by PreferLurking** [comment]
I found some software that may be able to translate joystick input into keyboard input. It has a python API. Here's the link: http://hetgrotebos.org/wiki/uinput-mapper. Anyone with python skills want to give it a go? It may also require a modified keyboard.xml in .kodi/userdata/keymaps to get the input heard in kodi.

**Comment by Kub3** [comment]
Have you tried to compil buildrrot with Xorg and SDL?
As-tu essayé de compiler ta buildroot avec Xorg et SDL?

**Comment by PreferLurking** [comment]
Marcello,
Sorry it took me so long to reply. I have been away from home.I have not tried to build in Xorg with buildroot. I know that what you suggest will work.If you are interested, here is what is needed:Sixaxis/Dualshock 3 Controller as mouse in Xorg - FedoraForum.org

|   |
|   |  |   |   |   |   |   |
| Sixaxis/Dualshock 3 Controller as mouse in Xorg - Fedora...Sixaxis/Dualshock 3 Controller as mouse in Xorg Guides & Solutions (No Questions) |
|  |
| View on forums.fedoraforum.org | Preview by Yahoo |
|  |
|   |


I would like a lighter solution - like fixing sixad to translate buttons to keys properly.If that is not possible, then adding in lirc and lirc-rpi or uinput-mapper is much less software than Xorg+SDL.You have gotten everything else working without X or SDL now, so obviously it is not necessary. Those are a lot of code to add to get this small piece working.Lirc-rpi might conflict with mk_arcard_joystick_rpi though.
I have contacted a kodi developer and was told that they are reworking all of the input code on kodi, so joystick support on ARM will return - the question is when? I am trying to lobby the kodi devs to join your project to help integrate it into recalbox.
Also, the retropie programmers are making great progress with mupen64plus on ARM - the experimental branch is moving very fast.
Thanks for the great work.Carman


     On Saturday, April 25, 2015 9:51 AM, Kub3 <notifications@github.com> wrote:
   

 Have you tried to compil buildrrot with Xorg and SDL?
As-tu essayé de compiler ta buildroot avec Xorg et SDL?—

**Comment by reivaax** [comment]
Good news in the last update of kodi no ? :)
http://kodi.tv/kodi-15-0-isengard-beta-2/
https://www.youtube.com/watch?v=2QrhphxMJCQ

**Comment by digitalLumberjack** [comment]
HOLLY CRAP !
I CAN CLOSE THIS ONE !

**Comment by NedScott** [comment]
Does this mean joysticks are working now, or are you just cleaning up issues that aren't actually RecalBox's?

**Comment by nadenislamarre** [comment]
it works.

**Comment by cabana-banana** [comment]
that’s great news, but how was this problem solved?
