### ISSUE TITLE
Splitscreen Game Boy Advance ? 

### ISSUE THREAD

**Issue by BexSweetAss** [recalbox/recalbox-os#1201]
I'm sorry i don't know where to ask for this , i've been searching for a while now and can't find any answr.
It's not really an issue , it's more a request i guess  

Is there a Way to play Game Boy Advance Roms such as Pokemon with an other player split screen ?

**Comment by rockaddicted** [comment]
Nope you can't, there is no available emulator with this feature.

Next time, please use the forum to ask this kind of question.
Github issues is place for development.
