### ISSUE TITLE
add support for cheap usb snes pad in es_input.cfg

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#1205]
Could you please add this mapping for my snes pad:

	<inputConfig type="joystick" deviceName="usb gamepad           " deviceGUID="030000001008000001e5000010010000">
		<input name="a" type="button" id="1" value="1" code="289" />
		<input name="b" type="button" id="2" value="1" code="290" />
		<input name="down" type="axis" id="1" value="1" code="1" />
		<input name="hotkey" type="button" id="8" value="1" code="296" />
		<input name="left" type="axis" id="0" value="-1" code="0" />
		<input name="pagedown" type="button" id="5" value="1" code="293" />
		<input name="pageup" type="button" id="4" value="1" code="292" />
		<input name="right" type="axis" id="0" value="1" code="0" />
		<input name="select" type="button" id="8" value="1" code="296" />
		<input name="start" type="button" id="9" value="1" code="297" />
		<input name="up" type="axis" id="1" value="-1" code="1" />
		<input name="x" type="button" id="0" value="1" code="288" />
		<input name="y" type="button" id="3" value="1" code="291" />
	</inputConfig>

**Comment by RupertAvery** [comment]
Can't you map in in ES?  All you have to do is plug in a new controller and hold any button down to allow ES to detect it and open the mapping dialog.

**Comment by substring** [comment]
@RupertAvery is he asks it, it's beacause he wants the pad to be mapped our of the box :) That's an excerpt from the pads configuration file :)

@bigboo3000 i'll do it, thanks for your contribution

**Comment by RupertAvery** [comment]
I see, so we can contribute specific mappings? Like PS3 for instance?

**Comment by rockaddicted** [comment]
yep, if you have controllers that aren't mapped out of the box, map them in ES with a snes layout. Then open an issue with the `es_input.cfg` corresponding section.
