### ISSUE TITLE
[PPSSPP] Hotkey + START does not open PPSSPP Pause menu

### ISSUE THREAD

**Issue by RupertAvery** [recalbox/recalbox-os#1206]
I understand this is probably a PPSSPP upstream issue, as it appears you cannot map more than one button to the Pause function in PPSSPP, but I'm just putting this here to track it.

### What happened

Nothing. It appears no button is mapped to Pause in the Controller configuration menu.

### What should have happened

Game is paused and emulator Pause menu is displayed, allowing you to change settings or exit the game

### Enumerate your devices

Rpi3

### How to reproduce the bug

Have a USB Gamepad mapped as usual, with SELECT as hotkey.
Start any PSP game from ES.
Press Hotkey + START to try to activate the emulator PAUSE menu.

### Workarounds

ESC button is already mapped of course, but needing a keyboard to exit is a hassle.
Manually map a button in PPSSPP that a PSP does not have., like L2/R2 or L3/R3.

**Comment by substring** [comment]
I'll look into this. But the problem will surely be worse for people playing with SNES pad ...

**Comment by RupertAvery** [comment]
Thanks! I tried using a PS3 controller and the PS button as Hotkey seemed to work fine.  (Not so sure, will try it again)

One other thing, how does configgen setup the controller mapping?  It appears you need to explicitly set the controller you want to play with to Input #1 in order to get it to work in PPSSPP.  It would be cool if the controller you launched with became player 1.

**Comment by substring** [comment]
We don't have such information as which pad launched. You didnthe right way by forcing P1 as it's the only player that is configured for ppssop

**Comment by lackyluuk** [comment]
Same issue with my 8Bitdo NES30 Pro. I cannot access the PPSSPP menu nor exit the emulator. It also does not respond when I press L, R, L2 or R2 Buttons

**Comment by substring** [comment]
Ppsspp is no retroarch core + ppsspp doesn't handle key combo. The behaviour for now is :
-HK opens ppsspp menu
- you can exit ppsspp through this menu

I tested HK as L3 or the Playstation button, it worked fine.

**Comment by substring** [comment]
@lackyluuk @RupertAvery looks like ppsspp dosn't handle well when the hotkey is assigned to a key that is already mapped for the PSP controls

Please make sure you do not set your hotkey to something else than L3 R3 or hotkey when available

**Comment by lackyluuk** [comment]
@substring great, this works now. Thanks :)
But the L + R buttons are not working in the game. E.g. I cannot play GTA China Wars, because I cannot break the car window in the beginning. There is no action with L+R. 
8bit Nes30 pro is configured properly in ES

**Comment by RupertAvery** [comment]
I also found I had to manually remap my L and R buttons in PPSSPP to get them working. My gamepad is a ps1/ps2 to usb adapter

**Comment by pablomacaluso** [comment]
I had the same problem. Im using a PC USB Generic Control. ( Like PS2 controller )
Still have this issue.

I change it de HK to R3 and works fine. But when i want to exit other emulators i cant. 
Thats the same problem? 

Sorry for my english, im from Argentina

**Comment by substring** [comment]
@pablomacaluso the hotkey+start combo should work in other emulators. I've never had any problem

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0

use the usual Retroarch combos
