### ISSUE TITLE
bootscreen error

### ISSUE THREAD

**Issue by advertime** [recalbox/recalbox-os#1207]
### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

When I installed Recalbox on my 32GB micro SD card it all worked fine. The Pi was rebooting but then I got this error on my screen

Someone who can help?
![file_000 1](https://cloud.githubusercontent.com/assets/26068086/23371779/9024ea66-fd19-11e6-84c2-133a104aeb27.jpeg)
![file_000](https://cloud.githubusercontent.com/assets/26068086/23371780/904ed182-fd19-11e6-93b9-d37d25e82438.jpeg)

I retried the installation 3x times and it always gives me the same error

**Comment by rockaddicted** [comment]
Github is a place to talk about dev issue, not to do users support.
Thanks to use the [forum](http://forum.recalbox.com/) and open a post for that.

See you next ++
