### ISSUE TITLE
[4.1.0-unstable] Upload screenshot in ROM management from web

### ISSUE THREAD

**Issue by pillabichos** [recalbox/recalbox-os#1209]
The new ROM management allows to edit data about a ROM but there some thing may be improvement:
- Allow upload an image, screenshot or cover.
- Respect the information supplied by local user when rescraped.
- Allow upload and complete some databases (f.e.: screenscraper) suggesting your own information.

**Comment by rockaddicted** [comment]
I don't know if @DjLeChuck watch this repo.
The new recalbox manager have his own issue repo https://github.com/DjLeChuck/recalbox-manager/issues

**Comment by DjLeChuck** [comment]
Nop I'm not watching this. Thanks for the redirection rock. :)

**Comment by rockaddicted** [comment]
you are welcome dude. I close this issue, lets continue here : https://github.com/DjLeChuck/recalbox-manager/issues/30
