### ISSUE TITLE
[4.0.2] [Buildroot] Update S40network to mount network filesystems in fstab

### ISSUE THREAD

**Issue by pwatk** [recalbox/recalbox-os#1213]
Please consider adding **mount -a** to the S40network init script to facilitate mounting any network filesystems present in fstab and move the Emulation Station init script to start after the network is up e.g. S41emulationstation.

I understand this involves the user editing fstab to make use of this and I also understand that changes to fstab may not persist after an update. However, this would make life easier for the people who want to use a network share to store roms.

Patch: [S40network.txt](https://github.com/recalbox/recalbox-os/files/812150/S40network.txt)

**Comment by rockaddicted** [comment]
The way to mount a network fs has been reworked. So I close this issue.
