### ISSUE TITLE
[4.1 unstable RPI] add optionnal dispmanx support in retroarch for lower input lag

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#1215]
Could you add dispmanx support in retroarch? It's currently the only driver with low display lag on RPI.

adding --enable-dispmanx to the retroarch ./configure is all thats needed to compile the support ,so it should work from retroarch.sh build_retroarch()

You can leave GL by default, and if you want to use dispmanx, all you have to do is change the video driver in retroarch menu.

more info here:
https://github.com/RetroPie/RetroPie-Setup/issues/744

**Comment by rockaddicted** [comment]
dude, don't need to open twice you issues... Check before open a new one : https://github.com/recalbox/recalbox-os/issues/973

**Comment by bigboo3000** [comment]
sorry I forgot about this!
