### ISSUE TITLE
[4.1 unstable] gamepad mapping problem for colecovision with the game H.E.R.O

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#1217]
This game is currently unplayable, when I press a button it seems to reset the game, other colecovision games are working fine.

**Comment by rockaddicted** [comment]
Thanks for this feedback, but if it is a specific game issue and don't impact massively other games, I won't investigate on that.
This game is available on other platforms `Atari 2600, Apple II, Atari 5200, Atari 8-bit, ColecoVision, Commodore 64, MSX, SG-1000, ZX Spectrum`.

I close this issue, but if you find other coleco games impacted, please feel free to change the title and reopen this issue.

**Comment by paradadf** [comment]
Just for the record, I remember that the donkey kong version (not the regular, but the enhaced or whatever it is called from the no-intro romset) has the same issue.

**Comment by bigboo3000** [comment]
I found a third game with the same problem : River Raid.

Like in H.E.R.O. sometimes when you press a button or the dpad, the game restart at the begining of the level. It happens almost all the time in H.E.R.O, and very often in River Raid, particulary at the very begining.

**Comment by bigboo3000** [comment]
@rockaddicted I can't reopen this issue because you closed it and not me.

**Comment by rockaddicted** [comment]
As said before if a very low minority of games are impacted, I won't fix.
