### ISSUE TITLE
screenshots on pc version

### ISSUE THREAD

**Issue by anibalardid** [recalbox/recalbox-os#1225]
hi, I'm using pc version 64 bits, 4.1 unstable.
I cant take screenshots.
I tried via web manager using screenshots button. And nothing happened.
And via ssh with raspi2png it doesnt recognize command.

best regards !

**Comment by substring** [comment]
raspi2png is a pi only tool to take screenshots from the GPU mem

@DjLeChuck could you consider disabling this option on the web manager when `/recalbox/recalbox.arch` showy something else than rpi* ?

**Comment by rockaddicted** [comment]
@substring  yep indeed raspi2png is a RPI specific tool. But we should add a similar tool on PC builds and why not on odroids builds too.

**Comment by paradadf** [comment]
Here some alternatives:
https://wiki.archlinux.org/index.php/taking_a_screenshot

**Comment by substring** [comment]
@rockaddicted odroids use framebuffer, but not videocore could try https://fbgrab.monells.se/
X86 uses X11, not framebuffer -> xwd

There are more important matters for now, retroarch can take screenshot anyway. So the non screenshotable systems are quite limited
