### ISSUE TITLE
[4.1 unstable][ES] Can't leave a Dreamcast game without reboot the Raspberry Pi 3

### ISSUE THREAD

**Issue by hamdyaea** [recalbox/recalbox-os#1227]
### What happened
I play with Tony Hawk Pro skater 2 on Dremacast or Crazy Taxi. The hotkey + start don't work and i have no solution to leave the game to come back to the Recalbox menu.

### What should have happened
I press hotkey + start and leave the Dreamcast game.

### Enumerate your devices
Raspberry Pi 3 Model B, Micro SD Class 10, PS3 controller, Belkin Bluethtooth dongle, Micro SD Class 10.

### How to reproduce the bug
Open a Dreamcast game. Try to leave it. Press Hotkey + start.

**Comment by substring** [comment]
Just press hotkey, not the usual hk+start combo

**Comment by hamdyaea** [comment]
I tryed all the keyboard and ps3 controller button but I can't leave a Dreamcast game without rebooting the Rapsberry Pi 3. Please don't close it.

**Comment by substring** [comment]
I'm closing it because this is no issue. Have you tried what i suggested ?

**Comment by hamdyaea** [comment]
Yes I tried it and many other things but it don't work at all.

**Comment by substring** [comment]
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
