### ISSUE TITLE
[4.1-beta][ES] Yellow ES text doesn't show correctly in-game

### ISSUE THREAD

**Issue by Oinksauce** [recalbox/recalbox-os#1237]
### What happened
When saving a state, or selecting a slot in which to save a state the yellow text only shows a series of little yellow squares.  This happens with other items such as retroachievement status updates as well.

### What should have happened
Should have said "state saved to slot x" when saving state, or achievements etc

### Enumerate your devices
Raspberry Pi 3

### How to reproduce the bug
Updated to 4.1 from the 4.0.1 original install.

**Comment by guythnick** [comment]
In the ~/configs/retroarch/retroarchcustom.cfg  file, change :
video_font_path = ""
to:
video_font_path = /recalbox/share_init/system/.emulationstation/themes/recalbox/data/ubuntu_condensed.ttf

**Comment by Laddyacris** [comment]
Hello
you have 4.1 ? but what version ? because this problem has been corrected.

**Comment by Oinksauce** [comment]
Thought I was using the most recent version, however the update today 3-24-2017 resolved this issue.
Thanks - closing.

**Comment by sismo99** [comment]
I Got the latest version )Downloades The RBPi 3 image and get the little squares how cai fix it thanks

**Comment by R041** [comment]
It looks like the Retroarch font isn't configured properly.

You'll need to add the line "video_font_path = /storage/assets/xmb/retroactive/font.ttf" to the Retroarch Config located here: /recalbox/share/system/configs/retroarch/retroarchcustom.cfg
