### ISSUE TITLE
[4.0.2] pHAT DAC "hifiberry-dac" not working in Recalbox

### ISSUE THREAD

**Issue by Cleantex** [recalbox/recalbox-os#1238]
The pHAT DAC card use the same chip as the hifiberry-dac (PCM5102a) and use the same dtoverlay.
In Recalbox 4.0.x I didnt arrive to make it working, so I decided to go back to Raspian Jessie to first test if hardware and compatibility where ok.

I changed /boot/config.txt in Raspian Jessie with

 commenting
#dtparam=audio=on

adding
dtoverlay=hifiberry-dac
dtoverlay=i2s-mmap

that was everything necessary to make, and the DAC card was working.

In Recalbox all modifications where unsuccessfully, it wa even not easy to stop the internal driver.
In Recalbox,there is no /etc/modules file but a file /etc/modules.conf with the line snd_bcm2835 internal ALSA driver. Commenting it out was having no effect.

Only effect of stopping was to put a file alsa-blacklist.conf into /etc/modprobe.d with the content
blacklist=snd_bcm2835

So killing him was having no effet on loading the hifiberry-dac.
And I also dont understand how hifiberry-dac could appear in the list with choice hdmi-jack-auto ?

I have no problem to buy a new Hifiberry card, but doubt that it would be a difference, if in Jessie everything is ok with the pHAT DAC ?

Or perhaps not yet in 4.0.2 ? 

I use a Raspberry PI3

**Comment by Laddyacris** [comment]
Hello
this tutoriel can help you ?
https://github.com/recalbox/recalbox-os/wiki/Audio-HiFiBerry-%28EN%29

**Comment by Cleantex** [comment]
Thank you,
I think I perhaps understand. Recalbox is in different from Rasbian, in this that you have already 3 directories PI1,PI2,PI3 for installation and reading the Hifiberry issue, consider that DAC's PMC5102a should be connected by P5 Header, like older versions from this. My hope is that Hifibery DAC+ will work, so it is on it way to me. No clone anymore. And I will not blame your guys before I insert it ;)

**Comment by Cleantex** [comment]
So, today I tried with Hifiberry DACplus (Swizerland original board) and again the same....
Raspbian Jessie perfect, led on the board illuminated, it is there in the sound selection.
Recalbox, led stays off, no card recognized.
Now, users are always a little bit silly, but I have 25 years of informatic behind me.
So I can enter 5 lines of parameters.
I think that you have some mess in your software, I want just to see by my 2 eyes the Recalbox-Menu with in the Sound Settings a line with Hifiberry Card. Please post a picture...
Card is working (like the 2 other before)  in Raspbian, card ist not working (like the 2 other before) in Recalbox.
Or may be, your instructions are uncomplete or wrong ?

**Comment by substring** [comment]
Well, what you do not understand is that recalbox has nothing from raspbian. Absolutely nothing comes from raspbian.

The audio devices selection just outputs 3 fuxed values, you need recalbox 4.1 to get a selector of audio cards.

Does alsa find your dac ? Is the overlay compatible with the 4.1 kernel from recalbox ?

**Comment by Cleantex** [comment]
Hi,
I was relying on this chapter 
https://github.com/recalbox/recalbox-os/wiki/Audio-HiFiBerry-%28EN%29

So, I was assuming that DAC's work under Recalbox, including Kodi.
But as the card is not found at all, I just ask myself the question, what is the base of the upper chapter ?
If you know, that it dont works in Recalbox, you could make economy on money and time.
If this description was for unreleased version 4.1, why this is not mentioned there ???

**Comment by substring** [comment]
Have you at least read my message ? The audio selection was just some information like you can't get anything other than auto/hdmi/jack unless on 4.1. It never ever meant that no audio device other than the bcm2835 can work.

Again, does alsa find your card or not ? Which commands have you run to find out ?

Have you checked what `dmesg` outputs ? Are you sure the overlay you need is available on recalbox ?

Please keep your messages friendly, and provide some more technical information.

**Comment by Cleantex** [comment]
AlSA dont find the card. On the board of Hifiberry DAC+ (hifiberry-dacplus.dtbo in \boot\overlays\ you have an led that is lighted on when the card is connected. It never lights on in Recalbox. The card is not existing in Recalbox. I'am not angry with you, i'am angry about upper description that have no relation to an existing reality. DAC's dont work.

**Comment by Cleantex** [comment]
I just install 4.1.x unstable. And here he find the Hifiberry DAC+ card, I didnt try the other. Ok, in ALSAmixer you find now the beloved snd_BCM2835 as card 0 and the Hifiberry as card 1.
But now reason to open Veuve Cliquot, the driver is in working order, but neither in Recalbox or in Kodi you can configurate it, I dont know where I can stop BCM2835 and replace.

So finally this WiKi DAC story is fake news, because unrelated to a stable version and not yet fixed in the next. Better to put some warning or repeal.

**Comment by substring** [comment]
The wiki page you mentionned does work because it was written by a very reliable community member, and I translated his tutorial to english.

Looks like the audio output selection in ES hasn,'t been updated in the recalbox-buildroot project, it's just a matter of days. I've been testing it thoroughly with @rockaddicted and we're pretty satisfied with it

Meanwhile, you just need to write `~/.asoundrc` file that points to your DAC.

**Comment by rockaddicted** [comment]
Hummm...
If @lackyluuk said this DAC is ok on his recalbox, he wrote a wiki, so that is this DAC works on recalbox...
I don't see the interest of lying or loose time to redact a "fake wiki news"...
Maybe you don't understand it, or missed something in this wiki that can explains that don't work on your setup.

Anyways, github issue tracker is a place to track development bugs, not to resolves user side problems.
So, create a post on [our forum](https://forum.recalbox.com/) that you can use with your github ID.
Then send a notification to @lackyluuk to ask more explanations and his help.

And keeps in mind that this project is an open source, FREE project. We can't test compatibility and support all hardwares on earth.
So please, be less aggressive the next time if you want support... I don't really like your tone.

**Comment by lackyluuk** [comment]
@Cleantex I sent you a message in the forum. Let us discuss there and post the solution after or correct the wiki if needed :) see ya there
