### ISSUE TITLE
[4.1] I can't see some items from recalbox.local in my browser

### ISSUE THREAD

**Issue by pillabichos** [recalbox/recalbox-os#1240]
I access from the browser of my PC to the adress recalbox.local but the following elements shows all the time the wait icon:

- Audio.
- Controllers
- System
- Configuration

My version is 4.1.0-master-rpi2-2017-03-23-13-01-28-12832534

**Comment by kryptalivian** [comment]
Do a screen shot of the pc window if you would.

**Comment by substring** [comment]
@djlechuck any idea ?

**Comment by DjLeChuck** [comment]
@pillabichos can you launch the manager manually with SSH?

* Type `cd /usr/recalbox-manager2`
* Type `NODE_ENV=production PORT=3000 node dist/server.js`
* Go to http://recalbox.local:3000/
* Try to navigate to one of the page
* Look at your console if something went wrong
* When all is done, you can CTRL+C to kill the instance

**Comment by pillabichos** [comment]
I try these commands and I see the problem in the same circustances.
The console only shows this message:
`Find the server at: http://localhost:3000/`
But If I access with my mobile phone shows ok, the problems happends only with the computer.

**Comment by DjLeChuck** [comment]
Hum that's strange...

And can you see in your browser console if something happens?
With Chrome, hit `F12` -> `Console` tab or `Network` tab. 
Besides, it doesn't work with all of your browsers?

**Comment by pillabichos** [comment]
But this works in previous versions.
I try with mozilla firefox debugger and shows these message when I select ROM and any system:

> TypeError: Object.entries is not a function
Traza de la pila:
a@http://recalbox.local:3000/static/js/main.6eaf7284.js:1:15517

**Comment by DjLeChuck** [comment]
I'm on it: https://github.com/DjLeChuck/recalbox-manager/issues/39

Thank you!

**Comment by DjLeChuck** [comment]
@pillabichos your browser is not update. The portion of code doesn't work because it's only compatible with Firefox 47+ (but I will fix that, I only said this if you don't want wait a new version!)

**Comment by DjLeChuck** [comment]
@substring you can close this one please?
