### ISSUE TITLE
[4.1.0][Buildroot] Static IP Failure

### ISSUE THREAD

**Issue by xstrex** [recalbox/recalbox-os#1241]
### What happened
No matter what I've tried, I can NOT set a static IP address. 

After remounting / rw. 
/etc/network/interfaces:
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet static
address 192.168.2.41
netmask 255.255.255.0
gateway 192.168.2.1
dns-nameservers 192.168.2.7 192.168.2.1

reboot - DHCP address.. 
Been at this for hours, where oh where is dhcp configured???

**Comment by rockaddicted** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems.
If you needs support, please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
I'm closing this issue, see you on the forum.
