### ISSUE TITLE
[4.1 Alpha] [ES] Snes joysticks via GPIO doesn't work

### ISSUE THREAD

**Issue by betoesteves85** [recalbox/recalbox-os#1244]
---
Please fill the following form :

### What happened
First, excuse my English.
The controls appear in the input menu in Emulationstation but neither works.
I modified the lines in the recalbox.conf (controllers.gamecon.enabled = 1 and controllers.gamecon.args = map = 0,0,1,1) as I did in version 4.0.1, but it did not work.
### Enumerate your devices
Raspberry Pi3
### How to reproduce the bug
The controls appear in the input menu in Emulationstation but neither works.
I modified the lines in the recalbox.conf (controllers.gamecon.enabled = 1 and controllers.gamecon.args = map = 0,0,1,1) as I did in version 4.0.1, but it did not work.

**Comment by substring** [comment]
Hi,

There is a known issue with the gamecon driver. It has been fixed but not yet merged in unstable.

**Comment by betoesteves85** [comment]
Thanks for the answer.
Is there a way to fix it manually?



Em 02/04/2017 04:45, "Subs" <notifications@github.com> escreveu:

**Comment by substring** [comment]
I should provide you a fixed kernel module (which will be overwritten with every update until it's merged)

**Comment by betoesteves85** [comment]
I'd be grateful if you would send me this module.


Em 02/04/2017 07:03, "Subs" <notifications@github.com> escreveu:

**Comment by substring** [comment]
@betoesteves85 can you give a try to http://www27.zippyshare.com/v/D1ArSun2/file.html ?do you know where to place the file after ? should be in `/lib/modules/4.4.0-72-generic/kernel/drivers/input/joystick/gamecon.ko`

**Comment by betoesteves85** [comment]
Thank you so much. I'll try it

**Comment by betoesteves85** [comment]
Unfortunately, it still does not work.

Actually, the folder in lib/modules in my recalbox is 4.4.13-v7

**Comment by substring** [comment]
try http://www93.zippyshare.com/v/GYZuMYa0/file.html and drop it in `/lib/modules/4.4.13-v7/extra/`

**Comment by betoesteves85** [comment]
Thanks for the help! Now the only works in the emulationstation menu, but still off in the games. I configured on the emulationstation menu but it didn't work.

**Comment by betoesteves85** [comment]
Now I noticed that if I disconnect the USB devices, the gamepads work normally. Is it a kind of a conflict?

**Comment by substring** [comment]
The very first person who told me about the gamecon bug also had that problem ... it may just be player orders, i have no idea unless you plug everything and make a support archive from http://recalbox/help (http://recalbox.local/help if you're running mac/linux)

**Comment by betoesteves85** [comment]
https://file.ac/GIoNCmCTxUA/

**Comment by substring** [comment]
you forgot to plug your usb pad(s) ;)

**Comment by betoesteves85** [comment]
Sorry! hehe
https://file.ac/hy3ZOsLcmjg/

Please, help! I need to play DOSbox games! lol

**Comment by substring** [comment]
once you plug your USB pads, it kicks your gamecon pads to player 3 and 4, that's why

**Comment by betoesteves85** [comment]
So I always have to disconnect the USB controls to use the GPIO?

In version 4.0 I changed the order of the inputs through the EmulationStation menu. But it looks like even in version 4.1 Alpha this is not possible. I changed on the menu but not works in the game

Do you know of a way to get this without disconnecting the usb?


Thank you so much for the help .

**Comment by substring** [comment]
depends on emulators you use. Retroarch cores shouldn't be bothered by the players order you set. That may not be the case of all emulators though

**Comment by betoesteves85** [comment]
I'd like to use my GPIO controls in NES, SNES, sega genesis and Master System emulators.
I need to configure individually the retroach of each emulator?

**Comment by substring** [comment]
No, just change players order

**Comment by betoesteves85** [comment]
I can't do this. I disconnected the USB controls and configure e save a new configuration for only the snes emulator. I modified the snes.configfile line in recalbox.conf to load my custom configuration, but when I turned on the usb controls again, the GPIO controls stopped working. Neither did the USB controls work on the emulator.

**Comment by substring** [comment]
Because that's not how you shoyld configure custom controls. Plugging / unplugging pads changes the devices order ;)

You should stick to what you used to do before : change players order in ES. Nothing more

**Comment by betoesteves85** [comment]
It doesn't work. I changed the order in ES and the controls not working unless I disconnect the USB controls.
![p_20170420_083635](https://cloud.githubusercontent.com/assets/24824180/25229032/0fab3d0e-25a5-11e7-8276-da0d710eaac6.jpg)
I also tried changing the order in the retroarch without disconnecting the USB controls, but it did not work

**Comment by substring** [comment]
just tested pad order substitution, and it is indeed a miserable failure, must be a bug in retroarch. I'll have to dig ...

**Comment by betoesteves85** [comment]
Thank you so much for the help! I'll keep waiting for the solution. Good luck!

**Comment by substring** [comment]
A new unstable release was publixhed yesterday. The gamecon driver is ok but not the retroarch problem. If you're feeling adventurous, i'm running an updated build with retroarch 1.5.0 so that you can confirm your issue is solved. I'll tell you how to get the update if you're ok to test. Once tested and solution validated, you can switch back to the unstable release

**Comment by betoesteves85** [comment]
I'll test. Can you tell how can I get the update?

Thanks

**Comment by substring** [comment]
HEre is the procedure:
- edit recalbox.conf
- set updates.type to `gitlab/74-pad-reordering-doesn-t-work-anymore-in-retroarch`
- update recalbox
- confirm it's solved ^^
this update branch has the gamecon update, as well as the new unstable that was released a few days ago

**Comment by betoesteves85** [comment]
WORKS FINE NOW!!!

Thank you so much!!!

**Comment by kadugamero** [comment]
@substring , I talked with @betoesteves85 on facebook because I'm with the same problem. I got his config file (reclabox.config), but not working yet. Can you help me? Thanks,

**Comment by substring** [comment]
The gamecon should work fine, but the pas reordering will be solved in the next unstable

**Comment by kadugamero** [comment]
The steps that you told to betoesteves working yet?

"Updates.type to gitlab/74-pad-reordering-doesn-t-work-anymore-in-retroarch"

**Comment by substring** [comment]
the update is deleted after a month,. Anyway, that was mainly for the pad reorder as the GPIO driver is fixed in the current unstable

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0
