### ISSUE TITLE
gamepad on recalbox doesn't work

### ISSUE THREAD

**Issue by recalbox-user11** [recalbox/recalbox-os#1246]
hi i installed recalbox on my rpi3 today and after the configuration i can't add my xbox one controller 
the os doesn't find it, why?
how can i fix ?
Please help me and excuse me for my english......

**Comment by Spaeda** [comment]
Hi

Same problem, I can't use my Xbox One S controller.
Not found in bluetooth and not detected when I use an USB cable.

**Comment by Laddyacris** [comment]
Hello @recalbox-user11 and @Spaeda 
please use forum for your problem. 
Xbox one work only recalbox 4.1 unstable.
