### ISSUE TITLE
[4.1] [ES] Dreamcast no audio

### ISSUE THREAD

**Issue by azvarel** [recalbox/recalbox-os#1247]
The dreamcast emulator is not working the sound, the boot already starts mute, I even thought it was a bios problem, I changed the bios, I changed regions by pressing start + a + b + x + y, I changed the isos, I made tests With several games in .cdi, .gdi and without success.

**Comment by Laddyacris** [comment]
Hello
do you have fresh install ? 
because my game on dreamcast no audio problem.

**Comment by azvarel** [comment]
@Laddyacris 

Solved! 

https://forum.recalbox.com/topic/6453/4-1-unstable-bug-reports/283
