### ISSUE TITLE
 [4.0.2][optional : KODI|ES] Only one Controller works

### ISSUE THREAD

**Issue by Babelini** [recalbox/recalbox-os#1248]
Hello Community

I just bought 2 USB Wireless Controller, that means 1 USB Dongle 2.4GHz which connect 2 Wireless Controllers. The Controllers are from Shanwan (China) they are Ps3 Dualshok Clones.
Now i tried to connect them to my Recalbox to play Mario Kart 64 whith 2 players.
When i connect one of them i can use one controller but the other one won't work.
When i connect the other controller (with configurate controller) it works, but the other controller won't work.
So i can use only one Controller at the same time :(

I tried to solve it in the config file but it doesn't work.

What can i do? I hope you can help me.

Thanks in advance

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
