### ISSUE TITLE
[4.0.1-stable][network] wifi cannot connect to a no password ssid.

### ISSUE THREAD

**Issue by wzhy90** [recalbox/recalbox-os#1252]
If your wifi ssid has no password, it cannot be connected!!!
Try other one has password that works.

**Comment by Laddyacris** [comment]
You need password for security.

**Comment by wzhy90** [comment]
@Laddyacris My home's wifi has set mac filter for connection. So I dont set any password.

**Comment by Laddyacris** [comment]
use forum for your request , it's not a bug. 
another member ask same information, you need to use search function in english or french category

**Comment by wzhy90** [comment]
Thanks
