### ISSUE TITLE
[4.1.0][ES] Start/Select button not working

### ISSUE THREAD

**Issue by sbowler** [recalbox/recalbox-os#1255]
### What happened
Used automatic built in functions in GUI to update to 4.1.0 from 4.0.2 after changing the conf file to unstable. Afterwards my controller that registers as xbox 360 controller (it's not really an xbox 360 controller) doesn't seem to work correctly. It seems as though most buttons work except the start and select button. This causes a lot of issues. So I also have no way to easily get into the menu to try to re-configure the controller. I'm a little confused and surprised that no one else seems to have this issue.

### What should have happened
All previously working buttons should keep working. 

### Enumerate your devices
Raspberry PI 2. Here's a log message of the controller
lvl2: 	Approximative device found using guid=030000005e0400008e02000014010000 name=Microsoft X-Box 360 pad)
lvl2: 	Added known joystick Microsoft X-Box 360 pad (instance ID: 0, device index: 0)

### How to reproduce the bug
Configure a xbox 360 controller with 4.0.2. Update to 4.1.0 (unstable).

**Comment by sbowler** [comment]
[InputConfigInfo.txt](https://github.com/recalbox/recalbox-os/files/923150/InputConfigInfo.txt)

I've attached some output from my current input configuration. Hopefully that can help you see what might have gone wrong. I've only attached one controller to this since installing Recalbox.

**Comment by Laddyacris** [comment]
Hello
Have you remapped your controller?
You have to do it under recalbox 4.1.0.

**Comment by sbowler** [comment]
I though all upgrades are pretty much seamless? I thought that was part of the user friendly goal. No way to re-map buttons if select and start don't work. I had to delete my inputConfig file in order to get it to work, but I didn't think that was the normal upgrade process. I'd suggest considering adding another way to get to the settings menu.

**Comment by substring** [comment]
@sbowler I guess you missed the _unstable_ part of "4.1.0 unstable" ;)

**Comment by sbowler** [comment]
I'm aware it's marked unstable, but this was not listed as a known issue so I thought maybe there was an unknown issue here to bring to your attention. It sounds like this is expected, at least for the time being and will be fixed prior to 4.1.0 release.

**Comment by substring** [comment]
I guess the known issues page is outdated ;)

Anyway, a fix is done on dev side to migrate the Xbox pads configuration from 4.0.xto 4.1 + a simple manual remap solves the problem, so ne reason to keep this issue opened ;)
