### ISSUE TITLE
5.5 c2 odorid cpu core / psx

### ISSUE THREAD

**Issue by blaze2051** [recalbox/recalbox-os#1257]
### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

### What happened
Os only detects 1 core instead of 4 on the c2 board and psx games run really slow unplayable.

### What should have happened

Os needs to use all 4 cores and makes psx playable at least

### Enumerate your devices
odriod c2

### How to reproduce the bug
install Os on C2

**Comment by substring** [comment]
Hi

Are you running batocera ?

**Comment by blaze2051** [comment]
Yes 5.5

**Comment by substring** [comment]
We are not the batocera devs nor do we give any support for it.
