### ISSUE TITLE
[Last Updated Recalbox] - NDS Rom - BIOS missing 

### ISSUE THREAD

**Issue by cristo1985** [recalbox/recalbox-os#1258]
Hi,
i wanna add nds game trough webpage inside recalbox. It says when I go to Nintendo Family Computer Disk System section and try upload I see this message:

This system requires one or more bios file that are missing from your installation:

disksys.rom

What I must do for get working with nds games?

Thanks

**Comment by substring** [comment]
Why are you mixing up NDS and FDS ? Nintendo DS emulation has never been
part of recalbox ...

**Comment by cristo1985** [comment]
Oh sorry I thought recalbox can emulate ds roms.... Is there a trick that we can play ds games? Or I must create a dual boot recalbox and retropie?

**Comment by substring** [comment]
It's nit that simple to add an emulator, it requires some advanced linux knowledge.

I'm colsing the issue, please start a thread on the forum if you want to keep talking about tgis subject.

**Comment by cristo1985** [comment]
ok thanks
