### ISSUE TITLE
Kodi version upgrade & PS4 controller?

### ISSUE THREAD

**Issue by dreamscape440** [recalbox/recalbox-os#1261]
When will the kodi version be upgraded to the latest version as support for many add ons on 15 is running out and a lot of them have stopped working for me (works fine on my other Pi which runs version 17).

Also, does the PS4 controller work on blue tooth on the current latest version of Recalbox?

**Comment by lackyluuk** [comment]
Kodi 16 is available with recalbox 4.1 (try the latest unstable if you are curious). The Kodi version depends on the buildroot development status and not on the recalbox team. 
the internal bluetooth works with 4.1
