### ISSUE TITLE
Is it possible to have 2 controllers on only one usb entry?

### ISSUE THREAD

**Issue by benjdum59** [recalbox/recalbox-os#1263]
Is it possible to have 2 controllers on only one usb entry? I'm on 4.0.1 version.

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
