### ISSUE TITLE
Wifi is not working

### ISSUE THREAD

**Issue by nozil33** [recalbox/recalbox-os#127]
I setup wifi but wifi does not want to connect.
on command line interface, ifup wlan0 does not manage to get an answer from dhcp server.

My wifi usb dongle works fine with other raspberry pi projects...

I use the latest version (3.2.7)

**Comment by hstampfl** [comment]
can you provide more information about your wifi dongle... eg. manufacturer, model?

**Comment by nozil33** [comment]
it.s the one sold by the pihut, sorry i don't have more precise info on it
you.ll find it here http://thepihut.com/products/usb-wifi-adapter-for-the-raspberry-pi

is there a way to give you more precise information (os command, even in windows) ?

**Comment by nozil33** [comment]
doing some research :  chipset in dongle is ralink rt5370

**Comment by digitalLumberjack** [comment]
I'll take a look, but there are some strange issues with drivers and firmware for wifi...

**Comment by Dermiste** [comment]
Hello, I am having the same issue here ! I just copied and paste a working config from an old project, and I cannot get to connect to my router ...
Wifi model soon

**Comment by Dermiste** [comment]
I cannot find which chip it is (don't know how to find), but I originally bought it from a list of compatible hardware for Raspberry's.

**Comment by Inglebard** [comment]
Hi, 
I have an issue pretty similar.
I have a edimax dongle and i can't connect to wifi.

But I notice something strange.
I set password and ssid in wpa_supplicant.conf, check my interface file what seems right (even if i don't really interstand the difference between wpa-roam and wpa-conf).
And when I connect the raspberry 2 with cable, the wifi works too. why ?

**Comment by nadenislamarre** [comment]
wifi error should be fiexed in 4.1.
