### ISSUE TITLE
[4.0.1] raspberry pi 2, cant install vnc to stream to screen

### ISSUE THREAD

**Issue by ArnavJain13** [recalbox/recalbox-os#1270]
### What happened
I found out that i cant install vnc, when i tried to install it through the comandline(F4, Alt+F2). 
### What should have happened
I thought i could cast the screen, not controls just the display to a remote device since my pc monitor doesnt have hdmi and i would like  it on my phone too. 
I just need the display i have the gpio controller setup properly
### Enumerate your devices
I have a raspberry pi 2 and a android device to stream the display to
Is there another way to stream the display to my phone wired or wireless?

**Comment by rockaddicted** [comment]
Indeed you can't install by yourself some new software. We are using an embed linux, build from scratch, without any package manager and we didn't planned to add vnc software.

So if you need this software, you'll have need to built your own custom recalbox image, using buildroot and our wiki.

I close this issue.
