### ISSUE TITLE
Rotate the touchscreen

### ISSUE THREAD

**Issue by RisverRassert** [recalbox/recalbox-os#1271]
Hi, I can not rotate the 7 "raspberry touch screen and I would need a tutorial step by step thanks and sorry for my english

### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
