### ISSUE TITLE
Recalbox 4.0.1 cannot connect to network

### ISSUE THREAD

**Issue by JohnWayne01** [recalbox/recalbox-os#1272]
Just got recalbox 4.0.1 on my raspberry pi 3 model b. I can't get it to connect to my network via wifi or ethernet. I have tried multiple ethernet cables with wifi both on and off. Tried turning my pi off and back on and reinstalling recalbox. I can't figure out why it wont connect to the network.

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
