### ISSUE TITLE
Two different joysticks (Gasia and Shanwan)

### ISSUE THREAD

**Issue by ricardoclaus** [recalbox/recalbox-os#1273]
Hello guys,
I am using Recalbox 4.1 with internal bluetooth.
I have two wireless joysticks, makers Gasia and Shanwan, both are generic, unofficial gamepads of the PS3.
My question is if I can use both synchronized joysticks at the same time.
In the configuration of the drivers in the recalbox.conf, which driver do I put?
Thank you!

**Comment by substring** [comment]
Hey !

Gasia and shanwans have different initialization routines. Give a try to the official driver, the bluez one doesn't work (yet ?) With gasia. As for my personnal experience, i couldn't make both work together

**Comment by ricardoclaus** [comment]
Thanks for the support.
I'll do a test here and come back then.
In order for me to be able to use both wireless / bluetooth joysticks efficiently, does the two gamepads have to be the same model and manufacturer?

**Comment by kryptto** [comment]
Hey Subs!  I was going to post this same sentiment.  I am patiently awaiting bluez updating the driver.

On Jun 18, 2017 8:39 AM, Subs <notifications@github.com> wrote:

Hey !

Gasia and shanwans have different initialization routines. Give a try to the official driver, the bluez one doesn't work (yet ?) With gasia. As for my personnal experience, i couldn't make both work together

**Comment by substring** [comment]
Hey kryptto ! Long time no see !

Let's say we are using some patches from one of the main contributers to bluez, these patches have never been merged into bluez but work rather fine. I don't expect the author to work again on them soon (i've spoken with him a few months ago). So unless i patch the patches ... Making gasia work was already quite a pain !

So from my (limited) perpective, the only combinations that should successfully work are shanwan + genuine with the bluez driver, or gasia+genuine using the official driver.

**Comment by ricardoclaus** [comment]
What if I use two shanwan, or two gasia?
This way it would work well?

**Comment by substring** [comment]
It should. I could pair 3 shanwans without a hitch. And I own just 1 Gasia

**Comment by ricardoclaus** [comment]
I was able to use the two gamepad controls, using the "official" driver.
It worked normally.
Thanks for the support.
