### ISSUE TITLE
Use External USB HD

### ISSUE THREAD

**Issue by ricardoclaus** [recalbox/recalbox-os#1274]
Gentlemen,
I have an external 1TB USB HD. I would use it in Recalbox, connected to Raspberry Pi3. This HD uses power via the USB cable.
The intention is to use the external storage to put the Roms.
Can anyone tell me if I can use this HD as an external storage in Recalbox 4.1?
Thank you!

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
