### ISSUE TITLE
[4.1][ES] ellow ES text doesn't show correctly in-game

### ISSUE THREAD

**Issue by slowdown** [recalbox/recalbox-os#1276]
### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

### What happened

When saving a state, or selecting a slot in which to save a state the yellow text only shows a series of little yellow squares. This happens with other items such as retroachievement status updates as well.

### What should have happened

Should have said "state saved to slot x" when saving state, or achievements etc

### Enumerate your devices

Raspberry Pi 3

### How to reproduce the bug

Updated to 4.1 from 4.0.2

**Comment by substring** [comment]
That is a known bugs, many threads on the forum about it.
