### ISSUE TITLE
[4.0.2][ES] ps2 adapter not working anymore

### ISSUE THREAD

**Issue by alfredox123** [recalbox/recalbox-os#1279]
my generic ps2 to usb adapter doesnt work anymore since 4.0.1, however the adapter Works on my pc without problems

**Comment by rockaddicted** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on the recalbox forum where you can even log with your github account.
I'm closing this issue, see ya on the forum :)
