### ISSUE TITLE
Wi-Fi static IP problem in 4.1

### ISSUE THREAD

**Issue by AndCoderJr** [recalbox/recalbox-os#1280]
### What happened
I can not connect to my network using static connection, I did not have this problem with version 4.0.1, but when upgrading to 4.1 the connection does not work, I already configured /et /network/interfaces, but Always appears a random ip when I try to enter my network, something like 169.xxx.xx.
### What should have happened
Connect to static network.
### Enumerate your devices
Raspberry Pi 3 model B
### How to reproduce the bug
Trying to connect to a static network with version 4.1

**Comment by rockaddicted** [comment]
Hi, we are now using conman to manage wifi connection, so look at this file `/var/lib/connman/recalbox_wifi.config`

Anyways, 
issues are made to track bugs, not resolve user side problems ;)
Please post your topic on the recalbox forum where you can even log with your github account.
I'm closing this issue, see ya on the forum :)
