### ISSUE TITLE
N64 games Not loading and returning to Recalbox home screen 

### ISSUE THREAD

**Issue by Recalblox** [recalbox/recalbox-os#1283]
Dear Reader,
I know the issue has been brought up time and time again and I am sorry for waisting your time. But, through all the forums I have read, I have not been able to find a clear way to fix the issue. If you could please comment below to help me, I would be most great-full. If you do not know the answer please do not clutter the forum because it makes it harder for people who are just looking for answers.

**Comment by paradadf** [comment]
If you wanna get any help, use the forum for such support questions. Moreover, show what you've tried and give all relevant information. Refer to the forum threads you have read, etc, etc.
A minimum show of effort is expected before bothering helping.
Github is a development platform, not to solved user-side problems.
See you in the forum!
