### ISSUE TITLE
No Conif option on main menu 

### ISSUE THREAD

**Issue by joejsorrells** [recalbox/recalbox-os#1285]
Please fill the following form :

### Enumerate your devices
I noticed that I had 4 download options shown below but I only downloaded the top one. Should I download the others and copy them on to my SD card. I'm using a Raspberry Pi 3.

recalboxOS-4.0.1.zip
63 BytesrecalboxOS-4.0.1.zip.sha1
Source code (zip)
Source code (tar.gz)

**Comment by rockaddicted** [comment]
Hi, issues are made to track bugs, not resolve user side problems ;)
Please post your topic on the recalbox forum where you can even log with your github account.
I'm closing this issue, see ya on the forum :)
