### ISSUE TITLE
Add SPI support for MCP23S17

### ISSUE THREAD

**Issue by mortaca** [recalbox/recalbox-os#1289]
This is an improvement proposal, I am developing a project for a JAMMA to GPIO adapter and the only way is to use the SPI port with two MCP23S17 for the buttons, to make this output compatible with the DPI output it should be possible to place the CS (ChipSelect ) of the SPI port on any GPIO pin, this is possible without too much difficulty.

It would be very helpful to add this support for Recalbox so that my project can be developed in your platform and not be forced to use other systems.

Thanks in advance.

**Comment by excitecube** [comment]
This improvement proposal is very interesting,please add this support for Recalbox.

Thanks.

**Comment by substring** [comment]
That's the kind of thing that will take very much time to do

**Comment by mortaca** [comment]
I'm going to try with i2c bus to make it possible.
