### ISSUE TITLE
[4.0.1 - Final] Black screen at random time while start game

### ISSUE THREAD

**Issue by unStatiK** [recalbox/recalbox-os#1293]
I'm see black screen all time on this version, when run any game, but not at first run.
Tried another new sd card, but problem reproduced again. After reboot os any game guaranteed start without black screen. Then with it. At any time game start normally, after again with black screen.

My hardware :
RPi 3 model B

P.S. I hear sound always.

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)

+ this has been solved in 4.0.2, please upgrade
