### ISSUE TITLE
[4.0.2]hifiberry-dacplus pas reconnu/détecté

### ISSUE THREAD

**Issue by germainmarty** [recalbox/recalbox-os#1294]
Bonjour !
Tout d'abord merci pour ce projet tiptop.

Je suis confronté à un problème concernant le son.
Mon matos:
_RPi3
dac hifiberry-dacplus
l'alim qui va bien et une µSD de 8go
manette FC30pro et son dongle BT_

J'applique scrupuleusement ce tuto:
https://github.com/recalbox/recalbox-os/wiki/Audio-HiFiBerry-(EN)

Mais rien de sort de ma carte :-/
Elle fonctionne avec un OSMC qui va bien.

- Modification effectuées -

/boot/config.txt
```
# uncomment for lirc-rpi
dtoverlay=hifiberry-dacplus
```

/etc/asound.conf (création du fichier)
```
pcm.!default {
type hw card 0
}
ctl.!default {
type hw card 0
}
```

L'outil alsamixer ne me propose pas le dacplus...

Je suis en manque d'inspiration pour trouver des pistes !
Si vous avez un moment pour l'aiguiller.

Merci !

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
