### ISSUE TITLE
GPIO Increased Input

### ISSUE THREAD

**Issue by raspberrypi321** [recalbox/recalbox-os#1295]
Can u add more input to gpio like a separate analog input that will be detected as joypad analog stick even single is enough and existing gpio input has only 2 shoulder buttons "TRIGGERS" .Can two more shoulder buttons be added. I need it to make pi psp after releasal of recalbox os 4.1 stable.

Meaning

Up Down Left Right [exists on gpio]
A B X Y [exists on gpio]
analog up analog down analog left analog right [required on gpio]
left trigger right trigger [exists on gpio]
left shoulder right shoulder [required on gpio]

i can neglect 2nd player since i dont need it to add gpios.

Thanks!

**Comment by substring** [comment]
This would lean the pi would hve some digital to analog converters embedded, which is not the case. So no, we can't. There are some usb encoders tht support analog sticks like some 1P xinmo

**Comment by raspberrypi321** [comment]
and what about shoulder buttons

**Comment by substring** [comment]
Analog is analog. Be it a stick or a button. Still the same problem
