### ISSUE TITLE
[4.0.2] wired controller for xbox one (PDP brand) Not recognized

### ISSUE THREAD

**Issue by fabmind** [recalbox/recalbox-os#1297]
### What happened
Gamepad controler on USB (i correct the sound problem with (blacklist snd-usb-audio) jack on this pad and my usb keyboard)
But the pdp xbox one wired gamepad still not recognized on recabox 4.0.2.

model: https://www.amazon.fr/Manette-Afterglow-pour-Xbox-One/dp/B01K3VMBYS/

**Comment by wilviana** [comment]
Sorry for ask here, actually I don't know the best place to ask about this.

So, the wireless controller of xbox one is working on recalbox?

I tried to pair my xbox one controller, the raspberry pi 3 can find my controller (pad name:Xbox Wireless Controller) and display that my controller was paired. However doesn't work and a could not find the controller on configure screen.
I did not use a dongle.

**Comment by rockaddicted** [comment]
xbox one pads are supported on 4.1 only and using usb.
so you'll have to retry on this version once released.

anyways, github is not a support place, and before opening an issue, first post on forum to discuss of the point here.
if needed, we'll ask you to open a github issue.
