### ISSUE TITLE
4.1 on stable channel?

### ISSUE THREAD

**Issue by optyfr** [recalbox/recalbox-os#1298]
Installed 4.0.1 image last Saturday... After installation, an online update was immediately available, I thought it was 4.0.2 but it is in fact 4.1.0 from 07/09/2017, I've always been on stable channel, I'm still on that channel, but today I got 4.1.0 from 21/09/2017, what's wrong?
Fortunately it seems to work well, and I was able to connect my PS3 SIXAXIS controller with internal Bluetooth of my rpi3 and a Maxxter keyboard (after using bluetoothctl to get pin code)

**Comment by substring** [comment]
I'm glad this build works for you and you enjoy the 4.1 :) Despite it's not supposed to be on the stable branch yet and something is failing somewhere ... We're investigating :mag_right: :bug:

**Comment by substring** [comment]
solved ^^
