### ISSUE TITLE
Wiimote

### ISSUE THREAD

**Issue by JoshGelman** [recalbox/recalbox-os#13]
Not really a bug...
I see you've added bluez and cwiid in buildroot. I can successfully connect my wiimote, and it appears as a wiimote in /sys/bus/hid/. Now I just need to setup the config for input. How did you obtain the GUID for the other controllers? I'll post my scripts once it is working.

**Comment by digitalLumberjack** [comment]
Hi !
Do you have a special /dev/input/jsX corresponding to your wiimote ? If you don't, you cannot configure it yet, because no driver is loaded for the wiimote... Else you can configure it in emulationstation directly from the menu (it get automatically the guid)

To get the guid, it's directly from sdl : https://wiki.libsdl.org/SDL_JoystickGetGUID?highlight=%28%5CbCategoryAPI%5Cb%29%7C%28SDLFunctionTemplate%29 but it will be use

**Comment by JoshGelman** [comment]
When I connect the remote, 3 eventX's and 1 jsX are created in /dev/input/ (with a classic controller connected it creates 4 eventX's and 2 jsX's). When I go to the configure section from ES, it does not recognize the device when I'm prompted to hold a button.

**Comment by digitalLumberjack** [comment]
Hum ok. `jstest /dev/input/jsX`shows event when you press buttons ?

**Comment by JoshGelman** [comment]
Yes, perfectly. I think the issue is that I'm pairing the wiimote over SSH (on root), and the recalbox user is not getting access to it. Where can we place startup scripts? Please excuse me, I'm not experienced with buildroot systems.

Also, my bluetooth dongle is working, feel free to add it to the list: BCM2046B1

**Comment by JoshGelman** [comment]
Rather, where is the current startup script? For example, where/when is ES being started?

**Comment by digitalLumberjack** [comment]
/etc/init.d/S32emulationstation starts /recalbox/scripts/emulationstationLauncher.sh

**Comment by JoshGelman** [comment]
Okay, thank you. I'll look into SDL2 and see if I can get it functioning.

I added my script to the end of emulationstationLauncher.sh to test out pairing on boot, and it did not work. I'll mess around with that more later. The script is as simple as it gets:

hciconfig hci0 down
sleep 2
hciconfig hci0 up
sleep 2
hidd --connect <MY-WIIMOTE-HARDWARE-ADDRESS>

**Comment by digitalLumberjack** [comment]
Ok i see thread telling we are not the only ones having this issue...

**Comment by JoshGelman** [comment]
Same, looks like it may have been recently fixed:

https://code.google.com/p/dolphin-emu/issues/detail?id=6768

**Comment by JoshGelman** [comment]
This was mentioned as well:

https://wiki.archlinux.org/index.php/Gamepad#Mimic_Xbox_360_controller

Essentially, mapping it to the xboxdrv driver. Not a bad idea as a workaround

**Comment by digitalLumberjack** [comment]
You saw https://hg.libsdl.org/SDL/file/704a0bfecf75/README-linux.txt ?
Tell me if you have something

**Comment by JoshGelman** [comment]
Also interesting:

https://wiki.archlinux.org/index.php/Gamepad#Joystick_Input_Systems

No, I'll read it now.

**Comment by JoshGelman** [comment]
Posting for reference, first gen wiimote with classic controller:
idVendor:
    ATTRS{idVendor}=="0461"
    ATTRS{idVendor}=="0a5c"
    ATTRS{idVendor}=="0424"
    ATTRS{idVendor}=="1d6b"

idProduct:
    ATTRS{idProduct}=="4d75"
    ATTRS{idProduct}=="4500"
    ATTRS{idProduct}=="9514"
    ATTRS{idProduct}=="0002"

**Comment by JoshGelman** [comment]
So we need to set a udev rule adding ID_INPUT_JOYSTICK=1 to ATTRS{idProduct}=="4d75"  ATTRS{idVendor}=="0461"

**Comment by JoshGelman** [comment]
I created this rule:

KERNEL=="event*", SUBSYSTEM=="input", ATTRS{idProduct}=="4d75", ATTRS{idVendor}=="0461", ENV{ID_INPUT_JOYSTICK}="1"

I then use this script to connect the wiimote:

hciconfig hci0 down
sleep 4
hciconfig hci0 up
sleep 4
hidd --connect 00:17:AB:38:AB:BC


ES crashes immediately once the wiimote connects. HOWEVER, if I navigate to the config dialogue where it asks to hold a button on the controller, and THEN use that script to connect the wiimote, it does not crash and it recognizes the wiimote.

**Comment by JoshGelman** [comment]
I think the issue is that the rule creates 4 joysticks, as the wiimote + classic controller creates 4 event entries. I'll test by changing from event* to event6.

**Comment by JoshGelman** [comment]
Okay so that taught me something: the final event created (in my case, event6) does not contain all the buttons! I will try the other 3 and report back. Do you know of a way to map multiple event entries as a single joystick?

**Comment by JoshGelman** [comment]
KERNEL=="event*" can be removed, but this also results in 4 joysticks

**Comment by JoshGelman** [comment]
https://github.com/dvdhrm/xwiimote/issues/51

**Comment by JoshGelman** [comment]
Maybe forcing the joystick isn't the best solution. Another idea is to map the native buttons (what's being shown with jstest) to SDL_GameControllerAxis and SDL_GameControllerButton attributes, as per https://wiki.libsdl.org/CategoryGameController

**Comment by JoshGelman** [comment]
Another action plan would be to compile cwiid and wminput for recalbox

**Comment by digitalLumberjack** [comment]
That's a good plan, but i won't have time for now. I'll open an issue for
that.

Le Thu Feb 19 2015 at 14:19:53, JoshGelman <notifications@github.com> a
écrit :

**Comment by JoshGelman** [comment]
Great, thanks. Should I keep working on this or abandon until they're compiled?

**Comment by JoshGelman** [comment]
Just posted this on that issue as well, but this may be exactly what you need:

https://github.com/jgeumlek/WiimoteGlue

**Comment by digitalLumberjack** [comment]
I'll check that next week if i find a wiimote...
If you're brave enough you could try to compile the system and add your own package :) 
https://github.com/digitalLumberjack/recalbox-os/wiki/Compilation-%26-Modifications-%28EN%29

**Comment by JoshGelman** [comment]
Okay; I'll get around to it some time this week/end

**Comment by JoshGelman** [comment]
Update: I've been incredibly busy; haven't gotten around to working on this any more yet. I'll let you know when I do

**Comment by johanpoirier** [comment]
Any update on this issue?

**Comment by digitalLumberjack** [comment]
Wii controller added in 3.3.0. Thanks @nadenislamarre
