### ISSUE TITLE
[Feature Request] Save OR Load game automatically instead of AND

### ISSUE THREAD

**Issue by dem1980** [recalbox/recalbox-os#1302]
In 4.1.0 beta, we have the option to automatically load and save game.

It could be nice to separate those functions.
When i run a game, i would like to load the previous savegame (which is in slot -1 for example).
But when i left the game, i don't wanted to save the game in the slot -1 automatically.
If i want to save the game before i left, i press the "save to slot" shurtcut or i select the option in retroarch menu.

Thank you

**Comment by substring** [comment]
Hi,

Knowing which slot you've been using when playing is not something that is stored. So we can't find which savegame you've been using so far. We sadly can't do such a feature.

**Comment by dem1980** [comment]
Hi,

It seems that today, Recalbox forces those values.
If i set "Save / Load game automatically=Yes" in Recalbox Menu
So Recalbox forces "Save / Load game automatically" in Retroarch cfg :
```
savestate_auto_save = true
savestate_auto_load = true
```
If i set "Save / Load game automatically=No" in Recalbox Menu
So Recalbox forces "Save OR Load game automatically "
```
savestate_auto_save = false
savestate_auto_load = false
```
There is no way to Recalbox doesn't forced those values.
I am going in Retroarch menu and i set manually thoses options : 
```
savestate_auto_save = false
savestate_auto_load = true
state_slot = "-1"
```
And then i save the config file from Retroarch Menu.
But when i run a new game, Recalbox forces "savestate_auto_save" and "savestate_auto_load" with values from Recalbox menu. The param "state_slot" is ok.

**Comment by substring** [comment]
This is very true : we do set the auto savestate_auto vars as we offer an option in ES to autload the previous savestate. So those 2 paramaeters are written by recalbox at each start of an emulator.

Now regarding `state_slot` : it's not even documented in https://github.com/libretro/RetroArch/blob/master/retroarch.cfg so I don't know what is its purpose.

**Comment by dem1980** [comment]
Ok, i have no problem with `state_slot` so you could forget it ;-)

My problem is `savestate_auto_save` and `savestate_auto_load`.
It could be nice to have 2 options in Recalbox menu instead of only one.

So it is now in Recalbox menu : 
`Auto save/load savestate = Yes/No`
It could be nice to be : 
`Auto load savestate = Yes/No`
`Auto save savestate = Yes/No`

**Comment by rockaddicted** [comment]
Hello,   
so, even if in ES menu I split these 2 options `auto_load` and `auto_save`, behind I will be obliged to force them on `no` to reset them.
So that won't solve this issue.

I think, the best way to do in your case should be to append a config file with your custom options that will overwrite the generated ones.

**Comment by rockaddicted** [comment]
correction, I read carefully a second time and indeed could be able to split them.
But i don't know if could work.
When you use `auto_save` option, retroarch don't create a standard savestate.
It creates a file `game_name.state.auto`.  
And the `auto_load` option, loads this specific file.   

I didn't try to disable `auto_save` option, force a specific savestate slot, and try to load automatically this specified "manual/standard savestate" with `auto_load` option.

**Comment by dem1980** [comment]
If you split this option in 2, i can do what i need : 
```
## Set autosave/load savestate for all emulators (0,1)
global.autosave=0
global.autoload=1
```

I will look at add config file for now
