### ISSUE TITLE
Raspberry Pi Model B+ Black Screen on 4.0.1 and 4.0.2

### ISSUE THREAD

**Issue by jonmarcoreyes** [recalbox/recalbox-os#1304]
What happened:
Games would not launch and would produce a black screen. Any MAME roms would crash and go back to Emulation Station. Sound indicates that the game launched properly (SNES and NES)

What should have happened:
Games should launch properly, of course

Enumerate your devices
Raspberry Pi Model B+, EXTREME setting on OC

How to reproduce the bug
Launch any game

**Comment by rjonmarco** [comment]
Solution:
"edit recalbox.conf, set global.videomode to default" -substring @ IRC recalbox

**Comment by rockaddicted** [comment]
Hi, can we have more information about your screen ?

**Comment by jonmarcoreyes** [comment]
It was a 1024x 768 screen run with a VGA connector + HDMI to VGA adapter.
