### ISSUE TITLE
[Recalbox 4.1] some games from DOSBOX Impossible to play

### ISSUE THREAD

**Issue by betoesteves85** [recalbox/recalbox-os#1306]
I tried to play Prince of Persia on dosbox but it didn't work correctly.
When the game starts, the main character ducks and can't move, it's like an key was pressed.
I try to unplug my gpio controllers but it didn't work.

**Comment by rockaddicted** [comment]
GitHub is not a place to ask user support.
Please use the Recalbox forum.
