### ISSUE TITLE
[4.1]Ps3 controller does not work in Kodi

### ISSUE THREAD

**Issue by hgomezsa** [recalbox/recalbox-os#1307]
After pairing with cable my ps3 dual shock won't work in Kodi. 

The way to reproduce it is just pressing triangle on the paired controller. Kodi won't respond with ps3 controller after it starts

**Comment by rockaddicted** [comment]
Hello does it work in ES ? Ingame?

**Comment by hgomezsa** [comment]
I was reverting to 4.0.1 but update popup prevents the controller for working. Flashing 4.1 again. I will edit this reply with the answer :)

**Comment by hgomezsa** [comment]
After pairing controllers it seems that it is solved

**Comment by rockaddicted** [comment]
BT controllers needs to be reappaired / sync on 4.1 due to BT management evolution.
The reset button on gamepads may be used to reset pairing.

I'm closing this issue.
If you need any kind of user support, please use our forum first.
Thank you.
