### ISSUE TITLE
Recalbox 4.1 (stable)camera issue on Donkey Kong 64 

### ISSUE THREAD

**Issue by Karloxee** [recalbox/recalbox-os#1310]
Hello my issue is on N64 when y play Donkey kong 64 the camera zoom on Donkey Kong always when i play.I don't understand why because On Recalbox 4.0.2 I didn't have this bug moroever Mario 64 Paper Mario Rayman 2 and Conker's Bad Fur Day have issue. The N64 emulation is no perfect have some issue graphical and lag. Help me Recalbox Team's to improve n64 emulation 

Bonjour mon problème est sur N64 quand vous jouez Donkey kong 64 la caméra zoom sur Donkey Kong toujours et cela devient injouable.Je ne comprends pas pourquoi parce que sur Recalbox 4.0.2 je n'ai pas eu ce bug de plus Mario 64 Paper Mario Rayman 2 et Le mauvais jour de la fourrure de Conker a un problème. L'émulation N64 n'est pas parfaite avoir un problème graphique et lag. Aidez-moi à Recalbox Team pour améliorer l'émulation n64

**Comment by rockaddicted** [comment]
Hi we bumped gliden64 video plugin on last public release. Some games work better, some other have some regression... We'll see with a new bump version in the future.
N64 emulation is not perfect yet and rpi3 is a very limited hardware, so we can't do miracles.

Anyway,  on 4.1 release there a new N64 emulator, a retroarch core Glupen.
You can try it by pressing on select on your game, in ES, edit metadata, en switch emulator/core on libretro/glupen64.
With mupen64plus standalone version (the defaults one) there is some others video plugins (rice/n64).
You can try them too.

Anyway, github is not a place to do user support.
So please, the next time use the forum for this kind of request.

Let's use this issue tracker to track development issues/features.
Thank you.
