### ISSUE TITLE
[v4.0.0-build-170 2016/08/13 08:46] "Update not available"

### ISSUE THREAD

**Issue by peteer01** [recalbox/recalbox-os#1311]
When I try to update through System Settings, it does not matter if automatic updates are enabled or not, when attempting to update, I get "Update not available."

I have tried to /recalbox/scripts/recalbox-upgrade.sh after SSHing into the Pi3.  Here is the output:

# /recalbox/scripts/recalbox-upgrade.sh
--2017-10-14 20:10:12--  http://archive.recalbox.com/4/rpi3/stable/last/boot.tar.xz
Resolving archive.recalbox.com... 163.172.157.49, 163.172.157.55, 163.172.161.187, ...
Connecting to archive.recalbox.com|163.172.157.49|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-14 20:10:12 ERROR 404: Not Found.

None of my devices have any issues connecting to 163.172.157.49, and my other Recalbox was built with the same code, it was updated more regularly, but never had this issue.

**Comment by rockaddicted** [comment]
Updates from 4.0.0 aren't not supported.
you must do a clean install.
You can download files here : http://archive.recalbox.com/

Next time you need support, please use first the forum.
Issues traker must be used to track development issue/improvement, not to do support.
