### ISSUE TITLE
4.1 stable - Scrapes don't save for Mame

### ISSUE THREAD

**Issue by sibob** [recalbox/recalbox-os#1312]
### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

### What happened

UPDATE - I found out the gamelist is only saved when the system is fully shut down, restarting doesn't save the gamelist for me. 

All Mame roms are found and renamed properly, with images. On a reboot, everything is lost. I checked the gamelist after scraping, it remains at 0 bytes and empty. 

### What should have happened

Scraped names, descriptions and images should be saved

### Enumerate your devices

Raspberry pi 3

**Comment by rockaddicted** [comment]
Hi, your mame `gamelist.xml` file is corrupted. So close ES (F4 or `/etc/init.d/S31emulationstation stop`), delete your gamelist file, and restart.

Anyway, as explained in text that you didn't erase, GitHub is not a place to do user support. But one to track development issues/features.
So next time please use our forum first.

Thank you
