### ISSUE TITLE
Can't connect Gamepad Defender to RecalBox

### ISSUE THREAD

**Issue by SirMunkyHead** [recalbox/recalbox-os#1314]
Instaled RecalBox 4.1.0 on Pi3

connected my Defender Scorpion X7 to Pi3 and "Gamepad not Detected"

dmesg says:
[ 1438.993114] usb 1-1.4: New USB device found, idVendor=1345, idProduct=6006
[ 1438.993123] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1438.993130] usb 1-1.4: Product: USB Controller
[ 1438.993137] usb 1-1.4: Manufacturer:
[ 1438.993143] usb 1-1.4: SerialNumber: CF9B9100
Can somebody help?
on PC gamepad  is defined as a "controller xbox 360 for windows"

**Comment by SirMunkyHead** [comment]
search in Google find next
"sudo yum install xboxdrv
sudo xboxdrv --device-by-path 001:005 --type xbox360 --silent
xboxdrv 0.8.5 - http://pingus.seul.org/~grumbel/xboxdrv/ 
Copyright © 2008-2011 Ingo Ruhnke <grumbel@gmx.de> 
Licensed under GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> 
This program comes with ABSOLUTELY NO WARRANTY. 
This is free software, and you are welcome to redistribute it under certain conditions; see the file COPYING for details. 

Controller:        unknown
Vendor/Product:    1345:6006
USB Path:          001:005
Controller Type:   Xbox360

Your Xbox/Xbox360 controller should now be available as:
  /dev/input/js0
  /dev/input/event14"
How can I make it in recalbox?

**Comment by substring** [comment]
Hi,
Issues are made to track bugs, not resolve user side problems ;)
Please post your topic on [the recalbox forum](https://forum.recalbox.com) where you can even log with your github account.
 I'm closing this issue, see ya on the forum :)
