### ISSUE TITLE
Add Favorites will be deleted after Reboot the Rasperry Pi3

### ISSUE THREAD

**Issue by tobim80** [recalbox/recalbox-os#1324]
New Favorites will be deleted after reboot the Raspberry Pi3.

This will happend since the Update to Build 17.11.02 from Recalbox 4.1

It seems that the Gameboy games will be in the List after rebooting the Recalbox, but the N64 and SNES Favorites are delete. 

### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

**Comment by rockaddicted** [comment]
Hello, you must have a gamelist.xml issue on N64/SNES.
Delete your gamelist.xml files (once emulationstation stopped) and retry.

Anyway, github is not a place to do user support, but only to track development issue.
If you need support, please use our forum.

Thank you.
