### ISSUE TITLE
cwiid and wminput for recalbox

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#14]
Related to issue https://github.com/digitalLumberjack/recalbox-os/issues/13
In order to have wiimote working on recalbox, we should compile the drivers and add the support in frontend

**Comment by JoshGelman** [comment]
Look into this, it combines the multiple event entries from the wiimote into a single device (literally exactly what I needed):

https://github.com/jgeumlek/WiimoteGlue

**Comment by JoshGelman** [comment]
"The Linux kernel driver for wiimotes is pretty handy, but the extension controllers like the Nunchuk show up as separate devices. Not just that, extra features like the accelerometers or infared sensors also show up as separate devices. Not many games support taking input from multiple devices for a single player, so using a wiimote for tilt controls or using the wiimote/nunchuk combo is often not possible. WiimoteGlue acts to combine these into a synthetic gamepad, and adds some extra features to further improve usability."

**Comment by digitalLumberjack** [comment]
Closed too :)
