### ISSUE TITLE
allow special characters to scrapper + character limit

### ISSUE THREAD

**Issue by Energizing** [recalbox/recalbox-os#148]
can't scrap games with special characters (ex: X-MEN, F-ZERO)
and looks like there is a 4 characters limit, so scrapper is unable to find games like NBA JAM

**Comment by Raulval82** [comment]
Recalbox uses the standard scraper from Emulation Station? Because in any other distro I was able to scrap "The dig",  or F-zero... Only manual option...

**Comment by Energizing** [comment]
easily fixed but lumberjack will do it later, it's the default configuration of emulationstation, i guess the other distros did it manually too

**Comment by digitalLumberjack** [comment]
I did not modify the scrapper.

**Comment by alexan** [comment]
is there any update on this issue? Or a workaround which does not include manual metadata input.

**Comment by rockaddicted** [comment]
These games can now be scraper using screenscraper 
https://github.com/recalbox/recalbox-emulationstation/pull/159
