### ISSUE TITLE
bluetooth ASUS BT-211

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-os#155]
Bonjour
le dongle n'est pas détecté sous recalbox.

[  194.192286] usb 1-1.4: new full-speed USB device number 4 using dwc_otg
[  194.297324] usb 1-1.4: New USB device found, idVendor=0cf3, idProduct=3000
[  194.297350] usb 1-1.4: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[  194.303210] usb 1-1.4: Direct firmware load for ath3k-1.fw failed with error -2
[  194.303265] Bluetooth: Firmware file "ath3k-1.fw" not found
[  194.303307] ath3k: probe of 1-1.4:1.0 failed with error -2
^
Serait il possible de l'ajouter ?

On a essayé de l'ajouter manuellement dans le dossier /lib/firmwares/ sans succès

http://blog.recalbox.com/forums/topic/dongle-bluetooth-non-detecte/#post-2559
Merci

**Comment by digitalLumberjack** [comment]
Ok je vais regarder ca.

**Comment by nadenislamarre** [comment]
recheck in 4.1 version.
we support only linux/buildroot supported hardware.
