### ISSUE TITLE
Add airplay in Kodi

### ISSUE THREAD

**Issue by bbouko** [recalbox/recalbox-os#156]

**Comment by bobsoppe** [comment]
I alse would really like this

**Comment by gtkow** [comment]
Bonjour, 

je voulais savoir si effectivement c'est possible de compiler kodi avec la lib airplay? Et sinon quel sont les difficultés et surtout si on peut aider??

@++

**Comment by digitalLumberjack** [comment]
Salut, le seul problème de airplay sur kodi est qu'il nécessite avahi. Avahi (le deamon en tout cas) a fait pété la beta 7 parcequ'il empêche d'une façon ou d'une autre le réseau (le wifi) de se lancer. 
N'ayant pas le temps de passer du temps dessus, et airplay/kodi n’étant clairement pas la priorité de recalbox j'ai laissé ça en suspend. Si il te faut une beta avec kodi/airplay activé pour tester et essayer de le configurer pour qu'il laisse le wifi se connecter correctement je peux te compiler.

**Comment by xcybermanx** [comment]
Merci bien pour le boulot que vous faite merci de publier une version beta Avec air play activer

Merci

**Comment by substring** [comment]
@nadenislamarre c'est fait en 4.0.0 il me semble ? Je ne sais pas sur quel commit/PR
histoire de fermer l'issue ...

**Comment by nadenislamarre** [comment]
$ git log --oneline --author=nicolas.adenis.lamarre | grep -i airplay
b681f66 Kodi : add airplay required libraries to compile

$ git show b681f66
commit b681f6696e3ee4a770169e0d84fb63ed92ded476
Author: Nicolas Adenis-Lamarre <nicolas.adenis-lamarre@gmail.com>
Date:   Sun Dec 13 21:38:38 2015 +0100

    Kodi : add airplay required libraries to compile

    Signed-off-by: Nicolas Adenis-Lamarre <nicolas.adenis-lamarre@gmail.com>

**Comment by substring** [comment]
https://github.com/substring/recalbox-buildroot/commit/b681f6696e3ee4a770169e0d84fb63ed92ded476
@digitalLumberjack @rockaddicted issue can be closed

**Comment by rockaddicted** [comment]
nice
