### ISSUE TITLE
Scrapper issues in 3.2.9 beta 2

### ISSUE THREAD

**Issue by Raulval82** [recalbox/recalbox-os#169]
Hi,

The system crashes if I search for a game using "Thearchive" database, and some times manual scrapping is not saved.

**Comment by digitalLumberjack** [comment]
Hi, thanks for the report, we are already aware of that we will try to
correct this soon

**Comment by digitalLumberjack** [comment]
the archive has been removed by https://github.com/recalbox/recalbox-emulationstation/commit/f57c21d77338229f0d10915cba1eedf6e38876f9
