### ISSUE TITLE
[Request] Seperate partition for roms, saves, settings, etc 

### ISSUE THREAD

**Issue by C-Fu** [recalbox/recalbox-os#171]
This might have been implemented in Recalbox OS, but I'm not sure. Anyway, it would be awesome I think if everytime we restore from NOOBS our rom & save files would stay intact and not get "reformatted" so to speak. Possibly a FAT32 partition so Windows can see it, but this is not really necessary.

**Comment by digitalLumberjack** [comment]
Good idea but too much work and modifications on noobs. I won't do it for now. If someone is couragous enough you can begin with recalbox-rescue

**Comment by C-Fu** [comment]
I see. Didn't know how complicated my request was, but many thanks for the reply.

**Comment by hstampfl** [comment]
In retropie there is something like this, if you plug in an usb with roms on it, it will automatically copy them. Perhaps we could adapt it and do this auto symlink it as you mentioned.

**Comment by substring** [comment]
this has been done in 4.0.0 : the /recalbox/share can be moved on a USB key. And it's well integrated in recalbox/EmulationStation
I'm closing it :)
