### ISSUE TITLE
Trouver le moyen d'éviter aux enfants de voler nos recalbox...

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#179]
Après avoir essayé la recalbox de papa, beaucoup de jeunes joueurs s'approprient la recalbox sans vergogne.
- Ajouter un questionnaire au lancement ou certaines questions seront posés au joueur pour verifier son age.
- Q1 : Qu'est-ce qu'une VHS ?
- Q2 : En franc, combien valait un credit a "la tete dans les nuages" de sega ?

**Comment by harqun** [comment]
Q3 : qui est Rémy Bricka ?

**Comment by fmaida** [comment]
Q4: Qui était Goldorak? ;-)

**Comment by xaviusius** [comment]
Q4 : Qu'elle est le jeu phare du nokia 3310
Q5 : Le jeu "démineur" est un jeu Playstation ? Vrai / Faux

Avec ces 2 là en plus, je pense que tu auras une bonne protection ! :p

**Comment by dem1980** [comment]
Sinon simplement un code pin ?
Sinon c'est une issue sérieuse ou c'est le premier avril avant l'heure ? :)

**Comment by digitalLumberjack** [comment]
;) c'est lié a http://blog.recalbox.com/forums/topic/je-te-deteste-retroboy/

**Comment by nadenislamarre** [comment]
l'autorité parentale ne doit pas être electronique ;-)
