### ISSUE TITLE
N64 emu

### ISSUE THREAD

**Issue by laurin92** [recalbox/recalbox-os#186]
Hey,
I've got some problems with the N64 emu:
- controller mapping is diffrent then the one configured in emulationstation (using xbox360 wireless controller)
- most of the games don't run well (graphik mistakes, low fps)
- on composite video no game is shown. seems like it freezes, the hotkey button doesn't bring me back to the emulationstation.
rpi2 os v. 3.2.10

**Comment by kryptto** [comment]
Thanks Retroboy, wanna get my N64 on!

**Comment by rockaddicted** [comment]
updated core and plugins to the last commit
added gfx plugin rice with a switch to recalbox.conf

I recommand to overclock your RPI2 to use this emulator.

**Comment by rockaddicted** [comment]
Some TV don't seem be able to switch in VGA mod (640*480) properly.
So we have to add this to the `/recalbox/configs/mupen64/mupen64plus.cfg` file, and boot using the video mode 4.

```
[Video-General]

# Use fullscreen mode if True, or windowed mode if False
Fullscreen = False
# Width of output window or fullscreen width
ScreenWidth = 1280
# Height of output window or fullscreen height
ScreenHeight = 720
# If true, activate the SDL_GL_SWAP_CONTROL attribute
VerticalSync = False
```

**Comment by Dragda** [comment]
Can you add the Shanwan ps3 controller configuration?

**Comment by Guzilli** [comment]
I think the N64 Emulator in recalbox Beta 6 runs a lot better than on retropie. Tried Mario Kart 64 and it runs almost perfect even in two player splitscreen. Only minor slowdown when starting a race and a minimal audio delay. 

Wonder if there is anything to reduce audio delay. What about changing the Memory Split Value, could this improve anything?

**Comment by rockaddicted** [comment]
Auto full screen, ratio 4/3, with rice and n64 plugin is supported with the 3.3.0 beta 9

**Comment by digitalLumberjack** [comment]
@rockaddicted what do we do with this one ?

**Comment by rockaddicted** [comment]
We can't do more job on N64 emulation on rpi2 for the moment.
Only thing to add, is a configgen, and there is a specific issue opened about it.
I'll continue to update core/plugins on next recalbox versions.
So we can close it.

**Comment by digitalLumberjack** [comment]
A toi l'honneur.

**Comment by rockaddicted** [comment]
vous êtes trop bon.
