### ISSUE TITLE
add hifiberry dac support

### ISSUE THREAD

**Issue by colwyn1978** [recalbox/recalbox-os#191]
Is it possible to add support for hifiberry dac in recalbox or at least in the recalbox kodi?
Thank you!

**Comment by nekomania** [comment]
Please also add DAC+ and Digi to the list if it is possible, thanks!

**Comment by thorty77** [comment]
Please also add DAC+

**Comment by substring** [comment]
@nekomania @colwyn1978 @thorty77 are you sure they require a particular build ? Seems it may just be a single "boot command" to have it started

**Comment by thorty77** [comment]
@substring I tried all boot commands I know from Openelec where DAC+ works. But it doesnt work on recalbox.

**Comment by substring** [comment]
@thorty77 what commands did you try ?

**Comment by lackyluuk** [comment]
Is there any news about HifiBerry? Is it possible to get it to work with Recalbox? The audio jack sound is terrible :(

**Comment by lackyluuk** [comment]
Ok. Seems to work. I just had to change the config.txt dtoverlay=hifiberry-dac and it works perfectly. Good old config.txt  :) 

Think this issue can be closed.

**Comment by Gouigz** [comment]
@lackyluuk works for me to, but can't change the volume anymore in recalbox. The volume adjustment bar defaults to zero. Increase the volume has no effect.
No problem in Kodi.

Do you have this problem to ?

Thanks

**Comment by lackyluuk** [comment]
@Gouigz Yes you are right. I have the same problem. But I do not use the volume adjustment bar from recalbox. I adjust the volume by changing the control modules (amixer) from the hifiberry dac+ using the GPIOs. 

What is the default "dtoverlay = " value in the config.txt? Unfortunately I do not know it anymore. Maybe with the overriding of dtoverlay the drivers of the default raspi soundcard are not loaded at startup and the recalbox volume adjustment bar is controlling the default soundcard?

**Comment by Gouigz** [comment]
@lackyluuk thanks for answering so quickly !
you maybe right :-/ Excuse me if i am wrong but... using amixer isn't dynamic, right ? The volume is set in config file or in a cmd.

**Comment by lackyluuk** [comment]
you can either use alsamixer (graphical interface to access the audio controls) or use line commands like "amixer sset Digital (or whatever the control is called) to control the system volume. I wrote a small python script to set the amixer volume according to GPIO inputs. Or what do you mean with dynamic? :)

**Comment by Gouigz** [comment]
@lackyluuk Ok thanks. I will seek information about alsamixer.

**Comment by nekomania** [comment]
Thanks @lackyluuk for the config.txt setup tips, it now works great and it sounds amazing!
I am interested in the python script you wrote to control volume, can you tell us more about it? :-)

For the developers: according to the official hifiberry setup guide, the default volume of DAC+ at 100% will cause clipping and distortions, the command "amixer -c 0 set Digital 80%" will make things right.
Hope the audio settings will be integrated to the GUI in the future.

**Comment by lackyluuk** [comment]
@nekomania  Sure I can. Note that you must use a DAC+. The DAC light has no controls in alsamixer

You can use call from the subprocess module:
from subprocess import call
call(["amixer", "sset", "Digital", "--", "0dB"])
"Digital" is the name of the control that you want to change (sometimes its Master or whatever)
For "0dB" I just put a parameter which I change with the GPIOs and then concatenate the string. Instead of "0dB" write str(yourVolumeParam)+"dB". I recommend to use dB because the % is not the correct scale for volume. If needed I could send you the file somehow.

**Comment by substring** [comment]
@lackyluuk @nekomania @colwyn1978 shall I close it ? you "just" need to add an overlay and eventually play around with `amixer`

**Comment by lackyluuk** [comment]
@substring I do not have any problems with hifiberry anymore. All works fine. According to me you can close it

**Comment by substring** [comment]
Mind making a small wiki page about that ? I'd be grateful :)

**Comment by substring** [comment]
And if you do write a wiki page, please give it the same name in english and german (if you lready wanna translate). Say "audio-hifiberry-(EN)" and "audio-hifiberry-(DE)" :)

**Comment by lackyluuk** [comment]
I can do. I am in touch with @Nachtgarm. When I find some time i will set something up and give it to him for verifying ok?

**Comment by Nachtgarm** [comment]
@lackyluuk I'm in. Just let me know :)

**Comment by substring** [comment]
https://github.com/recalbox/recalbox-os/wiki/Audio-HiFiBerry-%28EN%29
@lackyluuk did it, thank you pal :)
