### ISSUE TITLE
Auto load and Auto save - FBA libretro

### ISSUE THREAD

**Issue by nickdj** [recalbox/recalbox-os#192]
I've added the following lines to retroarchcustom.cfg :

savestate_auto_save = true
savestate_auto_load = true

With FBA libretro:
I can see a file being saved called *.state.auto when I exit but when I start although it says "Auto-loading savestate from.." but the autosave doesn't load.

With PSX:
This is working without issues.

**Comment by lordtaki** [comment]
Since savestate_auto_save and savestate_auto_load work pretty well with retroarchcustom.cfg, it could be a good idea to have this feature available in the configuration menu instead of editing manually. What do you think?

**Comment by digitalLumberjack** [comment]
Good idea, can you open a new issue for this feature ?

**Comment by digitalLumberjack** [comment]
@nickdj did you tried again on the beta ?

**Comment by rockaddicted** [comment]
we will continue in this issue : https://github.com/recalbox/recalbox-os/issues/647
