### ISSUE TITLE
Add other libretro mames

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#193]

**Comment by hstampfl** [comment]
yeah, thanks, that would be great

**Comment by Churchill92** [comment]
Which other mame versions will you be supporting? Is there one you are going for first?

**Comment by digitalLumberjack** [comment]
@rockaddicted let's put that in 3.3.1 ?

**Comment by rockaddicted** [comment]
I won't have time to work on these cores the next days.
So if it is slowing down the 3.3.0 bêta release, we can put that in the 3.3.1.

BUT, if someone with build skills want to integrate them, no problem ;-D

**Comment by digitalLumberjack** [comment]
@hstampfl Do you  have time to try that  ?

**Comment by digitalLumberjack** [comment]
So it will be for a later release

**Comment by rockaddicted** [comment]
libretro-mame2003 core was added during recalbox 3.3.0 beta 10
libretro-mame2010 don't seems to have good performances on rpi.
So should we add it ?

**Comment by kryptto** [comment]
Poor performance only means complaints later. Keep the emulator running smoothly. You say RPI but does that mean RPI 2?  Maybe if it only performs poorly on RPI then include it and provide a warning for RPI 1 users. My two cents.

**Comment by Churchill92** [comment]
Define "poor performance". Screen tearing? Not loading roms? 

Add the updated version with a note stating poor performance under rp1.  

If this also has poor performance on rp2 then dont include it until a fix is known.

**Comment by Dragda** [comment]
Now with libretro-mame2003 we need a keyboard to type "OK" in order to start the games XD

**Comment by digitalLumberjack** [comment]
We will describe each libretro core in a specific issue
