### ISSUE TITLE
LIRC / X10 Remotes (for Kodi)

### ISSUE THREAD

**Issue by nickdj** [recalbox/recalbox-os#207]
I have found the following URL which may help.

http://archlinuxarm.org/forum/viewtopic.php?f=9&t=5940

Whilst there isn't any PS3 controller support in Kodi would it be possible to get this working instead?

**Comment by PreferLurking** [comment]
In x86 architecture sixad supports translating Dualshock events into keyboard input (keystrokes). This does not work in recalbox. I think it would be easier to figure out why this does not work here then to add lirc to the image. Unlike the lirc alternative, getting this feature of sixad working would not require any additional software or hardware.

**Comment by digitalLumberjack** [comment]
lirc supported in 3.3.0
