### ISSUE TITLE
Gert's VGA Adapter support

### ISSUE THREAD

**Issue by mgoulartBR** [recalbox/recalbox-os#210]
Hi again,

Could you add it a future release?

The Raspberry Pi has an HDMI port to connect a display. If your monitor only has VGA, you have to use an adapter. Because this requires a digital-to-analogue conversion, those adapters can be quite pricey, and they can draw lots of power. So our friend Gert van Loo (who developed the Alpha board that became the Raspberry Pi, and the man behind the Gertboard and Gertduino) has created a VGA adapter that uses the Pi’s GPIO.

https://github.com/fenlogic/vga666

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0
