### ISSUE TITLE
Problems with Scraper... 

### ISSUE THREAD

**Issue by mfwhite** [recalbox/recalbox-os#213]
Some games do not find the covers in scraper , even though with the correct name THEGAMEDB . How do I manually covers?

**Comment by digitalLumberjack** [comment]
Hi, you can edit the gamelist.xml files and add images in downloaded_images. All of this in /root/.emulationstation :)

**Comment by nickdj** [comment]
You can also try using the PC scraper.  It's not perfect but will find more game information and the game names are more accurate.  I created batch file to do this (on the forum) if you want to give it a go.

I scraped over 3000 nes, snes, gamegear, sega32x, gameboyadvance roms and it only missed a few hundred.  The reset I scraped with Recalbox so only about 50 are now missing and those are mostly PD and Demos.

(Note:  PSX games don't scrape via this method)

**Comment by rockaddicted** [comment]
A new scraper has been added. If the game is not found with this one, check your rom's name (base on no-intro romset) and/or add it upstream in the www.screenscraper.fr database.

https://github.com/recalbox/recalbox-emulationstation/pull/159

**Comment by dmschwartzii** [comment]
How do I delete all the scrape data?
