### ISSUE TITLE
Scummvm Day of tentacle screen issue

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#22]
When playing Day of the Tentacle in scrummvm it only shows a portion of the screen, about 4/5 of the total screen is displayed.

**Comment by digitalLumberjack** [comment]
Need to release the 3.2.3 today, will be corrected in 3.2.4

**Comment by hstampfl** [comment]
I do have this problem with all scummvm games

![scummvm_issue_screen](https://cloud.githubusercontent.com/assets/11168045/6400731/54dde3d6-bdfb-11e4-893a-d28ff687b9dd.jpg)

**Comment by digitalLumberjack** [comment]
Ok, i'm using a modiied version of scummvm from vanfanel http://www.raspberrypi.org/forums/viewtopic.php?f=78&t=96258 i'll test the standard version for now

**Comment by digitalLumberjack** [comment]
@hstampfl i tested with the standard version i have the same issue. Did you try many games? did you tried to change the resolution (with the menu CTRL+F5)
Can i let you see if you can find something ?

**Comment by hstampfl** [comment]
I do have a lot of scummvm games. I only installed 2 at the moment, but I can test with more of course.
When I press CTRL-F5 I do not have any option for change the resolution. When I go back to the launcher menü, I get some options for the graphic settings. for some of them I need to restart scummvm.
When I relaunch the system, it looses these settings. -> I will now try if I can do with a modification of your startup script.

**Comment by hstampfl** [comment]
@digitalLumberjack I did some investigation - there are several issues that need to be adjusted that scummvm really will be usable. ;)

1st: the screenissue i posted with my picture is caused from the starttype you set via runcommand.sh when scummvm will be started from emulatorlauncher.sh. The best starttype for scummvm is 1 or 3.

2nd: I recoginized that joystick is not working within scummvm. regarding the commandline help from scummvm there should be an option --joystick=x. I added this option in the emulatorlauncher.sh:
         /recalbox/scripts/runcommand.sh 3 "scummvm --joystick=0 --path=\"$dirName\" 

But this is not really working. I am currently looking into this.

**Comment by digitalLumberjack** [comment]
@hstampfl 1st: the screenissue i posted with my picture is caused from the starttype you set via runcommand.sh when scummvm will be started from emulatorlauncher.sh. The best starttype for scummvm is 1 or 3.

When i set 1 on Broken sword, i have 1/4 of the image on the screen, like a big bad zoom.
I think vanafel scummvm uses some information for the screen size that are not the appropriate ones...

I tried to compile and tun the original scummvm, but guess what, black screen, because of a sdl bug.

**Comment by digitalLumberjack** [comment]
I'll see for 3.2.6 as it's blocking the 3.2.5

**Comment by hstampfl** [comment]
it's for me no problem, I only post bugs und try to help to fix them ;)
I meanwile also tried to compile the libretro-scummvm core, but I haven't not figured out how to start the games there properly

**Comment by digitalLumberjack** [comment]
Yes the scummvm retroarch core compile with some patchs but i cannot run games on it.
I'm stuck with this one...

**Comment by Raulval82** [comment]
Any updates? I noticed that command --joystick=0 works, but the analog stick is not attached as mouse. The  screen issue is still there, I tried -f command for full screen but nothing happens...

**Comment by niekverw** [comment]
on my rpi2 its the other way around, i only see 1/4 of monkey island across the whole screen, where can i set the resolution?

**Comment by EwoutV6** [comment]
edit the emulatorlauncher.sh file in /recalbox/configs/ and change the "4" to "2" at this line:

"/recalbox/scripts/runcommand.sh 4 "scummvm --path=\"$dirname\" \"$filenameNoExt\"""

That will fix the screen resolution bug
changing this setting for other emulators also fixed other issues. Like the "no screen only sound" issue with the N64 emulator.

**Comment by digitalLumberjack** [comment]
@rockaddicted is it ok with the official scummvm sources ?

**Comment by MajinChibi** [comment]
Any solutions yet?

"Fixed it:
edit the emulatorlauncher.sh file in /recalbox/configs/ and change the "4" to "2" at this line:

"/recalbox/scripts/runcommand.sh 4 "scummvm --path=\"$dirname\" \"$filenameNoExt\""" "

doesnt work for me. What i can see changes (like a lot more zoom, so i cant see everything on the screen) but never fullscreen.

**Comment by substring** [comment]
Hi

Obviously this won't ve fixed in 3.3. Could you tell me at which screen resolution you want to play ?

**Comment by MajinChibi** [comment]
The native resolution of my tv is 1920x1080, but i would take anything, as long as its fullscreen ^^

**Comment by substring** [comment]
ok. The old launcher emulatorlauncher.sh doesn't handle better than 720p. The question is : at which resolution is ES running ? 720p our 1080p ?

I just tried on the dev version of 4.0.0; it's almost fullscreeen, just the game doesn't have a 16/9 ratio

**Comment by MajinChibi** [comment]
The TV info says ES is running at 1080p

http://abload.de/img/boarderbxs6r.jpg
Scummvm is also running on 1080p, but looks like this +.+

**Comment by substring** [comment]
I'm not sure i get the problem ... If it fits vertically, then perfect. But remember this game was programmed for a 4/3 screen ratio. Therefore i don't see any problem

**Comment by MajinChibi** [comment]
mh i can see a little difference
http://abload.de/img/mario5ssed.jpg (4/3 game, recalbox nes, tv info says 720p)

aaaand
http://abload.de/img/mi3boarderu2sv0.jpg (4/3 game, recalbox scummvm, tv info says 1080p)

i can spot a little black boarder in scummvm ^^ 

When it would git vertically it would be awesome (even though streched option would be nice too ^^ )

Scummvm in retropie was able to do that, but i like recalbox much more +.+

Thanks for you replys!

**Comment by substring** [comment]
as i told you : it won'"t be solved in 3.3, and i don't have this problem on the dev 4.0.0. I suggest you try 4.0.0 when it's publicly available

**Comment by MajinChibi** [comment]
sorry, i thought, you couldnt see the problem ^^

Okay, thank you :)

**Comment by rockaddicted** [comment]
fixed in recalbox v4.0.0
