### ISSUE TITLE
fba semble créer un fichier de log à la racine de la carte SD

### ISSUE THREAD

**Issue by dem1980** [recalbox/recalbox-os#221]
Il serait plus logique de le déplacer ailleurs, genre en /recalbox/configs/fba/output.log à moins qu'un autre dossier de log existe.

**Comment by digitalLumberjack** [comment]
Effectivement

**Comment by digitalLumberjack** [comment]
Must be corrected for the ro root.

**Comment by digitalLumberjack** [comment]
corrected with https://github.com/recalbox/pifba/commit/419faa7c3967560f6fa149f2f78b5aedca5b123a
