### ISSUE TITLE
Les captures d'écran de ScummVM se mettent à la racine de la SD

### ISSUE THREAD

**Issue by dem1980** [recalbox/recalbox-os#222]

**Comment by pierrrrrrre** [comment]
Hi @dem1980, could you provide the following info?
- Version of Recalbox used
- ScummVM games tested
- Steps to reproduce the issue

I'll then try to reproduce your problem.

Salut @dem1980 , est-ce que tu peux fournir les infos suivantes ?
- Version de Recalbox utilisée
- Liste des jeux ScummVM avec lesquels tu as testé
- Liste des étapes à suivre pour reproduire le problème

Avec ces infos j'essaierai de reproduire le problème.

**Comment by digitalLumberjack** [comment]
Must be corrected for ro root.

**Comment by digitalLumberjack** [comment]
@rockaddicted what about this one ? can you reproduce ?

**Comment by rockaddicted** [comment]
I'll check that and configure paths on share partition if needed.

**Comment by digitalLumberjack** [comment]
@rockaddicted should be corrected the same way as https://github.com/recalbox/recalbox-os/issues/580
