### ISSUE TITLE
3rd PS3 controller cant be sync on rpi2

### ISSUE THREAD

**Issue by ynizon** [recalbox/recalbox-os#224]
I can connect all my PS3 (dualshocks) controllers, but only 2 at the same time. 
The 3rd cant be sync on the rpi 2. 
On rpi 1 they works all on  the same time .

**Comment by darkymtp** [comment]
Same here.
I've tested only on RPi2.

**Comment by digitalLumberjack** [comment]
Idem here,

2015-04-27 9:38 GMT+02:00 darkymtp <notifications@github.com>:

> Same here.
> I've tested only on RPi2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalLumberjack/recalbox-os/issues/224#issuecomment-96539142>
> .
>



-- 
DigitalLumberjack
@digitaLumberjak

**Comment by MatPie78** [comment]
Same here. Is there allready a solution for this?  The third ps3 controller won't work :(.

**Comment by digitalLumberjack** [comment]
That's really weird. The driver is the same on both rpi1 and rpi2...

**Comment by digitalLumberjack** [comment]
could be fixed with the branch https://github.com/recalbox/recalbox-buildroot/tree/unified-4.0.0 and the https://github.com/recalbox/recalbox-os/issues/520

**Comment by ynizon** [comment]
ok it's fixed in v4. Thanks :)
