### ISSUE TITLE
Support for standard bluetooth controller

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#23]
to me : get a bluetooth controller and add the support of standard bt controller in recalboxOS

**Comment by digitalLumberjack** [comment]
Thank to people that made donations on the website, i commanded a bluetooth controller, i will be able to add en entry in menus in order to associate a controller to the recalbox.

**Comment by Laddyacris** [comment]
Bonjour j allais ajouté une issues mais je pense que c est ici que c est le mieux
as tu ajouté dans le mode bluetooth la possibilité de se connecter avec la commande
hidd --connect aa:bb:cc:ee:ff:gg ?

**Comment by digitalLumberjack** [comment]
Oui tu peux déjà faire ca manuellement. J'ai connecté ma NES30 de 8bitdo, ca marche mais le pad directionnel ne fonctionne pas, juste les boutons.

**Comment by Laddyacris** [comment]
Oui manuellement je peux le faire mais je dois sortir d emulationstation , connecter la manette puis relancer emulationstation.
Je dois refaire la manipulation à chaque démarrage
ça serait bien que la manette se connecte au démarrage automatiquement
J ai pu configurer la manette
 j ai pas le souvenir pour ma part d un problème sur les directionnels.
Je vais refaire des tests.

**Comment by frthery** [comment]
@digitalLumberjack: oui il s'agit d'un BUG dans le firmware de la manette, la croix est reconnu comme un keyboard, on en parle ici: http://www.open-consoles-news.com/2014/10/raspberry-pi-realiser-une-retro-gaming.html

Pour régler le problème, il faut passer sur le firmware 2.5 et démarrer la manette en mode joystick "START + R"

**Comment by digitalLumberjack** [comment]
Super cool merci je regarde ça

Le dim. 1 mars 2015 à 17:40, SpikeSpiegel <notifications@github.com> a
écrit :

**Comment by antde** [comment]
il semblerait qu'avec bluez le nes30 fonctionne comme il faut, ça serait possible de l'intégrer dans une release ?

**Comment by reivaax** [comment]
Une psite en passant. J'ai trouvé ce projet sur le forum de 8bitdo pour gérer des manettes bluetooth.
https://github.com/Death259/PiAssist

Peut-être qu'il y a quelque chose à faire avec ça :)

**Comment by arzouille** [comment]
Bonjour,

Tout d'abord félicitations pour al release, elle est vraiment top et correspond parfaitement à ce que je cherche.
Une petite question concernant le branchement d'une manette bluetooth. Je suis un vrai newbie en linux, j'aimerai savoir comment ajouter ma manette 8bitdo NES30. Comment j'ouvre le terminal, quelle ligne de commande je dois taper. Si je pouvais avoir un auto pour méga débutant ça serait super.

**Comment by rockaddicted** [comment]
Hello, si je ne dis pas de connerie les manettes 8bitdo sont supportés qu'en filaire pour le moment. Il faudra attendre une prochaine version de recalbox pour voir leur support arriver.

**Comment by arzouille** [comment]
Ok merci de l'info.

**Comment by digitalLumberjack** [comment]
O yeah ! Supported in 3.3.0
