### ISSUE TITLE
Dongle Wifi : Firmware rtlwifi/rtl8188eufw.bin not available

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-os#230]
Bonjour
juste un firmware manquant ajouté dans une prochaine realase 

Firmware rtlwifi/rtl8188eufw.bin not available

Voici le contenu de dmesg :
[ 3.222121] usb 1-1.4: new high-speed USB device number 6 using dwc_otg
[ 3.322578] usb 1-1.4: New USB device found, idVendor=0bda, idProduct=8179
[ 3.322604] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 3.322615] usb 1-1.4: Product: 802.11n NIC
[ 3.322626] usb 1-1.4: Manufacturer: Realtek
[ 3.322637] usb 1-1.4: SerialNumber: 00E04C0001
[ 3.402068] usb 1-1.5: new low-speed USB device number 7 using dwc_otg
[ 3.522544] usb 1-1.5: New USB device found, idVendor=046d, idProduct=c521
[ 3.522569] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 3.522580] usb 1-1.5: Product: USB Receiver
[ 3.522592] usb 1-1.5: Manufacturer: Logitech
[ 3.545253] input: Logitech USB Receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.5/1-1.5:1.0/0003:046D:C521.0004/input/input3
[ 3.545897] hid-generic 0003:046D:C521.0004: input,hidraw3: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-bcm2708_usb-1.5/input0
[ 3.572216] input: Logitech USB Receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.5/1-1.5:1.1/0003:046D:C521.0005/input/input4
[ 3.632650] hid-generic 0003:046D:C521.0005: input,hiddev0,hidraw4: USB HID v1.11 Device [Logitech USB Receiver] on usb-bcm2708_usb-1.5/input1
[ 3.715231] r8188eu: module is from the staging directory, the quality is unknown, you have been warned.
[ 3.722528] Chip Version Info: CHIP_8188E_Normal_Chip_TSMC_D_CUT_1T1R_RomVer(0)
[ 3.747996] random: nonblocking pool is initialized
[ 3.753972] usbcore: registered new interface driver r8188eu
[ 7.875193] smsc95xx 1-1.1:1.0 eth0: hardware isn’t capable of remote wakeup
[ 7.875427] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[ 17.275223] r8188eu 1-1.4:1.0: Direct firmware load for rtlwifi/rtl8188eufw.bin failed with error -2
[ 17.275262] r8188eu 1-1.4:1.0: Firmware rtlwifi/rtl8188eufw.bin not available
[ 17.275277] MAC Address = c4:6e:1f:20:05:50
[ 17.284671] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[ 17.339468] usb 1-1.4: USB disconnect, device number 6
[ 17.340061] R8188EU: ERROR indicate disassoc
[ 88.533073] bcm2708_fb_pan_display(0,0) returns=16
[ 399.036827] usb 1-1.2: USB disconnect, device number 4
[ 421.032038] usb 1-1.4: new high-speed USB device number 8 using dwc_otg
[ 421.132510] usb 1-1.4: New USB device found, idVendor=0bda, idProduct=8179
[ 421.132530] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 421.132542] usb 1-1.4: Product: 802.11n NIC
[ 421.132553] usb 1-1.4: Manufacturer: Realtek
[ 421.132564] usb 1-1.4: SerialNumber: 00E04C0001
[ 421.135576] Chip Version Info: CHIP_8188E_Normal_Chip_TSMC_D_CUT_1T1R_RomVer(0)

solution , ajouter le firmware manuellement : 
wget https://github.com/lwfinger/rtl8188eu/blob/master/rtl8188eufw.bin
cp  ~/rtl8188eufw.bin /lib/firmware/rtlwifi/rtl8188eufw.bin

Conversation : http://blog.recalbox.com/forums/topic/cle-wifi-realtek-non-supportee/

**Comment by mxjoe** [comment]
As my french is pretty poor I am not sure I did understand above completely but I think it's because of missing firmware file rtl8188eufw.bin in recalbox distribution.
I have a pretty common WiFi dongle which is using this chipset and therefore my WiFi isn't working out of the box.

So I suggest, please add rtl8188eufw.bin to the folder /lib/firmware/rtlwifi to make WiFi dongles using this chipset working. If you need the firmware file please let me know, I got it and tested it.

**Comment by rockaddicted** [comment]
firmware ok in recalbox 4.0.0
```
# ls -la /lib/firmware/rtlwifi/rtl8188eufw.bin 
-rw-r--r--    1 root     root         13904 Dec  7 03:17 /lib/firmware/rtlwifi/rtl8188eufw.bin
```
