### ISSUE TITLE
dosbox libreto core

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-os#233]
Bonjour
est il possible d'ajouter dosbox :D https://github.com/libretro/dosbox-libretro

**Comment by NerosTie** [comment]
Doublon : https://github.com/digitalLumberjack/recalbox-os/issues/4

**Comment by digitalLumberjack** [comment]
Will not be in 3.3.0

**Comment by substring** [comment]
same as #4 though the libretro core may not be the best option for it, but rather the standalone
