### ISSUE TITLE
Kodi : Addons lists are empty for any repo 

### ISSUE THREAD

**Issue by Gog0** [recalbox/recalbox-os#235]
On recalbox 3.2.11 with a raspberry pi B rev 1 when trying to browse addons to download, the lists are empty even with custom repo installed via USB.

Doesn't seem to be a network problem (the scrapper works correctly in emulationstation).

I got these 3 lines in kodi logs each time it tries to get the addons list:

    ERROR: Open - Unhandled exception
    ERROR: Open - Error opening http://mirrors.kodi.tv/addons/gotham/addons.xml.md5
    ERROR: Failed to fetch checksum for directory listing http://mirrors.kodi.tv/addons/gotham/addons.xml for repository repository.xbmc.org.

**Comment by nadenislamarre** [comment]
Works in 4.0.
Kodi upgraded in 4.0 and in 4.1 again.
