### ISSUE TITLE
SD partitions can no longer be mounted in Linux

### ISSUE THREAD

**Issue by nicosensei** [recalbox/recalbox-os#236]
Hi,

I recently upgraded from 3.2.10 to 3.2.11. On the former version, when I plugged my SD card (via an USB reader) to my Linux PC (Linux Mint 17.1, so Ubuntu based), the various partitions on the SD card would automount. This was very convenient for transfering roms (so much faster than Samba!) and backup/edit configuration files.

Since 3.2.11 it doesn't work anymore. Inspecting the SD card partition layout with GParted shows warnings and an extended partition that holds all partitions but the recovery. Might this be an OpenElec issue?

**Comment by digitalLumberjack** [comment]
Hi,
I updated to ubuntu 15.04, and the new kernel added a feature that produce a bug with extended partitions reading.
If you have the last version of linux mint, it could be that. Otherwise try 'sudo partprobe' and then 'dmesg' to see what happen.

**Comment by nicosensei** [comment]
I run Mint 17.1, so yes latest version, but it is based on Ubuntu 14.04.2 and run a 3.13 kernel. I believe 15.04 uses a more recent kernel.

I'll try to set up VMs with regular Ubuntu 14.04 and 12.04 to see what happens. 

I'll report on my findings.

**Comment by nicosensei** [comment]
One thing worth to mention I run my Mint 17.1 as a VM on a Windows 8.1 host. Still I could access the sd partitions on 3.2.10 with this setup.

**Comment by digitalLumberjack** [comment]
Ok weird. The partprobe did nothing ?

**Comment by t-moreau** [comment]
Hi,

This problem affects Ubuntu 14.04.2 and 15.04 (and probably its derivatives, such as Linux Mint 17.2 LTS).

There is a conflict between the msdos partition table (MBR) and the ADFS partition table, both present on the SD card.

NOOBS (the Operating System install manager for the Raspberry Pi) writes these two partitions tables on the SD card for compatibility reasons (RISC OS is unable to boot without the ADFS partition table).

The ADFS partition was ignored in older versions of Ubuntu (prior to 14.04.2), but not in the recent versions (such as 14.04.2 and 15.04).

This issue has been reported to the Ubuntu team but the bug has been considered as "Invalid". This issue has also been reported to the NOOBS team but the issue has been considered as "wontfix".

As a workaround, you can use dd to zero out the ADFS partition table. For more info, see:

Ubuntu Bug#1457526 "recognized partitions incomplete on 14.04.2 and 15.04"
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1457526

NOOBS Issue#262 "partition table conflicts when plugging SD card to newer ubuntu 15.04/14.04.2 kernel"
https://github.com/raspberrypi/noobs/issues/262

**Comment by nadenislamarre** [comment]
fixed if you burn the sd card from the img and not from noobs.
