### ISSUE TITLE
Add dosfstools 

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-os#238]
Bonjour
si j'ai bien compris le package dosfstools permet de corriger l'altération des fichiers à la manière de chkdsk sous windows et de les réparer
Il serait intéressant pour être de l'ajouter dans recalbox-OS ça pourrait servir à ceux utiliser des périphériques externes (clé usb ou disque dur externe) pour réparer les problèmes de corruptions de données directement via putty.
http://daniel-baumann.ch/gitweb/?p=software/dosfstools.git

Exemple :

on disque dur n’a pas été démonté correctement :[ 7.493459] FAT-fs (sda1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
Il semblerait qu’il soit altéré
[ 20.340397] FAT-fs (sda1): error, fat_get_cluster: invalid cluster chain (i_pos 35283238)

On voit bien que ton disque dur est en lecture (RO) et non en lecture et écriture (RW)
/dev/sda1 on /recalbox/share type vfat (ro,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)

Résultat sous recalbox : 
fsck /dev/sda1
fsck (busybox 1.23.1, 2015-03-23 23:20:34 CET)
fsck: fsck.vfat: No such file or directory
# umount /dev/sda1
# fsck /dev/sda1

fsck (busybox 1.23.1, 2015-03-23 23:20:34 CET)
fsck: fsck.vfat: No such file or directory
# fsck.vfat /dev/sda1

-sh: fsck.vfat: not found

**Comment by nadenislamarre** [comment]
done in 4.1
