### ISSUE TITLE
Compatibility with wifi dongle ASUS WL-167G V3

### ISSUE THREAD

**Issue by JehanApathia** [recalbox/recalbox-os#239]
The wifi dongle ASUS WL-167G V3 is not supported yet by Recalbox.

It is a verified peripheral of RPI : http://elinux.org/RPi_USB_Wi-Fi_Adapters
Maybe it could help :)

Thanks!

**Comment by mxjoe** [comment]
This is a duplicate of issue  #230: https://github.com/recalbox/recalbox-os/issues/230

Please close.
