### ISSUE TITLE
Ajout de crédits jeux CPS FBALibretro

### ISSUE THREAD

**Issue by NeeeeB** [recalbox/recalbox-os#251]
Sur plusieurs jeux CPS3 dans FBALibretro il est impossible de mettre des crédits avec le bouton select du joueur 1.
Le seul moyen pour moi (j'utilise le GPIO) est de mettre des crédits à l'aide du bouton select du joueur 2.

On many CPS3 games in FBALibretro i'm unable to add credits with the player 1 select button.
Only way to do it (i'm using GPIO) is by using the player 2 select button.

**Comment by digitalLumberjack** [comment]
Hi,
is select your hotkey ? If so, can you test with an other buton as the hotkey (L2, R2)

**Comment by digitalLumberjack** [comment]
@NeeeeB ? :)

**Comment by NeeeeB** [comment]
Yeah sorry i totally forgot to make a feedback.
I've tried with another button as hotkey (L2) and it works.
;-)
