### ISSUE TITLE
Website transaltion - traduction du site web

### ISSUE THREAD

**Issue by AldoFerrari** [recalbox/recalbox-os#252]
I could help to make the website recallbox.fr translated and multilanguage.
it is in your plan?

Je purrai aider à rendre le site recallbox.fr traduit et multilingue.

**Comment by AldoFerrari** [comment]
You should add the wordpress plugin https://wordpress.org/plugins/polylang/ to your wordpress website to have the possibility to have all your pages transalted. You could even give right to transaltors to translate pages without touching wordpress setting.

You should activate a plugin to optimise SEO (https://wordpress.org/plugins/wordpress-seo/) to be more visible on the search engines even in other languages not only french

suggestions:
install plugin to optimise your database like https://wordpress.org/plugins/wp-optimize/
install a plugin to automatically Backup your website and database like https://wordpress.org/plugins/backupwordpress/

**Comment by nadenislamarre** [comment]
@digitalLumberjack this issue should not be here, can we close it ?

**Comment by digitalLumberjack** [comment]
Yep
