### ISSUE TITLE
exit from KODI turn off my tv

### ISSUE THREAD

**Issue by AldoFerrari** [recalbox/recalbox-os#254]
I have a Samsung smart tv.
I use the recalbox v 3.2.11

when I go on the power off button on cody --> on the menu I press EXIT; it exit from kodi but  it turn off also my TV.

**Comment by Bluelightcrew** [comment]
You can disable this in settings from kodi

**Comment by digitalLumberjack** [comment]
We should set a default preferences for kodi where this doesn't happen anymore.

**Comment by Cissoubaka** [comment]
Did you set some CEC configuration in kodi ?

**Comment by Cissoubaka** [comment]
Ok I think i have the solution
when playing with CEC setting a file rpi_2708_1001.xml is created with the default configuration, if we overwrite the file, maybe it's solve the issue
content of file :
http://pastebin.com/U2pj9MQb

**Comment by Cissoubaka** [comment]
Ok I think i have the solution
when playing with CEC setting a file rpi_2708_1001.xml is created with the default configuration, if we overwrite the file, maybe it's solve the issue
content of file :
http://pastebin.com/U2pj9MQb

**Comment by Cissoubaka** [comment]
there is also a setting to add in the xml file :  hdmi_ignore_cec set to 0 or 1 to disble or activate CEC

**Comment by digitalLumberjack** [comment]
<settings>
    <setting id="activate_source" value="1" />
    <setting id="cec_hdmi_port" value="1" />
    <setting id="cec_standby_screensaver" value="0" />
    <setting id="cec_wake_screensaver" value="1" />
    <setting id="connected_device" value="36037" />
    <setting id="device_name" value="Kodi" />
    <setting id="device_type" value="1" />
    <setting id="double_tap_timeout_ms" value="300" />
    <setting id="enabled" value="1" />
    <setting id="pause_playback_on_deactivate" value="1" />
    <setting id="physical_address" value="0" />
    <setting id="port" value="" />
    <setting id="send_inactive_source" value="1" />
    <setting id="standby_devices" value="231" />
    <setting id="standby_devices_advanced" value="" />
    <setting id="standby_pc_on_tv_standby" value="13011" />
    <setting id="standby_tv_on_pc_standby" value="1" />
    <setting id="tv_vendor" value="0" />
    <setting id="use_tv_menu_language" value="1" />
    <setting id="wake_devices" value="231" />
    <setting id="wake_devices_advanced" value="" />
</settings>

(the pastbin will  expire soon)

**Comment by fschaefer** [comment]
The related entry seems to be `<setting id="standby_devices" value="231" />` and valid values are defined in [PeripheralCecAdapter.cpp#L53](https://github.com/xbmc/xbmc/blob/f8c153570320e9650a0c5d11f8fa1c184693be92/xbmc/peripherals/devices/PeripheralCecAdapter.cpp#L53).

I've edited the entry in `rpi_2708_1001.xml ` on my box without touching the settings menu in Kodi and the TV stays powered on.

**Comment by Didlith** [comment]
hello 
on Kodi i modify cec setting 
at the Line device to power off when stopping Kodi  set option to none 
validate 

and retest 
for me when i stopped Kodi my TV and my Ampli cannot stop

cdly

**Comment by digitalLumberjack** [comment]
Let's try that

**Comment by Laddyacris** [comment]
Bonjour
si je suis sur kodi puis que je choisis exit , ecran de ma tv devient noir et je ne reviens pas sur emulationtation, ma tv semble s éteindre puis je reviens sur kodi.

**Comment by rockaddicted** [comment]
In the beta 2, this problem is not fixed. So reopen this issue :cry:

**Comment by Didlith** [comment]
Hello 

i'm testing this Feature on Beta 2 
for me after modify specifique section on parameter CEC on Kodi my TV cannot switch Off with Kodi 

in second time i try to modify the XML on /root/.kodi/userdata/peripheral_data/rpi_****_****.xml
in this Line <setting id="standby_devices" value="231" />
but Kodi cannot take the manual Modification of this File 

So for sure your TV cannot switch Off with Kodi 
go to System > parameters > System > preripheral 
and enter to CEC Adaptater and go  "device to power off when stopping Kodi set option to none"

normaly when push exit bouton you return to EmulationStation

cdly

**Comment by digitalLumberjack** [comment]
I cannot reproduce on my tv. Beta 9 is on it's way, @Didlith could you try again on it ?

**Comment by Didlith** [comment]
hello 

cannot reproduce on my tv to

**Comment by nadenislamarre** [comment]
fixed for release 4.1 (option changed by default in new kodi configuration, you've to disable in option if you've already a .kodi)
