### ISSUE TITLE
Support du dongle wifi TP-LINK TL-WN725N

### ISSUE THREAD

**Issue by boopr** [recalbox/recalbox-os#255]
_Version française_
Bonjour,

Il serait bien d'avoir le support du dongle wifi TP-LINK TL-WN725N directement intégré dans Recalbox. Ce dongle coûte environ 7€ soit deux fois moins que le modèle d'Edimax proposé à 14€. Il est donc souvent choisi par les utilisateurs car sa configuration est extrêmement rapide sous Raspbian, comme on peut [le remarquer sur ce blog](http://blog.alexandredubois.com/2014/05/20/installer-la-clef-wifi-tp-link-tl-wn725n-v2-sur-un-raspberrypi-avec-raspbian/).

Merci pour Recalbox qui est, selon moi, la meilleur plateforme de retrogaming, mais surtout, merci de la rendre toujours meilleure.
---

_English version (may have some mistakes)_
Hello,

It will be nice to support the wifi dongle TL-WN725N directly in Recalbox. This dongle costs about 7€, twice unless the model proposed Edimax (14 €). It is thus often chosen by users because its configuration is extremely fast in Raspbian, as can [notice this blog](http://blog.alexandredubois.com/2014/05/20/installer-la-clef-wifi-tp-link-tl-wn725n-v2-sur-un-raspberrypi-avec-raspbian/).

Thank you for Recalbox which is, in my opinion, the best retrogaming platform, but mostly, thank you to make it better.

**Comment by Ninmania** [comment]
*Français*

Bonjour, 
Je suis également intéressé par cet ajout, c'est la clé Wifi la moins cher sur Amazon !
J'ai trouvé un lien qui explique comment l'ajouter lors de la compilation de Buildroot mais je t'avouerai que la tache est longue pour comprendre comment compiler tout depuis le début malgré le Wiki assez fourni. :) 

C'est le lien qui explique comment ajouter le driver pour Buildroot : 
http://agrou.eu/en/compile-the-tp-link-tl-wn725n-v2-linux-driver-with-buildroot/
Merci pour cette distribution qui me ramène à cette époque magique de la SNES.
En attendant un retour ;) 

*English*

Hello,
I am also interested by adding this key, it's the cheapest on Amazon !
I've found a link which explain how to add it when you compile Buildroot but it's quite challenging to understand all the steps from the beginning to compile despite a well maintain Wiki. :) 

Here the HowTo link to add this driver for Buildroot : 
http://agrou.eu/en/compile-the-tp-link-tl-wn725n-v2-linux-driver-with-buildroot/
Thank you for this release which bring me back to the sweet sweet time of the SNES.
Wish for a reply ;)

**Comment by Laddyacris** [comment]
Bonjour
à tester : http://blog.recalbox.com/forums/topic/tuto-faire-fonctionner-la-carte-wifi-tp-link-tl-wn725n/

**Comment by Ninmania** [comment]
Merci Laddyacris, 
Works like a charm et rapide a mettre en place ! :D

**Comment by nadenislamarre** [comment]
firmware included in the 4.1
