### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by antonlindgren** [recalbox/recalbox-os#260]
Hi,

I get "Update available" when booting, but if I go "Menu" -> "Update" it says "Working.." for ~1 second then "Update fails, now rebooting".

updates.log:
begin update
info : will conntect to recalbox.com with credential : public
info : starting share update
error : unable to update share

recalbox.log (the end of it):
update available
PING recalbox.com (94.23.55.163): 56 data bytes
64 bytes from 94.23.55.163: seq=0 ttl=53 time=50.096 ms

--- recalbox.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 50.096/50.096/50.096 ms
---- recalbox-config.sh ----
update available

After breaking down the script, it appears that rsync fails - unable to connect;
rsync -rltXv --exclude-from=/recalbox/scripts/rsync-update/always-exclude.cfg --exclude-from=/recalbox/scripts/rsync-update/exclude-share.cfg rsync://public@recalbox.com/recalbox-share

rsync: failed to connect to recalbox.com (94.23.55.163): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

I do not run any sort of blockage on my end, though it appears that rsync isnt running on recalbox.com.

(So this might not be a bug, more of a "FYI")

**Comment by antonlindgren** [comment]
Apparently the rsync server is down until v3.3.0 - so you can ignore this ticket.

However, the script doesn't output the errors from rsync into updates.log correctly.

**Comment by digitalLumberjack** [comment]
Thank you for the issue, i'll take care of that.

**Comment by matthuisman** [comment]
@digitalLumberjack 

Could you explain the update process a bit to me?

I have swapped out the NOOBS for standard NOOBS and was wondering if update would still work?
I tried updating last night but it failed.

Does update require your specific version of NOOBS?

**Comment by digitalLumberjack** [comment]
Hi, what version are you running ? The update is no longer available for 3.2.X

**Comment by sturze** [comment]
hey guys! i also tried to update via GUI and via shell rsync-update.sh without success
i always get:
´´´
@ERROR: chroot failed
rsync error: error starting client-server protocol (code 5) at main.c(1635) [Receiver=3.1.1]
´´´´
Space is:
´´´
[root@RECALBOX rsync-update]# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 1.9G    570.3M      1.2G  31% /
devtmpfs                235.7M         0    235.7M   0% /dev
tmpfs                   240.0M         0    240.0M   0% /dev/shm
tmpfs                   240.0M    256.0K    239.7M   0% /tmp
/dev/mmcblk0p7           27.2G     10.4G     16.8G  38% /recalbox/share
/dev/mmcblk0p5           59.1M      7.6M     51.5M  13% /boot
´´´
what's wrong? can anybody tell me how to upgrade to the newer version?

**Comment by sturze** [comment]
still nobody? rsync-server not running? doing something wrong?

**Comment by sturze** [comment]
Version 3.3.0 beta 2
--
@digitalLumberjack i think its the rsync-server... am i wrong?
rsync-update.sh failes at updating share...  

```
[root@RECALBOX ~]# cat /root/updates.log                                                                        
begin update
info : will conntect to recalbox.com with credential : public
info : starting share update
error : unable to update share
```
tried to fill all variables "by hand":
```
rsync -rltXv --exclude-from=/recalbox/scripts/rsync-update/always-exclude.cfg --exclude-from=/recalbox/scripts/rsync-update/exclude-share.cfg rsync://public@recalbox.com/recalbox-share-rpi2-beta /recalbox/share >> /root/updates.log
```
but its all the same....
can you check that?

**Comment by matthuisman** [comment]
Have you moved your share? It's not on the network maybe with insufficient write permissions?

**Comment by sturze** [comment]
@digitalLumberjack pleeeeeeeeeeeaaaseee!

**Comment by nadenislamarre** [comment]
the rsync upgrade mode is no more used since 4.0
Closing.
