### ISSUE TITLE
PVR issue - possibly due to curl not being installed

### ISSUE THREAD

**Issue by StephenGoodall88** [recalbox/recalbox-os#268]
Hi,
I'm getting this error in my logs, using the VU plus PVR addon:
>
15:55:00 T:1802609680  NOTICE: AddOnLog: VU+ / Enigma2 Client: Open - VU+ Addon Configuration options
15:55:00 T:1802609680  NOTICE: AddOnLog: VU+ / Enigma2 Client: Open - Hostname: '192.168.1.75'
15:55:00 T:1802609680  NOTICE: AddOnLog: VU+ / Enigma2 Client: Open - WebPort: '8000'
15:55:00 T:1802609680  NOTICE: AddOnLog: VU+ / Enigma2 Client: Open - StreamPort: '8001'
15:55:00 T:1802609680  NOTICE: AddOnLog: VU+ / Enigma2 Client: Open Use HTTPS: 'false'
15:55:00 T:1802609680    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Open webAPI with URL: 'http://192.168.1.75:8000/web/deviceinfo'
15:55:00 T:1802609680   DEBUG: CFileCache::Open - opening <web/deviceinfo> using cache
15:55:00 T:1802609680   ERROR: Open - Unhandled exception
15:55:00 T:1802609680   ERROR: Open - Error opening http://192.168.1.75:8000/web/deviceinfo
15:55:00 T:1802609680   DEBUG: AddOnLog: VU+ / Enigma2 Client: GetHttpXML - Could not open webAPI.
15:55:00 T:1802609680   DEBUG: AddOnLog: VU+ / Enigma2 Client: Unable to parse XML: Error document empty. at line 0
15:55:00 T:1802609680   ERROR: AddOnLog: VU+ / Enigma2 Client: Open It seem's that the webinterface cannot be reached. Make sure that you set the correct configuration options in the addon settings!
15:55:00 T:1802609680   DEBUG: AddOnLog: VU+ / Enigma2 Client: ~Vu Stopping update thread...
15:55:00 T:1802609680   DEBUG: AddOnLog: VU+ / Enigma2 Client: ~Vu Removing internal channels list...
15:55:00 T:1802609680   DEBUG: AddOnLog: VU+ / Enigma2 Client: ~Vu Removing internal timers list...
15:55:00 T:1802609680   DEBUG: AddOnLog: VU+ / Enigma2 Client: ~Vu Removing internal recordings list...
15:55:00 T:1802609680   DEBUG: AddOnLog: VU+ / Enigma2 Client: ~Vu Removing internal group list...
15:55:00 T:1802609680   ERROR: ADDON: Dll VU+ / Enigma2 Client - Client returned bad status (1) from Create and is not usable
15:55:00 T:1802609680    INFO: Called Add-on status handler for '1' of clientName:VU+ / Enigma2 Client, clientID:pvr.vuplus (same Thread=no)
15:55:00 T:1802609680 WARNING: UpdateAndInitialiseClients - failed to create add-on VU+ / Enigma2 Client, status = 1
15:55:00 T:1793704976  NOTICE: Thread AddonStatus pvr.vuplus start, auto delete: true
15:55:00 T:1793704976   DEBUG: Thread AddonStatus pvr.vuplus 1793704976 terminating (autodelete)

Looking at the addon code (https://github.com/kodi-pvr/pvr.vuplus/blob/master/src/VuData.cpp line 574):
```
CStdString Vu::GetHttpXML(CStdString& url) 
{
//  CLockObject lock(m_mutex);

  XBMC->Log(LOG_INFO, "%s Open webAPI with URL: '%s'", __FUNCTION__, url.c_str());

  CStdString strTmp;

  CCurlFile http;
  if(!http.Get(url, strTmp))
  {
    XBMC->Log(LOG_DEBUG, "%s - Could not open webAPI.", __FUNCTION__);
    return "";
  }

  XBMC->Log(LOG_INFO, "%s Got result. Length: %u", __FUNCTION__, strTmp.length());
  

  return strTmp;
}
```

It seems to fail at this point:
```
CCurlFile http;
  if(!http.Get(url, strTmp))
```

I can wget the url from the terminal on the recalbox and it works fine, it downloads the XML file.

I'm just guessing about this but does that mean it needs curl installing in order for it to work? Is there a way of manually installing it to RecalBox or would it need to be in a release for it to get installed?
Thanks! :smile: :thumbsup:

**Comment by xavier1306** [comment]
Hi Stephen,

Did you find a solution for your issue with kodi VU+ plugin on Recalbox image ?

I think i am facing the same issue, and VU+ streaming is a must on my Pi/emulationstation :(
How did you get out of the problem ?

Thanks

**Comment by StephenGoodall88** [comment]
Hi xavier,
I didn't get past this. It's not too much of an issue as I dont really use the recalbox, I have a server running kodi anyway.
I just tried manually installing curl but there are lots tools and program's missing as the image is a stripped down version of unix I think. Having apt-get or yum would make this much easier!
Sorry I couldn't be more help, let us know if you sort it yourself :)
Steve

**Comment by xavier1306** [comment]
Thanks a lot for your answer ! And well understood :'(

I will continue looking for a raspberry pi image including emulationstation
and kodi WITH vu+ plugin functional ;-)

By the way, did you succeed in having the vu+ plug-in working on a Pi ?
Which distribution ?

Thanks again
Le 3 déc. 2015 20:47, "StephenGoodall88" <notifications@github.com> a
écrit :

> Hi xavier,
> I didn't get past this. It's not too much of an issue as I dont really use
> the recalbox, I have a server running kodi anyway.
> I just tried manually installing curl but there are lots tools and
> program's missing as the image is a stripped down version of unix I think.
> Having apt-get or yum would make this much easier!
> Sorry I couldn't be more help, let us know if you sort it yourself :)
> Steve
>

**Comment by StephenGoodall88** [comment]
I have but I have played around with so many distributions I can't remember! I think it may have been raspbmc. Of course this doesnt include emulationstation but you may be able to install it manually.
Kodi may be built into RetroPie now, haven't checked recently but there is a section in their Wiki about Kodi: https://github.com/RetroPie/RetroPie-Setup/wiki/KODI

**Comment by StephenGoodall88** [comment]
https://gist.github.com/brianclements/9802627
This looks like it might help resolve it but I'm not sure whether @digitalLumberjack would want to include it in the buildroot or not as it might be considered to be bloating the install.

It's something I can live without, as mentioned I have a separate Kodi machine, but the Vu+ PVR addon would be a nice feature to have (although I don't think many people would use it)

**Comment by digitalLumberjack** [comment]
I added curl binary in the 3.3.0 branch, will be available in the next release.

**Comment by xavier1306** [comment]
Very good  news for some happy few :)
Will try it as soon as available.

@StephenGoodall88 : 
I made the kodi VU+ plugin work with another distribution (that of course it not as good as recalbox ;-))
Nevertheless, it does not work good : 
The sound is always cutting, a lots of noise in the picture, it can hardly been watched...
I can't figure out if it is a matter of : 
- LAN speed (i don't think it is, i am using a RJ45 connection  through PLC plugs) 
- or a matter of Raspberry Pi 1 model B unsufficient capacity, 
- or a matter of buggy PVR driver ?...

How good was it working on yours ? Are you using a RPI 2 ?
(I will have to identify my CPU loaed while using the PVR - "top" command is my friend)

I am using an original VU+solo 2 with the last VTI distribution (maybe i should try the last Blackhole as well ?)

**Comment by StephenGoodall88** [comment]
@digitalLumberjack thanks for including it, I'll update this weekend and try it out

@xavier1306 I use the vix image, with wired Ethernet and it works fine on non HD channels. HD are sometimes ok and sometimes break up, I think it's a network limitation though, maybe because of the vu and pi's 10/100 Ethernet ports?

**Comment by StephenGoodall88** [comment]
The PVR addon seems to be working now, cheers for adding the library in :)
