### ISSUE TITLE
emulateur commodore 64

### ISSUE THREAD

**Issue by stephdoc** [recalbox/recalbox-os#270]
bonjour,
voila j'ai vu sa : http://www.commodorepi.co.nr/

serait il possible d'integrer un emulateur commodore 64?

merci

**Comment by mgoulartBR** [comment]
+1

**Comment by bjoernroehrbein** [comment]
+1

**Comment by Haris1977** [comment]
+1

**Comment by substring** [comment]
dupe of #38 ;)
