### ISSUE TITLE
Plantage au démarrage manette de PS4

### ISSUE THREAD

**Issue by boopr** [recalbox/recalbox-os#271]
Bonjour,

J'ai relevé un bug qui m'a longtemps énervé avant d'en trouver la source (je n'en suis pas sûr mais ça m'a tout l'air..). Quand, au démarrage de la machine, une manette de PS4 est branchée, il y a des chances qu'elle ne démarre pas correctement. On se retrouve devant un écran noir. Il ne reste plus qu'a débrancher-rebrancher jusqu'à ce que ça fonctionne... 

Mais si cette manette n'est pas branchée au démarrage, et qu'on la branche après, il n'y a aucun soucis (en plus elle est parfaitement reconnue !).

Merci pour Recalbox,
Bonne journée

**Comment by digitalLumberjack** [comment]
Salut, merci pour l'issue, dis moi tu pourrais essayer de reproduire le bug, en branchant ta manette et un clavier USB. A l'écran noir, tu pourrais utiliser le clavier et faire CTRL + ALT + F3 pour afficher la console et me dire si tu vois quelque chose ?
Ça serai vraiment utile a la correction de ce bug, qui est rencontré dans d'autres cas sur le RPI2

**Comment by boopr** [comment]
Je te redis ça quand le bug se représentera ! (Dans la journée je pense)

**Comment by boopr** [comment]
Bon bah le bug vient juste d'arriver... Voici ce que j'ai à l'écran : 
![wp_20150618_10_18_24_pro](https://cloud.githubusercontent.com/assets/4344540/8227065/57310c0c-15a4-11e5-8835-798758e534e9.jpg)

En espérant vous aidez!

**Comment by nadenislamarre** [comment]
Works in 4.0.0 with an official ps4 controller.
