### ISSUE TITLE
LIRCD sur une future version de Kodi

### ISSUE THREAD

**Issue by EmulFab** [recalbox/recalbox-os#281]
Bonjour, tout d'abord félicitation pour votre travail....

Serait-il possible que Lirc soit disponible sur une future version de Kodi pour pouvoir utiliser un lircd.conf comme sur osmc (ma télé n'est pas compatible avec la norme hdmi cec).
d'avance Merci

Fabien

**Comment by nadenislamarre** [comment]
fixed inrelease 4.0 beta1

**Comment by EmulFab** [comment]
Merci super travail....

Envoyé de mon iPhone
