### ISSUE TITLE
support Xarcade2Jstick for Xarcade Tankstick

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#283]

**Comment by reivaax** [comment]
peut-être une solution donnée sur le forum : http://blog.recalbox.com/forums/topic/x-arcade-duval-stick/#post-13410

**Comment by substring** [comment]
Done : https://github.com/recalbox/recalbox-buildroot/pull/137
@digitalLumberjack @rockaddicted can be closed

**Comment by rockaddicted** [comment]
:+1:
