### ISSUE TITLE
Support dongle wifi MediaTek

### ISSUE THREAD

**Issue by nosfay** [recalbox/recalbox-os#288]
Bonjour,

Est-il possible d'ajouter le support de dongle wifi MediaTek?

Ci dessous le résultat de la commande "dmesg"

[    2.522252] usb 1-1.3: new high-speed USB device number 4 using dwc_otg
[    2.633172] usb 1-1.3: New USB device found, idVendor=148f, idProduct=7601
[    2.633213] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.633234] usb 1-1.3: Product: 802.11 n WLAN
[    2.633252] usb 1-1.3: Manufacturer: MediaTek
[    2.633268] usb 1-1.3: SerialNumber: 1.0

Le driver est à cette adresse : http://groenholdt.net/Computers/RaspberryPi/MediaTek-MT7601-USB-WIFI-on-the-Raspberry-Pi/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913.tar.bz2

Merci :)

**Comment by nadenislamarre** [comment]
done in 4.1
