### ISSUE TITLE
Duplicate games in PSX listing

### ISSUE THREAD

**Issue by Mojo4242** [recalbox/recalbox-os#290]
Hi !

PSX games often come with several files with the same name and with different extension like:
awesome-game.cue (tracks description)
awesome-game.bin (one of the tracks)

In Recalbox, the same game appears several times in the list because there are several files.
Some games even provides more than 60 tracks + 1 cue which become quite a mess.

I only describe this problem with PSX but maybe there is the same problem with another platform ?

One idea is to detect that files seems to be the same game based on their name (can be tricky).
An other idea is to have a folder for each games, the name of the game would simply be the folder name and one of the files will be given to the emulator

**Comment by rockaddicted** [comment]
Yes it a "problem" known.
If you don't want anymore see the *.bin files in your list of games.
You can edit this file, https://github.com/digitalLumberjack/recalbox-buildroot/blob/recalbox/board/recalbox/fsoverlay/root/.emulationstation/es_systems.cfg#L135
and delete the `.bin .BIN` extension.
This way, after a reboot you'll no more see this files and you'll be able to boot your games using the .cue file associated.

**Comment by Mojo4242** [comment]
Great :)

I agree it's not a real "problem" as we still can launch any game.

Thanks for the tip !

**Comment by paradadf** [comment]
Fixed in 4.1 with https://github.com/recalbox/recalbox-buildroot/pull/544
