### ISSUE TITLE
Wifi not working with wep

### ISSUE THREAD

**Issue by LvZ90** [recalbox/recalbox-os#291]
Hello,

I'm new to the Raspberry Pi and downloaded Recalbox OS. It booted fine and recognized my PS3 controller and my wireless Keyboard. But when I try to enable the Wifi in the menue, it shows an Error.

I have no special characters in either the SSID or in the Password. Only numbers and letters.

What can I do? Please consider that I am a beginner. Thank you. :)

**Comment by rockaddicted** [comment]
Hello, your wifi dongle is supported by recalbox (I'm using one).
So the problem come from your configuration.
To activate and configure your wifi, you must edit the recalbox.conf file.

https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-%28EN%29
https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-%28FR%29

Go in the wifi section, uncomment the wifi_ssid=new ssid and wifi_key=new key line by deleting the `;` at the start of the lines, and add your network informations.
After a reboot, your wifi should be configured.

If you it is not ok, go to the forum. There is many post about this.  http://blog.recalbox.com/forums/

**Comment by LvZ90** [comment]
Hello. Thank you for your help and reply. After long research I figured out that the wlan has to be wpa. I changed it and now it works.

**Comment by digitalLumberjack** [comment]
I should add this information in the wiki.

**Comment by davmanypsp** [comment]
Sorry if I'm not supposed to ask this here, but will the WEP feature be added at some point?

**Comment by nadenislamarre** [comment]
it's in my todo list.
So yes.
However it suggest you to avoid wep, while it's almost the same as no
security at all.

2016-01-21 11:41 GMT+01:00 davmanypsp <notifications@github.com>:

**Comment by davmanypsp** [comment]
Thanks. I prefer to wait until WEP support is added, rather than changing the security settings in my router and all devices and computers of my family members in my house. But is nice to hear that WEP support will be added. Thank you!

**Comment by nadenislamarre** [comment]
done in 4.1
