### ISSUE TITLE
Wired Xbox 360 controller: not recognized immediately in game

### ISSUE THREAD

**Issue by Colmea** [recalbox/recalbox-os#296]
Hi,

Weird bug with my wired 360 controller: When I launch recalbox, everything's alright, controller is working well.
But when I launch a game (whatever the bios/game launched), the controller is not responding anymore.
However, it's recognized because I see the yellow alert at the bottom of the screen ("Joypad 0 Xbox 360 blabla...").

I then need to wait 10 to 30 seconds so that the controller responds (from that moment, everything is ok).

Recalbox version: 3.2.11
Game/Bios: all
Controller: Wired Xbox 360 controller
Config controller: default one
Device: Rasp 2

Thanks for your help :)

**Comment by t-moreau** [comment]
Hi,

I have the same problem. I can either wait for 30 seconds (feels like forever :D) or lose patience and unplug then plug back the wired xbox 360 controller.

Recalbox version: 3.2.11
Controller: Wired Xbox 360 controller
Device: Rasp 2

**Comment by Colmea** [comment]
Update:
- This issue seems to disappear when Xbox360 controller is on player 2 and there is another controller on player 1 (xbox controller is detected quickly).

- The xbox controller seems to be detected when I press random buttons (something like R1 + L1 + a + b + x + y...). I can't understand how and ...why.

**Comment by digitalLumberjack** [comment]
One should launch a game, and start jstest in a ssh terminal. If the game doesn't respond, does jstest show events ?

**Comment by mpotier** [comment]
Same here

**Comment by antoinegiard** [comment]
Still the same issue, on 3.3.5

**Comment by rockaddicted** [comment]
when you activate xboxdrv driver in your recalbox.conf, this bug is still present ?

**Comment by t-moreau** [comment]
Hi,

I installed recalboxOS 4.0.0-beta1 (released on the 23rd of February, 2016) and this is no longer an issue. The Wired Xbox 360 controller is recognized immediately in game. I suppose this is thanks to the new version of xboxdrv introduced in recalboxOS v3.3.0-beta17 (released in December 2015), but I haven't tested it.

Recalbox version: 4.0.0-beta1
Controller: Wired Xbox 360 controller
Device: Rasp 2

**Comment by substring** [comment]
Don't necro
