### ISSUE TITLE
Colecovision support

### ISSUE THREAD

**Issue by mgoulartBR** [recalbox/recalbox-os#300]
Hi guys,

I'm looking an update from PES 1.3 and I saw that they add Colecovision support using libretro-fba. Is it possible to do the same thing on Recalbox?

**Comment by mgoulartBR** [comment]
Just an update.

https://www.youtube.com/watch?v=Yy0kT9ABcFI

There is a emulator called CoolCV, any possibility to see it on an future Recalbox release?

**Comment by mgoulartBR** [comment]
http://atariage.com/forums/topic/240800-coolcv-emulator-for-mac-os-x/

It was released in Feb 15th!

**Comment by rockaddicted** [comment]
Done with https://github.com/recalbox/recalbox-buildroot/pull/441 using bluemsx libretro core.
Will need more testing.
