### ISSUE TITLE
 Implement support for MAME samples

### ISSUE THREAD

**Issue by customcarvin** [recalbox/recalbox-os#301]
MAME sound samples folder and/or zips do not appear to be working/recognized in Recalbox. No documentation is available in regards to this issue. The default location for the samples folder is usually inside of the mame "roms" folder:

.../roms/samples/

Yet placing the zip files with the SOUND SAMPLES in 16-bit pcm wav format - with the same corresponding name - still does not work. For example:

/roms/zaxxon.zip   (contains ROM files)
/roms/samples/zaxxon.zip   (Contains .wav sound samples)

**Comment by Voljega** [comment]
Duplicate https://github.com/recalbox/recalbox-os/issues/740

**Comment by paradadf** [comment]
As mentioned by Voljega, this is a duplicate and the original issue is already fixed.
