### ISSUE TITLE
Include rpix86 (DOS)

### ISSUE THREAD

**Issue by MaxCorpEnjoy** [recalbox/recalbox-os#315]
http://rpix86.patrickaalto.com/

Unrelated to DOSBox, a dos emulator optimized for rpi.

**Comment by mgoulartBR** [comment]
+1

**Comment by Krantz984** [comment]
+1

**Comment by substring** [comment]
rpix86 is X11 only and not open source. It can't be added to recalbox
@digitalLumberjack @rockaddicted issue can be closed
