### ISSUE TITLE
Add category options // Sort/hide enhancement

### ISSUE THREAD

**Issue by MaxCorpEnjoy** [recalbox/recalbox-os#317]
If we have a lot of roms to try out, i would be great if you could somehow flag them by putting them into some categories.
Examples :
- I try a game and I found it reall hard, I put it in the 'hard' category 
- I really like one, and want to set it up as one of my 'favorite'
- I already finished this one once and would like to mark it as 'done'

Each rom could be affected to multiple categories (chosen in a list that may be customized by the user) and the selection screen could offer to hide or show only one category of roms.
The type (Action, RPG, Sports, ..) is already available but, as far as I know, cannot be used as a filter to sort (or hide/show) games.

**Comment by customcarvin** [comment]
You might want to place this suggestion into the Emulation Station git... not Recalbox.

**Comment by reivaax** [comment]
a favorites option arrived with the 3.3.0. it's not perfect like your idea but that help you to see on emulationstation only your favorites games.

You can use folder inside the rom directory and put inside your rom... It's not user frendly but that is a solution...

**Comment by digitalLumberjack** [comment]
You can now mark as favorite and hide/show in metadata edition since 4.0.0

**Comment by rockaddicted** [comment]
since 4.0.0 you can mark as favorite or hide a game.

Now you can display hidden games, sort your games by genre, number of players and developer's name.

https://github.com/recalbox/recalbox-emulationstation/pull/160
https://github.com/recalbox/recalbox-emulationstation/pull/161
