### ISSUE TITLE
MSX Libretro Core (BlueMSX)

### ISSUE THREAD

**Issue by mgoulartBR** [recalbox/recalbox-os#322]
Guys,

Is it working on RPi?
https://github.com/libretro/blueMSX-libretro

**Comment by rockaddicted** [comment]
The core is builded, but I didn't test it. You can find it here `/usr/lib/libretro/`
If you want to try and give feebdack ;)

**Comment by achelio** [comment]
No, the bluemsx core is not working.

I inserted the following lines in RECALBOX.CONF file:

msx_emulator = libretro
msx_core = bluemsx

But the game does not run . A few seconds after choosing a game, the system returns to the Recalbox menu.

**Comment by rockaddicted** [comment]
Ok i didn't try it.
Are you ok with bios ? I don't know if this core use the same files than fmsx

http://wiki.libretro.com/index.php?title=BlueMSX#BIOS

**Comment by achelio** [comment]
Hi,
I used the same bios with BlueMSX CORE in RETROPIE , and it worked perfectly ( I only changed the CORE in the options, no other changes have been made ) .

**Comment by rockaddicted** [comment]
Ok so we'll have to give a look to this core.

**Comment by mgoulartBR** [comment]
achelio,

Did you try to use controllers or just keyboard?

**Comment by achelio** [comment]
Hi mgoulart,
I tried to use controllers, and they worked perfectly in BlueMSX (Retropie). I switched to BlueMSX just because I could not make the controls work in fmsx.
Translate my bad english:
Os controles funcionam perfeitamente no BlueMSX :)

**Comment by mgoulartBR** [comment]
It's awesome!!! I hope to see blueMSX on a future Recalbox release!

Thanks!

Obrigado!!!

**Comment by geannf** [comment]
Could someone explain how I can use the blueMSX order to use the joystick on recalbox.

**Comment by mgoulartBR** [comment]
How I use bluemsx on Recalbox? I installed the bios files and changed the settings on recalbox.conf:

msx.core=bluemsx

But It's not working. I select a game, a black screen appears and after that returns to Emulationstation.

**Comment by geannf** [comment]
mgoulartBR, estou com o mesmo problema. Não estou conseguindo usar o bluemsx.

I have the same problem. I am unable to use the blueMSX.

**Comment by digitalLumberjack** [comment]
@mgoulartBR @rockaddicted is the core available and working ?

**Comment by rockaddicted** [comment]
I planned to do tests this week with this core.
I think you have just to add rom images in bios folder.

**Comment by digitalLumberjack** [comment]
:)

**Comment by rockaddicted** [comment]
Yep I confirm only need to add roms files.
You need to download the standalone version of bluemsx.
Then extract `Databases` et `Machines` folder from this version, and add them in recalbox `bios` folder.
Once done, go in `recalbox.conf` file, and add this line `msx.core=bluemsx` to switch on this core.

**Comment by bigboo3000** [comment]
MSX1 roms are working, but MSX2 roms are not working at all (scrambled image after bios). I wonder if bluemsx is loading the good bios file for msx2? (it's the same image for the bios when starting a msx1 or msx2 game). And why not separate folders for msx1 and msx2 like in retropie and in no-intro dat?

**Comment by rockaddicted** [comment]
did you switch the core option, in the retroarch menu, to select system to emulate MX1/Mx2 ?

**Comment by bigboo3000** [comment]
ok thanks!
Why not make msx2+ by default and enable ym2413 by default? all msx1 games that I tried works with those options turned on..

**Comment by substring** [comment]
we're done with it on 4.0.0. Shall we close it ? the default core has been changed in the 4.0.0-beta4

**Comment by caseyparker** [comment]
It seems to me that MSX of any sort doesn't function in any way...
