### ISSUE TITLE
Popcorn time

### ISSUE THREAD

**Issue by Ranashenka** [recalbox/recalbox-os#326]
Hello, first of all thanks you soo much for all the good work you have done.
I have a question, would it be possible to add the "popcorn time" addon to the kodi?

**Comment by mattbladen** [comment]
I've got it working well:

1) Download https://github.com/Diblo/KODI-Popcorn-Time/releases/download/0.6.3-beta/KODI.Popcorn.Time.Gotham.0.6.3.beta.zip

2) I added it to XBMC-Movies Share via IP address

3) Kodi > Settings > Addon > Install from zip > recalbox/shares/xbmc/movies
