### ISSUE TITLE
Bluetooth Support in Kodi

### ISSUE THREAD

**Issue by lilpharao** [recalbox/recalbox-os#327]
Hi
I'm using the Recalbox with an PS3 Controller over Bluetooth.
When i switch to Kodi within the Recalbox i'm not able to use the PS3 controller any more.
Is there a setting to activate Bluetooth in the RecalBox Kodi?

Thank you

**Comment by rockaddicted** [comment]
It is not a bluetooth problem. Indeed, Kodi don't support controllers for now.
If your TV is CEC compatible, you can use tv command to control Kodi or use a smartphone application as Yatse.

https://github.com/digitalLumberjack/recalbox-os/issues/12

**Comment by lilpharao** [comment]
Thanks for the information, 
My TV is CEC compatible and I'm using the TV remote,

What i wanted to say is that, it woiuld be great just to use one device (PS3 Controller) to controll the Recalbox and the Kodi inside of it :-)

**Comment by ajankuv** [comment]
Kodi does support controllers, it's just not built in yet. He has it on his list of todo's. If you built everything from scratch you can use this method. http://kodi.wiki/view/HOW-TO:Set_up_PS3_BD_Remote

**Comment by digitalLumberjack** [comment]
MOUAHAHA !
