### ISSUE TITLE
Only single player for N64

### ISSUE THREAD

**Issue by immertroll** [recalbox/recalbox-os#328]
Hello,

I configured my keyboard and a Microsoft Sidewinder as controls (also at the config file for mupen). At every emulator they are mapped to different players. At mupen you can control with both inputs only the first Player.

Please fix this. Mario Kart is no fun with only one player. ;-)

I use version 3.2.11.

**Comment by Reick** [comment]
I have the same Problem and my original N64 Controllers works with the Mayflash Adapter to USB. Signals come to the Pi, but Mupen64 cannot handle two controllers.

**Comment by MiguelAngelLV** [comment]
The keyboard and the first gamepad always are the player 1. You need two gamepads.

**Comment by Reick** [comment]
I have two Gamepads... But I solved the problem.
