### ISSUE TITLE
EightyOne ZX81 Emulator (Libretro core)

### ISSUE THREAD

**Issue by mgoulartBR** [recalbox/recalbox-os#331]
Guys,

Is it possible to include this core on a future release?
https://github.com/libretro/81-libretro

**Comment by digitalLumberjack** [comment]
@rockaddicted ? :P

**Comment by rockaddicted** [comment]
haha no problem, I'll test it

**Comment by wobblyrampack** [comment]
Oh this would be amazing, please include it!

**Comment by rockaddicted** [comment]
libretro core added
need testing
