### ISSUE TITLE
replace dropbear with opensshd?

### ISSUE THREAD

**Issue by phavx** [recalbox/recalbox-os#333]
I just spent 30 minutes googling why sshfs is not working, only to finally see that the problem is dropbear not supporting it. Personally I'd prefer sshfs over smb or the other options, so either of a) a note regarding this problem in the manual, b) replacing dropbear with opensshd by default or c) making it easy to do (have an option under systemsettings or similar).

**Comment by arthurlutz** [comment]
+1 to get sshfs and sftp to work with recalbox-os (b or c)

**Comment by sturze** [comment]
+1

**Comment by Dany21000** [comment]
+1 sshd

**Comment by dhobi** [comment]
+1 since I just spent another 30 minutes (ok, lets say one hour+) to find out why there is no sftp protocol option in kodi when adding a network source.
(Btw: can somebody point me how to easily install sshd. Without apt-get I'm kinda lost :))

**Comment by nadenislamarre** [comment]
what is the link between replace dropbear by sshd and the kodi sftp support
?

**Comment by dhobi** [comment]
Hmm I was just assuming that if dropbear will be replaced by openssh we would get a sftp-client by default and kodi would then show the sftp protocol option (again)? Sorry if I'm completely wrong here :)

**Comment by nadenislamarre** [comment]
Kodi sftp support added in 4.0 with pr
https://github.com/recalbox/recalbox-buildroot/pull/98 (not tested, but
passes the configure script successfully with sftp enabled)


2015-12-30 22:00 GMT+01:00 Daniel Hobi <notifications@github.com>:

**Comment by substring** [comment]
works fine for with a combination of gesftpserver and dropdbear 2015.71, that's aeons ago ;)

Shall i close ? Or is the problem still there ?

**Comment by fmarot** [comment]
Also just lost 30 minutes trying to sshfs into recalbox 4.0.2... to find out about Dropbear andit's lack of support for sshfs :/

**Comment by substring** [comment]
@fmarot just sftp. We won't switch to OpenSSH
