### ISSUE TITLE
No wired internet (ethernet) at all (RPi1)

### ISSUE THREAD

**Issue by Haris1977** [recalbox/recalbox-os#348]
I ve installed latest version (3.2.11) for my rpi1. While everything else works i have no wired internet!! When trying to update an error says "NETWORK CONNECTION NEEDED"

Is this a known bug?

**Comment by Laddyacris** [comment]
Hello
there no update available after 3.2.11.
3.2.11 is the latest version.

**Comment by Haris1977** [comment]
I know..my problem is that my recalbox image file doesnt connect to the internet thus doesnt have an ip address. So i have no ssh, no internet, no updates, nothing..

Am i doing smth wrong?

**Comment by digitalLumberjack** [comment]
Hi, you should connect via CLI with keyboard and use commands like "ifconfig" to see your network config and "ifup eth0" to enable the eth0 interface (see wiki -> how to)

**Comment by Haris1977** [comment]
I dont know..i am frustrated....i am trying to install it again (to check my prob) and i cannot install it..:( The progress bar stops at 100% and nothing happens..i dont know what is happening (in the morning i had no problem). Is there any other file i can try? Maybe a previous version?

**Comment by digitalLumberjack** [comment]
If you don't help us finding what happened to you, we cannot help you. I asked you about the result of ifconfig, you iddn't respond. Thousand of players installed recalbox in 5 minutes and it works out of the box. But we would have helped you :)

**Comment by Haris1977** [comment]
Sorry for being late but for personal reasons i couldn't test it. My last problem though was that i couldn't install it at all..That's why i couldn't use ifconfig.. I m thinking that my problem may be the sd-card..

I wiil try others as well

**Comment by digitalLumberjack** [comment]
Yep we have many problems with some sdcards brands. The Sandisk ultra are reported to work very well.

**Comment by Haris1977** [comment]
Ok. I use a Sony 2GB old class 4 card (if this is of interest)

**Comment by Jace37** [comment]
You wil need a class10 card with the pi.... Check Google there is a list of sd cares for the pi..

Verstuurd vanaf mijn iPhone

**Comment by digitalLumberjack** [comment]
On the diy page of the website you will see that you need at least a 16gb sdcard. The root partition is 2gb big. So there is no space left for your share partition.

**Comment by Haris1977** [comment]
Hmm..maybe you are right..First time i installed recalbox was in an 8 GB card though..Anyway,  i think my problem is the sd card..

Thanks:)
