### ISSUE TITLE
Dreamcast Emulation

### ISSUE THREAD

**Issue by mgoulartBR** [recalbox/recalbox-os#359]
Hi,

It was reported on Raspberry Pi fórum that an user from RetroPie Forum (free5tyle) improved many aspects from Dreamcast Emulation. The Raspberry Pi forum user (Jako) said that "That updates works very fine, nice sound and with a bit more of performance the emu will be playable with many more games."

Is there any plan to have it on Recalbox?

**Comment by rockaddicted** [comment]
Yep I tried this version too, and it is not really playable at the moment... :-/
Only few games run well...
But I'm watching the work on the main repo, and these  last days, they modified the master branch to build reicast for all systems. So I hope we will have a more optimized version for rpi in the next weeks.

**Comment by mgoulartBR** [comment]
https://github.com/libretro/reicast-emulator

Great news! I don't know the performance on Rpi2

**Comment by julianxhokaxhiu** [comment]
Feedbacks on the official forums seems really positive! https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=100076

**Comment by rockaddicted** [comment]
Libretro ports are normally a little less efficient than the standalone version for the same emulator. So I don't think this version will be better than standlone version.

This morning I tested a recent reicast version, build from scratch, to see modifications since my last test. And it is not ever playable on rpi2 (overclocked).
Sound is choppy, emulation is not fullspeed, so a Sonic is unplayable :-/
I think we'll have to wait a rpi3 more powerfull to see a real dreamcast emulation on rpi2.

I won't add it to recalbox if only 4-5 2D games are really playable.

**Comment by mgoulartBR** [comment]
Marvel vs Capcom 2 😁

**Comment by rockaddicted** [comment]
haha sure, so I'll let you explain every weeks on github issues or forum why the other 99% dreamcast games are not supported =)

I really love dreamcast (maybe my favorite game station) and I would like add it on recalbox... But only if emulation on rpi2 is really usable.

**Comment by mgoulartBR** [comment]
It's important to include only systems with good emulation support. It's
avoid many "headaches" from users complaning about Recalbox system.

**Comment by kryptto** [comment]
Like Nintendo64   ; /

**Comment by rockaddicted** [comment]
Yes indeed N64 emulation was limit to be integrated.
But on N64 you can play 40-50% of games, and many Hits of this platform are playable.
We are very far of this kind of results with dreamcast emulation on rpi2.

**Comment by mchtt** [comment]
issue #118 is the same no ? maybe you should close one of the two ?

**Comment by mgoulartBR** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=138362&p=918433#p918433

Great news for RPi3 users!

**Comment by substring** [comment]
guyz guyz guyz ... #118 
i'm closing this issue ;)
