### ISSUE TITLE
Feature request - add auto_save and auto_load savestate support in the configuration menu

### ISSUE THREAD

**Issue by lordtaki** [recalbox/recalbox-os#366]
Since 'savestate_auto_save' and 'savestate_auto_load' work pretty well with retroarchcustom.cfg, it could be a good idea to have this feature available in the configuration menu instead of editing manually.

I've been tested these options since the beginning and got no issues so far.

**Comment by digitalLumberjack** [comment]
:+1:

**Comment by substring** [comment]
done in 4.0.0 ? https://github.com/recalbox/recalbox-buildroot/commit/39f70fc1e4502a146ad82fc4a404934195cf50cb
shall we close it ?
