### ISSUE TITLE
Plugin selection on ROM (N64)

### ISSUE THREAD

**Issue by sturze** [recalbox/recalbox-os#367]
it would be incredible cool to seperate emulation plugins (n64, rice) by each rom!
to change systemwide for starting different roms with different setting is kinda annoying

is there any chance to do that? or to add it in the future release?

like
n64.plugin=rice
n64.rom("Mario Kart").plugin=n64

or maybe in the contextmenu in the roms GUI "plugin" with a switch n64 ord rice

**Comment by hstampfl** [comment]
+1

**Comment by MiguelAngelLV** [comment]
I think the more simple way use two folder in roms folder: n64 and n64rice.

**Comment by sturze** [comment]
would do the same job, indeed....
but to switch plugins you need to leave the GUI and copy files :-/... not that nice as switching a switch with your controller in the context-menu of emulationstation

**Comment by MiguelAngelLV** [comment]
If you know the compatibily, when you copy the roms, put each in the correct folder.

**Comment by sturze** [comment]
but i dont... i always test both... and because a few dont work without rice, my standard is rice...:-/
if both work, i often chose n64 (seems to be quicker...)

but as i said... would also do it's job...

but the nicer (better looking) would be the GUI way... ;)

**Comment by sturze** [comment]
another idea but maybe to komplex:
maybe a reference file with the perfekt settings?! would that be able to do?! would make anything like that (folder, switches... ect.) obsolete!

is it possible to identify a rom unique on loading/starting/uploading? like: well filename is "mario1.n64" but its identified as "Super Mario 64" and that runs perfect with n64 (not rice). on chosing it in emulationstation it checks the perfect settings from the settingsfile(or db) and all settings are preSet! it starts with the best working emulator! done! 
maybe with the scraped infos??? maybe not Unique enough? 

that would be more then perfect :D  there would be nothing more userfriendly!

**Comment by digitalLumberjack** [comment]
4.0.0 bring the core and emulator selection at the game level. That closes this one
