### ISSUE TITLE
Add ability to hide games in the gamelist

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#374]
Only for having the possibility to hide .zip bios, and unessecary files that have the same extension as games.

**Comment by Haris1977** [comment]
+1 for especially the bios files

**Comment by digitalLumberjack** [comment]
Yep harris, now that i got you, maybe you could correct what you said about recalbox on the retropie forum. You let people think that's it's bugged and uninstallable, but it was only caused by the fact you used a cheap 2gb micro sd.

**Comment by Haris1977** [comment]
digitalLumberjack when i said about "bugs" i couldnt know that (maybe) my card was incompatible. Haven't tested though on a 16 gb card (i only have an 8 GB one).

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-emulationstation/commit/574faa68f1d3b9d8a0d17b6f24e419f00a85d4bd
