### ISSUE TITLE
Add mupen64 support in configgen

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#378]
Need info on how to configure mupen for a given controller.

@rockaddicted ?

**Comment by rockaddicted** [comment]
I think the driver ```mupen64plus-input-sdl.so``` look the file ``` /usr/share/mupen64plus/InputAutoCfg.ini``` to find the mapping of the controler.
Then it write the configuration inside ```/recalbox/configs/mupen64/mupen64plus.cfg````for each controler.

**Comment by substring** [comment]
Done https://github.com/recalbox/recalbox-configgen/commit/4345bf6256b646aaa3d8dda34674421416b691b2
