### ISSUE TITLE
Add support for Commodore 64 Emulator

### ISSUE THREAD

**Issue by gibStu** [recalbox/recalbox-os#38]
If possible add support for a Commodore 64 emulator such as VICE

**Comment by AldoFerrari** [comment]
+1

**Comment by czyz** [comment]
+1

**Comment by julianxhokaxhiu** [comment]
+1

**Comment by wobblyrampack** [comment]
Agree this would amazing. +1 from me.

**Comment by czyz** [comment]
Does anyone have any idea how to add support for an emulator? It'd be interesting to try.

**Comment by nadenislamarre** [comment]
first, get recalbox sources, compile and make it work from sources.
After, it's just some modifications :

in recalbox sources (i recommend 4.0.0 for new features)
1) see file package/libretro-snes9x-next or any other to check how such
emulator has been added
2) some other files have to be updated for configuration (check the
configgen repository too)

come on irc if you need help.


2016-01-04 18:38 GMT+01:00 czyz <notifications@github.com>:

**Comment by wobblyrampack** [comment]
Where is recalbox 4.0.0? I can only see 3.x

**Comment by nadenislamarre** [comment]
the 4.0.0 git branch.

2016-01-04 21:59 GMT+01:00 Mark Docherty <notifications@github.com>:

**Comment by wobblyrampack** [comment]
Oh I see, got it. thanks!
I'd love to see C64 and ZX Spectrum supported emulation in Recalbox.

**Comment by Khalzaam** [comment]
Need this C64 too !

**Comment by Nokturn** [comment]
Please add Commodore 64

**Comment by MICKtheBIG** [comment]
https://github.com/recalbox/recalbox-buildroot/pull/247

**Comment by rockaddicted** [comment]
ohhhhh yeahhhh thank you @MICKtheBIG

**Comment by substring** [comment]
closing this one, keep talking about this topic on https://github.com/recalbox/recalbox-os/issues/452

**Comment by irr1tated** [comment]
Please do it!!!
