### ISSUE TITLE
Add hability to specify custom NTP server

### ISSUE THREAD

**Issue by Dany21000** [recalbox/recalbox-os#380]
For restricted network, can you add a custom NTP server in recalbox.conf ?

I know, it's easy to edit /etc/ntp.conf, i just submit the idea.

**Comment by digitalLumberjack** [comment]
Yop @Dany21000 yes i think you'll be only 2 or 3 users to do that, and other users won't understand why this option is in recalbox.conf.
Let's say it stays in /etc/ntp.conf :)
