### ISSUE TITLE
Different folders for game saves

### ISSUE THREAD

**Issue by RudyProme** [recalbox/recalbox-os#385]
Currently there is only one folder for all the game saves regardless of the system. The problem is, there could be some conflicts if you play two or more games with the same name but on different systems. So I suggest to create one subfolder by system in the save directory.

Thank's

**Comment by Dany21000** [comment]
Yes this will be great, I have tried two roms with same name on two emulator and they share the same saved file.... 

This is the same problem with saved states file's.

**Comment by esmith13** [comment]
If not subfolders at least use rom extension as part of name perhaps?

Mario Bros.a78.srm
Mario Bros.nes.srm
etc?

**Comment by lordtaki** [comment]
Don't know for the other releases, but I'm running 3.3.0 beta 6 and this is possible:
- Hotkey + B to enter the retroarch menu
- Settings
- Saving
- Set ON for "Sort Saves in Folders" and "Sort Savestates in Folders"

**Comment by rockaddicted** [comment]
@digitalLumberjack : should we activate this option by default ?

**Comment by esmith13** [comment]
Yes please! Both saves and save states should be sorted in folders by default.
There are a lot of games that released for multiple platforms that cause
conflicts with saves and save states not sorted in sub folders.

On Sat, Nov 07, 2015 at 10:54 AM, rockaddicted < notifications@github.com [notifications@github.com] > wrote:
@digitalLumberjack [https://github.com/digitalLumberjack] : should we activate this option by default ?

—
Reply to this email directly or view it on GitHub
[https://github.com/digitalLumberjack/recalbox-os/issues/385#issuecomment-154718268] .[https://github.com/notifications/beacon/ANrFZKbxTomKsLXiaKikeOjD3PfWb7iiks5pDhYkgaJpZM4Fzjrz.gif]

**Comment by kryptto** [comment]
I agree too, please enable.

**Comment by digitalLumberjack** [comment]
Yep

**Comment by esmith13** [comment]
I assume if you do change it in an upcoming beta that we would have to manually
sort any preexisting saves/states for them to continue to be used. Perhaps then
you should note that detail in the change log that pops up on the Pi after an
update - not just say that save sorting is now enabled. Just a thought.

On Sat, Nov 07, 2015 at 3:12 PM, digitalLumberjack < notifications@github.com [notifications@github.com] > wrote:
Yep

Le sam. 7 nov. 2015 17:41, kryptto <notifications@github.com> a écrit :

> I agree too, please enable.
>
> Sent from my iPad
>
> > On Nov 7, 2015, at 10:57 AM, esmith13 <notifications@github.com> wrote:
> >
> > Yes please! Both saves and save states should be sorted in folders by
> default.
> > There are a lot of games that released for multiple platforms that cause
> > conflicts with saves and save states not sorted in sub folders.
> >
> > On Sat, Nov 07, 2015 at 10:54 AM, rockaddicted <
> notifications@github.com [notifications@github.com] > wrote:
> > @digitalLumberjack [https://github.com/digitalLumberjack] : should we
> activate this option by default ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > [
>
https://github.com/digitalLumberjack/recalbox-os/issues/385#issuecomment-154718268]
> .[
>
https://github.com/notifications/beacon/ANrFZKbxTomKsLXiaKikeOjD3PfWb7iiks5pDhYkgaJpZM4Fzjrz.gif
> ]
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
>
<https://github.com/digitalLumberjack/recalbox-os/issues/385#issuecomment-154722202>
> .
>
—
Reply to this email directly or view it on GitHub
[https://github.com/digitalLumberjack/recalbox-os/issues/385#issuecomment-154744234] .[https://github.com/notifications/beacon/ANrFZLZbpxT1OAZB5VW7RNGNnF9cPL50ks5pDlKQgaJpZM4Fzjrz.gif]

**Comment by sveetch** [comment]
:+1: 

Following this, as actually this is pretty difficult to manage saves in the recalbox-manager (i thought about to be able to save/restore them from tarball, but only one tarball for all systems will indubitably be leaded to fail, the rpi will suffer a lot to tarball something than can be so huge (experienced player can have hundred of saves, meaning hundreds of Megaoctets to archive).

**Comment by nadenislamarre** [comment]
i ve a very bad connection to get infos but :
1) branch 4.0 scrip have the parameter
2) i will allow to save / have data on a usb key in 4.0. no tar.gz
required. just an rsync to do incrzmzntal backup quickmy. i do it when i
come back. you ll be able to switch from sdcard to usb to store data. thus
this coymd be used qs a backup.

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-configgen/pull/25/files

**Comment by rockaddicted** [comment]
tested the last commit with retroarch, scummvm, mupen64.
everything is ok

**Comment by digitalLumberjack** [comment]
O YEAH
