### ISSUE TITLE
Dongle Wifi EDUP EP-N1528

### ISSUE THREAD

**Issue by Bobo14** [recalbox/recalbox-os#386]
Hello 

Serait-il possible d'ajouter le dongle wifi EDUP EP-N1528 
Merci beaucoup !

Les drivers ce trouve a cette endroit : http://edupwireless.com/profile/download/183701/0

Merci

**Comment by nadenislamarre** [comment]
to be tested in 4.1, while we have added several wifi firmware
however note that we support only firmware supported by linux/buildroot.
