### ISSUE TITLE
Add ExFat support

### ISSUE THREAD

**Issue by Guzilli** [recalbox/recalbox-os#387]
I know you can install the Exfat driver on the Raspberry pi to use exfat formatted drives in kodi. could you implement those drivers in recalbox?

**Comment by TomCarton** [comment]
+1 this would be a nice add-on

**Comment by mchtt** [comment]
+1 here ;-)

**Comment by ujellyx** [comment]
anything new on this matter? i'd like to connect my exFat external drive, where i have all my media on - to load roms off it and use as kodi-drives.

**Comment by nadenislamarre** [comment]
can you confirm it doesnt work in 4.0 where exfat is enavled ?

**Comment by Dragda** [comment]
@nadenislamarre I can confirm it doesn't work with kodi in the Version 4.0.0 build 113 of recalbox. 
The pendrive is a Sandisk Ultra 64GB.
If i format it in ntfs, works well (but you loose general w/r performance, as you know :(  .)

**Comment by paradadf** [comment]
Can this driver be implementet?
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/fuse-exfat/package.mk

**Comment by nadenislamarre** [comment]
exfat is already implemented in recalbox,
i think it's just the automounting which filter on fat, ntfs, ext*, ...
i've that action in my todo list.

**Comment by nadenislamarre** [comment]
just commited.
Works in 4.1 now.

**Comment by nadenislamarre** [comment]
can be close. Just waiting an eventual feedback.

**Comment by jordirodo** [comment]
@nadenislamarre 
will this eventually be backported to 4.0 branch?

**Comment by substring** [comment]
4.0.0 features are frozen, so you'll have to be a little patient :)

**Comment by rockaddicted** [comment]
here is the PR : https://github.com/recalbox/recalbox-buildroot/commit/21b9c577b1e21537485615fb19f70fe186af018f
You can edit your files until we switch on 4.1.0 version ;)
