### ISSUE TITLE
optimise the boot sequence of recalbox

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-os#390]
Many boot problems when we want to place the share partition on a NAS or HDD.
The support don't have time to be mounted before ES start.

**Comment by JanBaunooo** [comment]
Renaming ES init script to S61emulationstation make the job here ; with NFS mount/umount commands added to S60nfs init script for some share subfolders.

**Comment by digitalLumberjack** [comment]
Maybe a switch for the lazy start of the frontend.

**Comment by nadenislamarre** [comment]
in 4.0.0, the wait time is 5sec max for the hdd (it could be extended, but in case you have not the hdd plugged, it will switch to the internal mode only after that 5 sec (it's why the anyusb option is not wanted by default))

for the nas, perhaps we shoud add an option for roms only mount ?
while /recalbox/share is required to get the wifi password ; if nfs is required to get /recalbox/share...

or in case nfs is used, login/password for wifi should be saved in /boot/recalbox.conf too.
but i guess that /share/recalbox fully in nfs could be slower.
Somebody to make tests on the 4.0.0 ?

**Comment by nadenislamarre** [comment]
share over nfs/samba can be done in 4.1
To be closed.
