### ISSUE TITLE
Add multiple Wifi SSID/KEY

### ISSUE THREAD

**Issue by dem1980** [recalbox/recalbox-os#392]
I am using Recalbox in two houses and i would like to use wifi at both.
It could be nice to add for example 2 or 3 Wifi SSID : 
## Wifi SSID (string)
;wifi.ssid=new ssid
;wifi.ssid1=new ssid
;wifi.ssid2=new ssid
## Wifi KEY (string)
;wifi.key=new key
;wifi.key1=new key
;wifi.key2=new key

**Comment by mgoulartBR** [comment]
+1

**Comment by jammet** [comment]
I know this isn't directly related, but is it now possible to boot directly into Kodi AND have Wifi active?

**Comment by nadenislamarre** [comment]
done in 4.1.
