### ISSUE TITLE
Wrong FBAlpha dat file?

### ISSUE THREAD

**Issue by nekomania** [recalbox/recalbox-os#395]
I noticed that you are using the most updated v0.2.97.36 core, but the dat file found in \roms\fba_libretro is a lot older. Here is the correct dat if you need one.

https://www.dropbox.com/s/05r35g0pqow027y/FB%20Alpha%20v0.2.97.36%20%28ClrMame%20Pro%20XML%29.dat?dl=0

**Comment by rockaddicted** [comment]
Yes indeed we didn't update this file ^^
We'll do that.

**Comment by rockaddicted** [comment]
update .dat, gamelist, readme, ok

**Comment by rockaddicted** [comment]
update .dat file with 0.2.97.34 version

**Comment by rockaddicted** [comment]
updated dat file with 0.2.97.37 version
