### ISSUE TITLE
DosBox on recalboxOS

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#4]
By @mgoulartBR : 
Hi again,

I saw on http://dosonthepi.blogspot.com/ that is possible to run Dosbox using gamepads and running games from EmulationStation menu! Could be great for recalboxOS!!!

**Comment by agenttank** [comment]
that's essential sooner or later ;)

**Comment by Raulval82** [comment]
And suport for controllers directly would be awsome!

**Comment by mgoulartBR** [comment]
http://www.raspberrypi.org/forums/viewtopic.php?f=78&t=102268

**Comment by digitalLumberjack** [comment]
What do you think about trying the libretro dosbox port ?

**Comment by mgoulartBR** [comment]
Could be a good idea!!!

**Comment by C-Fu** [comment]
+1!!!

**Comment by hstampfl** [comment]
+1, I would also like to have this

**Comment by jeremyputeaux** [comment]
+1 !!

**Comment by TuKo1982** [comment]
+1 too ;-)

**Comment by digitalLumberjack** [comment]
Let's make this one a 3.3.0 feature

**Comment by rockaddicted** [comment]
The libretro-dosbox core don't have good performances on rpi2.
So if someone want integrate dosbox in recalbox, he must use the standalone version.
There is some links to start the work : 
about the building with dynamic recompilation enabled : https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=95421
about the conf generation to start games by emulationstation : http://dosonthepi.blogspot.fr/2015/02/dosbox-configuration-for-individual.html
about the mapper to generate an automatic mapping in recalbox : http://dosonthepi.blogspot.co.uk/2015/01/configure-game-controllers-in-dosbox_29.html

**Comment by arthurlutz** [comment]
+1

**Comment by Niehztog** [comment]
+1

**Comment by substring** [comment]
@rockaddicted @digitalLumberjack assign it to me

**Comment by MajinChibi** [comment]
Would also like to have dosbox in recalbox

**Comment by cpcbegin** [comment]
DosBox in Recalbox will be a marvellous idea.

**Comment by nadenislamarre** [comment]
works in 4.1.
