### ISSUE TITLE
Scraping avec Thearchive freeze

### ISSUE THREAD

**Issue by nosfay** [recalbox/recalbox-os#404]
Quand j'essaie de scraper des jeux avec la base "thearchive", je perds la main sur emulation station, la musique continue à tourner mais je ne peux plus rien faire.

**Comment by digitalLumberjack** [comment]
I will remove this scrapper, as it freeze and when it didn't it doesn't work at all...

**Comment by digitalLumberjack** [comment]
removed thearchive scrapper in https://github.com/recalbox/recalbox-emulationstation/commit/f57c21d77338229f0d10915cba1eedf6e38876f9
