### ISSUE TITLE
Unplug a controller in controller config menu make emulationstation crash

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#41]

**Comment by digitalLumberjack** [comment]
Need to fix that for 4.0.0

**Comment by julianxhokaxhiu** [comment]
In my case It doesn't crash, but it make them definitely losing they "position". For example I'm using a Wireless Pad, and it's assigned as number 1 on boot. If I unplug it and I replug it it's assigned as 2. And I have to reboot via SSH the system to get it running again as 1.

Ah, the Pad is working through xboxdrv.

**Comment by nadenislamarre** [comment]
the problem : 
1) the list in the ui contains pointers to all the InputConfig
2) when you unplug, it calls UNPLUG which remove the InputConfig
3) when you click back, it saves, trying to access InputConfig

I suggest :
1) add a member in InputConfig : to_be_removed
2) when you unplug => to_be_removed = true
3) when you list item, don't list the one with to_be_removed = true

**Comment by digitalLumberjack** [comment]
This has been resolved with https://github.com/recalbox/recalbox-emulationstation/commit/8c67b52337965957ea24a9a38eb1f3eb239fea36 anyone tested ?

**Comment by substring** [comment]
I had the issue on my pi0 yesterday while exchanging between a wifi key and a pad

**Comment by rockaddicted** [comment]
Humm tested to unplug my freebox controler during the maping, and ES didn't crash.

**Comment by nadenislamarre** [comment]
subs, on which screen ?

**Comment by substring** [comment]
I was un ES, probably on the 1st system. Will try to reproduce it and give the steps

**Comment by nadenislamarre** [comment]
subs, you were on the first screen, you unplug a joystick, plug a wifi, and
you got a black screen ?

**Comment by substring** [comment]
couldn't reproduce it. I'll reopen if i ever have the problem again
