### ISSUE TITLE
Quick shutdown menu acces

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#430]
Pourrais t'on imaginer une combinaison de touche, par ex. HOTKEY+SELECT+START qui ferait apparaitre directement le menu d'arrêt : "Éteindre/Redémarrer" ?

From http://blog.recalbox.com/forums/topic/v3-3-0-beta-testers-needed-besoin-de-beta-testeurs/page/13/#post-12724

**Comment by digitalLumberjack** [comment]
Disons plutot HOTKEY + START

**Comment by nadenislamarre** [comment]
hotkey + start, c'est pas la combinaison pour quitter un jeu ? genre si on fait la manip 2 fois on risque de tomber sur le menu un peu facilement ?

**Comment by digitalLumberjack** [comment]
It's done. Select do that.
