### ISSUE TITLE
Official wifi dongle support

### ISSUE THREAD

**Issue by creaforge** [recalbox/recalbox-os#431]
Hi there,

Raspberry.org has released their official wifi dongle ([see here](https://www.raspberrypi.org/products/usb-wifi-dongle/)), but it is not detected. Probably the driver is missing?

The chip used is a Broadcom bcm43143 and the firmware is available here :

```
git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
```

The bcm43143 firmware is located in .../linux-firmware/brcm
- brcmfmac43143.bin
- brcmfmac43143-sdio.bin

If it can help, an article here that explains [how to build the bcm43143 driver in OSMC](https://www.chrisaw.com/install-official-raspberry-pi-wifi-adapter-wlu6331-bcm43143-on-osmc-2/)

I'd be happy to run some tests if needed.

Thanks again for the amazing work done.
## Français

Hello,

Raspberry.org a sorti un dongle wifi officiel ([voir ici](https://www.raspberrypi.org/products/usb-wifi-dongle/)), mais il n'est pas détecté. Le driver est probablement manquant ?

La puce du dongle est la Broadcom bcm43143, son driver est disponible ici

```
git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
```

Le  firmware se trouve dans le dossier .../linux-firmware/brcm
- brcmfmac43143.bin
- brcmfmac43143-sdio.bin

Si ça peut être utile, un article explique comment [compiler ce driver sous OSMC](https://www.chrisaw.com/install-official-raspberry-pi-wifi-adapter-wlu6331-bcm43143-on-osmc-2/)

Je peux lancer des commandes de test de mon côté si besoin.

Merci encore pour ce superbe projet!

**Comment by digitalLumberjack** [comment]
:+1:

**Comment by walkertron** [comment]
Hello,

Great project, really enjoying playing my old games. However, regarding Wifi...

I have the new Wi-Pi dongle, and its not detected. I've tried running as it states above via SSH

git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

but getting -sh:sudo "Command not found"

The Wi-Pi dongle is listed on the compatibility list? So it should be detected anyway?

Please can you point me in the right direction. 

Thank you

**Comment by nadenislamarre** [comment]
Hi,

i've fixed a bug recently about wifi connexion which could help.
You've 2 possibilities to test wether it can help you :
- wait the next beta
- plug a keyboard, press f4, press ctrl+alt+f2, login as root/recalboxroot,
type ifup wlan0, if an ip is display, the patch will help you. To continue,
run : /etc/init.d/S31emulationstation restart

**Comment by walkertron** [comment]
Hello,

As expected, the device is not detected.

ip: SIOCGIFFLAGS: No such device

Is there a way of installing the correct drivers for this device?

Thanks

**Comment by substring** [comment]
as we know the pi3 wifi, might be the same firmware. Anybody can confirm ?

**Comment by nadenislamarre** [comment]
both files are in 4.1.
