### ISSUE TITLE
recalbox-manager integration

### ISSUE THREAD

**Issue by sveetch** [recalbox/recalbox-os#434]
So here it is, the version 0.8.3 has been released with fixes from test on Recalbox 3.3.0 beta 7.

The Readme contains the full procedure to install it in production (on Recalbox), just ensure you've fully readed the readme (for notes about production environment).

https://github.com/sveetch/recalbox-manager

Cheers

**Comment by Dany21000** [comment]
I've just installed this great Web interface.. 

It's a very good job and a good idea to integrate it.
