### ISSUE TITLE
Add Controller support to ScummVM

### ISSUE THREAD

**Issue by Guzilli** [recalbox/recalbox-os#435]
On Retropi you can use a controller to play scummVM games. Would be great to get this feature on RecalBox too

**Comment by digitalLumberjack** [comment]
on retropie is scummvm standalone or is it a retroarch core ?

**Comment by Guzilli** [comment]
i think it was standalone, i cant say for sure. But if i remember correctly there was no retroarch menu for it. you could press a button to bring up the scummVM Menu though

**Comment by rockaddicted** [comment]
https://github.com/vanfanel/scummvm/blob/master/backends/events/sdl/sdl-events.cpp

`/recalbox/scripts/emulatorlauncher.sh`
```
if [[ "$emulator" == "scummvm" ]]; then
         /recalbox/scripts/runcommand.sh 4 "scummvm --joystick --path=\"$dirName\" \"$filenameNoExt\""
```

**Comment by digitalLumberjack** [comment]
@rockaddicted any feedback on joystick support with the last modifications.

**Comment by rockaddicted** [comment]
done in recalbox 4.0.0
