### ISSUE TITLE
Ajouter imagevewer_libretro.so

### ISSUE THREAD

**Issue by ghost** [recalbox/recalbox-os#436]

**Comment by digitalLumberjack** [comment]
:+1: good idea

**Comment by DrNosh** [comment]
Je remonte le topic car j'ai trouver une technique assez simple pour afficher les screenshots sans avoir besoin de rajouter quelques chose a la recalbox. En utilisant mame l'affichage du png est parfait et on peut revenir en arrière avec les boutons habituel. J'ai juste rajouter   <system>
        \<fullname>Screenshots\</fullname>
        \<name>mame\</name>
        \<path>/recalbox/share/screenshots\</path>
        \<extension>.png\</extension>
        \<command>python /usr/lib/python2.7/site-packages/configgen/emulatorlauncher.pyc %CONTROLLERSCONFIG% -system %SYSTEM% -rom %ROM%\ \</command>
        \<platform>arcade\</platform>
       \<theme>fds\</theme>
    \</system> a es_systems.cfg (oui j'utilise le thème de la fanicom disk faute de mieux).

**Comment by digitalLumberjack** [comment]
On va ajouter ca dans la prochaine release.

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-buildroot/commit/da397a9c9bcf983b8b6b65b3a743649134c6440f bring the libretro imagevewer.
We need a theme for that. And then we can display the screenshots easily

**Comment by digitalLumberjack** [comment]
@rockaddicted shouldn't i move that in 4.0 ?

**Comment by rockaddicted** [comment]
yep it is done, aded to the system, using the screenshots theme.
so we can move in 4.0.0 and close it

**Comment by digitalLumberjack** [comment]
A toi l'honneur :)

**Comment by rockaddicted** [comment]
haha
