### ISSUE TITLE
New controllers to add to mupen64plus (8bitdo, etc...)

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-os#437]
Salut
serait il possible d'ajouter dans inputAutoCfg.ini de Mupen64Plus , la configuration pour toutes les manettes 8bitdo + joystick et autres ?
afin de ne pas devoir le rajouter à chaque mise à jour.

Merci

**Comment by rockaddicted** [comment]
Haha ou faire un configgen avant la sortie de la 3.3.0.
/me part de cacher ;-D

**Comment by Didlith** [comment]
la nes30 pro a été ajouté pour la N64 je ne sais pas ce qu'il en ai des autres

**Comment by rockaddicted** [comment]
Pas de soucis pour ajouter les config, il faut juste faire passer les configs car je n'ai pas les manettes sous la main.

**Comment by redgod** [comment]
[Microntek USB  Joystick  ]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(2)
A Button = button(1)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(2+)
C Button U = axis(2-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch = 
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by idarius** [comment]
[XiaoMi Bluetooth Wireless GameController                        ]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(11)
Z Trig = button(9)
B Button = button(3)
A Button = button(0)
C Button R = axis(2+)
C Button L = axis(2-)
C Button D = axis(5+)
C Button U = axis(5-)
R Trig = button(7)
L Trig = button(6)
Mempak switch =
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by rockaddicted** [comment]
[Microntek USB Joystick ] & [XiaoMi Bluetooth Wireless GameController ] added

**Comment by draxx31** [comment]
;Joystick (DragonRise Inc.   Generic   USB  Joystick  ) has 7 axes (X, Y, Z, Rx, Rz, Hat0X, Hat0Y)
;and 12 buttons (Trigger, ThumbBtn, ThumbBtn2, TopBtn, TopBtn2, PinkieBtn, BaseBtn, BaseBtn2,
;BaseBtn3, BaseBtn4, BaseBtn5, BaseBtn6).
[DragonRise Inc.   Generic   USB  Joystick  ]
pluggued = True
plugin = 2
mouse = false
AnalogDeadZone = 4096,4096
AnalogPeak = 32768,32768
D Pad R =
D Pad L =
D Pad D =
D Pad U =
Start = button(9)
Z Trig = Button(8)
B Button = button(4)
A Button = button(5)
C Button R = button(1)
C Button L = button(3)
C Button D = button(2)
C Button U = button(0)
R Trig = Button(7)
L Trig = Button(6)
Mempak switch =
Rumblepak =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by psyberpunk** [comment]
Please add this controller:

[USB Gamepad ]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(0)
B Button = button(2)
A Button = button(1)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(2+)
C Button U = axis(2-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(3)
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by rockaddicted** [comment]
wiki to follow to configure N64 controllers : https://github.com/recalbox/recalbox-os/issues/437

**Comment by Cluf20** [comment]
After Beta 14, config for NES30 Pro

;Nes30 Pro Controller
[Bluetooth Wireless Controller   ]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = axis(1+)
DPad L = button(1-)
DPad D = button(0+)
DPad U = button(0-)
Start = button(181)
Z Trig = button(179)
B Button = button(171)
A Button = button(170)
C Button R = axis(2+)
C Button L = axis(2-)
C Button D = axis(3+)
C Button U = axis(3-)
R Trig = button(177)
L Trig = button(176)
Mempak switch =
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by rockaddicted** [comment]
@draxx31 Hello, est ce normal que tu n'ais pas mappé les Dpad dans ton config ?
```
D Pad R =
D Pad L =
D Pad D =
D Pad U =
```

**Comment by draxx31** [comment]
J'ai ajouté la conf pour les D-PAD dans mon post original, vous pouvez donc l'intégrer à présent :)

**Comment by rockaddicted** [comment]
[DragonRise Inc. Generic USB Joystick ] &  [USB Gamepad ] added
;Nes30 Pro Controller [Bluetooth Wireless Controller ] updated

**Comment by GithubWerner** [comment]
Please add this controller:

[SPEEDLINK TORID]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(1)
A Button = button(2)
C Button R = axis(2+)
C Button L = axis(2-)
C Button D = axis(3+)
C Button U = axis(3-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch =
X Axis = axis(0-,0+)
X Axis = axis(1-,1+)

**Comment by GithubWerner** [comment]
Please add this controllers:
Upper Comment has a failure duplicate X Axis

[SPEEDLINK TORID]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(1)
A Button = button(2)
C Button R = axis(2+)
C Button L = axis(2-)
C Button D = axis(3+)
C Button U = axis(3-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

[Performance Designed Products Wireless Controller for PS3]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(1)
A Button = button(2)
C Button R = axis(2+)
C Button L = axis(2-)
C Button D = axis(3+)
C Button U = axis(3-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by SandroBR** [comment]
Change
[DragonRise Inc. Generic USB Joystick]
to
[DragonRise Inc.   Generic   USB  Joystick]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(1)
A Button = button(2)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(4+)
C Button U = axis(4-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by SandroBR** [comment]
correct
"DragonRise Inc.   Generic   USB  Joystick"
incorrect
"DragonRise Inc. Generic USB Joystick"

**Comment by SandroBR** [comment]
correct 
"DragonRise_Inc.___Generic___USB__Joystick__"  --> change _ to espace
incorrect
"DragonRise Inc. Generic USB Joystick"

**Comment by SandroBR** [comment]
Sorry, I am unable to send the correct string.
correct
"DragonRise Inc._-_Generic_-_USB_-Joystick_-"    --> change "_" or "-" to espace
incorrect
"DragonRise Inc. Generic USB Joystick"

[DragonRise Inc. Generic USB Joystick]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(1)
A Button = button(2)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(4+)
C Button U = axis(4-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by SandroBR** [comment]
Sorry, I am unable to send the correct string.
correct
"DragonRise Inc. x3Generic x3USB x2Joystick x2" --> change " x2" to 2 espaces and " x3" to espaces
incorrect
"DragonRise Inc. Generic USB Joystick"

[DragonRise Inc. Generic USB Joystick]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(1)
A Button = button(2)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(4+)
C Button U = axis(4-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by SandroBR** [comment]
test &nbsp;&nbsp;&nbsp;&nbsp;oooo

**Comment by SandroBR** [comment]
[DragonRise Inc.&nbsp;&nbsp;&nbsp;Generic&nbsp;&nbsp;&nbsp;USB&nbsp;&nbsp;Joystick&nbsp;&nbsp;]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(1)
A Button = button(2)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(4+)
C Button U = axis(4-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by SandroBR** [comment]
Change
[DragonRise Inc. Generic USB Joystick]
to


[DragonRise Inc.&nbsp;&nbsp;&nbsp;Generic&nbsp;&nbsp;&nbsp;USB&nbsp;&nbsp;Joystick&nbsp;&nbsp;]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(1)
A Button = button(2)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(4+)
C Button U = axis(4-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)


Thanks

**Comment by Dimidanger** [comment]
[ShanWan Gioteck PS3 Wired Controller]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(3)
A Button = button(2)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(2+)
C Button U = axis(2-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch = 
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by wgmyers** [comment]
The above config for the NES30 Pro did not work for me.

The following config did:

```
;Nes30 Pro Controller
[Bluetooth Wireless Controller]
[8Bitdo NES30 Pro]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = axis(6+)
DPad L = axis(6-)
DPad D = axis(7+)
DPad U = axis(7-)
Start = button(11)
Z Trig = button(4)
B Button = button(1)
A Button = button(0)
C Button R = axis(2+)
C Button L = axis(2-)
C Button D = axis(3+)
C Button U = axis(3-)
R Trig = button(7)
L Trig = button(6)
Mempak switch = 
Rumblepak switch = 
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)
```

**Comment by rockaddicted** [comment]
I close this issue, because a configgen is now integrated to recalbox 4.0.0

**Comment by guilegatan** [comment]
[ZEROPLUS PS(R) Gamepad Adaptor]
pluggued = True
plugin = 2
mouse = false
AnalogDeadZone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(5)
B Button = button(3)
A Button = button(2)
C Button R = axis(2+)
C Button L = axis(2-)
C Button D = axis(3+)
C Button U = axis(3-)
R Trig = button(7)
L Trig = button(6)
Mempak switch =
Rumblepak =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by guilegatan** [comment]
[Dual PSX-USB Adaptor  Dual PSX-USB Adaptor ]
pluggued = True
plugin = 2
mouse = false
AnalogDeadZone = 4096,4096
AnalogPeak = 32768,32768
DPad R = button(13)
DPad L = button(15)
DPad D = button(14)
DPad U = button(12)
Start = button(9)
Z Trig = button(7)
B Button = button(3)
A Button = button(2)
C Button R = axis(2+)
C Button L = axis(2-)
C Button D = axis(3+)
C Button U = axis(3-)
R Trig = button(5)
L Trig = button(4)
Mempak switch =
Rumblepak =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by paradadf** [comment]
[ELAN TURBO PAD]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32767,32767
DPad R = axis(4+)
DPad L = axis(4-)
DPad D = axis(5+)
DPad U = axis(5-)
Start = button(9)
Z Trig = button(4)
B Button = button(0)
A Button = button(1)
C Button R = axis(2+)
C Button L = axis(2-) button (3)
C Button D = axis(3+) button (2)
C Button U = axis(3-)
R Trig = button(7)
L Trig = button(6)
Mempak switch = 
Rumblepak switch = 
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by substring** [comment]
As rockaddicted said, in 4.0.0, mupen takes the config from ES, so no need to customize any file

**Comment by paradadf** [comment]
Ups, sorry! I just followed the link from the wiki and pasted my configuration.

**Comment by wakeuteu** [comment]
For those still running 3.3.0, I have noticed a typo for [Thrustmaster dual analog 3.2] line 634, 'Thrustmaster' referenced as 'Mega World', just replace that and it will work :-)
Sorry to comment a closed issue but I don't think a new issue for a single typo is relevant.

**Comment by guilegatan** [comment]
Please keep these comments! I am still using RecalBox 3.3 and this is a good reference whenever I loose my configs :-)
Here is another one sold as "Gioteck VX3 Wired PS3 Controller" in Europe.

[ShanWan Gioteck PS3 Wired Controller]
pluggued = True
plugin = 2
mouse = false
AnalogDeadZone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = Button(7)
B Button = button(3)
A Button = button(2)
C Button R = axis(2+)
C Button L = axis(2-)
C Button D = axis(3+)
C Button U = axis(3-)
R Trig = Button(5)
L Trig = Button(4)
Mempak switch =
Rumblepak =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)
