### ISSUE TITLE
mupen64 / GPIO Controller 1 / Select closes Emulator

### ISSUE THREAD

**Issue by hstampfl** [recalbox/recalbox-os#44]
When pressing 'SELECT' on GPIO Controller 1 the emulator go back to emulationstation (exit).
PS3 Controller works fine.

**Comment by digitalLumberjack** [comment]
This is because the HOTKEY button closes the N64 emulator. There is no way
to add a button combination in mupen64 to quit... Sorry for now it will be
like that...

**Comment by hstampfl** [comment]
hmmm...aren't there gpio's free for giving the GPIO Controller one more button. 
perhaps a modified joystick driver without the possibilites but with the limitation of only 2 controllers.

**Comment by digitalLumberjack** [comment]
I kept the 2 i2c gpio free on the driver, in order to add MCP23017 for
exemple to get more gpio controller (up to 16 i think)
Except thoses 2 gpio, all are taken.
The best would be to change the mupen64 sources to quit on a button
combination.
I'll do it when it's time.

**Comment by hstampfl** [comment]
when is this driver loaded during startup?
A solution could also give the driver a configuration file were the user can defines what he needs.
eg. how many gpio controllers, how many buttons per controller,  i2c gpio for mor than 2 controllers, usw...

**Comment by digitalLumberjack** [comment]
yes that could do the trick :)

**Comment by digitalLumberjack** [comment]
See https://github.com/digitalLumberjack/recalbox-os/issues/55
The configuration of the driver could be in this file.

**Comment by jamiecounsell** [comment]
+1 would love to see a button combination for emulator exit. Seems like this issue dates back [to 2010](https://code.google.com/p/mupen64plus/wiki/ControllerSetup).

**Comment by rockaddicted** [comment]
done  : https://github.com/recalbox/recalbox-os/issues/616
