### ISSUE TITLE
8bitdo Zero contrôle partiellement fonctionnel 

### ISSUE THREAD

**Issue by Didlith** [recalbox/recalbox-os#446]
Bonjour 

j'ai eu l'agreable surprise lors de la connexion de ma 8bitdo Zero a la recalbox de me rendre compte que celle ci fonctionne en partie sous Kodi
seul les touche directionnel son active comme vous pouvez le voir sur la video que j'ai faite : 
 https://youtu.be/nPEZXEM8_tg

j'ai fait les test sur 2 recalbox
la premiere j'ai ajouté la manette en BT via le menu
puis j'ai essayer de configurer les boutons et ne faisant cela j'ai remarque que les control directionnel ne ce validais pas j'ai donc abandonner cette config

pour la seconde ( on apprend de ces erreur ) 
j'ai donc appairé via le menu
fait la conf en allant directement sur les conf des touche 
A,B,X,Y,L,R,start,select + HK

je suis aller sous Kodi et j'ai refait le test de la video
et encore une fois seul les direction fonctionne

a voir si on peut aller plus loins
si besoin de fichier ou autre dite le moi

**Comment by rockaddicted** [comment]
controllers support added to Kodi
