### ISSUE TITLE
Streamer sur Twitch

### ISSUE THREAD

**Issue by orion2036** [recalbox/recalbox-os#447]
Je vous propose d'inclure une fonction permettant de streamer nos parties sur Recalbox vers Twitch, un site qui stream les parties de joueurs sur divers jeux :)

We could add a stream function that could stream our games to a website like Twitch

**Comment by digitalLumberjack** [comment]
I don't think the bradcom and videocore will be able to do that.

**Comment by julianxhokaxhiu** [comment]
I think it can, and it should be quite easy to be done ( a Python script is necessary I guess ) :)

https://www.reddit.com/r/raspberry_pi/comments/3fxnyz/twitchtv_and_a_raspberry_pi_2/
