### ISSUE TITLE
xbox wireless controller does not work in games

### ISSUE THREAD

**Issue by hackgrid** [recalbox/recalbox-os#45]
Hi,

thanks for this great product! :-)

My wireless xbox controller only works in the input config and in emulation station. 
I can start a game (snes) but then the button don't work anymore. The yellow text at the beginning shows at the bottom and mentions the xbox controller though...

Normal USB controller works fine!

Would be great if you could fix that or tell me how I could help with this. (dmesg or something?)

Recalbox would be perfect then :-)

**Comment by digitalLumberjack** [comment]
Yes many people have issues with that.
Could you past me the following files : 
```
/recalbox/configs/retroarch/retroarchcustom.cfg
/recalbox/configs/retroarch/inputs/*

/root/.emulationstation/es_input.cfg
/root/recalbox.log
/root/generateconfig.log
``` 
And a `dmesg` when you plug your usb dongle and connect the controller.

And `cat /proc/bus/input/`

**Comment by digitalLumberjack** [comment]
No news @hackgrid ?

**Comment by hackgrid** [comment]
Sorry, will try to get the files tonight or tomorrow :-(

**Comment by hackgrid** [comment]
Hi,
i just tested it again and it works. The wireless xbox controller works if it is the only controller plugged in. If i start with a ripoff snes usb controller and the xbox controller, then both will work in emulationstation, but the xbox controller won't work ingame. ( i can still press any button on the xbox controller to skip intros and such, but I cannot use the pad or any buttons).

I just try to unplug both usb controllers and plug the xbox controller into first, this way the xbox controller works but not the other usb controller. I guess so it is not a problem with the xbox controller but with two different usb controllers at once?

**Comment by hackgrid** [comment]
Pastebin with only the xbox controller (all files, search for "# cat")
http://pastebin.com/6239YZnS

Pastebin with xbox controller plugged in first, then plugged the other usb controller in. #2 controller does not work correctly ingame.

http://pastebin.com/hn3RbTTf

**Comment by substring** [comment]
@hackgrid wireless xbox360 pads should work by now (since months alerady). Shall we close this issue ?

**Comment by nadenislamarre** [comment]
no feedback as requested for several monthes. I close.
