### ISSUE TITLE
C64 support

### ISSUE THREAD

**Issue by jogges** [recalbox/recalbox-os#452]
Hi guys,

Can you add C64 support? When it comes to retro games, I don't think you should skip that!

Thanks in advance ;)

**Comment by mawilmsen** [comment]
+1 appreciate C64 support very much

**Comment by Haifisher** [comment]
+1 Please make C64 support. Thanks

**Comment by chrismelikian** [comment]
+1 for C64 support!

**Comment by MICKtheBIG** [comment]
+1 would love to play Giana Sisters again

**Comment by Stonejackit** [comment]
+1 reC64lbox for 2016 would be awesome!!!

**Comment by cpetry** [comment]
+1 C64 support!

**Comment by Khalzaam** [comment]
+1 for this one !

**Comment by boeserwolf** [comment]
+1 for Commodore C=64 support

**Comment by MICKtheBIG** [comment]
Unfortunately not part of release 4.0

**Comment by Stonejackit** [comment]
:'( maybe in later releases?

**Comment by rockaddicted** [comment]
So few people working in recalbox, and so many work ... We must do some choices :-/
So yeah, C64 should be supported in the next releases, but not 4.0.0
If someone is very impatient and want take this point to help us, no problem, you are welcome. :wink:

**Comment by Stonejackit** [comment]
oh, I didn't mean to push...sorry. take your time. Unfortunately i am no programmer, but a decent graphic artist. So if you are in need of some graphix stuff, let me know!

**Comment by mawilmsen** [comment]
thanks for the update @rockaddicted

**Comment by MICKtheBIG** [comment]
@rockaddicted: Yeah, no problem. I just were hoping for C64-Support within Release 4.0. I would be interested in helping to provide C64-Support but I don't have a clue where to start. Would you mind helping me getting started?

**Comment by rockaddicted** [comment]
haha I understand, no problem. We have everyone some systems in our heart that we would see in recalbox.
So if you want to help us on C64, you are welcome.
First recalbox is not based on a debian distri as raspbian. It an OS build from scratch, using buildroot.
So we don't have any package manager.
If you want to add a software, you must create a specific buildroot package.

So in a first time, you should read the wiki about compilation & modification of recalbox : https://github.com/recalbox/recalbox-os/wiki/Compilation-&-Modifications-%28EN%29
Then come in irc https://kiwiirc.com/client/irc.freenode.net/#recalbox to talk with us and ask your questions.

**Comment by rockaddicted** [comment]
@Stonejackit actually we are working on a new ES theme.
And we need to vectorize many elements.
So if you have skills on adobe illustrator, you could look this post and help the team working on the graphics side. http://blog.recalbox.com/forums/topic/new-theme-we-need-you/

**Comment by Khalzaam** [comment]
Problem is, I'm bad at graphic design, and bad at dev ... So .. ^^'
Let me learn a little, I'll try to figure out how to compil and modif ...
while on windows :)

2016-02-25 15:02 GMT+01:00 rockaddicted <notifications@github.com>:

**Comment by Stonejackit** [comment]
@rockaddicted ok, i can do that. unfortunately my french is rather "basic"...as in "I don't speak a word" *^_^* But I think i know what is needed. So I could pick one of the not checked systems in the todo list, let's say MSX 2+ and do a vektorbased illustration + background in system like colors, right? Since there were different MSX computers I would pick this beauty: http://i.ebayimg.com/00/s/NjAwWDc4NA==/z/CMcAAOSwyQtV6b06/$_1.JPG 
Can I add myself to the todo list?

**Comment by MICKtheBIG** [comment]
https://github.com/recalbox/recalbox-buildroot/pull/247
https://github.com/recalbox/recalbox-configgen/pull/46

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0
