### ISSUE TITLE
Root read only file system

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#453]

**Comment by digitalLumberjack** [comment]
retroarch and pifba are ok with the ro root now

**Comment by julianxhokaxhiu** [comment]
If you place the root filesystem as RO keep in mind you'll kill any possibility to have a custom configuration for /etc/fstab or any script change ( such in my case ) for Samba remote share automount.

Just my 2 cents.

**Comment by digitalLumberjack** [comment]
You're wrong. One can remount the fs in rw with one commandline if necessary.

**Comment by digitalLumberjack** [comment]
reste a 
- séparer les fichiers de config persistants et leurs versions crées par configgen.
- verifier le home lors d'un lancement standard
- mupen et scummvm

**Comment by nadenislamarre** [comment]
i m do ing several changes about that points (configuration files in ro).
please wait m'y changes to avoid conflits please. before january 1 i hope.
it should be possible to switch via the menu between i'ternal and listed
external usb keys for user data.
Le 22 déc. 2015 15:42, "digitalLumberjack" <notifications@github.com> a
écrit :

**Comment by digitalLumberjack** [comment]
tkt j'avais ça en tête.

**Comment by nadenislamarre** [comment]
if the todo is about 4.0 i add :
1) es segfault when synchro bluetooth
2) es keyboard broken if es started after network and network available -
s31 & s40
Le 22 déc. 2015 16:31, "digitalLumberjack" <notifications@github.com> a
écrit :

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-os/issues/580 for scummvm
mupen seems ok @rockaddicted  @substring can you confirm ?

**Comment by digitalLumberjack** [comment]
ok the only remaining problem is Bluetooth and we have a issue for that https://github.com/recalbox/recalbox-os/issues/629
