### ISSUE TITLE
Automatically copy roms from usb 

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#454]

**Comment by Tloz** [comment]
Je suis d'accord pour m'en charger s'il le faut

**Comment by digitalLumberjack** [comment]
En fait la nouvelle politique de partition share de la 4.0.0 rend cette issue différente de ce pourquoi elle a été créée. Aujourd'hui l'utilisateur peut choisir sur quel périphérique il veut placer ses données (roms, gamelists, sauvegardes etc) (une option dans ES arrive pour permettre un choix simplfié).

Je pense qu'on va close celle ci, et ouvrir une autre issue https://github.com/recalbox/recalbox-os/issues/605

**Comment by digitalLumberjack** [comment]
Mais tu es le bienvenue si tu veux participer :)
