### ISSUE TITLE
ad ps4 bt support with ds4drv

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#456]
https://github.com/chrippa/ds4drv

**Comment by PhilG** [comment]
I think it might be possible to use a DualShock 4 controller by using >=BlueZ 5.14. Release notes said they added support for the DS4 in this version, though I don't know if a userspace driver might still be required.

**Comment by razzia23** [comment]
Is there a how to, to update the driver support? Or can someone help? I dont want to wait until the next release comes out.

**Comment by digitalLumberjack** [comment]
You can compile the system and create a buildroot package for the driver

**Comment by razzia23** [comment]
Hi digitalLumberjack, thank you for the quick answer - i've found the wiki page "https://github.com/recalbox/recalbox-os/wiki/Compilation-%26-Modifications-%28EN%29" but as a newbie its difficult to follow the instructions. How can I add the required ">BlueZ 5.14"-package into the buildroot ?

**Comment by kryptto** [comment]
My suggestion is wait till it goes live in the next update.  Just my two cents, if you can't do the build and test.

Sent from my iPad

On Jan 23, 2016, at 7:33 AM, razzia23 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi digitalLumberjack, thank you for the quick answer - i've found the wiki page "https://github.com/recalbox/recalbox-os/wiki/Compilation-%26-Modifications-%28EN%29" but as a newbie its difficult to follow the instructions. How can I add the required ">BlueZ 5.14"-package into the buildroot ?

**Comment by mxjoe** [comment]
PS4 Controller support would be awesome! :-)

**Comment by kryptalivian** [comment]
http://blog.petrockblock.com/forums/topic/what-controllers-are-you-using/page/2/#post-12791

**Comment by substring** [comment]
bluez5 has a native support for the PS4 controller ...

**Comment by gregoryfein** [comment]
Hey all.  Anything going on in regards to this feature request?

**Comment by substring** [comment]
My bad, it does need python3 + ds4drv
