### ISSUE TITLE
Enable/Disable samba

### ISSUE THREAD

**Issue by MaxCorpEnjoy** [recalbox/recalbox-os#459]
Add a switch somewhere to enable/disable the samba share.
Indeed, it's nice when you are alone on your local network, but when sharing the network (work, school, ...), your files are not safe.
Another option would be to add password support (no idea if it's possible).

**Comment by Djiit** [comment]
+1

**Comment by Dragda** [comment]
+1

**Comment by mgoulartBR** [comment]
+1

**Comment by digitalLumberjack** [comment]
+1

**Comment by rockaddicted** [comment]
done
