### ISSUE TITLE
recalbox-api for developper

### ISSUE THREAD

**Issue by MikaXII** [recalbox/recalbox-os#462]
Hi everyone,

If you are developper go check [recalbox-api](https://github.com/neolao/recalbox-api).
With this REST api you will be able to make your own apps (web/desktop) for recalbox.
You can use it since v3.3.b, but you must [install it](https://github.com/neolao/recalbox-api/blob/1.0.x/documentation/install-on-recalbox.md)
An buildroot package coming soon to make it available by default.

**Comment by Djiit** [comment]
This is AWESOME.

**Comment by MikaXII** [comment]
Api officialy released in [3.3.0-beta15](https://github.com/recalbox/recalbox-os/releases/tag/v3.3.0-beta15)

**Comment by matthuisman** [comment]
Maybe add reboot and shutdown end points that use the clean methods that emulationstation uses?

**Comment by MikaXII** [comment]
@matthuisman issue add [recalbox-api](https://github.com/neolao/recalbox-api/issues/2).
Please for next issues go to [recalbox-api/issues](https://github.com/neolao/recalbox-api/issues).
