### ISSUE TITLE
N64 and 8bit Controller NES30PRO Problem

### ISSUE THREAD

**Issue by bogi1102** [recalbox/recalbox-os#465]
data: RP2 with Recalbox 3.3.0 Beta 9 and 8 bit controller N64 does not play. All games can be started but the controller has no function

**Comment by bogi1102** [comment]
now works with firmware V1.66
Only the X and Y buttons are not working. Can you set this yet?

**Comment by bogi1102** [comment]
Wrong does not work with 1.66

Has only works because it has recognized the controller 2.

How do I order the 1 is selected as the controller and not 0 ??

N64 does not recognize designation as a controller 0. Please update with change or help with brief assistance.

**Comment by bogi1102** [comment]
And How can I possibly one the fuktionieren the 2 other buttons on the controller?

X and Y do not work as well as R1 and L1

Please help

**Comment by rockaddicted** [comment]
Hello, N64 is a standalone version, not libretro, and it is not ever added to the configuration generator.
So you need to configure manually your controllers.
If you need more informations, I wrote this page : https://github.com/digitalLumberjack/recalbox-os/wiki/Configure-N64-controllers-%28EN%29

**Comment by bogi1102** [comment]
and as I have a point that the controller will be recognized at all leg N64 Games. it is only a 2 detected controllers. So if 2 are connected controller I can play with the controller 3. c you can not remove the problem?

**Comment by bogi1102** [comment]
and as I have a point that the controller will be recognized at all leg N64 Games. it is only a 2 detected controllers. So if 2 are connected controller I can play with the controller 2. c you can not remove the problem?

**Comment by bogi1102** [comment]
why it works then when I connect a 2 Controller <?????????????

**Comment by rockaddicted** [comment]
Once started a n64 game, close it, and give me these files on pastebin.
`/usr/share/mupen64plus/InputAutoCfg.ini` and `/root/recalbox.log`

**Comment by bogi1102** [comment]
pastebin ??

**Comment by rockaddicted** [comment]
http://pastebin.com

**Comment by rockaddicted** [comment]
You dont need a login. You can use it as guest. Paste your files, upload them and give us links on this post. It is really easy to use ;)

**Comment by bogi1102** [comment]
Ok ! Thank you

**Comment by bogi1102** [comment]
http://pastebin.com/HDFEgSiG

**Comment by bogi1102** [comment]
So mistakes as before. N64 games work when infected with the 2 controller. But not all of the keys.
Can not we no longer occurs in an update with the embed this Error NES30Pro

**Comment by rockaddicted** [comment]
So if I understand, your first controller is not recognized, and your second one, nes30pro is recognized? I need your `/recalbox/configs/mupen64/mupen64plus.cfg` file please.
What kind of controller is your first one?

**Comment by bogi1102** [comment]
http://pastebin.com/RF0QXqYS

**Comment by bogi1102** [comment]
exactly they have understood correctly.
Currently, only 1 controller is logged. And this is not working in N64

**Comment by rockaddicted** [comment]
Ok, so mupen64plus is a standalone emulator, not a retroarch as others emulator. And it is not included in the recalbox's configgen (auto configuration's generator), so, if your controller is not recognized, you need to configure it manually.   
You first one controller is not recognized, so need to add your configuration to the system.   
I wrote this tuto to help you.   

Another thing to know about Mupen64Plus, is about controller/player number allocation. When you start your recalbox, the first controller connected, will be automatically assigned to the first player in Mupen64Plus, the second one as player 2 etc...
So if you want to play with your NES30Pro as player one, start your recalbox without connected controllers, connect your NES30Pro, then your other controllers.

About the NES30pro configuration, included in Mupen64Plus. All N64's buttons are configured, so no problem to play with it out the box. Some buttons are not affected to the configuration, because N64 don't need them. You can use these buttons to affect specials commands (look my tuto).   
More informations about out the box, NES30Pro configuration :   
```
;Nes30 Pro Controller
[Bluetooth Wireless Controller   ]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = axis(1+)
DPad L = button(1-)
DPad D = button(0+)
DPad U = button(0-)
Start = button(11)
Z Trig = button(9)
B Button = button(1)
A Button = button(0)
C Button R = axis(2+)
C Button L = axis(2-)
C Button D = axis(3+)
C Button U = axis(3-)
R Trig = button(7)
L Trig = button(6)
Mempak switch =
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)
```

**Comment by bogi1102** [comment]
I understand everything.
But it could be so manually touch with in your file.
The controller name on the Recalbox for NES30Pro reads:
szmy-Power Ltd. Joypad
Try it now. He will now play also recognized at N64

**Comment by rockaddicted** [comment]
Did you updated your NES30Pro firmware to the last version ?
Did you start it in the good mode ?
https://github.com/digitalLumberjack/recalbox-os/wiki/8bitdo-on-recalbox-%28EN%29

**Comment by bogi1102** [comment]
have the firmware 1.62

As from 1.63 no automatic connection stops working.

have chosen the normal connection. Normal switch and connect

**Comment by bogi1102** [comment]
He is now well recognized. You should also play at N64. Just a few keys such as Y, B, R1 and L1 not go

**Comment by bogi1102** [comment]
This controller has indeed quite different keys as for example your controller. Deswergen your settings will not work either.

But what I find funny. Add through which he is indeed now recognized as such if I have a 2 Controller switched on.

Now we have to hammer out the keys here just yet.

**Comment by bogi1102** [comment]
This controller is simply just the right for Recalbox and I think the more this problem have not just me.

**Comment by rockaddicted** [comment]
OK so adapt your configuration using the tuto, and once your config is OK, backup your InputAutoConf.ini because it will be erased during the next recalbox update.

Mupen64Plus will be added to configgen to autoconfig emulator, but it is a lot of work. So that will be done in the next 3.3.1, not before.

**Comment by psyberpunk** [comment]
Hi every one, I need your help to configure my controler, my controler is a snes usb gamepad, when I use jstest /dev/input/js0 command I get this:

Joystick (USB Gamepad ) has 2 axes (X, Y)
and 10 buttons (Trigger, ThumbBtn, ThumbBtn2, TopBtn, TopBtn2, PinkieBtn, BaseBtn, BaseBtn2, BaseBtn3, BaseBtn4)

I know that I need to add the information to the end of this file:
/usr/share/mupen64plus/InputAutoCfg.ini

But where or how I can get the info that I need to map my controller right to get it work for n64 games? 
I just have name of the controller correct

Joystick (USB Gamepad )
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(2)
A Button = button(1)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(2+)
C Button U = axis(2-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch = 
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

![control super nintendo](https://cloud.githubusercontent.com/assets/15371449/10864399/7f41bb4c-7fb2-11e5-92cb-dbfd5c90be73.jpg)

I hope you can help with this matter, thank you vey much...

**Comment by bogi1102** [comment]
Joystick [USB Gamepad ]

That is correct.
The important thing is the name as it is recognized by the Recalbox.

possibly the wrong characters used.

**Comment by psyberpunk** [comment]
Thanks bogi1102 for your early reply, I changed the characters and paste it at the end of the file /usr/share/mupen64plus/InputAutoCfg.ini like this: 

Joystick [USB Gamepad ]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(9)
Z Trig = button(7)
B Button = button(2)
A Button = button(1)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(2+)
C Button U = axis(2-)
R Trig = button(5)
L Trig = button(4)
Mempak switch = button(6)
Rumblepak switch = 
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

and still does not work, I can enter any n64 game but when I'm inside of a game none of the buttons work but one "select" and if a press it send me to N64 game menu.

Do you another recommendation to make it work?

Thank you very much...

**Comment by bogi1102** [comment]
do you have a 2 controller because you can simultaneously infect times?
To test whether he can then control with 2 controllers?
Which game did you tested?
But the games start?


The settings you have saved but?

**Comment by psyberpunk** [comment]
Thank's again bogi1102,

I just have two controller (same model as above), but only one conected to recalbox,  I can enter the game but I can not start the game,  just one button works, and that button is Select, when i press it return me to the nintendo 64 games list,

I tested Mario Kart 64, Super Mario 64, Golden Eye,

Thank's in advance for all your help

**Comment by bogi1102** [comment]
you can try it if all are infected 2 controller? Whether then 1 works?

**Comment by rockaddicted** [comment]
Hello, and if you try with that in `your /usr/share/mupen64plus/InputAutoCfg.ini`

```
[USB Gamepad ]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
...
```

**Comment by psyberpunk** [comment]
rockaddicted, Thank you very much... It worked, I really appreciate all your help. 

bogi1102, thanks also for your help, You rock guys
