### ISSUE TITLE
Kodi returns to the recalbox

### ISSUE THREAD

**Issue by bogi1102** [recalbox/recalbox-os#469]
Kodi returns to the recalbox. if you start Kodi he jumps off and back into the recalbox

**Comment by digitalLumberjack** [comment]
@bogi1102 still the same with beta 14 ?

**Comment by bogi1102** [comment]
Problem persists even after the update yet.
Once Kodi is started and it is ready to load the EPG files he returns to the Recalbox unless you change coinciding with the keyboard between menus then he remains in Kodi

**Comment by bogi1102** [comment]
do you have a 2 controller because you can simultaneously infect times?
To test whether he can then control with 2 controllers?
Which game did you tested?
But the games start?

**Comment by bogi1102** [comment]
The settings you have saved but?

**Comment by nadenislamarre** [comment]
not enough information.
