### ISSUE TITLE
RecalBox/Kodi file system size problem

### ISSUE THREAD

**Issue by phoenixmn75** [recalbox/recalbox-os#472]
I have been noobs since two weeks ago. I am trying to find what file to modify to allow when the beta9 version build the OS on the sd for the root partition that is is bigger than 1.9gb. As I add add-on in Kodi I am running out of space. Also when can we expect the kodi 15.2 version be installed with reacalbox release.

So two things:

Bigger /dev/root more than 2gb or a way to extend it in a file before the load prefer it to be 6gb with the use of a 16gb card.
Loading Kodi 15.2 within the recalbox extraction If possible. 14.2 is working. 

Raspberry pi 2
not overclocked
recalbox 3.3 beta 9
Kodi 14.2
16GB SD Ultra

**Comment by phoenixmn75** [comment]
if easier to give step by step or a file I should modify in the zip folder before extracting on SD card I would appreciate it.

**Comment by rockaddicted** [comment]
Once your recalbox downloaded and uncompressed on your SD card.
You can change partitions size with this file : 
https://github.com/recalbox/recalbox-rescue/blob/dual/sdcontent/os/recalboxOS-rpi2/partitions.json

**Comment by digitalLumberjack** [comment]
Corrected in 4.0.0 as kodi files are now on storage.
