### ISSUE TITLE
Aspect Ratio - vertical black borders in game on 5:4 1280x1024 DVI Screen v3.3.0-beta-9

### ISSUE THREAD

**Issue by yy-cube** [recalbox/recalbox-os#473]
Hi,
I just switched from recalboxOS-v3.2.11 to recalboxOS-v3.3.0-beta-9.
On my 1280x1024 monitor the recalboxOS mainscreen is fullscreen but every game I start has borders like I would run it on a 16:9 screen. I switched to my 16:9 TV & Monitors and everything had the correct aspect ratio. Switched back, still borders. Was testing on Pi B and Pi2. No problems with v3.2.11.
So i was playing around a bit with the aspect ratio settings within the game itself (retroarch) and from what I'm seeing it has probably something to do with this. Selected Aspect Ratio Index settings when I go to the video options menu are: "Config" which is the same like switching to "core provided" or  "4:3" to me. When switching to "16:9" in this menu I get the perfect Fullscreen for this game.
So what can I do to get every game in fullscreen like it was with the old version? Or can you maybe fix it?
Thanks in advance.

**Comment by digitalLumberjack** [comment]
Hi, you should try to change the videomode to default in recalbox.conf `global.videomode=default`
Or choose a video mode you want with tvservice see https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-(EN)#1---global-configuration
