### ISSUE TITLE
Wifi dongle D-link DWA-110

### ISSUE THREAD

**Issue by PixelReveur** [recalbox/recalbox-os#476]
Le dongle wifi DWA-110 de D-Link ne semble pas compatible.

Voila les drivers :
http://ftp.dlink.ru/pub/Wireless/DWA-110/Drivers/

**Comment by digitalLumberjack** [comment]
L'ajout des drivers fera l'objet d'un chantier pour les prochaines releases.

**Comment by nadenislamarre** [comment]
./rt73.bin added in 4.1
