### ISSUE TITLE
Update isn't working

### ISSUE THREAD

**Issue by mgoulartBR** [recalbox/recalbox-os#477]
Hey guys,

I'm trying to update Recalbox 3.3.0 Beta 9 to Beta 12 but it's not working. I have 6GB free on my SD Card. Do I need more space?

**Comment by digitalLumberjack** [comment]
No it should be enought, but dod you have free space in the root partition ?
What `df` show in CLI ?

**Comment by mgoulartBR** [comment]
I will check it!

**Comment by mgoulartBR** [comment]
```
[root@RECALBOX ~]# df
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/root              1983056   1483900    380372  80% /
devtmpfs                241384         0    241384   0% /dev
tmpfs                   245720         0    245720   0% /dev/shm
tmpfs                   245720       644    245076   0% /tmp
/dev/mmcblk0p7        28129856  21810336   6319520  78% /recalbox/share
/dev/mmcblk0p5           60479      7776     52704  13% /boot

```

**Comment by ed0c** [comment]
Same for me.
I also tried with the script rsync-update.sh which isn't seems to work.
Where is the update log file ?

**Comment by digitalLumberjack** [comment]
/root/updates.log

**Comment by ed0c** [comment]
Ok.
So i'v got these errors :
$./rsync-update.sh

rsync: safe_read failed to read 1 bytes [Receiver]: Connection timed out (110)
rsync error: error in rsync protocol data stream (code 12) at io.c(276) [Receiver=3.1.1]

$cat updates.log

begin update
info : will conntect to recalbox.com with credential : public
info : starting share update
error : unable to update share

**Comment by digitalLumberjack** [comment]
Ok you cannot connect to the rsync server. I'll check that.

**Comment by digitalLumberjack** [comment]
rsync server is up and it was never down. can you ping recalbox.com from your rpi ?

**Comment by ed0c** [comment]
ping recalbox.com
PING recalbox.com (94.23.55.163): 56 data bytes
64 bytes from 94.23.55.163: seq=0 ttl=47 time=150.608 ms
64 bytes from 94.23.55.163: seq=1 ttl=47 time=151.200 ms
64 bytes from 94.23.55.163: seq=2 ttl=47 time=149.734 ms
^C
--- recalbox.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 149.734/150.514/151.200 ms

Ping is working... Weird

**Comment by digitalLumberjack** [comment]
Ok so let's restart the rsync server just in case... I should wait the current updates are done.

**Comment by digitalLumberjack** [comment]
If you retry now ? It may be an issue beacause all slots where taken

**Comment by ed0c** [comment]
I'm trying.
I'v also a big ping, as you can see. It may be the problem.

**Comment by ed0c** [comment]
I have the same issue...
Do you have another rsync command detailled, and not a script, to see what's happening? 
Thanks!

**Comment by mgoulartBR** [comment]
I tried using rsync script, it's working!

**Comment by wjanes** [comment]
For me ist also not working.
Hangs on:


sent 11,607 bytes  received 9,787 bytes  8,557.60 bytes/sec
total size is 7,947,007  speedup is 371.46
info : starting root update
receiving incremental file list
bin/
bin/bash
error : unable to update root

**Comment by ed0c** [comment]
It worked with the script !! Maybe a slot problem.

**Comment by wjanes** [comment]
the script says that root Partition is full

**Comment by digitalLumberjack** [comment]
Did you scrape movies with kodi ?
Check with a `df` shows you 100% for root, and you can use a `du -s /root/.kodi` to see if it take place

**Comment by wjanes** [comment]
Hi digitalLumberjack you are right . the Folder is 1.3gb big
It was the Kodi Log file ^^. Thanks
