### ISSUE TITLE
Make snes9x_next the default

### ISSUE THREAD

**Issue by nadenislamarre** [recalbox/recalbox-os#478]
It has the advantages to :
- fix the mario all stars bug (players pad)
- fix the mario kart bug (position)
- add the multitap support (3 or 4 players)

People using it on irc says it works perfectly (except bomberman bug, but fixed recently)
It is supposed to have a lower framerate on rp1.

**Comment by digitalLumberjack** [comment]
Hi,
yes it does have lower framerate on rpi1. But also on rpi2. That's why it's not the default. But we are thinking about discussing about that

**Comment by digitalLumberjack** [comment]
done
