### ISSUE TITLE
mount ntfs device in rw mode from fstab

### ISSUE THREAD

**Issue by Dany21000** [recalbox/recalbox-os#482]

**Comment by Dany21000** [comment]
With this line in fstab : 
/dev/sda1 /recalbox/share ntfs     defaults,rw       0      0

The device is mounted, but cannot write on it, (mount return it in rw mode), Everytime permission denied...


I have edited /etc/init.d/S31emulationstation file and add in the start section theses lines :
umount /recalbox/share
ntfs-3g /dev/sda1  /recalbox/share

With this tip, the device is mounted by ntfs-3g/fuseblk wich is not included in the kernel so fstab cannot mount ntfs device in ntfs-3g or fuseblk type.

**Comment by nadenislamarre** [comment]
ntfs devices are now mounted in rw since 4.0
