### ISSUE TITLE
WPA2 connection problem

### ISSUE THREAD

**Issue by gulaschsuppn** [recalbox/recalbox-os#485]
I can not connect to my WPA2 network. 
In my SSID and in my password i have special character (@) and there is no way to connect to my WLAN network. 

I dont have any problem to connect to the same WLAN network with RetroPie.

**Comment by rockaddicted** [comment]
Did you try to configure your wifi through your recalbox.conf file?
https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-%28EN%29

**Comment by gulaschsuppn** [comment]
Yes.
Did not work.

**Comment by rockaddicted** [comment]
Which recalbox version are you using? 3.2.11 or 3.3.0 ?

**Comment by gulaschsuppn** [comment]
3.3.0 beta 14

**Comment by gulaschsuppn** [comment]
I think i have found the Problem.
When WLAN SSID is set to invisible than recalbox did not connect to the network.
SSID=visible -> no problem.

**Comment by nadenislamarre** [comment]
Can you retry in 4.1 beta once available and make a feedback please.

**Comment by cantero6** [comment]
Same problem here.

SSID not visible and Recalbox is not connectiong.

I am using the last version published recalboxOS-4.0.0-beta6

Any solution?

Thank you.

**Comment by rockaddicted** [comment]
Wait for the 4.1 version
