### ISSUE TITLE
N64 hotkey should be disable due to non working multiple button press

### ISSUE THREAD

**Issue by draxx31** [recalbox/recalbox-os#486]
Hello, 

I have a replica of N64 game pad and all my buttons are allocated for this emulator. But If I try to use the "Z" button allocated to the hotkey function and the same button used in the same time for the n64, the emulator exits.

If I tried to remove the event, recalbox set again the default value and my "z" button is again used as hotkey
Joystick event string for stopping the emulator
Joy Mapping Stop = "JB08"

This is very annoying because I often use the hotkey for all emulators to save my state, reload... but for N64 it blocks the use of one important button. Moreover it is not possible to move the hotkey to another button cause all buttons are used by each emulator (snes uses all buttons too, n64 too...).

My suggestion should be to allow to disable on n64 the auto allocation of hotkey for exit or to be able to map differently the hotkey per console.

**Comment by rockaddicted** [comment]
hotkey added : https://github.com/recalbox/recalbox-os/issues/616
