### ISSUE TITLE
External storage format.

### ISSUE THREAD

**Issue by iagotorrado** [recalbox/recalbox-os#487]
Just wanted to know (because I don't have any reason to believe otherwise) if the automounted external storage MUST be in FAT32. I mean is there a requirement by the system for it to be FAT32, or can we just format it as ext4?
My guess (as a noobie) is that you said FAT32 so users can pull out their USB drive and plug it into Windows PC to load ROMs and media files, but I must still ask. Also, there are some media files (such as HD movies) which are over the 4GB limit of FAT32.
Thanks for your patience.

**Comment by digitalLumberjack** [comment]
Hi, no it can be anything, but i cannot guarantee that it will automount if it is ext4.
