### ISSUE TITLE
Basque language in EmulationStation doesn't work

### ISSUE THREAD

**Issue by xa2er** [recalbox/recalbox-os#492]
Hello,

After changed the language in EmulationStation to basque and restart the recalbox, the language continues in english. This doesn't happen with other languages.

Thank you very much for your work!

Regards.

**Comment by digitalLumberjack** [comment]
Corrected that, it dos work now, and it will be in the soon to be release next beta :)

**Comment by xa2er** [comment]
Thank you very much!
