### ISSUE TITLE
Shanwan controllers won't connect anymore

### ISSUE THREAD

**Issue by yusf** [recalbox/recalbox-os#496]
I've been trying to set up two Dual Shock clones with an older Bluetooth adapter. When they connect at all the performance is poor and the connection never stays on for more than a minute. Got myself a new 4.0 Bluetooth adapter but now the controllers won't connect at all.
Where can I delete the settings for associated bluetooth devices and start the pairing process all over again?

**Comment by rockaddicted** [comment]
You can reset your controller using reset button behind the controllers.
Next time, thanks to use the forum to ask support on recalbox ;)
http://blog.recalbox.com/forums/

**Comment by yusf** [comment]
I was looking for a way to clear out any settings recalbox may have of BT controllers. 

Yes, sorry.
