### ISSUE TITLE
Unable to NOT map the special button in controller settings

### ISSUE THREAD

**Issue by MathijsG** [recalbox/recalbox-os#497]
I'm using a SmartJoy device which ables me to connect my original SNES controller, which is much better than those fake SNES controllers you find on Chinese websites.

However I'm unable to skip the special button at the end of the button list. I can skip other buttons I don't have on my controller with holding a certain button, but this button doesn't allow that, it also doesn't allow a combo of two buttons. So now my only option is to actually map this special button to a real button, but when I press this special button it will immediately go back to the games list. So this button must be designed to get out of the game. How am I supposed to play without skipping this button :-).

**Comment by digitalLumberjack** [comment]
Without the Hotkey, you won't be able to leave games you play. Just map it on select, as explained in the manual https://github.com/recalbox/recalbox-os/wiki/Manual-(EN)#configurecontrollers

**Comment by MathijsG** [comment]
But you also need select I think? Anyways I will try your solution. 

With my 360 controller without mapping things in a certain way I was able to reset with pressing both select and start button.

**Comment by digitalLumberjack** [comment]
I already answered that in the manual. Select can be Hotkey, as it have no special function.

**Comment by MathijsG** [comment]
In many emulators this does work now. But when I only press the select button in the N64 emulator now, it's already jumping back to EmulationStation.

**Comment by draxx31** [comment]
For me it is the same issue thatn : https://github.com/recalbox/recalbox-os/issues/486
