### ISSUE TITLE
Composite-Out Bugs in v3.3.0-beta-14

### ISSUE THREAD

**Issue by oson** [recalbox/recalbox-os#499]
I got some problems running RecalBox on my CRT. I changed the config.txt, so I get the Emulstation-Menu after startup.

N64-Emulator runs on my CRT. After changing starttype to 7 in emulatorlauncher.sh SNES games start correctly too. But I got a black screen after starting a PSX-Game!
tvservice -s shows me this information after starting the game:

`state 0x120019 [HDMI CEA (4) RGB lim 16:9], 1280x720 @ 60.00Hz, progressive`

Why the psx-emulator is switching to HDMI?

After exiting a Emulator-Game, Emulstation tries to start the menu again, but in HDMI-Mode, not again in Composite-PAL-Mode. Why?

`state 0x120015 [DVI CEA (1) RGB lim 4:3], 640x480 @ 60.00Hz, progressive`

**Comment by rockaddicted** [comment]
https://github.com/recalbox/recalbox-os/wiki/Connect-your-recalbox-to-a-CRT-with-composite-%28EN%29

**Comment by oson** [comment]
Thanks, but I know this wiki-site and I changed all files like it is described. Does it work with your CRT?

**Comment by rockaddicted** [comment]
Did you modify your global.videomode parameter in your recalbox.conf file ?
 
`global.videomode=default`

https://github.com/recalbox/recalbox-os/wiki/recalbox.conf-%28EN%29

Next time than you need support about recalbox, please go on forum and open a new topic.
Github is not the right place to do that, thanks.

http://blog.recalbox.com/forums/

**Comment by rockaddicted** [comment]
And yes, I am using recalbox a my CRT screens without any kind of problems.

**Comment by oson** [comment]
Yes I did. Sorry, I will do it next time in the forum. Is it able to delete this issue here?
