### ISSUE TITLE
Remap the SDL2 controllers with new sdl2 patches

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#501]

**Comment by orion2036** [comment]
BigBen PS3PAD http://pastebin.com/kPxQ8k12

**Comment by digitalLumberjack** [comment]
nice i'll add that to the new file

**Comment by substring** [comment]
NVIDIA Corporation NVIDIA Controller v01.03 http://pastebin.com/CqNfyfBu
Logitech Logitech RumblePad 2 USB http://pastebin.com/GaWR9DDk
DragonRise Inc.   Generic   USB  Joystick   http://pastebin.com/uXqUhAxW
All mapped with HK on L3

**Comment by rockaddicted** [comment]
manettes : 
- xbox360 wireless xboxdrv=on / xboxdrv=off / dongle officiel
- virtual gamepads
- trustmaster firestorm digital 2 usb

http://pastebin.com/AtM84t3x

**Comment by Laddyacris** [comment]
Broadcom Bluetooth Wireless  Joystick (idroid snakebyte)
http://pastebin.com/rHTh4ky7

**Comment by Laddyacris** [comment]
ipega bluetooth : http://pastebin.com/mCwrvKpm
Il semblerait qu il faut une regle udev : http://pastebin.com/6Zyf3Wq5
voir  : http://blog.recalbox.com/forums/topic/recalbox-et-manette-ipega-9025/#post-18137

**Comment by substring** [comment]
IPAC2 avec le Player 1 configuré en gamepad : http://pastebin.com/hEqFBYvX

**Comment by rockaddicted** [comment]
done
