### ISSUE TITLE
Odd KODI not starting bug?

### ISSUE THREAD

**Issue by matthuisman** [recalbox/recalbox-os#502]
After I install beta14 and then update to beta15, my KODI button in the emulation station menu doesn't work.

It's quite strange and I can't figure out what is happening.
Something is causing emulationstation to not even launch the kodilauncher.sh script.

However, if I manually run kodilauncher.sh once via terminal and let it boot into KODI, then the emulationstation link starts working from then on. (ODD!)

Any ideas?

**Comment by matthuisman** [comment]
Steps to reproduce (Raspberry Pi2)

Download Recalbox Beta14
Install
Update straight away
KODI link won't work
Open up terminal
/recalbox/scripts/kodilauncher.sh
KODI boots.
Exit KODI
Black screen
Power cycle
KODI link now works

**Comment by digitalLumberjack** [comment]
I will correct that thanks :)

**Comment by digitalLumberjack** [comment]
Corrected in beta 16

**Comment by matthuisman** [comment]
Out of curiosity, I can't see any commits in the repo related to the fix?
