### ISSUE TITLE
Image for Raspberry Pi Zero ?

### ISSUE THREAD

**Issue by christophprokop** [recalbox/recalbox-os#503]
Will there be an image for the Pi Zero?

https://www.raspberrypi.org/blog/raspberry-pi-zero/
http://thepihut.com/collections/new-products/products/raspberry-pi-zero

**Comment by Djiit** [comment]
I should have guess someone would propose that :)

**Comment by digitalLumberjack** [comment]
Firsst thought : I can't see gpu vc on this device. Does it have video acceleration ?

**Comment by digitalLumberjack** [comment]
Ok it does have the vc, that is builtin with the BCM :) good news

**Comment by MikaXII** [comment]
http://opensource.com/business/15/11/raspberry-pi-zero
Pi Zero packs the same great GPU as the regular Raspberry Pi, and comes with 512MB RAM

**Comment by lordslair** [comment]
Hello,

Is it not embedded in the BCM2835 ?

**Comment by christophprokop** [comment]
So maybe i can use the same image as i use for standard Raspberry Pi?

**Comment by digitalLumberjack** [comment]
Maybe.

**Comment by christophprokop** [comment]
ok, i ordered one and will find out ;)

**Comment by digitalLumberjack** [comment]
Cool let us know.

**Comment by kryptto** [comment]
http://www.element14.com/community/docs/DOC-68090/l/raspberry-pi-zero-pi-2-b-a-compute-module-dev-kit-comparison-chart

Comparison chart.

**Comment by kryptalivian** [comment]
I have a raspberry pi zero and I'm unable to get the image to work. Ended up grabbing a copy of noobs and dragging the raspberry pi 1 image in the OS folder in order to installation to boot.. 

It installs then when it goes to boot Recalbox, it just goes to a black screen. I've tried SONY, PNY, Samsung EVO, EVO+ and SAMSUNG PRO cards. Sizes range from 16-64GB

**Comment by nadenislamarre** [comment]
what about trying to boot on the rpi2 image ? as far as i understand, it's
more a rpi2

2015-12-01 21:32 GMT+01:00 kryptalivian <notifications@github.com>:

**Comment by kryptalivian** [comment]
Same issue with Raspberry Pi 2 Image :-(

**Comment by nadenislamarre** [comment]
ok.
I need a raspberry 0 to analyse.


2015-12-01 22:24 GMT+01:00 kryptalivian <notifications@github.com>:

**Comment by kryptalivian** [comment]
@nadenislamarre I'd be happy to test out some builds if you need me to down the road.

**Comment by kryptalivian** [comment]
Just saw this over on Lakka's site. They were having issues with Rpi 1 images working on the zero, but fixed it by "The new low cost version of the first Raspberry Pi has been released 10 days ago. This version is very small, and very cheap ($5). It’s already out of stock. We were not lucky enough to get one, but we upgraded our RPi build with the latest bootloader and kernel to make Lakka compatible with the tiny board."

**Comment by substring** [comment]
Pi0 is supported with v4
@rockaddicted issue can be closed

**Comment by digitalLumberjack** [comment]
Yep it's alright

**Comment by amilanesi67** [comment]
With Pi0W doesn't work. 
Recalbox Version 4.01: 
1) First appears multicolor screen (pi0 power led on)
2) Appears Recalbox logo (pi0 power led on)
3) Appears a black screen and no more (pi0 power led off)

Someone has the same problem?

**Comment by kryptalivian** [comment]
I'm pretty sure I got mine to work. I'll check tonight and make sure I was using the pi zero w. I know that I had to download a copy of noobs lite, and then drag and drop the rpi1 folder from my recalbox download over to the noobs lite OS folder. Otherwise recalbox download would boot noobs but not find the image to install.

**Comment by amilanesi67** [comment]
It's working! Sorry never used Noobs lite.
Now the problem is WiFi: with Noobs interface work perfect, SSID found and wifi recognized. Inside Recalbox Wifi doesn't work:  "WiFi configuration error" popup...

**Comment by kryptalivian** [comment]
Sounds like noobs had the driver, but recalbox is missing them. You wont see it working until at the very earliest, recalbox pushes out an update.
