### ISSUE TITLE
Cannot Exit, Shutdown, or Reboot from Kodi

### ISSUE THREAD

**Issue by elricsfate** [recalbox/recalbox-os#504]
Raspberry Pi 2 Model B. 
recalboxOS v3.3.0-beta16

How to replicate:

1. Fresh install. 
2. Enter Kodi from Emulationstation. 
3. Select "power button" icon in Kodi. 
4. Attempt to use Shutdown, Exit, or Reboot.
5. Goes back to Kodi with no black screen. The "power button" screens simply disappears.

**Comment by elricsfate** [comment]
From what I can tell, this only seems to happen SOME of the time. I tested it again and it now appears to be working correctly. I'll try and get a solid on the exact replication procedures.

**Comment by julianxhokaxhiu** [comment]
Happened also here. I guess it's a problem with controls. After I remapped them correctly it worked out of the box. But the "default" set is broken somehow ( at least with a Xbox-compatible Joypad ).

B was behavioring as A ( confirmation ) in main ES menu, but on Kodi any key was behavioring as B ( Cancel ).

**Comment by mxjoe** [comment]
I have a similiar problem. When I chose to leave Kodi the screen went black and it was stuck in this state.

**Comment by rockaddicted** [comment]
@mxjoe please read the wiki : https://github.com/recalbox/recalbox-os/wiki/Kodi-on-recalbox-%28EN%29#power-management-with-hdmi-cec

**Comment by mxjoe** [comment]
@rockaddicted Didn't know that, thank you!

**Comment by rockaddicted** [comment]
you are welcome :wink:

**Comment by nadenislamarre** [comment]
however,
keep the issue opened. I've work to do on the kodi exit menu.

2016-02-11 8:20 GMT+01:00 rockaddicted <notifications@github.com>:

**Comment by nadenislamarre** [comment]
fixed for release 4.0 beta2
