### ISSUE TITLE
USB keyboard with neogeo and 2 players

### ISSUE THREAD

**Issue by montabou** [recalbox/recalbox-os#505]
I had a problem when I was using a USB keyboard with the neogeo emulator. I was able to play with 1 player but not 2. The problem is linked to the keyboard. The emulator seems to take into account only the usb keyboard whereas the second controller was well configured.
The start and select buttons were not well recognized (I need to push 'f' to add coin and 'j' to start even if my keys were respectively space and enter).

If I disconnect the USB keyboard everything works correctly with 2 controllers.Thus, it's possible to play 2 players with 2 controllers but not with 1 controller and 1 usb keyboard.

Don't know if it should be considered as a bug or if it's just not supported. In that last case I guess a page on the wiki for that case should be mentioned. I've searched everywhere on issue, on forum, ask on IRC but I had no answer for that while it was in fact quite easy to solve. For now, I've encountered that problem only with neogeo.

I may add the wiki page if you think it should be mentioned!

**Comment by digitalLumberjack** [comment]
Keybard is not officially supported, neither configurated in configgen. So it's not a bug.
