### ISSUE TITLE
NES30 (v2.63) works in menu but not in games recalboxOS v3.3.0-beta16

### ISSUE THREAD

**Issue by fridayshoes** [recalbox/recalbox-os#507]
I have successfully paired 2 NES30 pads using START+B and START+B+R and have configured the buttons.

Both pads work fine in the RECALBOX menu, but when I start a game both pads fail to work at all

**Comment by Laddyacris** [comment]
try to resync and remapp gamepad

**Comment by neolao** [comment]
You need to use Start + R.
It does not work in game with the other modes.

**Comment by fridayshoes** [comment]
Thanks for the help guys, got it sorted now

For anyone else that is struggling this is the procedure.

1. Turn on the NES30 controller by holding START only
2. Then hold SELECT for a few seconds until both green and blue lights flash at the same time (This resets the controller)
3. Then, turn off the controller by holding START
4. Now turn on the controller by holding R and then hold START at the same time until the blue light flashes
5. Now keep clicking PAIR A BLUETOOTH CONTROLLER on the RECALBOX (you may have to keep doing this loads of times until it finds the controller. The blue light on the controller should stop flashing and go solid blue when it is successfully paired.
6. Now the controller is paired go to CONFIGURE A CONTROLLER on the RECALBOX and go through the procedure to assign each button.
7. Then set the controller to INPUT P1 (or P2, P3, P4 for each additional controller).

Repeat this procedure for each controller, step 5 you have to keep persevering with I found as it couldn't always detect the controller.

Hope this helps someone

**Comment by neolao** [comment]
I confirm that you need to retry several times to detect the device.
Sometimes it's quick.
