### ISSUE TITLE
GPU memory allocation

### ISSUE THREAD

**Issue by pedrocampelo** [recalbox/recalbox-os#509]
Hi guys! Is there any way to split the memory allocation in order to increase the GPU dedicated memory? Thanks.

**Comment by julianxhokaxhiu** [comment]
Guess by editing the `/boot/config.txt` ?

**Comment by pedrocampelo** [comment]
Thank you! I didn't know it was so simple.

**Comment by draxx31** [comment]
What is the interest on recalbox to add more memory to the GPU? Do you have encountered issues on with the preset memory settings?
