### ISSUE TITLE
Add support for Amstrad CPC

### ISSUE THREAD

**Issue by skitoo** [recalbox/recalbox-os#51]
Can you add support for Amstrad CPC ? 

Thank you :)

**Comment by digitalLumberjack** [comment]
https://github.com/libretro/libretro-cap32 someone already tried this libretro core ?

**Comment by diablodiab** [comment]
Yes, the sound quality is not very good and you will need to modify the code to add autoloading of disks.

**Comment by digitalLumberjack** [comment]
The core does not load disk specified on command line ?

**Comment by diablodiab** [comment]
It mounts the disk you specify on the command line, but you have to manually load and run the right executable on the disk. The executable can have any name on the disk.

**Comment by diablodiab** [comment]
I've submitted various fixes to the cap32 core:
- fixed sound problems
- improved screen resolution
- added autorun function (read readme.txt)

If the changes are approved then the core will be suitable for Recalbox.

**Comment by digitalLumberjack** [comment]
Nice @diablodiab 
I see you modified many things on your repository, i'm checking the changes right now.

**Comment by allanl1234** [comment]
The modifications have been merged to the master repository, so you can check them out there. Twinaphex also did some cleaning up after my changes, so the newest version is there.

**Comment by digitalLumberjack** [comment]
Nice i'll take care of that :)

**Comment by MaxCorpEnjoy** [comment]
+1

**Comment by rockaddicted** [comment]
libretro core added
We'll continue in this issue https://github.com/recalbox/recalbox-os/issues/232
