### ISSUE TITLE
Stick X Arcade Duo natif 

### ISSUE THREAD

**Issue by kasteelpiraat** [recalbox/recalbox-os#510]
Bonjour,

Je suis utilisateur d'un Xarcade Duo et apres y avoir passé deux grosses soirée (nuit) enfermé dans ma grotte, impossible de faire tourner la bête... 
Obligé malheuresement de partir sur RetroPie :/
Vous êtes vous déjà pencher sur le sujet ? 

Cordialement,

![stick-mini_1024x1024_e4986f42-6931-4316-8b66-7dda59ec4bbf](https://cloud.githubusercontent.com/assets/16114598/11526269/993bc93a-98d9-11e5-88ed-36d9e8b13a30.png)

**Comment by digitalLumberjack** [comment]
Hello,
ce genre de stick doit émuler un clavier, il te faudrait donc créer une configuration retroarch customisée et utiliser recalbox.conf pour définir ce fichier comme fichier de configuration par défaut pour chaque émulateur.
En gros https://github.com/recalbox/recalbox-os/wiki/Comment-personnaliser-mapping-manette-%28FR%29

**Comment by kasteelpiraat** [comment]
Merci pour la réponse, Je retente l'experience ce soir, j'avais effectué des modifications sur le fichier de conf retroarch mais pas sur recalbox.conf, ce qui explique peut être que ça ne fonctionnais pas :)

**Comment by kryptto** [comment]
Can this be translated to English?  Also where can I purchase this arcade joystick?

Kryptto

**Comment by kasteelpiraat** [comment]
kryptto : http://shop.xgaming.com/

**Comment by MikaXII** [comment]
@kryptto 
1st message say "didn't work on recalbox"
2nd say : 
This kind of stick must emulate a keyboard. You should create a custom retroarch config, and use recalbox.conf for define this config by default configuration file for each emulator

**Comment by nadenislamarre** [comment]
You can force it to be recognized as a joystick.
Run evtest to get the name of your device.

Add a rule like this one, this was done for wiimotes :

[root@RECALBOX ~]# cat /etc/udev/rules.d/99-wiimote.rules
SUBSYSTEM=="input", ATTRS{name}=="Nintendo Wii Remote", MODE="0666",
ENV{ID_INPUT_JOYSTICK}="1"
SUBSYSTEM=="input", ATTRS{name}=="Nintendo Wii Remote Classic Controller",
MODE="0666", ENV{ID_INPUT_JOYSTICK}="1"
[root@RECALBOX ~]#

2015-12-02 13:55 GMT+01:00 MikaXII <notifications@github.com>:

**Comment by digitalLumberjack** [comment]
@nadenislamarre we should add that in 4.0.0

**Comment by nadenislamarre** [comment]
can you join IRC and make test with susan33 please
Le 9 déc. 2015 15:20, "digitalLumberjack" <notifications@github.com> a
écrit :

**Comment by substring** [comment]
@kasteelpiraat xarcade sticks support has been added in 4.0.0. Do you still have the issue ?

**Comment by Thesundreamer** [comment]
Hello I tried today the xarcade profile. sadely my friend went into pluginig a ps3 controler.  Since it's impossible to get the xarcade settings .... option is set to 1 and I switched to 0 the os3 but even afeter rebbot xarcade is not recognized
