### ISSUE TITLE
Kodi problems

### ISSUE THREAD

**Issue by Olliko69** [recalbox/recalbox-os#513]
After updating to Beta 16 i recognize problems with Kodi. I use a selfmade Arcade Control via GPIO. The controls in Kodi are reverse. So up isn`t up but down. And it is not possible to eit Kodi back to emulationstation. Thanks for Help.

**Comment by nadenislamarre** [comment]
Hi,

can you reconfigure your joystick in emulationstation (es) menus please.

Nicolas

2015-12-03 19:03 GMT+01:00 Olliko69 <notifications@github.com>:

**Comment by Olliko69** [comment]
Hi Nicolas,

Thanks for the fast answer. I have reconfigured the controllers in the
setup menu. It is the same as before. I can push left but not to the right.
If i push up it goes down and i can not push down. The Buttons A and B are
working properly. So i can use Kodi. But now there is a network error. In
emulationstation the wifi is okay. Do you think a new installation will
solve the problems?
Sorry about the bad english. And for beeing a noob. I am such an old one
and not very good in these computer things. I also want to say, that i am
very happy about recalbox, so I can play all the games of my childhood.

Greetings,
Oliver
Am 04.12.2015 13:49 schrieb "Nicolas Adenis-Lamarre" <
notifications@github.com>:

**Comment by nadenislamarre** [comment]
hard to say if a new installation will solve.
I would say no.
I don't understand what can happen wrong.

Can you :

1)
evtest
then the number of your joystick
and then give me the output

2) can you give me the output of
udevadm info -q all -n /dev/input/eventX

by replacing X by the correct value

?

3) send me the file /root/.kodi/userdata/keymaps/* ?

If you need help to execute this, come on the irc please.


2015-12-04 18:45 GMT+01:00 Olliko69 <notifications@github.com>:

**Comment by Olliko69** [comment]
I will do so. Thanks for your support. But will last a little, because i am
not at home for a time.

2015-12-09 20:16 GMT+01:00 Nicolas Adenis-Lamarre <notifications@github.com>
:

**Comment by Olliko69** [comment]
Hi Nicolas,

I was in Hospital for a time. Yesterday i have installed Beta 4.0.0 and the
problems are gone.
Thanks for this great piece of Software.
One question please, how is the 'music' folder working in the shared
partition?

Grettings
Oliver
Am 10.12.2015 10:25 schrieb "Oliver Koch" <kocholiver1@gmail.com>:

**Comment by digitalLumberjack** [comment]
Hi, good to read it works again :)
The music folder will be used with the new theme to customize the musics in the frontend :)
