### ISSUE TITLE
I can't save my /etc/fstab changes and I can't exit or reboot!!

### ISSUE THREAD

**Issue by SargeRooster** [recalbox/recalbox-os#514]
I go and change the share location for my auto-mount, I follow the steps from this tutorial:

https://github.com/recalbox/recalbox-os/wiki/Auto-mount-of-usb-in-place-of-share-partition-%28EN%29

I just can't save and exit and reboot!! Please Help?!?!

**Comment by SargeRooster** [comment]
I'm also using the newest beta 16!!

**Comment by julianxhokaxhiu** [comment]
Are you typing `:wq` on `vi`? Try to use `nano` instead, maybe it easier. Or if you can, connect to the system through SCP ( WinSCP on Windows ) and edit the file directly using an editor like Sublime Text :)

Here I can confirm that it works.

**Comment by SargeRooster** [comment]
What exactly do you mean?  Can you show me?

**Comment by SargeRooster** [comment]
https://github.com/julianxhokaxhiu

Hey, I tried your method and it seemed to work but now I'm getting a "NOGAMEERRORMESSAGE", How do I solve it?

**Comment by julianxhokaxhiu** [comment]
In folder `/etc/init.d` rename the `SXXemulationstation` to `S90emulationstation`, and inside the file, at line 12 add `mount -a`, the command should be one-line only ( make sure that after that command it follows the one with `settings_lang=` etc.)

**Comment by SargeRooster** [comment]
sorry for my noobish comment but how exactly do i do that with in root access? plus i can't access the root after it tells me the nogameerrormessage.

**Comment by SargeRooster** [comment]
https://github.com/julianxhokaxhiu

I need access to that folder and how do i rename that line and whats inside the file?

**Comment by julianxhokaxhiu** [comment]
Through WinSCP for example or through basic linux commands

**Comment by rockaddicted** [comment]
https://github.com/recalbox/recalbox-os/wiki/Network-access-with-WinSCP-%28EN%29

**Comment by expouic** [comment]
I have the same problem when edit file /etc/fstab. I try to using vi and nano but have the same error message! 

vi : '/etc/fstab' is read only
nano: [ Error writing /etc/fstab: Read-only file system ]

**Comment by ian57** [comment]
You need to switch the filesystem to RW : 

`mount -o remount,rw /`

After you'll be able to modify the file
