### ISSUE TITLE
Two PS3 joysticks simultaneously original and gasia

### ISSUE THREAD

**Issue by saulgodino** [recalbox/recalbox-os#515]
I have two controllers of PS3 original Sony, one runs only with official driver and the other runs only with gasia driver. I can't use both at same time. Is there any sugestion to fix it?

**Comment by kruxty** [comment]
i have a similar problem. i bougth two wireless PS3 pads, one is shanwan and another is gasia. id like to know if its posible to have both working at same time... i have both two and i thought it was equal.. but inside, the chipset is different. 

both are working nice separately, but i have to change "/recalbox/share/system/recalbox.conf"
 file with lines:
 for shanwan pad:
## Choose an driver beetween official, shanwan and gasia if you have dualshock clones (official,shanwan,gasia)
controllers.ps3.driver=shanwan

 for gasia pad:
controllers.ps3.driver=gasia

is there any solution to keep them working at same time?

thanks ;)

**Comment by rockaddicted** [comment]
@saulgodino lets try this version : https://github.com/supertypo/qtsixa
@kruxty nope sorry, for the moment it is impossible. The driver is specific to each controller version and only one can be loaded in the same time.

**Comment by saulgodino** [comment]
@rockaddicted How do I use the qtsixa driver in Recalbox?

**Comment by rockaddicted** [comment]
We are already using qtsixa as driver in recalbox. But not this modified fork that seem allow to plug official/gasia controllers in the same time.
So you will have to wait than we switch on this qtsixa version in recalbox to test it.

**Comment by saulgodino** [comment]
@rockaddicted The modified fork of the qtsixa will be launched in the next beta of Recalbox?

**Comment by saulgodino** [comment]
@rockaddicted The modified fork of the qtsixa will be launched in the next beta of Recalbox?

**Comment by julianxhokaxhiu** [comment]
I guess the answer will be yes, no need to post it two times :)

**Comment by saulgodino** [comment]
Excuse me. posted duplicate unintentionally

**Comment by digitalLumberjack** [comment]
anyone with or a shanwan  and skills to install the last nightly build ? http://archive2.recalbox.com/4.0.0/

**Comment by bigboo3000** [comment]
J'ai essayé la dernière nigthly 4.0 mais ce n'est pas encore parfait (j'ai 2 gasia):

Les mieux : 
L'association fonctionne avec le driver "officiel" dans recalbox.conf
Les manettes ne restent plus parfois bloquées en restant tout le temps allumé meme apres l'extinction de la recalbox

Les moins:
après configuration dans recalbox, à l'arrière des 2 manettes la led 1 est allumée (donc toujours impossible d'identifier qui est la 1 et la 2)
et cette led clignote très rapidement (au lieu de rester allumée fixe)

en fouinant sur le net j'ai trouvé ca (je crois que c'etait sur le forum retropie) un autre fork qui pourrait etre interessant d'essayer?
https://github.com/paradxum/qtsixa/

**Comment by atangmac** [comment]
Hi,

I have tested recalbox-4.0.0-nightly-build-49 and both gasia and shanwan work in the main menu. So it seems it is good! :-)
I wanted to test both controllers in a game, but I can't find one which is multiplayer. When I want to copy a multiplayer game to /recalbox/share/roms/snes for example and restart the system, then the copied game is deleted.

Thanks!

**Comment by bigboo3000** [comment]
où ce fork qui à l'air plus récent et prend en compte les fix d'autres forks:
https://github.com/gizmo98/sixad/

**Comment by digitalLumberjack** [comment]
maybe if the https://github.com/gizmo98/sixad/commit/f7eb1307d2e71ed9939ccdd739b7edd8e7a64100 hack works, we could have a 3 in one ?

**Comment by fluffymadness** [comment]
Try this one from my post. 
http://blog.recalbox.com/forums/topic/dualshock-3-gasia-clone-info/
I have Original Dualshock 3, Gasia, and this one(http://www.dx.com/p/dualshock-wireless-bluetooth-v3-0-controller-for-sony-ps3-playstation-3-black-red-158616)
working simultaneously on the pi.
Force feedback is broken with this driver. And the controller from dx gets into a force-feedback-vibration-loop after disconnecting it.

**Comment by fluffymadness** [comment]
Oh. There are new commits on the git.
Maybe the led bug and rumble is also fixed now :)
https://github.com/ryonlabaw/qtsixa/commit/753e3253155a9f6edcf2a5381076c36d60a2e1fa

**Comment by fluffymadness** [comment]
This one lets me use original, gasia ds3 and shanwan
http://blog.recalbox.com/forums/topic/dualshock-3-gasia-clone-info/
There are some vibration issues and bugs with the player led. Can someone test this one to confirm?

**Comment by digitalLumberjack** [comment]
@fluffymadness we will check that. The choices today are : Official + GASIA, or Shanwan

**Comment by digitalLumberjack** [comment]
check the #615 for unified drivers. Closing this one as the job has been done for original + gasia
