### ISSUE TITLE
Moonlight is not present in emulationstation

### ISSUE THREAD

**Issue by Tuxliri** [recalbox/recalbox-os#516]
I have configured moonlight and it works fine but to use it I have to quit emulationstation, open a terminal, browse to /recalbox/scripts/moonlight and execute ./Moonlight.sh, how do I add it to the list of emulators?

**Comment by Tuxliri** [comment]
solved by manually creating the /recalbox/share/roms/moonlight directory, the gave the ./Moonlight.sh init command and the games scraped succesfully!

**Comment by substring** [comment]
You're not the first one to say that /recalbox/share/roms/moonlight is deleted. Gotta check that
But I'm glad you made it all by yourself :)

**Comment by rockaddicted** [comment]
folder `/recalbox/share/roms/moonlight` added in beta 17

**Comment by rockaddicted** [comment]
Can I close this issue ?

**Comment by substring** [comment]
seems it's solved in beta17, couldn't resintall from scratch to test yet. But the directory tree is fine since commit https://github.com/recalbox/recalbox-buildroot/commit/5a43133ea20bf5027acfa28e88bb36fdc9833ac8
