### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by matthuisman** [recalbox/recalbox-os#518]
GUI shows "Update available"
Click update
Nearly straight away, "Update Failed, rebooting"

/root/updates.log shows
error : unable to update share

Running the rsync-update.sh manually gives me below errors

rsync: failed to connect to recalbox.com (94.23.55.163): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

**Comment by digitalLumberjack** [comment]
Update server rebooted.

**Comment by sturze** [comment]
anybody else update issue from 3.3.2? 
#260 
need help! dont want to start all over again...  :(
