### ISSUE TITLE
Use modified QTSIXA

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#520]
https://github.com/supertypo/qtsixa can run both gasia and official controllers

**Comment by saulgodino** [comment]
Great news! I have an official controller and a gasia controller. Anxiously awaiting the next beta version of Recalbox.

**Comment by digitalLumberjack** [comment]
i made some progress on that. The 4.0.0 nightly build is now modified with this driver.

**Comment by digitalLumberjack** [comment]
The modified qtsixa is integrated. I close this one, we will continue on #615
