### ISSUE TITLE
make 2 differents recalbox.conf files rpi1/rpi2

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-os#522]
Default cores on rpi1/rpi2

| system | rpi1 | rpi2 |
| :--------------: | :--------------: |:--------------: |
| snes | libretro-pocketsnes | libretro-snes9x_next |
| gba | libretro-gpsp | libretro-mgba |
| mame | libretro-imame4all | libretro-mame2003 |
| nes| libretro-fceumm | libretro-fceu-next |

+ snes : Play-from-3-to-4-players-to-SNES-(EN)

**Comment by digitalLumberjack** [comment]
good job ! https://github.com/recalbox/recalbox-buildroot/pull/70
