### ISSUE TITLE
Apple][ emulation

### ISSUE THREAD

**Issue by czyz** [recalbox/recalbox-os#523]
It'd be awfully cool to be able to drop my apple ][ disk images into a folder in /roms and then launch linapple or GSPort from a menu. 

http://ivanx.com/raspberrypi/raspberrypi_emulators.html

**Comment by LaurentMarchelli** [comment]
@rockaddicted 
Hi managed the linapple-pie compilation on buildroot, the application works on recalbox (sound, movement), however I do not have any video output.
The application use the SDL layer, I tried it on Raspbian, and it worked with the video. 
I guess I have something missing on recalboxOS.
Do u known where I can find any information ?
Thanks

**Comment by substring** [comment]
@LaurentMarchelli What SDL version are you using ? the rax SDL1 library has frame buffer problems. Dunno if you can select a video output ... Also, had the kind same of problem with dos box that was fixed by removing stretch to fullscreen options, force a specific video output. But someone on the forum found a good fbcon patch for SDL1

**Comment by LaurentMarchelli** [comment]
Yep, I'm using SDL 1.2.15, I will try to force the video output and run it from the command line to check.
I will also see, if the patch can make my day.
Thank's :-)

**Comment by substring** [comment]
Check http://blog.recalbox.com/forums/topic/dosbox-scummvm-et-sdl-fbcon/ (dunno if you speak french, but check Laurent's second post)

**Comment by LaurentMarchelli** [comment]
Great ! No problem, with french, it's my mother tongue. :-)
As I understood, there is still no PR on recalbox-buildroot to fix SDL 1.2.15 problem, right ?
If still not, what about creating it and create the buildroot patch ?

**Comment by substring** [comment]
That was until ... https://github.com/recalbox/recalbox-buildroot/pull/228 He made his PR yesterday ;)
Once you think you're done, don't hesitate to join us on IRC or ask us how we are used to expect PRs, configs, and help you with default settings or where are systems files you may need to modify blablabla ... ;)

**Comment by LaurentMarchelli** [comment]
Great, I gonna check today. For now I already modified es_systems.cfg, and added apple2 to the limelight theme. I still have to write apple2 recalbox-configgen code.
Hopefully, it will be ready by end of this week or at worst end of next week.

**Comment by substring** [comment]
reminder : commit to recalbox-buildroot for system stuff, recalbox-configgen for configgen stuff ;)

**Comment by LaurentMarchelli** [comment]
No problem, I'll do. 
It works with SDL 1.2.15 patch got from https://github.com/recalbox/recalbox-buildroot/pull/228
You rock !

**Comment by substring** [comment]
@lmerckx you made someone happy withyour fbcon patch ;)

**Comment by lmerckx** [comment]
Great ! Happy it serves somebody else than me ... ;-)

**Comment by nadenislamarre** [comment]
it works to me. What is the remaining job ?

**Comment by LaurentMarchelli** [comment]
I Denis,

Yes it works, I still have some code on joysticks extension, but it is not an issue for the release.
I would like to support some keyboard features with joystick combo, but I do not have the time work on it now.

So, it is good enougth for release, I will bring improvement later.
Laurent

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0
