### ISSUE TITLE
"JY MR-P019 MICREAL Arcade Controller" Driver Request

### ISSUE THREAD

**Issue by zolderr** [recalbox/recalbox-os#524]
Hi, I bought this arcade controller, but I'm unable to make it work in recalbox (works fine in other systems). After a lot of searching I think maybe it's a driver problem. Maybe can you include it in a future update?
If you need more information, let me know. I would be glad to help.

http://es.aliexpress.com/item/free-shipping-1-kit-for-Xin-Mo-Arcade-to-USB-controller-2-player-MAME-Multicade-Keyboard/1465891803.html

Regards

**Comment by digitalLumberjack** [comment]
It's a xinmo clone. Did you tried on 3.3.0 beta ?

**Comment by zolderr** [comment]
yes, in beta 17 not work

**Comment by nadenislamarre** [comment]
Hi,

can you open a terminal on your rpi,
and type :

1)
evtest
then the number of your joystick
and then give me the output

2) can you give me the output of
udevadm info -q all -n /dev/input/eventX

by replacing X by the correct value

?


If you need help to execute this, come on the irc please.

Nicolas

2015-12-09 19:32 GMT+01:00 zolderr <notifications@github.com>:

**Comment by zolderr** [comment]
1. evtest
[root@RECALBOX ~]# evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      Arcade Controller JUYAO Dual Arcade
/dev/input/event1:      Logitech K400
Select the device event number [0-1]: 0
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x314 product 0x326 version 0x110
Input device name: "Arcade Controller JUYAO Dual Arcade"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 304 (BTN_SOUTH)
    Event code 305 (BTN_EAST)
    Event code 306 (BTN_C)
    Event code 307 (BTN_NORTH)
    Event code 308 (BTN_WEST)
    Event code 309 (BTN_Z)
    Event code 310 (BTN_TL)
    Event code 311 (BTN_TR)
    Event code 312 (BTN_TL2)
    Event code 313 (BTN_TR2)
    Event code 314 (BTN_SELECT)
    Event code 315 (BTN_START)
    Event code 316 (BTN_MODE)
    Event code 317 (BTN_THUMBL)
    Event code 318 (BTN_THUMBR)
    Event code 319 (?)
    Event code 320 (BTN_TOOL_PEN)
    Event code 321 (BTN_TOOL_RUBBER)
    Event code 322 (BTN_TOOL_BRUSH)
    Event code 323 (BTN_TOOL_PENCIL)
    Event code 324 (BTN_TOOL_AIRBRUSH)
    Event code 325 (BTN_TOOL_FINGER)
    Event code 326 (BTN_TOOL_MOUSE)
    Event code 327 (BTN_TOOL_LENS)
    Event code 328 (BTN_TOOL_QUINTTAP)
    Event code 329 (?)
    Event code 330 (BTN_TOUCH)
    Event code 331 (BTN_STYLUS)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 1 (ABS_Y)
      Value    127
      Min        0
      Max      255
      Flat      15
    Event code 2 (ABS_Z)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 3 (ABS_RX)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 4 (ABS_RY)
      Value    127
      Min        0
      Max      255
      Flat      15
    Event code 5 (ABS_RZ)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 6 (ABS_THROTTLE)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 7 (ABS_RUDDER)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 16 (ABS_HAT0X)
      Value      0
      Min       -1
      Max        1
    Event code 17 (ABS_HAT0Y)
      Value      0
      Min       -1
      Max        1
    Event code 18 (ABS_HAT1X)
      Value      0
      Min       -1
      Max        1
    Event code 19 (ABS_HAT1Y)
      Value      0
      Min       -1
      Max        1
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
Event: time 1449698449.517356, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90008
Event: time 1449698449.517356, type 1 (EV_KEY), code 311 (BTN_TR), value 1
Event: time 1449698449.517356, -------------- EV_SYN ------------
Event: time 1449698449.581360, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90008
Event: time 1449698449.581360, type 1 (EV_KEY), code 311 (BTN_TR), value 0
Event: time 1449698449.581360, -------------- EV_SYN ------------
Event: time 1449698468.719916, type 3 (EV_ABS), code 17 (ABS_HAT0Y), value 1
Event: time 1449698468.719916, type 3 (EV_ABS), code 1 (ABS_Y), value 255
Event: time 1449698468.719916, -------------- EV_SYN ------------
Event: time 1449698468.975947, type 3 (EV_ABS), code 17 (ABS_HAT0Y), value 0
Event: time 1449698468.975947, type 3 (EV_ABS), code 1 (ABS_Y), value 127
Event: time 1449698468.975947, -------------- EV_SYN ------------
Event: time 1449698470.128097, type 3 (EV_ABS), code 17 (ABS_HAT0Y), value -1
Event: time 1449698470.128097, type 3 (EV_ABS), code 1 (ABS_Y), value 0
Event: time 1449698470.128097, -------------- EV_SYN ------------
Event: time 1449698470.352126, type 3 (EV_ABS), code 17 (ABS_HAT0Y), value 0
Event: time 1449698470.352126, type 3 (EV_ABS), code 1 (ABS_Y), value 127
Event: time 1449698470.352126, -------------- EV_SYN ------------
Event: time 1449698472.208375, type 3 (EV_ABS), code 16 (ABS_HAT0X), value 1
Event: time 1449698472.208375, type 3 (EV_ABS), code 0 (ABS_X), value 255
Event: time 1449698472.208375, -------------- EV_SYN ------------
Event: time 1449698472.448405, type 3 (EV_ABS), code 16 (ABS_HAT0X), value 0
Event: time 1449698472.448405, type 3 (EV_ABS), code 0 (ABS_X), value 128
Event: time 1449698472.448405, -------------- EV_SYN ------------
Event: time 1449698473.088493, type 3 (EV_ABS), code 16 (ABS_HAT0X), value -1
Event: time 1449698473.088493, type 3 (EV_ABS), code 0 (ABS_X), value 0
Event: time 1449698473.088493, -------------- EV_SYN ------------
Event: time 1449698473.328523, type 3 (EV_ABS), code 16 (ABS_HAT0X), value 0
Event: time 1449698473.328523, type 3 (EV_ABS), code 0 (ABS_X), value 128
Event: time 1449698473.328523, -------------- EV_SYN ------------
Event: time 1449698479.137297, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90002
Event: time 1449698479.137297, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
Event: time 1449698479.137297, -------------- EV_SYN ------------
Event: time 1449698479.233309, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90002
Event: time 1449698479.233309, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
Event: time 1449698479.233309, -------------- EV_SYN ------------
Event: time 1449698480.161438, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1449698480.161438, type 1 (EV_KEY), code 304 (BTN_SOUTH), value 1
Event: time 1449698480.161438, -------------- EV_SYN ------------
Event: time 1449698480.193439, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1449698480.193439, type 1 (EV_KEY), code 304 (BTN_SOUTH), value 0
Event: time 1449698480.193439, -------------- EV_SYN ------------
Event: time 1449698481.569622, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1449698481.569622, type 1 (EV_KEY), code 309 (BTN_Z), value 1
Event: time 1449698481.569622, -------------- EV_SYN ------------
Event: time 1449698481.681636, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1449698481.681636, type 1 (EV_KEY), code 309 (BTN_Z), value 0
Event: time 1449698481.681636, -------------- EV_SYN ------------
Event: time 1449698482.177706, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90008
Event: time 1449698482.177706, type 1 (EV_KEY), code 311 (BTN_TR), value 1
Event: time 1449698482.177706, -------------- EV_SYN ------------
Event: time 1449698482.289730, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90008
Event: time 1449698482.289730, type 1 (EV_KEY), code 311 (BTN_TR), value 0
Event: time 1449698482.289730, -------------- EV_SYN ------------
Event: time 1449698482.657768, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90003
Event: time 1449698482.657768, type 1 (EV_KEY), code 306 (BTN_C), value 1
Event: time 1449698482.657768, -------------- EV_SYN ------------
Event: time 1449698482.705770, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90003
Event: time 1449698482.705770, type 1 (EV_KEY), code 306 (BTN_C), value 0
Event: time 1449698482.705770, -------------- EV_SYN ------------
Event: time 1449698483.249844, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1449698483.249844, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
Event: time 1449698483.249844, -------------- EV_SYN ------------
Event: time 1449698483.313868, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1449698483.313868, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
Event: time 1449698483.313868, -------------- EV_SYN ------------
Event: time 1449698483.457871, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90007
Event: time 1449698483.457871, type 1 (EV_KEY), code 310 (BTN_TL), value 1
Event: time 1449698483.457871, -------------- EV_SYN ------------
Event: time 1449698483.553886, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90007
Event: time 1449698483.553886, type 1 (EV_KEY), code 310 (BTN_TL), value 0
Event: time 1449698483.553886, -------------- EV_SYN ------------
Event: time 1449698483.985946, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1449698483.985946, type 1 (EV_KEY), code 308 (BTN_WEST), value 1
Event: time 1449698483.985946, -------------- EV_SYN ------------
Event: time 1449698484.065957, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1449698484.065957, type 1 (EV_KEY), code 308 (BTN_WEST), value 0
Event: time 1449698484.065957, -------------- EV_SYN ------------
Event: time 1449698484.193970, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1449698484.193970, type 1 (EV_KEY), code 304 (BTN_SOUTH), value 1
Event: time 1449698484.193970, -------------- EV_SYN ------------
Event: time 1449698484.257980, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1449698484.257980, type 1 (EV_KEY), code 304 (BTN_SOUTH), value 0
Event: time 1449698484.257980, -------------- EV_SYN ------------
Event: time 1449698485.834194, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9000d
Event: time 1449698485.834194, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 1
Event: time 1449698485.834194, -------------- EV_SYN ------------
Event: time 1449698485.842199, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9000d
Event: time 1449698485.842199, type 1 (EV_KEY), code 316 (BTN_MODE), value 1
Event: time 1449698485.842199, -------------- EV_SYN ------------
Event: time 1449698486.170237, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9000d
Event: time 1449698486.170237, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0
Event: time 1449698486.170237, -------------- EV_SYN ------------
Event: time 1449698486.178256, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9000d
Event: time 1449698486.178256, type 1 (EV_KEY), code 316 (BTN_MODE), value 0
Event: time 1449698486.178256, -------------- EV_SYN ------------
Event: time 1449698489.738717, type 3 (EV_ABS), code 18 (ABS_HAT1X), value -1
Event: time 1449698489.738717, type 3 (EV_ABS), code 3 (ABS_RX), value 0
Event: time 1449698489.738717, -------------- EV_SYN ------------
Event: time 1449698489.962741, type 3 (EV_ABS), code 18 (ABS_HAT1X), value 0
Event: time 1449698489.962741, type 3 (EV_ABS), code 3 (ABS_RX), value 128
Event: time 1449698489.962741, -------------- EV_SYN ------------
Event: time 1449698490.618829, type 3 (EV_ABS), code 18 (ABS_HAT1X), value 1
Event: time 1449698490.618829, type 3 (EV_ABS), code 3 (ABS_RX), value 255
Event: time 1449698490.618829, -------------- EV_SYN ------------
Event: time 1449698490.778850, type 3 (EV_ABS), code 18 (ABS_HAT1X), value 0
Event: time 1449698490.778850, type 3 (EV_ABS), code 3 (ABS_RX), value 128
Event: time 1449698490.778850, -------------- EV_SYN ------------
Event: time 1449698491.738979, type 3 (EV_ABS), code 19 (ABS_HAT1Y), value -1
Event: time 1449698491.738979, type 3 (EV_ABS), code 4 (ABS_RY), value 0
Event: time 1449698491.738979, -------------- EV_SYN ------------
Event: time 1449698491.850991, type 3 (EV_ABS), code 19 (ABS_HAT1Y), value 0
Event: time 1449698491.850991, type 3 (EV_ABS), code 4 (ABS_RY), value 127
Event: time 1449698491.850991, -------------- EV_SYN ------------
Event: time 1449698492.411067, type 3 (EV_ABS), code 19 (ABS_HAT1Y), value 1
Event: time 1449698492.411067, type 3 (EV_ABS), code 4 (ABS_RY), value 255
Event: time 1449698492.411067, -------------- EV_SYN ------------
Event: time 1449698492.539082, type 3 (EV_ABS), code 19 (ABS_HAT1Y), value 0
Event: time 1449698492.539082, type 3 (EV_ABS), code 4 (ABS_RY), value 127
Event: time 1449698492.539082, -------------- EV_SYN ------------
Event: time 1449698494.955405, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9000e
Event: time 1449698494.955405, type 1 (EV_KEY), code 331 (BTN_STYLUS), value 1
Event: time 1449698494.955405, -------------- EV_SYN ------------
Event: time 1449698495.131428, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9000e
Event: time 1449698495.131428, type 1 (EV_KEY), code 331 (BTN_STYLUS), value 0
Event: time 1449698495.131428, -------------- EV_SYN ------------


2. [root@RECALBOX ~]# udevadm info -q all -n /dev/input/event0
P: /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:0314:0326.0001/input/input0/event0
N: input/event0
S: input/by-id/usb-Arcade_Controller_JUYAO_Dual_Arcade-event-mouse
S: input/by-path/platform-bcm2708_usb-usb-0:1.2:1.0-event-mouse
E: DEVLINKS=/dev/input/by-id/usb-Arcade_Controller_JUYAO_Dual_Arcade-event-mouse /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2:1.0-event-mouse
E: DEVNAME=/dev/input/event0
E: DEVPATH=/devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:0314:0326.0001/input/input0/event0
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_TABLET=1
E: ID_MODEL=JUYAO_Dual_Arcade
E: ID_MODEL_ENC=JUYAO\x20Dual\x20Arcade
E: ID_MODEL_ID=0326
E: ID_PATH=platform-bcm2708_usb-usb-0:1.2:1.0
E: ID_PATH_TAG=platform-bcm2708_usb-usb-0_1_2_1_0
E: ID_REVISION=0102
E: ID_SERIAL=Arcade_Controller_JUYAO_Dual_Arcade
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Arcade_Controller
E: ID_VENDOR_ENC=Arcade\x20Controller
E: ID_VENDOR_ID=0314
E: MAJOR=13
E: MINOR=64
E: SUBSYSTEM=input
E: USEC_INITIALIZED=3333695

**Comment by nadenislamarre** [comment]
Ok,

type the following command :
echo 'SUBSYSTEM=="input", ATTRS{name}=="Arcade Controller JUYAO Dual
Arcade", MODE="0666", ENV{ID_INPUT_JOYSTICK}="1"' > /etc/udev/rules.d/t1

reboot
reconfigure the joystick
and confirm it works.
If yes, we wil add the rule in the next release.

In case it doesn't work, you can remove the file by :
rm /etc/udev/rules.d/t1

2015-12-09 23:05 GMT+01:00 zolderr <notifications@github.com>:

**Comment by zolderr** [comment]
not work

**Comment by Laddyacris** [comment]
Hello

Sorry for my english 

May be with  usbhid.quirks :`usbhid.quirks=0xvendor:0xProduct:0x040`


edit `/boot/cmdline.txt` file

add this line at the end of line with space between last word and new word

`usbhid.quirks=0x314:0x326:0x040`

like this 

`dwc_otg.fiq_fix_enable=1 sdhci-bcm2708.sync_after_dma=0 dwc_otg.lpm_enable=0 console=tty3 loglevel=3 elevator=deadline vt.global_cursor_default=0 logo.nologo usbhid.quirks=0x314:0x326:0x040
`



save and reboot.
Try to configure into emulationstation.

**Comment by nadenislamarre** [comment]
can you resend the udevadm command output please ?

**Comment by zolderr** [comment]
[root@RECALBOX ~]# udevadm info -q all -n /dev/input/event0
P: /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:0314:0326.0001/in                                                                                                                                                             put/input0/event0
N: input/event0
S: input/by-id/usb-Arcade_Controller_JUYAO_Dual_Arcade-event-mouse
S: input/by-path/platform-bcm2708_usb-usb-0:1.2:1.0-event-mouse
E: DEVLINKS=/dev/input/by-id/usb-Arcade_Controller_JUYAO_Dual_Arcade-event-mouse                                                                                                                                                              /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2:1.0-event-mouse
E: DEVNAME=/dev/input/event0
E: DEVPATH=/devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:0314:0326                                                                                                                                                             .0001/input/input0/event0
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_TABLET=1
E: ID_MODEL=JUYAO_Dual_Arcade
E: ID_MODEL_ENC=JUYAO\x20Dual\x20Arcade
E: ID_MODEL_ID=0326
E: ID_PATH=platform-bcm2708_usb-usb-0:1.2:1.0
E: ID_PATH_TAG=platform-bcm2708_usb-usb-0_1_2_1_0
E: ID_REVISION=0102
E: ID_SERIAL=Arcade_Controller_JUYAO_Dual_Arcade
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Arcade_Controller
E: ID_VENDOR_ENC=Arcade\x20Controller
E: ID_VENDOR_ID=0314
E: MAJOR=13
E: MINOR=64
E: SUBSYSTEM=input
E: USEC_INITIALIZED=3333695

[root@RECALBOX ~]#

**Comment by nadenislamarre** [comment]
did you remove the rule ?
can you check the name in the rule fit the nazme from evtest ?

**Comment by zolderr** [comment]
the rules ---> rm /etc/udev/rules.d/t1 <--- it is removed
I do a evtest and the name in evtest is--->  Input device name: "Arcade Controller JUYAO Dual Arcade"

I try what it says Laddyacris?

**Comment by nadenislamarre** [comment]
Hi,

please retry but by creating the t1 file,
i guess that the rule is not applied.

I think, it's just a problem with the ID_INPUT_JOYSTICK flag.
At least, this flag is missing.

Nicolas

2015-12-10 15:26 GMT+01:00 zolderr <notifications@github.com>:

**Comment by zolderr** [comment]
I tried creating the t1 file again, but does'nt work.
I next just ry what Laddyacris said and it works !!! 

My cmdline.txt

dwc_otg.fiq_fix_enable=1 sdhci-bcm2708.sync_after_dma=0 dwc_otg.lpm_enable=0 console=tty3 loglevel=3 elevator=deadline vt.global_cursor_default=0 logo.nologo root=/dev/mmcblk0p6 rootwait usbhid.quirks=0x314:0x326:0x040

I really apreciate your help, pals

**Comment by Laddyacris** [comment]
Nicolas peut être que l on doit patcher comme le xin-mo : 
je crois que digitaLumberjack a dû faire la meme chose que ce lien : https://github.com/raspberrypi/linux/pull/828/files

**Comment by Dreamersoy** [comment]
Great. Thanks for the solution. I have the same board. ^_^

**Comment by substring** [comment]
@zolderr you need to reboot once you created the udev rule Nicolas recommended you.
Once the rule is applied, the udevadm should show a new line : IS_INPUT_JOYSTICK=1
Then recalbox should be able to consider your system as a normal input

So :
  - create the rule
  - reboot
  - launch te udevadm command given above and check that IS_INPUT_JOYSTICK = 1 is here
  - ES should be just fine then

**Comment by saulgodino** [comment]
Great. I have this card. It would be great if this modification was implemented in future versions of Recalbox

**Comment by Dreamersoy** [comment]
Could be nice to see it in future version :)

**Comment by Laddyacris** [comment]
@Substring
information of my juyao : idVendor=0314, idProduct=0328 

# udevadm info -q all -n /dev/input/event0
P: /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.5/1-1.5:1.0/0003:0314:0328.0001/input/input0/event0
N: input/event0
S: input/by-id/usb-D_R_M_JUYAO_Dual_Arcade-event-mouse
S: input/by-path/platform-3f980000.usb-usb-0:1.5:1.0-event-mouse
E: DEVLINKS=/dev/input/by-id/usb-D_R_M_JUYAO_Dual_Arcade-event-mouse /dev/input/by-path/platform-3f980000.usb-usb-0:1.5:1.0-event-mouse
E: DEVNAME=/dev/input/event0
E: DEVPATH=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.5/1-1.5:1.0/0003:0314:0328.0001/input/input0/event0
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_TABLET=1
E: ID_MODEL=JUYAO_Dual_Arcade
E: ID_MODEL_ENC=JUYAO\x20Dual\x20Arcade
E: ID_MODEL_ID=0328
E: ID_PATH=platform-3f980000.usb-usb-0:1.5:1.0
E: ID_PATH_TAG=platform-3f980000_usb-usb-0_1_5_1_0
E: ID_REVISION=0102
E: ID_SERIAL=D_R_M_JUYAO_Dual_Arcade
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=D_R_M
E: ID_VENDOR_ENC=D_R_M
E: ID_VENDOR_ID=0314
E: MAJOR=13
E: MINOR=64
E: SUBSYSTEM=input
E: USEC_INITIALIZED=8204497

**Comment by substring** [comment]
@Laddyacris got a first release of a patched kernel, need testers ^^ meet you on IRC, i left your email at home
