### ISSUE TITLE
[4.0.0-beta1] Samba mount remote client

### ISSUE THREAD

**Issue by julianxhokaxhiu** [recalbox/recalbox-os#526]
Actually I tried to mount a samba share from Recalbox, but to accomplish that I had to edit `/etc/fstab` manually and then change the order of `/etc/init.d/S32emulationstation` to `/etc/init.d/S90emulationstation` with a `mount -a` command inside to make sure that samba share was mounted before emulation station was starting.

I know that manually this works fine. Although, is it possible to have a configuration section that is kept though updates? It's quite boring to do this all the time I have to update RecalboxOS.

Thanks in advance.

**Comment by julianxhokaxhiu** [comment]
@digitalLumberjack any idea on this?

**Comment by digitalLumberjack** [comment]
I saw your request. If it's not in the 4.x.x backlog, it's that i don''t really think that spending time on that is the priority right now. 
I'm not saying it's not a good idea, it's just that we have other things to do first.

**Comment by julianxhokaxhiu** [comment]
ok, thank you anyway :)

**Comment by julianxhokaxhiu** [comment]
Anyway when you want to this, it's really important that happens BEFORE emulationstation starts. Otherwise it will not work as user could expect :)

**Comment by julianxhokaxhiu** [comment]
@digitalLumberjack I saw that with version 4.0 beta-1 you did a LOT of progress in this area. Do you know if it's possible now to mount an external Samba share now?

**Comment by nadenislamarre** [comment]
done in 4.1.
can be closed.
