### ISSUE TITLE
Keep es_systems.cfg changes after an update

### ISSUE THREAD

**Issue by julianxhokaxhiu** [recalbox/recalbox-os#527]
Hi,

if you try to change the file `/root/.emulationstation/es_systems.cfg`, after an update, this will be resetted. Is it possible to keep the changes in `/root` or provide a way to do so?

Thanks in advance.

**Comment by digitalLumberjack** [comment]
If i don't update this file, how will you get new systems :P ?

**Comment by julianxhokaxhiu** [comment]
Good question, do you know if it's possible to provide some kind of configuation that can be parsed and outputted as es_systems.cfg at boot? That would be superawesome!

**Comment by nadenislamarre** [comment]
it would need a es_systems.custom.cfg + a merge tool with a priority on the
custom one... if somebody is intereted to do that, it can be just about 50
lines in python.

2015-12-09 20:21 GMT+01:00 Julian Xhokaxhiu <notifications@github.com>:

**Comment by julianxhokaxhiu** [comment]
I think this could be a good starting point :) http://stackoverflow.com/a/14879370

**Comment by digitalLumberjack** [comment]
This kind of feature could be ok for the recalbox.conf as it is modificated between revision of recalbox. But we cannot create merging system for file that are not meant to be modificated. Or we should merge smb.conf for those who modify it, fstab, the startup scripts etc. 

Let's not get in that kind of work.

**Comment by julianxhokaxhiu** [comment]
I had an idea about this issue. Which could be even easier than providing a whole script that merges.

It would be nice to have just a special folder mapped where we can place scripts and the system executes them just after an update ( like an hook ). That would be super awesome. So anyone could be free to script his own needs without impacting the whole system :)

What do you think?

**Comment by nadenislamarre** [comment]
in v4.0,
there are 2 places for es_systems.cfg,
system, and user.
if you never create the user file, system is updated automatically.
If you create the user file (from the system copy + update), you've to handle that.
I think this answer to this issue.

**Comment by julianxhokaxhiu** [comment]
Perfect! Thank you. More than enough :D
