### ISSUE TITLE
Bug traduction ES / FAVORIS

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-os#531]
Dans emultationstation, en langue française, il y a d'afficher par exemple : 

423 jeux disponibles, 4 favorites
au lieu de 
423 jeux disponible , 4 favoris

**Comment by ultrasuperpingu** [comment]
Pourquoi pas de s à disponible. Il y a encore une règle bizarre dont le français a le secret. Pour jeux vidéo (effectivement sans s), je comprend le principe, mais là, je donne ma langue aux chats...

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-emulationstation/commit/c953cd6344b4ea0a1098e505784e67e127484b6d
