### ISSUE TITLE
New systems to add to simplelight and zoid themes

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-os#532]
- [Viodeopack/Odyssey 2](https://github.com/libretro/libretro-o2em) : o2em-libretro
- [EightyOne ZX81](https://github.com/libretro/81-libretro) : 81-libretro
- [ZX Spectrum](https://github.com/libretro/fuse-libretro) : fuse-libretro

**Comment by nadenislamarre** [comment]
hum, and what about making zoid and fade effect by default ? (or it's just
i who find it's really nicer ?)

Ok, no link with the subject-> []

2015-12-11 18:49 GMT+01:00 rockaddicted <notifications@github.com>:

**Comment by substring** [comment]
zoid takes more RAM as its backgrounds are in 720p when Simplelight are 480p ...

**Comment by kryptto** [comment]
I agree there is a problem with Zoid and too many systems being selected.  I like Zoid a lot but hate the issue it creates...
