### ISSUE TITLE
Zoid theme freezes with Game & Watch v3.3.0-beta17

### ISSUE THREAD

**Issue by kryptto** [recalbox/recalbox-os#533]
Had Zoid as my default theme.  Loaded Game & Watch ROMs for the first time, upon a reboot the PSX game controller after a few seconds would freeze up.  Tried with two different PSX controllers, then switched to SimpleLight and all issues were fixed.  No more freezing up.  RPI2 over clocked.

Kryptto

**Comment by rockaddicted** [comment]
Hello, how many different systems are activated in your recalbox ?
I think it is more a vram problem that a specific problem with gw theme.
Zoid theme is known to crash rpi if many system are activated in the same time. ES load each background in bitmap in the rpi's vram. Zoid is using 720p backgrounds and SimpleLight 480p backgrounds. So you can activate more systems with SimpleLight theme than with Zoid theme.

**Comment by kryptto** [comment]
I have 90% or more of the systems activated, ;( I like variety...   That must be it, thanks Rockaddicted!

Might need to be added to the Wiiki as a potential hazard in case I missed it.
