### ISSUE TITLE
How do i start playing with Moonlight?

### ISSUE THREAD

**Issue by SargeRooster** [recalbox/recalbox-os#538]
I have done everything that is required! My PC is already paired with the Recalbox and for some reason, I don't know how to access it!! Nothing Happens, It just throws me into EmulationStation like normal but with NO MOONLIGHT!! What am I doing wrong? Please Help!!

**Comment by SargeRooster** [comment]
Is their anybody who can help me with this issue? I really need help!!

**Comment by Laddyacris** [comment]
Hello
are you read this tutorial : https://github.com/recalbox/recalbox-os/wiki/Setup-moonlight-%28EN%29

**Comment by substring** [comment]
which version of recalbox are you runnning ? did you follow the correct guide ? according to your version ?
If no games show, it means you didn't un the init part of the script. Or maybe you have no streamable games ...

**Comment by kryptto** [comment]
Sarge, I say this with all respect to you.  In the future please ask, not yell or demand help.  It causes people to feel reluctant to help.  This project is a volunteer project and the people that answer the posts have jobs and a full schedule of real life things to attend too.  I am sorry that I can't offer a suggestion to help you, in the future please include as much detail when you do have a bug or issue to report. I have found this community of programmers to be some of the kindest and most responsive people.  

Recalbox is the single best emulator I have ever used.  I have used 4 prior to using and staying with Recalbox.  Please don't make the folks here feel like they don't want to assist people and let the project die.  So please use a polite and patient tone during your posts for troubleshooting.  Thanks in advance!

Kryptto

**Comment by SargeRooster** [comment]
Hi Kryptto, I like to apologize if I hurt anyone's feelings, I tend to write things in all caps sometimes to focus on the issue. I did not mean in any way, shape, or form to be rude and I understand that where Netiquette stands, my words may have looked loud but they are there to just to point out what needs to be fixed. I would also like to say a big Thank You to you and the people who are a part of this community. Although I am not super savy with my coding skills, you guys are super helpful. I am someone who talks very enthusiastically and sometimes it comes across as loud or disrespectful so in turn, All I ask is that you respect the way I write and in no way is this against the people of this community. You guys are awesome in your own, individual way, and i'll respect you all for your way of expressing yourselves. 

On that note, I love Recalbox, I enjoy using it every time I turn on the tv and it works flawlessly. The issue I am running into is that my PC is already connected to the recalbox with moonlight but the problem is that when I restart the recalbox, no information about moonlight pops up. It doesn't show up as an emulator or as an option. So, what is it that I am doing wrong? Is there a code that needs to be placed before emulationstation starts or after? I have already followed every single step from this tutorial;

https://github.com/recalbox/recalbox-os/wiki/Setup-moonlight-%28EN%29

Now, it has already given me the code to enter on my pc and it has established the connection. Now, what am i missing? I have all my streamable games on my pc and in GeForce Experience as shortcuts to the games. Please help me, I would really appreciate it. Thank You.

P.S. I have used Moonlight on my phone and it detected all my games perfectly fine.

**Comment by substring** [comment]
moonlight on rpi can't detect yet computers, but it detects games just fine if you run the init command of the script. Please check 2.a.7 on the wiki https://github.com/recalbox/recalbox-os/wiki/Setup-moonlight-%28EN%29 : u have to start the moonlight.sh with the init parameter. It will get games, then scrape them. Have you done that step ?

**Comment by SargeRooster** [comment]
I Did but how would it detect the games?

**Comment by Laddyacris** [comment]
disabled firewall , and/or antivirus may be

**Comment by SargeRooster** [comment]
It also says this after putting in the init command;

Fetching games from 192.168.1.*** ...
Scraping games ...
cat: can't open 'gamelist.txt': No such file or directory

FYI: The stars aren't there, the ip address is there, i put them there for protection.

What do I do from here? Do i create file named gamelist.txt?

**Comment by substring** [comment]
can you come on irc ? 
check http://blog.recalbox.com/forums/topic/irc-channel/ to know how to get there

**Comment by SargeRooster** [comment]
so how do I make my games streamable?
and how do i access irc?

**Comment by substring** [comment]
i just gave you a link above on how to go on irc. As you'll have to pass quite some commands, it's easier to do it real time on irc

**Comment by SargeRooster** [comment]
Here is the pastebin Substring

http://pastebin.com/RzJ31D8s

**Comment by Laddyacris** [comment]
Je remet la liste ici car pastebin ne va pas conservé le fichier longtemps

  
1. Need for Speed(TM) The Run
2. Fallout 4 Launcher
3. DyingLight
4. Borderlands_ The Pre-Sequel launcher!
5. Activation Required Fix
6. Borderlands: The Pre-Sequel
7. Grand Theft Auto V
8. Far Cry 4
9. Fallout 4
10. League of Legends
11. Saints Row IV (DX 11)
12. Dying Light

**Comment by kryptto** [comment]
Happy holidays Sarge ;) thanks for your sentiment, and understanding.

**Comment by SargeRooster** [comment]
Thanks Kryptto, and a Happy Holidays to all

**Comment by substring** [comment]
Should be solved with https://github.com/substring/recalbox-buildroot/commit/2237766804e17e3eb8500bd5be9b232c762250a5
Meanwhile, if you want to solve the bug by yourself, join on me irc, i'll tell you how

**Comment by SargeRooster** [comment]
How would I go about doing this?

**Comment by substring** [comment]
join irc dude

**Comment by Roet-Ivar** [comment]
I'd suggest cleaning your pairing and re-run the init.
in /recalbox/scripts/moonlight/:

./Moonlight.sh clean
./Moonlight.sh pair
./Moonlight.sh init

Any difference?

**Comment by substring** [comment]
the bug itself is solved with the commit mentionned earlier
