### ISSUE TITLE
Add system in game metadata

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#539]
That will allow to start a game from any list. We could create multi system gamelist, and a Favorite system.

**Comment by substring** [comment]
And better : choose which core or emulator to run w/ a game. Which would make arcade so much easier ...

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-emulationstation/commit/e5a39b2e3ee222d88827f6761a121330dd5884c3
https://github.com/recalbox/recalbox-emulationstation/commit/941f98c384250c296953e1f39010761b310a9df4
