### ISSUE TITLE
Kodi / xBox360 Controller issues

### ISSUE THREAD

**Issue by spiwrx** [recalbox/recalbox-os#541]
Sorry, I'm not the most tech Savvy but I did get recalbox working without issue, I configured my controllers all the systems seem to function spot checking a few games in each. However when I switch to Kodi with 2 controllers plugged it gets confused and won't let me navigate Kodi Menu. Forces the Main Menu to the left and won't let me move right. If I re-boot with one controller plugged in it works fine. 

Also, I haven't reproduced the issue often but at least a few times with some hot swapping of controllers I occasionally get the player ID leds on the controllers opposite of how they respond in ES and some of the Games. When it has happened it's made the most recently plugged controller #0 (player 1) and the previously plugged controller bumped to #1(player 2) with their respective LEDs being just opposite. 

I really like the controller functionality inside KODI so hopefully this can be resolved??? 

RBP2
32GB (20+ gb of Roms loaded)
Knock-off 360 (wired) USB controllers

**Comment by nadenislamarre** [comment]
Bug confirm by something else on xbox360 controllers too.
I've some ideas i'll test with the personn coming on irc.
1) 4 items are put in recalbox.xml in the .kodi/userdata/keymaps directory : try with 1
2) Try with kodi 15

**Comment by spiwrx** [comment]
More testing last night reveals it also happens with just one controller, when switching between ES and Kodi it is very unpredictable if/when the controller works. 

I did notice: 
1) when KODI doesn't work w/ controllers it loads to a empty Kodi screen, just the original menu. when it does work it loads with Add-On icons below the menu. Sometimes shutting down to ES and relaunching KODI works, others time I have to do a full system re-boot. 

2) also it may be something to do with KODI running updates, I quickly get a little update notification in the lower right screen but to quick for me to read. I'm going to try adjust the auto update feature in KODI. 

Lastly, I did use the Fusion.TVAddons.ag configuration in KODI I had been using in other machines. I don't think it alters the configuration for controllers as it does work occasionally, just loads it's add-ons and programs. 

I think this is a known issue but using "EXIT" in Kodi locks my system up. Shutdown & reboot returns to ES as expected.

**Comment by Dragda** [comment]
This bug is fixed by activating the xboxdrv in recalbox.conf.

I was having the same problem until i change that setting.

**Comment by spiwrx** [comment]
I noticed that when I logged into the config through the IP/Browser that the Xbox was set to "0", I'll try that tonight...

**Comment by xbox360pad** [comment]
Like Dragda said, enabling xboxdrv in recalbox.conf the bug is fixed. Controlling kodi with my xbox360 pad is a GREAT feature, i don't need mouse anymore!. Kudos to the devs. I was using xbmc/kodi since XBOX1 days, now i am trying to get the same buttons configuration on recalbox.

xboxdrv also fixed "start" button on mupenplus, with normal joystick settings i couldn't start Super Mario 64 because start button was not working.

**Comment by nadenislamarre** [comment]
çan you send me output of evtest with thé 2 modes please so that i can
undertand.

**Comment by nadenislamarre** [comment]
çan you send me output of evtest with thé 2 modes please so that i can
undertand.

**Comment by spiwrx** [comment]
Changing the config fixed my issues. Though I had to do it twice, for some reason it didn't save the first time, probably me or maybe I forgot to disable the default (PS3?) on the first try....

Now KODI works with both controllers plugged and no control issues I've discovered so far. 

This has been really solid since struggling with all the different configs in retropie. 

I noticed some of the Williams Games (Defender/Joust) in MAME (I'm on the default MAME emulator 2003? with rom set 0.37b5) require a game restart to finish through the self-test. I discovered the emulator sub menu by hitting the 2 triggers to get past that problem. In my other non-pi MAME installs, you simply had to exit the game and restart the game but this didn't work on the pi.

**Comment by xbox360pad** [comment]
XBOXDRV ENABLED: http://pastebin.com/wJCNQSGS

NORMAL MODE: http://pastebin.com/LzbjA7jm

**Comment by nadenislamarre** [comment]
Hum, we should be able to fix that without having to change the driver.
Can you send me the result of
udevadm info -q all -n /dev/input/event6 with and without the xboxdrv.
Change the 6 if this is no more your xbox controller.
And the file /root/.kodi/userdata/keymaps/recalbox.xml when in default mode
and kodi launched (and why not the same with the xboxdrv)

**Comment by nadenislamarre** [comment]
Hum and what happend when you run evtest and press the start button please ?

**Comment by xbox360pad** [comment]
XBOXDRV ENABLED
udevadm: http://pastebin.com/x0g2hSTU
evtest pressing start button: http://pastebin.com/MaDDv8S7
This is my own keymap configuration: http://pastebin.com/MEfSW3KE

NORMAL MODE
udevadm: http://pastebin.com/gasmMtVe
evtest pressing start button: http://pastebin.com/7huwTVma
This is my own keymap configuration: http://pastebin.com/zTysNXK6
