### ISSUE TITLE
[BUG] es_input.cfg : mauvais code/value renvoyé quand le dpad est de type hat

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-os#542]
Quand le pad pour up/down/left/right est de type HAT, il n'y a pas de différenciation entre l'axe X et l'axe Y. Les 2 axes ont le même code (celui de ABS_HAT0X dans mon cas). Exemple :
es_input.cfg pour un pad NVidia Shield : http://pastebin.com/CqNfyfBu -> up down left et right on le même code 16 alors que evtest indique :
    Event code 16 (ABS_HAT0X)
      Value      0
      Min       -1
      Max        1
    Event code 17 (ABS_HAT0Y)
      Value      0
      Min       -1
      Max        1
Idem pour la partie value : ca devrait être 1 ou -1, pas 1 2 4 ou 8

**Comment by nadenislamarre** [comment]
je l'avais vu, mais sur le coup, j'ai pas trouvé cela génant :
cela vient de sdl,
sdl gère cela comme un seul objet (alors qu'en réalité, il y en a bien 2).
et la valeur 1, 2, 4, 8 indique la direction.
Cela pose t-il un problème ?

En réalité cela pose un problème, ca doit faire planter sdl si quand ta
manette a un axe HAT0X et pas d'axe HAT0Y, mais j'ai jamais vu encore de
tel joystick.

**Comment by substring** [comment]
ca pose un pb : je ne peux pas récupérer le code de l'axe Y

**Comment by nadenislamarre** [comment]
ben si.
si c est un hat
pour y
prendre la valeur de x
et a partir de la tu déterminé x et y.
je peux aussi remarcher sdl
mais la je pars 8 jours sa s ordi. donc patch ou attend.

**Comment by substring** [comment]
quand je lis le code 16, je ne peux pas savoir si c'est l'axe X ou Y, ni déterminer si l'autre axe c'est 15 ou 17.

Mais profite de tes vacances, rien n'urge va ! on en parle après les fêtes

**Comment by substring** [comment]
Il faudrait juste corriger le code de l'axe si possible. 

Pour les directions (1 2 4 8), on ne peut pas y toucher sinon ca casse la config pour fba et libretro

**Comment by nadenislamarre** [comment]
Exemple actuellement :
<inputConfig type="joystick">
    <input name="down"  type="hat" id="0" value="4" />
    <input name="left"  type="hat" id="0" value="8" />
    <input name="right" type="hat" id="0" value="2" />
    <input name="up"    type="hat" id="0" value="1" />
</inputConfig>

Le truc, c'est que pour 1 hat sdl, y'a 2 axes event.
C'est un concept SDL : 2 axes de type HAT = 1 seul objet = 1 seul id.
Donc tu peux pas changer l'id du hat.
Soit rajouter encore une valeur,
mais sinon, simplement,

si value = 1 ou 4, axe y, axe = id+1
sinon, si value = 2 ou 8, axe x, axe = id

mais tu notes que ca ne te donne pas le nom de l'axe non plus.
Et c'est vrai pour les axes "normaux" également.
Si vraiment il faut, je peux rajouter l'id (valeur input.h = celle de
evteest) de l'axe dans un champ axe_value, et c'est valable pour AXIS et
HAT. Tu confirmes que ton problème, ce n'est pas que pour les chapeaux ?

Peux tu me faire un retour.
Déjà, si c'est assez clair ce que je dis,
et si y'a un besoin supplémentaire ou pas.

Nicolas

**Comment by substring** [comment]
Le nom de l'axe, je ne l'utilise pas. C'est véritablement son code.
Mais on a eu la même idée pour se faciliter la tâche. D'arpès input.h, il peut exister 4 hat différents. L'id de Y, c'est bien toujours l'id de X +1. 
Value -> il ne faut pas toucher cette valeur, elle est nécessaire à retroarch
Donc on ne va pas se compliquer encore plus la tâche, et on ne change rien. Et on fait clore le bug

**Comment by substring** [comment]
@rockaddicted @digitalLumberjack l'issue peut être fermée
