### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by dupps29** [recalbox/recalbox-os#543]
Bonjour,
j'ai placé les fichier sur une carte SD de 16 GB, Cependant, quand j'insere la SD dans le Rpie2, l'installation ne démarre pas automatiquement. Je ne comprend pas pourquoi, l'écran reste bleu, pas d'image s'affiche et je suis bien en HDMI, je sais que le problème viens pas de la

Merci d'avance

**Comment by Laddyacris** [comment]
Bonjour 
peux tu détailler ton matériel, ainsi que la version utilisée de recalbox et la façon dont tu as préparé ta microsd

**Comment by dupps29** [comment]
J'ai le meme matériel que ce qui est demandé, j'ai beta17, la plus récente.
En faite, ma carte SD avait retropie avant et je me suis retrouvé avec 56MB d'espace libre, ce qui était insuffisant, j'ai alors utilisé MBRfix et easeUS pour enlever la repartition de Retropie. Ensuite j'ai mis les fichier dézipper dans la carte SD et l'ai insérer dans ma raspberry qui est conecté à internet et tout, et la, rien ne se passe, la raspberry a une lumière rouge et jaune

**Comment by dupps29** [comment]
rouge et vert*

**Comment by Laddyacris** [comment]
Bonjour
détruis les partitions et format en fat 32 (bien vérifier) avec l utilitaire minitool partition wizard.
retélécharge l archive et décompresse là puis copie colle les fichiers sur la microsd. 
tu es connecté sur un écran vga avec un adaptateur ou directement sur ta tv `?

**Comment by dupps29** [comment]
J'ai utilisé SD formatter et sa a marché finalement, Merci de ton aide

**Comment by Laddyacris** [comment]
ok

**Comment by rockaddicted** [comment]
Merci de cloturer l'issue.
Prochaine fois que tu aura besoin d'un support de ce type, merci de passer sur le forum au lieu d'ouvrir une issue sur github.
http://blog.recalbox.com/forums/
