### ISSUE TITLE
Add 5/4 ratio 

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-os#544]
Salut
serait il possible d'ajouter le 5/4 pour cette option dans recalbox.conf ou dans ES en plus de ceux présent ?

## Set ratio for all emulators (auto,4/3,16/9,16/10,custom)
global.ratio=auto

ref au sujet suivant : http://blog.recalbox.com/forums/topic/convertisseur-hdmi-vers-vgason/#post-17120
http://blog.recalbox.com/forums/topic/convertisseur-hdmi-vers-vgason/page/2/#post-17208

**Comment by Laddyacris** [comment]
Il semblerait que la bug a été corrigé dans beta 17
mettre ratio sur custom
 puis dans le menu retroarch, active l'option save on exit, puis dans les options videos de retroarch, regle ton ratio en 5/4 
et ca devrait être sauvegardé lors du lancement du prochain jeu.

**Comment by digitalLumberjack** [comment]
oui normalement c'est ok avec le custom ratio. Quelqu'un valide et on close.

**Comment by rockaddicted** [comment]
C'est tout bon en passant via l'option `custom ratio`.
Je cloture.
