### ISSUE TITLE
Remote (Yates) not working correctly with embedded kodi

### ISSUE THREAD

**Issue by francis-io** [recalbox/recalbox-os#545]
Hello,

When using the Yates app I always use flawlessly with standalone kodi, it seems to not be working correctly with the embedded version in recalbox. I can send basic direction/select messages, but can't do anything like browse files or start/stop media directly.

I believe this might be a conflict with it connecting over port 80, which I can currently see as something recalbox related.

System:
recalboxOS v3.3.0-beta17
Raspberry Pi 2

**Comment by nadenislamarre** [comment]
can you try with recalbox 4.1
however, this is not a recalbox issue.
