### ISSUE TITLE
No Game Error Message (NOGAMEERRORMESSAGE) - For auto mounting usb for storage

### ISSUE THREAD

**Issue by AustinTheBui** [recalbox/recalbox-os#547]
So I followed the steps on Auto mount of usb in place of share partition and i almost had it done
but when I boot up recalbox it says (as the title indicates) NOGAMEERRORMESSAGE I read that SargeRooster Had the same Problem but when I put mount a- on 12th line and what not it still does not work. Help would be great thanks.

**Comment by AustinTheBui** [comment]
help wanted

**Comment by kikeonline** [comment]
same here:

[root@RECALBOX ~]# mount -a
mount: mounting /dev/sda1/ on /recalbox/share failed: Not a directory

[    5.462458] usbcore: registered new interface driver rtl8192cu
[    6.342745] scsi 0:0:0:0: Direct-Access     Kingston DataTraveler 2.0 PMAP PQ: 0 ANSI: 4
[    7.722247] sd 0:0:0:0: [sda] 122915328 512-byte logical blocks: (62.9 GB/58.6 GiB)
[    7.722477] sd 0:0:0:0: [sda] Write Protect is off
[    7.722492] sd 0:0:0:0: [sda] Mode Sense: 23 00 00 00
[    7.722690] sd 0:0:0:0: [sda] No Caching mode page found
[    7.722702] sd 0:0:0:0: [sda] Assuming drive cache: write through
[    7.744715]  sda: sda1
[    7.747684] sd 0:0:0:0: [sda] Attached SCSI removable disk
[   10.584526] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   10.584687] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   12.027694] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   12.028481] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x4DE1
[   15.537384] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   27.682628] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   27.774574] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   29.217225] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x4DE1

**Comment by nadenislamarre** [comment]
you have modified the /etc/fstab file incorrectly.
/dev/sda1/ is not a directory. Remove the ending /.

2016-01-03 2:57 GMT+01:00 kikeonline <notifications@github.com>:
