### ISSUE TITLE
youtube live streams doesn't work

### ISSUE THREAD

**Issue by xbox360pad** [recalbox/recalbox-os#550]
This only happens with kodi in recalbox. I install youtube plugin, i can watch youtube videos but when i "start" a live broadcasting nothing happens. With openelec or osmc worked perfect, but not in recalbox.

Is this a known bug?

Thanks in advance.

**Comment by nadenislamarre** [comment]
works for me. can you confirm it's still the case in 4.0 beta1 while kodi was upgraded.

**Comment by nadenislamarre** [comment]
no feedback.
Works for me.
I close.
