### ISSUE TITLE
wifi EW-7811 not work

### ISSUE THREAD

**Issue by arv187** [recalbox/recalbox-os#557]
I have wpa2 psk and configured ## Wifi SSID (string) wifi.ssid=myssid ## Wifi KEY (string) wifi.key=mypassword.

I did this with wifi in raspbian https://www.raspberrypi.org/forums/viewtopic.php?p=777692#p777692 and work.

I tried:

```
[root@RECALBOX ~]# wget https://dl.dropboxusercontent.com/u/80256631/install-wifi.tar.gz
–2015-12-26 13:33:43–  https://dl.dropboxusercontent.com/u/80256631/install-wifi.tar.gz
Resolving dl.dropboxusercontent.com… 108.160.173.133
Connecting to dl.dropboxusercontent.com|108.160.173.133|:443… connected.
HTTP request sent, awaiting response… 200 OK
Length: 3556 (3.5K) [application/octet-stream]
Saving to: ‘install-wifi.tar.gz’

install-wifi.tar.gz 100%[=====================>]   3.47K  –.-KB/s   in 0s

2015-12-26 13:33:44 (92.1 MB/s) – ‘install-wifi.tar.gz’ saved [3556/3556]

[root@RECALBOX ~]# gunzip install-wifi.tar.gz
[root@RECALBOX ~]# tar xvf install-wifi.tar install-wifi
install-wifi
[root@RECALBOX ~]# ./install-wifi -c

Your current kernel revision = 3.19.3-v7+
Your current kernel build    = #1

Checking for a wifi module to determine the driver to install.

Your wifi module is Bus 001 Device 004: ID 7392:a812

And it uses the 8812au driver.

Checking for a new 8812au wifi driver module for your current kernel.
A driver does not yet exist for this update.
[root@RECALBOX ~]# ./install-wifi 8812au

Your current kernel revision = 3.19.3-v7+
Your current kernel build    = #1

Checking for a new 8812au wifi driver module for your current kernel.
A driver does not yet exist for this update.
```

But wifi dongle not power on.

dmesg:

```
[    2.483009] usb 1-1.4: new high-speed USB device number 4 using dwc_otg
[    2.583786] usb 1-1.4: New USB device found, idVendor=7392, idProduct=a812
[    2.583812] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber                    =3
[    2.583824] usb 1-1.4: Product: Edimax AC600 USB
[    2.583834] usb 1-1.4: Manufacturer: Realtek
[    2.583845] usb 1-1.4: SerialNumber: 00e04c000001
```

**Comment by Lilinator1981** [comment]
Hi , same problem with my new edimax ew-7811Un. 
dmesg shows:
[    2.842866] usb 1-1.4: new high-speed USB device number 5 using dwc_otg
[    2.944331] usb 1-1.4: New USB device found, idVendor=7392, idProduct=7811
[    2.944356] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.944368] usb 1-1.4: Product: 802.11n WLAN Adapter
[    2.944379] usb 1-1.4: Manufacturer: Realtek
[    2.944390] usb 1-1.4: SerialNumber: 00e04c000001
.....
.....
[  3.755088] usbcore: registered new interface driver rtl8192cu
........
.......
[   11.648141] usb 1-1.4: USB disconnect, device number 5
[   11.650192] rtw_cmd_thread: DriverStopped(0) SurpriseRemoved(1) break at line 482


So the Edimax is disconnected and there is no wlan0: 

[root@RECALBOX rules.d]# ifconfig
eth0      Link encap:Ethernet  HWaddr B8:27:EB:04:B2:24
          inet addr:192.168.2.4  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::ba27:ebff:fe04:b224/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1127 errors:0 dropped:0 overruns:0 frame:0
          TX packets:841 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:807798 (788.8 KiB)  TX bytes:119047 (116.2 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


lsusb:

[root@RECALBOX rules.d]# lsusb
Bus 001 Device 006: ID 046d:c218
Bus 001 Device 004: ID 046d:c31c
Bus 001 Device 003: ID 0424:ec00
Bus 001 Device 002: ID 0424:9514
Bus 001 Device 001: ID 1d6b:0002


Is this a driver problem?

**Comment by arv187** [comment]
Your device is compatible, then may be a driver issue but i dont know about this, I have trouble with 7811 UTC, not driver available to recalbox OLD kernel, and i not know compile a driver to kernel.

Check this to try something: http://www.savagehomeautomation.com/projects/raspberry-pi-installing-the-edimax-ew-7811un-usb-wifi-adapte.html

**Comment by Lilinator1981** [comment]
hm..hopefully it will run with new recalbox-version :-( I`m a Linux newbee, too. Don`t now much about installing drivers/Firmware etc :-(

**Comment by nadenislamarre** [comment]
@Lilinator1981 i close. i let you retest with a 4.1 recalbox version where drivers are up to date.
