### ISSUE TITLE
Add Support for the Raspberry Pi Official Touchscreen

### ISSUE THREAD

**Issue by fisch2** [recalbox/recalbox-os#561]
Add Module for it

**Comment by nadenislamarre** [comment]
would you be ready to pay one to me so that i make it work ?

**Comment by digitalLumberjack** [comment]
Haha.

**Comment by nadenislamarre** [comment]
i understand that you just want we enable a module in the kernel.
Do you have the name of the module ?

**Comment by julianxhokaxhiu** [comment]
I think that [this topic](https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=97271) may be useful to you

**Comment by nadenislamarre** [comment]
to me ?
i've still received nothing ;-)

While you've a such screen, do you have any possibility to work on that
issue so that we integrate it ?
If you buy a such screen, i guess you've that kind of capacities, haven't
you ?

2015-12-29 16:02 GMT+01:00 Julian Xhokaxhiu <notifications@github.com>:

**Comment by julianxhokaxhiu** [comment]
It was a link embed via markdown :) It's the first time I see someone using email replies. Why don't you consider a native app from your smartphone? Or using the web app of Github natively? :)

Btw the link is this one: https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=97271

**Comment by nadenislamarre** [comment]
Is it the same as https://github.com/recalbox/recalbox-os/issues/574 ?
can you try with 4.0.0 ?

**Comment by substring** [comment]
A user confirmed the official touchscreen works straight out of the box in 4.0.0

**Comment by mchtt** [comment]
@digitalLumberjack posted a video on youtube showing the screen under 4.0.0

**Comment by digitalLumberjack** [comment]
Yes it always worked. 3.3.0 is running on the version you see on the video. Seems like it's not working for everyone on 3.3.0 but it's alright with 4.0.0. I close this one.
