### ISSUE TITLE
Missing Libraries

### ISSUE THREAD

**Issue by Omnija** [recalbox/recalbox-os#562]
libpng12.so
 libSDL_image-1.2.so
 libSDL_sound0-1.0.so

Are some required libs to launch some emulators (c64 - vice , Dosbox and SMW) not sure if it's all of them, but it's a start.

**Comment by nadenislamarre** [comment]
in other words,
c64 - vice , Dosbox and SMW are missing and you would like to see them ?
or are you working on integrating them ?



2015-12-29 15:59 GMT+01:00 Omnija <notifications@github.com>:

**Comment by Omnija** [comment]
I would be working on integrating them but unable to test out due to the libraries missing. I also don't have a pc with linux or have enough space on my pc to launch a virtualbox to compile Recalbox with.

**Comment by nadenislamarre** [comment]
Hum, but if the libraries were present, you would have the same issue : no
space left on device to compile them ;-(
By the way, if somebody is interested to integrated them, personnally, i've
some dos game i keep  on a folder at home ;-)

2015-12-29 16:07 GMT+01:00 Omnija <notifications@github.com>:

**Comment by Omnija** [comment]
I have space issue on my windows pc not my rpi2

**Comment by julianxhokaxhiu** [comment]
@digitalLumberjack why are you closing this? Makes no sense...the libraries are still missing. Are they coming with 4.0.0?

**Comment by digitalLumberjack** [comment]
The libraries are not missing. You don't need any lib on recalbox, just softwares. If libpng12.so is requiered for Dosbox, then the issue is "Add dosbox to recalbox" and the work to do is to add dosbox, that requiere thoses libs.

**Comment by julianxhokaxhiu** [comment]
Understood.
