### ISSUE TITLE
Intellivision support.

### ISSUE THREAD

**Issue by kryptto** [recalbox/recalbox-os#564]
Good Day Team,

I was reading posts on https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=18874 about Intellivision emulation.  

Here is the link to the code:  http://spatula-city.org/~im14u2c/intv/

Is it possible to add to Recalbox?  If so I would like to see it added, I would like to play some old games from Mattel's game list.

Thanks for your consideration,

Kryptto

**Comment by mgoulartBR** [comment]
+1

I don't know if there is controller support!

**Comment by wraybowling** [comment]
In case anyone is wondering about mapping real intellivision controllers, the nice folks who made the intellivision have a 1st party serial-to-usb dongle and explain all the joystick bindings. http://www.intellivision.us/intvgames/interface/interface.php

But it's sort of uncertain how this would work out in recalbox with non-intellivision controllers or what would happen if you tried to use an intellivision controller for some other console's games. Things can get weird.

**Comment by substring** [comment]
dupe spotted ^^ #185 
closing this one ;)
