### ISSUE TITLE
Avoid auto start Recalbox

### ISSUE THREAD

**Issue by kruxty** [recalbox/recalbox-os#565]
I have my raspberry plugged to my TV via USB.
Id like to turn on my tv, and not to turn into Recalbox by default. I prefer get into TV out as standard, no Recalbox out.
I found the way to change it before, but i cant find it now again, can anyone helps me?

Thanks ;)

**Comment by nadenislamarre** [comment]
i would say it's in the config.txt (the raspberry bios)
No link with recalbox.

2015-12-31 10:45 GMT+01:00 kruxty <notifications@github.com>:

**Comment by kruxty** [comment]
a link where could i see the line to add?

**Comment by nadenislamarre** [comment]
http://lmgtfy.com/?q=stopping+RaspPi+from+auto+changing+source+on+tv
take the 1st link ;-)

2015-12-31 11:20 GMT+01:00 kruxty <notifications@github.com>:

**Comment by kruxty** [comment]
hahhaha thanks :$ :)
