### ISSUE TITLE
DAC+ for Recalbox and Kodi

### ISSUE THREAD

**Issue by thorty77** [recalbox/recalbox-os#568]
I use one PI2 in my car as mediacenter and gamingstation.
Because of the bad sound from the 3.5mm jack, i use a DAC+.
In normal Kodi I can install DAC. But in Recalbox not. On Retropie it is no problem to install.

So DAC and DAC+ for Recalbox would be perfekt !!

**Comment by substring** [comment]
It has always worked as the DTB are natively embedded. But you can refer to https://github.com/recalbox/recalbox-os/wiki/Audio-HiFiBerry-%28EN%29 if you are still struggling
