### ISSUE TITLE
D-link DWA 171 wifi dongle

### ISSUE THREAD

**Issue by ordidavid** [recalbox/recalbox-os#569]
Hello,

just to say that the wifi dongle D-link DWA 171 doesn't work in recalbox. it's seems that there's no driver implemented.

under debian, I can do it work with this precedure : 

http://www.coyotus.com/viewtopic.php?id=764

thanks in advance

**Comment by nadenislamarre** [comment]
the procedure is a 404 link.
firmwares have been update in 4.1
please rest and reopen if necessary.
however, we support only linux/buildroot hardware, however, if it works on debian, it should work.
