### ISSUE TITLE
Digital-only PSX games should automatically default to being launched with a "digital" controller config.

### ISSUE THREAD

**Issue by StateOfException** [recalbox/recalbox-os#570]
There are a large number of PSX games that are only playable with a pre-Dual Shock digital controller- launching the games in "analog" mode results in the games simply not accepting any controller input at all, necessitating a dive into settings to switch the controller type as required. The Dual Shock pads came with an "Analog" switch that made them appear as digital pads to deal with these problematic games, but this obviously isn't an option with most pads in use with RecalBox- so "Hotkey+B->Quick Settings->Core Settings->P1 input type=Digital" is the only way of getting around the problem when a non-analog compatible game is launched.

That's a really sub-optimal solution- there's no reason the games in question should ever launch with analog mode enabled, because they simply *don't work* in that mode, whereas most games with analog support work fine with digital controller configs- but still require switching mode to analog input to take advantage of the analog sticks. 

Given the fact that the set of digital-only games is well-known and unlikely to ever change, it seems like it would be worth hardcoding in a whitelist of game IDs that should launch in digital mode, with analog mode being the default. As things stand, it's a real barrier to usability.

An example of a problematic game's Castlevania: Symphony of the Night, if you want to test it.

**Comment by digitalLumberjack** [comment]
Hi, we already talked about that with the team, the issue was we could not find a way to identify the game with a UID in recalbox. It would be possible only in retroarch with the serial number of the game.

**Comment by StateOfException** [comment]
Ah! That makes sense. I'll submit it as an issue to RetroArch, then. Cheers.
