### ISSUE TITLE
Support Azerty keyboard

### ISSUE THREAD

**Issue by Guig92i** [recalbox/recalbox-os#571]
Hi, 
My French azerty keyboard is not properly working. 
Impossible to enter figures (especially a problem to configure wifi network)

**Comment by paradadf** [comment]
Have you read

https://github.com/recalbox/recalbox-os/wiki/Manual-(EN)#es-settings-network

?

**Comment by Guig92i** [comment]
yes !
it is just that my internet box is not by the tv, so I can't connect my RPI by ethernet easily to change the wifi settings

**Comment by paradadf** [comment]
You can edit the file recalbox.conf using a keyboard and direct access. To do so, connect your keyboard to recalbox and press F4, and then ALT+F2. To log in type "root" and "recalboxroot" as password. After that, write the following command:

nano /share/system/recalbox.conf

And edit the your Network Settings, special characters will work now. Exit it by pressing ctrl+x, y and enter to save. Finally type reboot. That should work.

**Comment by paradadf** [comment]
More about it on
https://github.com/recalbox/recalbox-os/issues/461

**Comment by paradadf** [comment]
Sorry, the right way is typing:

cd ../recalbox/share/system	(ENTER)
nano recalbox.conf			(ENTER)

to edit the configuration file.

**Comment by paradadf** [comment]
Was that it? Any feedback?

**Comment by Guig92i** [comment]
Yes thanks, I managed to connect the RPi with ethernet to change the config directly, easier for me ;)
