### ISSUE TITLE
Shanwan PS3 controller

### ISSUE THREAD

**Issue by nosfay** [recalbox/recalbox-os#572]
La manette (ps3 shanwan) ne fonctionne plus lorsqu'on la branche (pour la recharger notamment). Elle est à l'origine connectée en Bluetooth.

J'ai essayé avec une manette PS3 officielle et celle-ci reste bien connectée en Bluetooth lorsqu'on la branche.

J'ai la beta 3.3.0 v17

**Comment by francoiskha** [comment]
Bonjour,

As-tu testé [la procédure du wiki pour changer le driver](https://github.com/recalbox/recalbox-os/wiki/PS3-controllers-drivers-%28FR%29) ?

**Comment by substring** [comment]
demande de support ... bouhhhhhhh
