### ISSUE TITLE
fbtft build how to?

### ISSUE THREAD

**Issue by auras** [recalbox/recalbox-os#574]
Hello,

I've downloaded the sources to build my own recalbox os with fbtft support.

I've ran "make menuconfig" to enable fbtft support in the kernel.

I've ran make and it all compiled ok but without the support for fbtft in the resulting kernel.

I've looked in output/target/lib/modules/3.19.3-v7/kernel/drivers/video and there's no fbtft/fbdev folder

fbtft was downloaded and compiled by looking into output/build but it's not installed in the resulting image.

It's also in output/build/linux-..../drivers/video/fbdev

So... what was wrong with what I did? Was it actually compiled and I don't know where to look for it/how to activate it?

**Comment by nadenislamarre** [comment]
make menuconfig is for the buildroot packages configuration
make linux-menuconfig is for the linux configuration.

I guess you've enabled some tools, but not the drivers.
What you can do :

1) make linux-menuconfig to check that you can enable what you want
2) mv output/target output/target_ && make fbtft-rebuild && find
output/target to see what the fbtft package add on your recalbox


2016-01-04 16:38 GMT+01:00 Aurelian Dumanovschi <notifications@github.com>:

**Comment by auras** [comment]
I'm not sure that's how that works.
Isn't fbtft a kernel module and compiles with the kernel?
There's no fbtft mention in make linux-menuconfig but there is in make menuconfig as a kernel extension

**Comment by nadenislamarre** [comment]
As i can read on the fbtft github, fbtft was outside the kernel before
january 2015 and is now inside.
I've not a recalbox to check, but i guess that in your case, fbtft is still
outside.

make fbtft should compile and install inside the target directory.
please make :

mv output/target output/target_
make fbtf-rebuild
find output/target
i'm sure something like the driver is installed, but not where your think
;-)


2016-01-04 17:01 GMT+01:00 Aurelian Dumanovschi <notifications@github.com>:

**Comment by auras** [comment]
![virtualbox_debian_04_01_2016_17_29_11](https://cloud.githubusercontent.com/assets/332829/12094454/07f3836a-b309-11e5-9408-66d3b2d74b43.png)

**Comment by auras** [comment]
make fbtft-rebuild does nothing

**Comment by nadenislamarre** [comment]
effectively. At home too...
i guess the package is broken but worked at a given time.

It even doesn't compile nothing.
the file package/fbtft/fbtft.mk is probably wrong.


2016-01-04 17:32 GMT+01:00 Aurelian Dumanovschi <notifications@github.com>:

**Comment by nadenislamarre** [comment]
take the branch 4.0.0 of recalbox in git,
it is based on a new kernel version i which fbtft in included directly.
Do you need we include it for next release ?


2016-01-04 18:19 GMT+01:00 Nicolas Adenis-Lamarre <
nicolas.adenis.lamarre@gmail.com>:

**Comment by nadenislamarre** [comment]
i just ask diffenrently :
do you confirm we should include it for next release ? (ie it is usefull
for several people out of the box)

2016-01-04 18:40 GMT+01:00 Nicolas Adenis-Lamarre <
nicolas.adenis.lamarre@gmail.com>:

**Comment by nadenislamarre** [comment]
Hum, finally,
it's already set in recalbox 4.0.0 ;-)
you can get the nightly build from here :
http://archive2.recalbox.com/4.0.0/

2016-01-04 18:55 GMT+01:00 Nicolas Adenis-Lamarre <
nicolas.adenis.lamarre@gmail.com>:

**Comment by auras** [comment]
Cool, thanks. I'll try it out tomorrow.
