### ISSUE TITLE
/recalbox/share : make it ext4 in noobs 4.0.0 

### ISSUE THREAD

**Issue by nadenislamarre** [recalbox/recalbox-os#577]
it's now possible to make it fat32 in 4.0.0 for internal.

**Comment by nadenislamarre** [comment]
to be added in noobs

**Comment by digitalLumberjack** [comment]
i'm on it.

**Comment by digitalLumberjack** [comment]
Changing the name of this issue

**Comment by substring** [comment]
Avoid FAT32 at all costs, it became pretty weak in 4.0.0 ! If the users want to use a FAT32 USB key, let it be. But please don't format the SD car in FAT32, it's pretty useless as Windows will never see the 3rd partition of the SD card

**Comment by digitalLumberjack** [comment]
Non the internal share partition will be in ext4 don't worry

**Comment by substring** [comment]
when i tried 4.0.0 with noobs, the partition layout is not like with .img, take care ! /dev/mmcblk0p3 either doesn't exists, either is not the "real space left" on the sd

**Comment by digitalLumberjack** [comment]
alright
