### ISSUE TITLE
Remove "Exit" from Kodi power menu

### ISSUE THREAD

**Issue by spiwrx** [recalbox/recalbox-os#579]
I'm not sure if others have the same issue but if I use "Exit" from the KODI power icon to shut down (return to ES) my system locks. If there is another solution I couldn't find it but I removed the exit button from my menu by doing the following: 

using WinSCP (from root):
1) search for "advancedsettings.xml" 
2) focus and open file
3) before the closing tag add </advancedsetiings> the line:
<showexitbutton>false</showexitbutton>

I found this on YouTube and it works fine for me. 

I'm loving this version of RecalBox, thanks to the entire team for a rather solid build so far...

I have a testing system in our "Mancave" and Play system in our living room.
RBP 2 / 64gb(Sandisk) / overclocked / wired 360's 
RBP 2 / 64gb(microcenter/generic) / overclocked / Wireless PS3

**Comment by nadenislamarre** [comment]
Hi,
i've not the issue.
Can you confirm it's in v3.3 beta17 ?
for v4, i've an item in my todo list to make this list better (make
shutdown work for example)

**Comment by kryptto** [comment]
No problem using exit here either.

**Comment by spiwrx** [comment]
Definitely 3.3 b17 I stopped even trying the "exit" because it locked up so many times. If there have been updates, I have not updated since initial beta 17. I started on 16 with my first recalbox build and days later went to 17. 

My "Shutdown" and "Reboot" work fine taking me from Kodi back to ES. I have never tried the timer. 

I have updated my KODI using the TVaddons fusion installer, but I don't think that effects the basic power functions. It otherwise works great. 

Regardless I don't think the power menu needs so many options. I'm happy just removing the "Exit", as its intended to take you back to the OS which I don't need/want. 

I think it would be best if we could have the option there to either actually power down or return to ES.

**Comment by Gog0** [comment]
Having kind of the same issue on my raspberry pi 3 with the 4.0.0 beta 2. Can't exit kodi (with "exit" or "power off") because it always end up in a black screen. The only thing working is to use "reboot" but it's redoing the full boot process instead of just going back to recalbox.

Except that, everything seems to work perfectly for me :)

**Comment by nadenislamarre** [comment]
Can you confirm that the black screen is not just that you tv is off ?
In beta2, i've added a killer in case kodi remains up and you should go
back after 5 secondes in any case.
But i'm trying on an other tv, and i can see that exit in kodi shutdown
your tv if you tv supports it (can be disabled in kodi options i think)
And the first time, i thought that it was a black screen.

**Comment by Gog0** [comment]
Oh that's a good question and that would make me feel stupid but could totally be that. I guess it would have something to do with the HDMI CEC which is supported by my TV. Going to check that tonight.

**Comment by nadenislamarre** [comment]
as soon as i can commit, i do this for the next version :
- disable rss by default
- enable airplay by default
- disable cec actions on tv (start tv when kodi start, stop tv when exiting kodi)

**Comment by Gog0** [comment]
Just commenting to confirm that I was stupid and that you were right. It was definitely turning my TV off and I just didn't noticed that... So using "exit" works correctly and "power off" seems to actually really turn the system off (this link : https://github.com/recalbox/recalbox-os/wiki/Kodi-on-recalbox-(EN) says that both should get us back to ES)

**Comment by nadenislamarre** [comment]
fixed for release 4.0 and rss/airplay in 4.1 (option changed by default in new kodi configuration, you've to disable in option if you've already a .kodi)
