### ISSUE TITLE
Scummv in readonly mode

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#580]
https://github.com/recalbox/scummvm/commit/6a9413b8f97deb8097c2cb947377e053bbe6a306

to test

**Comment by rockaddicted** [comment]
I'll test that the next week.

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-buildroot/commit/a0ee9a94874b4339aa022912bc99651f28ce17c8

**Comment by rockaddicted** [comment]
I'll test that the next week.

Le 8 janv. 2016 11:44, digitalLumberjack <notifications@github.com> a écrit :
https://github.com/recalbox/scummvm/commit/6a9413b8f97deb8097c2cb947377e053bbe6a306

to test

---
Reply to this email directly or view it on GitHub:
https://github.com/recalbox/recalbox-os/issues/580
