### ISSUE TITLE
No way to exit game without keyboard

### ISSUE THREAD

**Issue by Daveinator** [recalbox/recalbox-os#581]
I love RecalBox OS and think it's a fantastic project but just have one major issue with it, it would appear there is no way to exit a game without having a keyboard attached which seems to really ruin the whole game console feel to it. I'm using a wireless Xbox 360 controller and when you're in a game there is not a single button (or combination) that can take you back to the main menu to play a different game. I have spent many hours searching on google but there seems to be no solution. Please for the love of god add this feature as it is desperately needed and imo is the only thing missing.

Thanks

**Comment by kryptto** [comment]
Dave,

Using a PSX controller and a friend that uses an Xbox controller easily exit every game.  First make sure you are using and follow the instructions for using the xBox driver. Just open a browser and go to your recalbox IP, http://192.168.1.x or whatever your up scheming is.  In recalbox you can see your IP under system.  Your can configure the Xbox driver from the config web page.  The instructions are in the user manual. 

With the PSX controller hit the PS button and start at the same time to exit.  With the xbox controller press the Xbox button and start at the same time.

In the future, please be more respectful in your request for assistance.  Thanks

Kryptto

**Comment by digitalLumberjack** [comment]
Did you read the manual ? The hotkey + start do not work ? https://github.com/recalbox/recalbox-os/wiki/Manual-(EN)#duringgame-special

**Comment by Daveinator** [comment]
All the manual says is "The Hotkey", nowhere does it specify what the hotkey actually is....

**Comment by digitalLumberjack** [comment]
Yes it's because before you have to configure the joystick for yourself. Now that it's out of the box, you are the first that do not guess it's the Xbox button or the home button on ps3 :P

**Comment by Daveinator** [comment]
Thank you digitalLumberjack :) (thought I had already tried that combo but obviously not)

**Comment by mchtt** [comment]
I added Home/PS hotkey to the wiki for Eng and FR.

**Comment by rockaddicted** [comment]
:+1:

**Comment by digitalLumberjack** [comment]
cool @mchtt
