### ISSUE TITLE
Wifi access with '&' character

### ISSUE THREAD

**Issue by thiouwz2** [recalbox/recalbox-os#587]
Hello,

Wifi password which contains '&' character can't be used. It seems being replaced by a spécific string in file /etc/wpa_supplicant/wpa_supplicant.conf

For exemple for password "toto&titi", you will find in wpa_supplicant.conf the line
psk="totopsk="titi"

**Comment by rockaddicted** [comment]
Hello which recalbox version are you using ?

**Comment by thiouwz2** [comment]
Sorry, the main thing is missing:
v3.3.0-beta17

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-buildroot/commit/2c1f2db31bf034df657ffce8dc5b19a4bccb8b5c correct that issue

**Comment by digitalLumberjack** [comment]
@digitalLumberjack test that

**Comment by bigboo3000** [comment]
latest nightly
&_ added at the end of ssid and password in router and in recalbox.conf, doesn't work

**Comment by thiouwz2** [comment]
Hello,
It doesn't work for me.
I tried withous modification in recalbox-config.sh but I wrote my SSID like that:
ssid=titi\\&toto
It's a workaround but it works fine. You should empty your file /etc/wpa_supplicant/wpa_supplicant.conf beacause turn off wifi doesn't do it correctly.
By the way, I don't know where recalbox-config.sh is called but maybe is there a calling problem with the third parameter.
I search a better definitive way but for now I have nothing.

Many thanks for your help and I continue to search.

**Comment by digitalLumberjack** [comment]
@thiouwz2 you may not be on the last nightly 4.0.0 ?

**Comment by thiouwz2** [comment]
Sorry it was not my SSID but PSK

**Comment by thiouwz2** [comment]
I'm currently using v3.3.0-beta17, i didn't see this update on https://github.com/recalbox/recalbox-os/releases

**Comment by digitalLumberjack** [comment]
because it is not. It's early developpement stage. archive2.recalbox.com/4.0.0

**Comment by thiouwz2** [comment]
OK, i will install it and try with his one

**Comment by digitalLumberjack** [comment]
Tested on 4.0.0 nightly : ok for ssid with spaces + & + _ + "
