### ISSUE TITLE
Adapt recalbox-manager to 4.0.0

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#588]

**Comment by substring** [comment]
see https://github.com/recalbox/recalbox-manager/issues/51

**Comment by digitalLumberjack** [comment]
@substring does it work on last revision ?

**Comment by substring** [comment]
@digitalLumberjack 
Nope :
IOError at /logs/

[Errno 2] No such file or directory: '/root/recalbox.log'

`# cat /usr/recalbox-manager/project/settings_production.py | grep RECALBOX_LOGFILE_PATH
RECALBOX_LOGFILE_PATH = "/root/recalbox.log"
`
https://github.com/recalbox/recalbox-manager/blob/recalbox_4-x/project/settings_production.py#L11

**Comment by digitalLumberjack** [comment]
should be ok with the next build

**Comment by digitalLumberjack** [comment]
http://jenkins.recalbox.com/job/recalbox-4.0.0-rpi2/132/ should be ok. Anybody can test ?

**Comment by rockaddicted** [comment]
ok on the last build

**Comment by substring** [comment]
the pi0/pi1 build is not good yet. I guess it will be okay with the night build

**Comment by digitalLumberjack** [comment]
yes i only rebuilt the rpi2 this afternoon

**Comment by substring** [comment]
Ok on pi0 and pi2
