### ISSUE TITLE
NES - Mario Bros - Manette PS3 - saut élevé impossible

### ISSUE THREAD

**Issue by karlkart** [recalbox/recalbox-os#589]
Bonjour,

Je viens de m'installer recalbox et suis ravi. Je n'arrive cependant pas à faire de grands sauts dans le jeu NES Mario Bros.

Y a-t-il un paramétrage spécial à faire ?

Merci pour votre aide.

**Comment by Laddyacris** [comment]
Bonjour
merci d utiliser le forum pour ce type de question
http://blog.recalbox.com/forums/
