### ISSUE TITLE
kodi extensions : busybox unzip fails to extract some zip archive (v4.0.0)

### ISSUE THREAD

**Issue by nadenislamarre** [recalbox/recalbox-os#591]
wget http://mirrors.kodi.tv/addons/helix/script.extendedinfo/script.extendedinfo-3.1.2.zip
unzip script.extendedinfo-3.1.2.zip
Archive:  script.extendedinfo-3.1.2.zip
  inflating: script.extendedinfo/changelog.txt
unzip: inflate error

**Comment by digitalLumberjack** [comment]
Same on my unzips on 4.0.0...
Simple zip file with some files inside doesn't extract. @substring had the same issue since the first 4.0.0 build

**Comment by substring** [comment]
Yes sir, I confirm

**Comment by rockaddicted** [comment]
a patch has been added a month ago in buildroot : https://github.com/buildroot/buildroot/blob/master/package/busybox/0003-g-unzip-fix-recent-breakage.patch

**Comment by digitalLumberjack** [comment]
I'll merge buildroot master

**Comment by rockaddicted** [comment]
:+1:

**Comment by substring** [comment]
Might bring back AZERTY keyboard, Who knows !

**Comment by nadenislamarre** [comment]
what is the problem with keyboard ?

2016-01-13 11:21 GMT+01:00 Subs <notifications@github.com>:

**Comment by substring** [comment]
You can't change the keymap. You can't notice that when you connecter through ssh. But on a local tty, the keyboard is QWERTY no matter what you do

**Comment by nadenislamarre** [comment]
ok.
1444 files updated... i guess you just want to introduce enough bugs into
4.0.0 to make it out after 3.3.0 ;-)

2016-01-13 13:11 GMT+01:00 Subs <notifications@github.com>:

**Comment by digitalLumberjack** [comment]
Just merged buildroot master :P

**Comment by nadenislamarre** [comment]
By the way, no pr, no commit (excluding merges),
the community will consider you did nothing ;-)

What do you make when you merge ?
- git pull xxx
- git merge master
- resolve conflicts
- ... what do you do / what do you check at this point ?


2016-01-13 13:17 GMT+01:00 digitalLumberjack <notifications@github.com>:

**Comment by digitalLumberjack** [comment]
I did nothing for that. 
The community will consider i only did recalbox :P

**Comment by digitalLumberjack** [comment]
But yeah, just pulling, merging two conflits, and now compiling and checking if all is ok. Sqlite doesn't compile anymore in it's 3.10.0 version, i rollback to 3.9.2 while i'm looking for the real correction

**Comment by substring** [comment]
resolved in build #87

**Comment by digitalLumberjack** [comment]
Nice !
