### ISSUE TITLE
change RPI2 overcloking to stable values

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#592]
Hi
I'm not sure but I think by defaut RAM is overclocked to 480. This is not stable and can cause random errors.
According to this article it should be set to 450, and over_voltage set to 3 to have a perfectly stable RPI2.
http://retroresolution.com/raspberry-pi-2-stable-and-unstable-overclock-values/

Could you change the default OC values to that?
arm_freq=1050
core_freq=525
sdram_freq=450
over_voltage=3

**Comment by digitalLumberjack** [comment]
@rockaddicted what do you think about that ?

**Comment by DarthNeo2** [comment]
I have tested this 1050 setting for 2 weeks and is very stable even without a sink. The configs with 1000mhz and 950mhz its very good too. 

Its very better than the atual overclock option in beta 17 wich made my PI2 turns off ever.

**Comment by rockaddicted** [comment]
Hum I never had any problems with the included presets.
But if other people have problems, why not try these settings.
We won't lose really perfs.
These settings are not talking about the `gpu_freq=`. Actually we are using a value of `350mhz`

**Comment by digitalLumberjack** [comment]
For RPI2 : 
High -> stable with 450 sdram
Turbo -> current config
Extrem ->
force_turbo=1
arm_freq=1100
over_voltage=4
core_freq=550 (rapport 1:2 freq proc)
gpu_freq=366 (rapport 2:3 freq core)
sdram_freq=480
over_voltage_sdram_p=2
over_voltage_sdram_i=2
over_voltage_sdram_c=2

**Comment by rockaddicted** [comment]
Let's try this Extrem setting

**Comment by rockaddicted** [comment]
In recalbox 4.0.0, it seem to have a problem about the OC switch in ES.
After switched the OC settings, after reboot, the OC parameter in ES is on `none` and not  `rpi2`.

**Comment by benutzer193** [comment]
@rockaddicted @digitalLumberjack  seems fixed with latest commit. The values stay, also in the menu.
and until now running rock solid with extrem settings ;)

**Comment by digitalLumberjack** [comment]
Ok i close :)
