### ISSUE TITLE
Pas de son sur l'émulateur 64 via le jack lorsque configuré via ES

### ISSUE THREAD

**Issue by funnuraba21** [recalbox/recalbox-os#594]
Bonjour,

Lorsque la sortie audio est configurée via la sortie jack depuis ES, on n'obtient pas de son sur l'émulateur n64.

Une solution de contournement a été trouvée, voir le forum: http://blog.recalbox.com/forums/topic/pas-de-son-sous-n64/

Mais il serait plus pratique que ce soit géré au niveau du recalbox.conf (le configgen, c'est ça?) avec une variable du style n64.output_sound=jack ou hdmi qui pointe vers le OUTPUT_PORT en 0 ou 1 du mupen64plus.cfg

Merci à la team ;)

**Comment by rockaddicted** [comment]
Pas besoin d'ajouter une variable dans le `recalbox.conf`
Il faudra faire en sorte que le configgen check le `recalbox.conf`
```
## Set the audio device (auto, hdmi, jack)
audio.device=auto
```
et modifie le mupen64plus.cfg en fonction : 
```
# Audio output to go to (0) Analogue jack, (1) HDMI
OUTPUT_PORT = 0
```

**Comment by rockaddicted** [comment]
@substring attend avant de bosser sur ce point. 
```
# Audio output to go to (0) Analogue jack, (1) HDMI
OUTPUT_PORT = 0
```
Cette option est propre au plugin son omx. Si on switch sous le plugin sdl, ça ne sera plus utile.

@funnuraba21 pourrais tu tester de basculer le plugin son défini dans le `mupen64plus.cfg` de : 
```
# Filename of audio plugin
AudioPlugin = "mupen64plus-audio-omx.so"
```
en
```
# Filename of audio plugin
AudioPlugin = "mupen64plus-audio-sdl.so"
```

et nous dire si le switch de sortie se fait bien ?

**Comment by substring** [comment]
@rockaddicted haha je la sentais venir celle-là lol

**Comment by funnuraba21** [comment]
@rockaddicted Je teste ça ce soir et je te fais un retour en début de semaine prochaine. Pas de souci.

**Comment by rockaddicted** [comment]
@funnuraba21 des nouvelles à propos de ce point ?

**Comment by rockaddicted** [comment]
tested, sound ok in jack output + plugin audio-sdl.
