### ISSUE TITLE
Little typo in recalbox.conf

### ISSUE THREAD

**Issue by paradadf** [recalbox/recalbox-os#595]
## The recommanded plugin is gliden64, but if your game is not compatible, you can try n64 or rice plugins.

It should be: recomm**e**nded

**Comment by rockaddicted** [comment]
:+1:

**Comment by digitalLumberjack** [comment]
thanks for the report @paradadf

**Comment by paradadf** [comment]
Thank you all for the great work you are doing!!!

**Comment by digitalLumberjack** [comment]
corrected with https://github.com/recalbox/recalbox-buildroot/pull/133
