### ISSUE TITLE
Audio Volume - N64

### ISSUE THREAD

**Issue by gulaschsuppn** [recalbox/recalbox-os#596]
The Audio Volume Settings in Emulationstation did not work with the N64 Emulator.

(beta 17)

**Comment by mchtt** [comment]
Same here.

**Comment by rockaddicted** [comment]
Switching plugin audio in the file `/recalbox/configs/mupen64/mupen64plus.cfg`
from : 
```
# Filename of audio plugin
AudioPlugin = "mupen64plus-audio-omx.so"
```
to : 
```
# Filename of audio plugin
AudioPlugin = "mupen64plus-audio-sdl.so"
```
solve this problem.
