### ISSUE TITLE
Turning on a paired wireless 360 controller starts Kodi

### ISSUE THREAD

**Issue by mikezila** [recalbox/recalbox-os#599]
I have the official 360 wireless controller adapter, and when I turn on a paired controller Kodi starts.  If I use a keyboard to navigate and disable Kodi then turning on a controller brings me to the system menu for Kodi instead, which I can then back out of.  This happens even if the "start kodi with X" option is disabled.

**Comment by Dragda** [comment]
Go to recalbox.conf and turn on the "xboxdrvr" in the D2 secction. 
Use the official forum for this problems, please.
