### ISSUE TITLE
Redundant filetypes for Playstation (possibly others)

### ISSUE THREAD

**Issue by mikezila** [recalbox/recalbox-os#600]
The default es_systems.cfg that recalbox comes with pretty much guarantees you'll end up with duplicate games in your list for Playstation, likely for other disc-based games as well. By default it allows img, bin, cue, and their upcase variants (and others). The problem with this is that any game that uses a cue is also going to have at least one bin/img. Having just a bin or img with no corresponding cue is very rare and usually an accident/oversight. I have all my games ripped as bin/cue, some games having a bin for each audio track. For example Twisted Metal 2 has a bin for each track of its redbook audio, this leaves me with an entry for the cue sheet, an entry for the large bin that is the game itself, and an entry for each music track.  The desired behavior would be to see just one entry for each cue and it's child bin/img files.

This can be solved in a couple says.

You could either ignore bin/img files out of the gate, which would be simplest, but possibly anger some people who don't understand why their improperly ripped/packaged games aren't showing up.

You could have the game list ignore any bin/img files that are refereed by a cue sheet. This would leave people like me who use cue/bin for their games with a tidy game list while also letting people that (for some reason) have loose bin/img files do their thing.

What would be really swell is if you could add a section of the webui that let you edit the file extensions you wanted to show up for each system. I'm sure there's an argument against this that it adds complexity, but there's no reason it couldn't be hidden in the normal config file someplace, or be placed in the same section. Exposing a raw text file in a web interface is already sufficient complexity that having a way to edit this doesn't seem unreasonable.

**Comment by paradadf** [comment]
Correct me please if I´m wrong, but I think there will be an option in version 4.0.0 to hide "unwanted" entries from the gamelists, so you don´t have any duplicates.

**Comment by mikezila** [comment]
I don't really think that's a good solution to the problem.  It's not really reasonable to make someone go through a collection of potentially 100+ games and manually hide all of the redundant entries.

Perhaps if it automatically hid any file that was referenced by a cue sheet.

**Comment by bigboo3000** [comment]
I agree, "redump" and "trurip" cd dumps always have either .cue or .ccd cue sheet, so only thoose files should be displayed. .bin alone are not good verified dumps.

**Comment by mchtt** [comment]
you can delete .cue, the emulator only needs the .bin (i'm doin it)
same for .ccd & .sub, i only keep the .img

**Comment by bigboo3000** [comment]
If you delete .cue & .ccd  the emulator doesn't know where are the differents tracks in the .bin (that's the whole point of a cue sheet file), so it can't play music tracka anymore for example

**Comment by mchtt** [comment]
So i'm lucky, i'm playing Thrasher with only the .img, and tracks are playing... it depends of the game soundtrack implementation .
And just checked it, all my other games are in .bin format and are working flawlessly without .cue...
(THPS 1,2 and 4; FF Tactics, Dave Mirra BMX, FF9, Gran Turismo 2, Street Fighter Alpha 3........)
Do you have an example of a non working soundtrack ?

**Comment by bigboo3000** [comment]
All games with audio tracks separated from bin
for example Cool Boarders 2 (redump version)
1 main .bin file
20 audio tracks (with .bin extension but there are in reality .wav files)
without the cue sheet it's impossible for the emulator to play the right music tracks

**Comment by mchtt** [comment]
yes i remember playing psx discs in a normal cd-player back in the day, some games worked (those with wavs) same for saturn discs :-)

**Comment by Voljega** [comment]
just modify your es_systems.file and only keep .ccd .CCD .cue .iso and .ISO
There are then just a few duplicate remaining those are games where you have both .ccd and .cue, rename the .cue to CUE and voilà !

**Comment by paradadf** [comment]
@rockaddicted this can be closed.

**Comment by rockaddicted** [comment]
Thx
