### ISSUE TITLE
Ping et connexion par ssh impossible

### ISSUE THREAD

**Issue by Tloz** [recalbox/recalbox-os#603]
En essayant de me connecter au PI en utilisant la commande ```ssh root@192.168.0.51```, j’obtiens l'erreur ```ssh: connect to host 192.168.0.51 port 22: No route to host```

Un ```ping 192.168.0.51``` échoue aussi. Or, Kodi m'indique bien que l'adresse IP du RPi est la bonne, et je reçois du contenu depuis mon NAS sur Kodi.

Par contre, un ```nmap -sP 192.168.0.0/24``` m'indique que la machine à l'adresse 192.168.0.51 est en marche.

En me connectant à un terminal directement sur le RPi, je ne trouve ni OpenSSH, ni un service similaire dans /etc/init.d

Comment faire pour me connecter par ssh?

**Comment by digitalLumberjack** [comment]
Salut, ifconfig te donne quoi ?
Tu as aussi un menu network dans recalbox qui te montre l'ip.

**Comment by Tloz** [comment]
eth0      Link encap:Ethernet  HWaddr **:**:**:**:**:**
             inet addr: 192.168.0.51 Bcast: 192.168.0.255 Mask 25.255.255.0
Donc l'ip est la bonne.

**Comment by Tloz** [comment]
Je viens de faire un test, le ping et la connexion ssh fonctionnent, à mon grand étonnement.
Faut il pour cela avoir ouvert le terminal et s'être connecté? (ce qui expliquerait pourquoi ça ne marchait pas hier, j'essayais de me connecter alors que j'étais sur EmulationStation)

**Comment by mchtt** [comment]
non je me co sous emulstation.
