### ISSUE TITLE
No controllers found on first hard reboot rpi1 4.0.0 nightly

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#604]
I just tested recalbox 4.0.0 on rpi zero. It's ok but i have an issue (putting that here to not forget)

Run the pi for the first time -> all ok
Hard reboot -> the input.cfg is not found by ES as it shows the configuration screen.

I'll test again with soft reboot.

**Comment by nadenislamarre** [comment]
i guess that es does save files only when closed correctly,
this could be an issue.

2016-01-17 9:27 GMT+01:00 digitalLumberjack <notifications@github.com>:

**Comment by nadenislamarre** [comment]
should be fixed in the last nighly.
flush options added to vfat mounts. Without this flag, the driver doesn't flush the buffer so that the regular sync writes them to the disk.
See http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=ae78bf9c4f5fde3c67e2829505f195d7347ce3e4
for more information.

**Comment by digitalLumberjack** [comment]
Seems corrected :)

**Comment by nadenislamarre** [comment]
cool.
on ext4 and vfat ?

2016-01-25 9:56 GMT+01:00 digitalLumberjack <notifications@github.com>:

**Comment by nadenislamarre** [comment]
the day we'll add a "formatage usine" option, we'll add the possibility to
change the internal partition to fat32 too ;-)

2016-01-25 11:08 GMT+01:00 Nicolas Adenis-Lamarre <
nicolas.adenis.lamarre@gmail.com>:

**Comment by substring** [comment]
reinstalled a pi0 from scratch to check if https://github.com/recalbox/recalbox-buildroot/commit/fc27ab7c94a66e69b28f255755f92405648eec9f was ok. Had several reboots since, no problem for me (/recalbox/share is on ext4)
I think the issue can be closed

**Comment by digitalLumberjack** [comment]
so i can close this one :)
