### ISSUE TITLE
Changer le shell par défaut empêche la connexion par ssh

### ISSUE THREAD

**Issue by Tloz** [recalbox/recalbox-os#606]
En étant connecté par ssh sur ma recalbox, j'ai modifié à la main le fichier /etc/passwd. J'ai changé la dernière partie de la première ligne, ce qui correspond au shell de l'utilisateur root.
Le ```/bin/sh``` a été modifié en ```/bin/bash```
Il est maintenant impossible de se connecter en ssh sur la machine (le connexion normale fonctionne toujours)

```ssh``` retourne juste après l'entrée du mot de passe la mention ```Connection closed by 192.168.0.51```

**Comment by nadenislamarre** [comment]
not reproductible.
Closing.
