### ISSUE TITLE
Manage Saves from the Web Interface

### ISSUE THREAD

**Issue by mchtt** [recalbox/recalbox-os#607]
Maybe adding the feature of uploading/downloading save files from the web interface ?

**Comment by digitalLumberjack** [comment]
@sveetch what do you think about that ? Do we move this issue on the manager ?

**Comment by sveetch** [comment]
I allready started something about save states but the current way of managing them is painful to support.

**Comment by digitalLumberjack** [comment]
The last developpent on the 4.0.0 branch closed https://github.com/recalbox/recalbox-os/issues/385 maybe it's better for you. All saves are located in a directory nammed after the system name
