### ISSUE TITLE
Support de DosBox

### ISSUE THREAD

**Issue by Tloz** [recalbox/recalbox-os#608]
Le support de DosBox est il prévu dans la version 4.0? Ou dans une version ultérieure?

Certains jeux pouvaient se passer de la souris et être joué uniquement au clavier, il devient facile de remapper les touches sur manette

**Comment by rockaddicted** [comment]
déjà 2 issues sur le sujet
https://github.com/recalbox/recalbox-os/issues/4 et https://github.com/recalbox/recalbox-os/issues/233
Je ferme donc celle ci.
Pour répondre à ta question il me semble en effet que quelqu'un commence à regarder pour une intégration future de dosbox. So wait & see =)
