### ISSUE TITLE
NOGAMEERRORMESSAGE

### ISSUE THREAD

**Issue by GitOeli** [recalbox/recalbox-os#609]
I've tried to install recalbox without NOOBS, because it wasn't possible to get picture through the composite out. So I took a look into the partitions.jason and created this partition table on my SD card and copied the stuff out of the tar files on the partitions. When this was done, I`ve put the card into my Pi and startet it. I see this colourfull screen, and the recalbox screen, and after this, i just get the message "NOGAMEERRORMESSAGE". Could somebody help me?

Please excuse misstakes. English is not my native language.

**Comment by digitalLumberjack** [comment]
you must edit the /etc/fstab to see if it references the good partitions (share seems not to be mounted)

**Comment by substring** [comment]
@GitOeli have you sorted things out ? Can we close ?
