### ISSUE TITLE
WiFi and DNS with static IP

### ISSUE THREAD

**Issue by jason-a69** [recalbox/recalbox-os#610]
Hi there,

This is the contents of my /etc/network/interfaces file

auto wlan0
iface wlan0 inet static
address 192.168.1.15
network 192.168.1.0 
netmask 255.255.255.0
broadcast 192.168.1.255
gateway 192.168.1.1
dns-nameserver 192.168.1.1 8.8.8.8
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

The problem I have is that DNS is not working properly, when I look in my network settings in the GUI it says "Not Connected" even though I can SSH into the machine and browse the shared folders with Samba. I cannot ping a DNS name from the command line.

Version is recalboxOS v3.3.0-beta17

Thanks

Jason

**Comment by Lilinator1981** [comment]
solution found on : http://blog.recalbox.com/forums/topic/i-would-like-back-to-the-future/ 
by user nEiMi
temporarly i fix it with a workaround…
i modifiy the network startup script…
add following line to /etc/init.d/S40network at the begining of the script
echo "nameserver 8.8.8.8" >> /tmp/resolv.conf

now reboot

This is certainly not the best solution, but temporarly it works…

**Comment by jason-a69** [comment]
Thanks very much

**Comment by nadenislamarre** [comment]
this seems ok for you.
Version 4.1 will allow more network configuration.
I close.
