### ISSUE TITLE
Enable to enter WIFI Key

### ISSUE THREAD

**Issue by piousteph** [recalbox/recalbox-os#611]
Hi

I have dowloaded the last released version of Recalbox (3.2.11) and
I have some trouble to enter my wifi key.
This one contain the following charaters -> ?^:_-,*+=)|;(
and i'm enable to enter it using my keyboard, the sift keys does not work.

I have tried to update recalbox.conf but after reboot the wifi is not activate.
I have tried to edit wpa_supplicant.conf but no progress.

Please help me.

**Comment by digitalLumberjack** [comment]
Hi, already corrected in 4.0.0.

**Comment by piousteph** [comment]
Hi,
Where is can download this version ?
Thanks
