### ISSUE TITLE
Wifi dongle disconnect (Not Power&Notsuspend-Mode)

### ISSUE THREAD

**Issue by Lilinator1981** [recalbox/recalbox-os#612]
Hi , I hava a problem with my new edimax ew-7811Un. 
dmesg shows:
[ 2.842866] usb 1-1.4: new high-speed USB device number 5 using dwc_otg
[ 2.944331] usb 1-1.4: New USB device found, idVendor=7392, idProduct=7811
[ 2.944356] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2.944368] usb 1-1.4: Product: 802.11n WLAN Adapter
[ 2.944379] usb 1-1.4: Manufacturer: Realtek
[ 2.944390] usb 1-1.4: SerialNumber: 00e04c000001
.....
.....
[ 3.755088] usbcore: registered new interface driver rtl8192cu
........
.......
[ 11.648141] usb 1-1.4: USB disconnect, device number 5
[ 11.650192] rtw_cmd_thread: DriverStopped(0) SurpriseRemoved(1) break at line 482

So the Edimax is disconnected and there is no wlan0:

[root@RECALBOX rules.d]# ifconfig
eth0 Link encap:Ethernet HWaddr B8:27:EB:04:B2:24
inet addr:192.168.2.4 Bcast:0.0.0.0 Mask:255.255.255.0
inet6 addr: fe80::ba27:ebff:fe04:b224/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:1127 errors:0 dropped:0 overruns:0 frame:0
TX packets:841 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:807798 (788.8 KiB) TX bytes:119047 (116.2 KiB)

lo Link encap:Local Loopback
inet addr:127.0.0.1 Mask:255.0.0.0
inet6 addr: ::1/128 Scope:Host
UP LOOPBACK RUNNING MTU:65536 Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)

It seems to be a driver problem? Pleasy help!

**Comment by nadenislamarre** [comment]
@Lilinator1981 the issue is old. i let you retest with version 4.1 (usb key version for example) and reopen if the problem still occurs.
However, we support only hardware supported by linux/buildroot.
