### ISSUE TITLE
PS3 controller in KODI fails after "wake up"

### ISSUE THREAD

**Issue by spiwrx** [recalbox/recalbox-os#614]
I can't seem to get my PS3 (wireless) controller to work after it goes to sleep while using KODI. It seems to pair back up, but no longer is able to control KODI. CEC still works and if I go back to ES the PS3 works. Back into KODI it's fine again. 

Concurrently using a 64gb card with root folder that is full due to heavy scraping. Not implying its related, mentioning it in case.

**Comment by nadenislamarre** [comment]
Ok.
This is normal.
I've not coded the plug/unplug part in kodi because the config file is
generated by es.
However, in your case, this is the same joystick that is plugged, so, no
need to rebuild the config file.
So I can fix it.

**Comment by nadenislamarre** [comment]
Fixed by https://github.com/recalbox/recalbox-buildroot/pull/167
please wait it goes in merged status
and retest in the following nightly build
and make a feedback please.

**Comment by nadenislamarre** [comment]
no feedback ;-(
however it works for me.
