### ISSUE TITLE
Mupen64plus - Add key combination

### ISSUE THREAD

**Issue by nosfay** [recalbox/recalbox-os#616]
Last Mupen64plus core (v2.5) can use key combination like retroarch did.

https://github.com/mupen64plus/mupen64plus-core/commit/14bf40b236af1d5a5e7b86cd15a6cb628b4153fd

**Comment by rockaddicted** [comment]
done
mupen64plus updated : https://github.com/recalbox/recalbox-buildroot/commit/7ebb6ff84f534bb20e7a28e160a5ecdf96857fec
specials commands added to configgen : https://github.com/recalbox/recalbox-configgen/commit/75259be69480aa99c408bab2dcdfe7d77ff42d35

**Comment by paradadf** [comment]
Would it be possible to add HK+A in configgen to reset the game?

mupenSettings.save('Joy Mapping Reset', "\"J{}{}/{}\"".format(controllers['1'].index, createButtonCode(controllers['1'].inputs['hotkey']), createButtonCode(controllers['1'].inputs['a'])))
