### ISSUE TITLE
Update the logo with a new one 

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#617]

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-emulationstation/commit/134ef1634ef7bdac4e0d9dcaeee450a4f4a1c84f

**Comment by digitalLumberjack** [comment]
Change the logo on the website + wiki too :)

**Comment by mchtt** [comment]
May we see the new logo ?

**Comment by digitalLumberjack** [comment]
https://raw.githubusercontent.com/recalbox/recalbox-emulationstation/134ef1634ef7bdac4e0d9dcaeee450a4f4a1c84f/data/resources/splash.svg

**Comment by mchtt** [comment]
Merci :-)

**Comment by digitalLumberjack** [comment]
Derien ;:)

**Comment by digitalLumberjack** [comment]
website, github, facebook, twitter, reddit and ?

**Comment by digitalLumberjack** [comment]
github twitter -> ok

**Comment by digitalLumberjack** [comment]
website facebook reddit wiki

**Comment by digitalLumberjack** [comment]
facebook -> ok
