### ISSUE TITLE
[4.0.0] recalbox locks up if the /recalbox/share was damaged

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-os#618]
Savagely rebooted my pi
recalbox was stuck at the black logo screen with the build date in the lower left corner

dmesg said :
[    5.722410] FAT-fs (mmcblk0p3): utf8 is not a recommended IO charset for FAT filesystems, filesystem will be case sensitive!
[    5.736512] FAT-fs (mmcblk0p3): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[    6.082051] FAT-fs (mmcblk0p3): error, fat_get_cluster: invalid cluster chain (i_pos 262450)
[    6.082075] FAT-fs (mmcblk0p3): Filesystem has been set read-only
[    6.082111] FAT-fs (mmcblk0p3): error, fat_get_cluster: invalid cluster chain (i_pos 262450)

@nadenislamarre do you think such errors can be automatically fixed before mounting /recalbox/share ?

**Comment by nadenislamarre** [comment]
yes, if we can detect it, we can do an fsck ;
i do it for ntfs by trying to write a file

2016-01-21 22:55 GMT+01:00 Subs <notifications@github.com>:

**Comment by substring** [comment]
I guess i have an idea, look :
 ```
# fsck /dev/mmcblk0p1
fsck 1.42.13 (17-May-2015)
fsck.fat 3.0.28 (2015-05-16)
/dev/mmcblk0p1: 130 files, 27051/201616 clusters
# echo $?
0
# fsck /dev/mmcblk0p2
fsck 1.42.13 (17-May-2015)
e2fsck 1.42.13 (17-May-2015)
/dev/mmcblk0p2: clean, 37361/131072 files, 227502/524288 blocks
# echo $?
0
# fsck -n /dev/mmcblk0p3
fsck 1.42.13 (17-May-2015)
fsck.fat 3.0.28 (2015-05-16)
0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
 Automatically removing dirty bit.
Leaving filesystem unchanged.
/dev/mmcblk0p3: 1155 files, 929527/1046527 clusters
# echo $?
1
```
See the return code of the last fsck ? From fsck's manpage :
```
       The exit code returned by fsck is the sum of the following conditions:
            0    - No errors
            1    - Filesystem errors corrected
            2    - System should be rebooted
            4    - Filesystem errors left uncorrected
            8    - Operational error
            16   - Usage or syntax error
            32   - Fsck canceled by user request
            128  - Shared-library error
```
If the return code is not 0, it means we may have some file system to repair. Even 1 means there were some errors (as i didn't solve anything on that test)

**Comment by nadenislamarre** [comment]
ok.
So, i forget that fat32 has no journal, so that fsck is required when you
badly shutdown the rpi.
fsck can take time.
So, for a better robustiness ;-)
i suggest :
- switch internal partition from fat32 to ext4
- ntfs is not eligeable while it has some similar issue because the format
is not well not enough.
- continue to propose fat32/ntfs as external device, but not advice to
shutdown down directly
- add an fsck on fat32

- not support bluetooth in a first time on fat32 (while the char : is
required without patch)

Nicolas

2016-01-22 13:04 GMT+01:00 Subs <notifications@github.com>:

**Comment by benutzer193** [comment]
happens to me when starting n64 games, with the following error:

    RECALBOX user.err kernel: [ 2492.681830] FAT-fs (mmcblk0p3): error, fat_get_cluster: invalid cluster chain (i_pos 492071)

After that I have to remount /dev/mmcblk0p3 with rw. At the moment I am not able to start N64 games.

**Comment by nadenislamarre** [comment]
the fsck was added in 4.0
