### ISSUE TITLE
Rpi 2 + ecran 7 pouces tactile

### ISSUE THREAD

**Issue by narigua** [recalbox/recalbox-os#620]
Bonjour !

Tout d'abord bravo pour tout ce beau boulot, sérieusement, BRAVO !

Ensuite, j'ai un souci, mon écran 7 pouces tactile officiel ne s'allume pas lors du démarrage du système. Absolument pas. Aucun souci en HDMI, et bien sûr l'écran fonctionne bien sur raspbian.
Je suis sur la dernière Beta.
Une idée du souci ?

**Comment by digitalLumberjack** [comment]
Oui tu dois utiliser la 4.0.0 sur les milestones. Le kernel / userspace / firmware ont été mis a jour, le support est ok.

**Comment by narigua** [comment]
Thanx a lot ;)
