### ISSUE TITLE
N64 - No Control - Xin-Mo

### ISSUE THREAD

**Issue by gulaschsuppn** [recalbox/recalbox-os#621]
My bartop controller (xin-mo) did not work with the N64 Emu.
In all other emus the xin-mo adapter works.

**Comment by rockaddicted** [comment]
N64 is emulated by a standalone emulator, mupen64plus.
In recalbox 3.3.0, there is no configuration generator on this emulator. So if your controller is not More informations on this wiki : https://github.com/recalbox/recalbox-os/wiki/Configure-N64-controllers-%28EN%29

I close this issue, if you have others problems about this create a post on recalbox's forum : http://blog.recalbox.com/forums/

**Comment by mchtt** [comment]
Thx for the infos, i was going to ask the same question !
Any chance that you include a config for xbox360 and ps3 gamepads in the future builds, they should be the most commonly used game controllers so it will be more convenient and attractive to include their profiles, no ?

**Comment by substring** [comment]
Pray the Lord for 4.0.0, emulation station pads config will be automatically imported into mupen. So be a little patient :)

**Comment by mchtt** [comment]
Sounds perfect !
