### ISSUE TITLE
Moonlight clean command

### ISSUE THREAD

**Issue by ultrasuperpingu** [recalbox/recalbox-os#623]
Hi,
I used moonlight to stream game from my computer and I really love this feature. However, I tried to pair my recalbox to another computer and the process is really painfull. I had to reinstall recalbox to switch streaming computer. I'm sure there is a way to do it without reinstall  but I wasn't able to find it. The Moonlight.sh script would be better with a "clean" command line, removing all previous pairing informations.

**Comment by substring** [comment]
@rockaddicted @digitallumberjack assign it to me please for 4.0.0
Meanwhile, if you need to undo a pairing, hou just need to erase the keys folder. I'll update my comment later today with its full path

**Comment by digitalLumberjack** [comment]
:)

**Comment by ultrasuperpingu** [comment]
Thanks for the reply,
However, I did try to delete the /recalbox/scripts/moonlight/keydir directory. But when trying to pair again to the first computer, I have the message: 
Failed to pair to server: Already paired
Is there any other files to delete or edit ?
Thanks a lot

**Comment by substring** [comment]
nope, that's the only dir to delete. At least if you tried to pair using the script. If not .... errrrr .... something like ~/.cache/moonlight, can't remember ... or ~/.config/moonlight

**Comment by substring** [comment]
Solved : https://github.com/recalbox/recalbox-buildroot/pull/170
@digitalLumberjack @rockaddicted can be closed
