### ISSUE TITLE
[4.0.0] zoid theme : no image for favourites

### ISSUE THREAD

**Issue by nadenislamarre** [recalbox/recalbox-os#625]
all is white.

**Comment by digitalLumberjack** [comment]
Known issue, i will remove zoid from the default distribution when the new theme is ready. People will have to download it and install it and know that it breaks the system when you have more that 15 systems. 

We may work on ES to load the themes as you said last time, but i'm really thinking that it will make ES slow. 

What do you think ?

**Comment by nadenislamarre** [comment]
hum, i don't know.
probably some tests to do to check.
but it's not an urgent issue for the moment.

2016-01-24 10:50 GMT+01:00 digitalLumberjack <notifications@github.com>:

**Comment by digitalLumberjack** [comment]
Zoid removed

**Comment by kryptto** [comment]
Thank goodness, caused me and others issues.  Not worth keeping if it is a problem.

Sent from my iPad

On Feb 10, 2016, at 5:21 AM, digitalLumberjack <notifications@github.com<mailto:notifications@github.com>> wrote:


Zoid removed
