### ISSUE TITLE
NES - Invert A & B mapping by default ?

### ISSUE THREAD

**Issue by mchtt** [recalbox/recalbox-os#626]
Dunno for you guys, but if i use an xbox 360 or PS3 gamepad, it ends with a non-logical mapping:
 Axbox = Anes and Bxbox = Bnes, it results in a really hard way to run and jump in Mario games, Bnes should be mapped to Xxbox (Square Ps3). So you can easily push the to buttons together with your thumb.

**Comment by substring** [comment]
The nes pad is like the SNES pad : A and B are inverted compared to the Xbox pad. We can't change the mapping because some people play with real nes pads, and they don't have X nor Y. 
You'll get used ;) we all had to when we were kids playing on NES ;)

**Comment by rockaddicted** [comment]
When you map your gamepad on ES, you must use a SNES layout.
So with a xbox gamepad, when ES ask to press A button, press B xbox button etc...

| xbox pad | snes pad |
| :--------------: | :--------------: |
| A | B |
| B | A |
| X | Y |
| Y | X |

More information : https://github.com/recalbox/recalbox-os/wiki/Notice-%28FR%29#ii---configuration

**Comment by mchtt** [comment]
The problem is that on **nes** games you jump with **A** and on **snes** you jump with B...

**Comment by digitalLumberjack** [comment]
So the mapping is normal. What you want is to customize the mapping for a system, with  non standard controls. 
It's a feature i'll add soon.

**Comment by mchtt** [comment]
yes it is, sorry i was unclear.
