### ISSUE TITLE
Bluetooth with fat32 ext device

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#629]

**Comment by Laddyacris** [comment]
Salut
après une fresh install, en local BT fonctionne.
Ensuite via le Menu ES, stockage vers ma clé USB 64 Go FAT32. Au reboot, la synchro est ok mais ES 
ne la voit pas impossible à la configurer.

**Comment by nadenislamarre** [comment]
la bluetooth est cassé je crois actuellement en fat32. (car il utilise des
noms de fichiers avec des : non supportés en fat32)
Digit, tu confirmes ?

**Comment by digitalLumberjack** [comment]
@Laddyacris tu as pu testé avec les dernieres modifications ?

**Comment by Laddyacris** [comment]
@digitalumberjack lesquelles ?
Jai testé il ya plus qu une semaine et ça fonctionnait. Jai pas mis à jour depuis dimanche.
Ya il eu de nouvelles modif depuis ?

**Comment by digitalLumberjack** [comment]
nope pas depuis, je close :)
