### ISSUE TITLE
www.recalbox.com web site down

### ISSUE THREAD

**Issue by piousteph** [recalbox/recalbox-os#631]
Bonjour,

Rien a voir avec la recalbox en elle meme, mais je constate que le site, ainsi que le forum et le blog ne sont plus accessible.

"
Lookup failed: recalbox.fr Host not found
No host name is associated with this IP address or no reverse lookup is configured.
Retrieving DNS records for recalbox.fr...
Attempt to get a DNS server for recalbox.fr failed: recalbox.fr does not exist in the DNS 
"

**Comment by digitalLumberjack** [comment]
Thanks, it's working now
