### ISSUE TITLE
Add a mDNS daemon 

### ISSUE THREAD

**Issue by alexduros** [recalbox/recalbox-os#633]
I'm new to recalbox-os so, please forgive if my request is out of field.
I suggest to add to recalbox environment a mDNS daemon so it should be easy to find the recalbox from a local network with a zeroconf / bonjour client, and may help for IP controller to find recalbox on the LAN.

**Comment by substring** [comment]
Hi

Avahi is in the next major release ;)

**Comment by alexduros** [comment]
Ah thanks, thanks for quick answer !
