### ISSUE TITLE
Recalbox 4.0.0 don't start piFBA games

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-os#636]
When I try to start a piFBA game, I come back to ES.
Tried to start game in SSH with : 
`/usr/bin/fba2x --configfile /recalbox/share/system/configs/fba/fba2x.cfg --logfile /recalbox/share/system/logs/fba2x.log /recalbox/share/roms/fba/3countb.zip`
I obtained a `Segmentation fault`

Then tried with : 
`/usr/bin/fba2x --configfile /recalbox/share/system/configs/fba/fba2x.cfg /recalbox/share/roms/fba/3countb.zip`
And the game start.

**Comment by Voljega** [comment]
Just commenting but is there really a need to keep piFBA now that we have a more uptodate FBA_libretro ? (performances are likely the same ?)

**Comment by rockaddicted** [comment]
Don't forget the rpi1/0's users. piFBA is the best arcade emulator for them.

**Comment by digitalLumberjack** [comment]
Clearly. As PI zero will reboost the usage of rpi1 version of recalbox, we will keep pifba for sure

**Comment by digitalLumberjack** [comment]
And yes it's stille the most optimized, even on pi2 :)

**Comment by Voljega** [comment]
So it is much less demanding in terms of computational power... even compared to mame0.78 or onlmy in comparison to FBA_libretro ?
 Should I then change the phrase "PiFBA is the most powerfull arcade emulator on the recalbox" to ""PiFBA is the most FBA optimized arcade emulator on the recalbox" ?

**Comment by digitalLumberjack** [comment]
Yes you could

**Comment by rockaddicted** [comment]
solved with https://github.com/recalbox/recalbox-buildroot/commit/619890aed3cc25225059f3cf165153267d7b5c24
