### ISSUE TITLE
Configure snes9x_next to use multitap by default

### ISSUE THREAD

**Issue by Voljega** [recalbox/recalbox-os#637]
If this is possible (maybe some games released early on the snes don't support multitap ?) it could be good to use multitap by default as described there :

https://github.com/recalbox/recalbox-os/wiki/Play-from-3-to-4-players-to-SNES-%28EN%29

so that 3-4 multiplayer games would be playable out of the (recal)box

**Comment by Voljega** [comment]
Same configuration would also be good for megadrive 6 buttons but I'm not sure the need is still there as the relevant wiki (https://github.com/recalbox/recalbox-os/wiki/Play-from-3-to-4-players-to-SNES-%28EN%29) is marked 3.2.11 on some links

**Comment by Laddyacris** [comment]
Megadrive est passé par défaut en 6 boutons en 3.3.0 beta

**Comment by Voljega** [comment]
ok thanks :)

**Comment by rockaddicted** [comment]
and multitap snes enabled by default on 4.0.0

**Comment by digitalLumberjack** [comment]
@rockaddicted isn't it done ?

**Comment by rockaddicted** [comment]
haha @digitalLumberjack
