### ISSUE TITLE
Wiki (EN) backup your scrape

### ISSUE THREAD

**Issue by schnirpf** [recalbox/recalbox-os#638]
Command to backup 'downloaded_images' creates another folder named 'downloaded_images' in the folder 'downloaded_images'

The command to backup should be:
`cp -r /root/.emulationstation/downloaded_images /recalbox/share/system/backup_scrape/ && cp -r /root/.emulationstation/gamelists /recalbox/share/system/backup_scrape/`

**Comment by rockaddicted** [comment]
Everyone have acces to the wiki.
Can you edit it ?

**Comment by schnirpf** [comment]
Sorry, tried to edit it first and it didn't work. Tried it now and editing the wiki worked:-)
