### ISSUE TITLE
Add delay when auto-launching Kodi

### ISSUE THREAD

**Issue by fognl** [recalbox/recalbox-os#639]
Depending on system and network, when Kodi is set to auto-launch in Recalbox, there is a chance the network won't be up in time.  For users who have remote filesystems mounted for their media such as NFS, shared databases, etc., this is an issue as they won't re-connect when network is available.  A quick work around is to quit Kodi and then re-launch.

Preposed solution would be an option in the ES->Kodi settings menu to enable a delay launch by X seconds to give the network a chance to come up before auto-launching Kodi.  This can add the delay to the Kodi launch script.  OpenELEC has this option in their custom Addon and it works quite well.

**Comment by nadenislamarre** [comment]
i add it in my todo list.
I will do this for the next release while it's easy to do.
i don't like the fact that it will take 0.2 seconds more to start kodi for
people don't using the option, but ok.

2016-01-29 22:40 GMT+01:00 fognl <notifications@github.com>:

**Comment by nadenislamarre** [comment]
Fixed by https://github.com/recalbox/recalbox-buildroot/pull/168 in next recalbox release.

**Comment by fognl** [comment]
Awesome, thank you for this.  Look forward to seeing it in the next nightly.  Cheers :)

**Comment by nadenislamarre** [comment]
the next when the pr is merged. (currently open)
So, perhaps tomorrow, perhaps so days later.

**Comment by nadenislamarre** [comment]
done in release 4.0
