### ISSUE TITLE
4.0.0-nightly-build-118 Extreme Setting Boot Failure

### ISSUE THREAD

**Issue by mchtt** [recalbox/recalbox-os#640]
After switching the overclock settings to "Extreme" i got a boot failure everytime. Anyone else ?

**Comment by digitalLumberjack** [comment]
Not yet. You're the first :)

**Comment by mchtt** [comment]
Will a screen capture help you ?

**Comment by digitalLumberjack** [comment]
It's related to either the SD, RPI2 or power supply :)

**Comment by mchtt** [comment]
my PSU is ok, so is the rpi2, i'll try with another SD.

**Comment by mchtt** [comment]
même problème sur la build 119... j'ai essayé avec une autre SD. une idée ?
(un reboot sans changer d'options d'overclock fonctionne)
l'overclock "HIGH" fonctionne sans problèmes.

**Comment by digitalLumberjack** [comment]
Tu as essayé un autre RPI2 ? Aprés si il y a quelque chose dans ta config qui t’empêche d'overclocker, reste en TURBO.

**Comment by mchtt** [comment]
Je n'en ai qu'un :+1:

**Comment by mspacemedia** [comment]
@mchtt just happened to me, thought it was the update but sounds like the extreme setting - corrupted the SD card so back to the start again and 14gb of copying to go through :D

**Comment by digitalLumberjack** [comment]
Seems like not all rpi can support the extrem settings.
RPI3 is on its way. Maybe we will not need to overclock anymore.
(hoax / info : choose your side :)

**Comment by mspacemedia** [comment]
RPI3 hoax = lmao :)
RPI3 info = damn only just bought RPI2 :(

**Comment by mchtt** [comment]
same but i will follow the recalbox team if they choose a more powerfull device (dreamcast, psp...)
