### ISSUE TITLE
Moonlight

### ISSUE THREAD

**Issue by sarsel33** [recalbox/recalbox-os#645]
Suivant la procédure du wiki , installation de moonlight sur une base recalbox 4.0.0 nightly 19 avec deux manettes PS3 shanwan appairées et fonctionnelles.

via putty, arret de emulastation puis poursuite de la procédure d'install moonlight

le pairing se fait parfaitement
l'init semble se dérouler sans accroc, pas de messages particulier, le scrapping fonctionne aussi

le mapping  suite à la commande # ./Moonlight.sh map
Too many options: No such file or directory
Can't map (reverse_z)
Can't map (reverse_rz)
Can't map (reverse_z)
Can't map (reverse_rz)
Can't map (reverse_z
Can't map (reverse_rz)
Can't map (reverse_z)
Can't map (reverse_rz)
puis le mapping se deroule de maniere apparament normale

ensuite, relance d'emulastation et demarrage de moonlight via la manette dans le menu
# /etc/init.d/S31emulationstation start
# lvl0:         Tried to use unset setting DefaultRomsPath!
lvl0:   Tried to use unset setting DefaultRomsPath!
lvl0:   Tried to use unset setting DefaultRomsPath!
lvl0:   Tried to use unset setting DefaultRomsPath!
lvl0:   System "favorites" is missing name, path, extension, or command!
lvl0:   Error loading sound "/etc/emulationstation/themes/simplelight/moonlight/../sounds/scroll.wav"!
        Mix_LoadWAV_RW with NULL src
lvl0:   Error loading sound "/etc/emulationstation/themes/simplelight/prboom/../sounds/scroll.wav"!
        Mix_LoadWAV_RW with NULL src
lvl0:   Tried to use unset setting INPUT P1NAME!
lvl0:   Tried to use unset setting INPUT P1GUID!
lvl0:   Tried to use unset setting INPUT P2NAME!
lvl0:   Tried to use unset setting INPUT P2GUID!
lvl0:   Tried to use unset setting INPUT P3NAME!
lvl0:   Tried to use unset setting INPUT P3GUID!
lvl0:   Tried to use unset setting INPUT P4NAME!
lvl0:   Tried to use unset setting INPUT P4GUID!
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/recalbox-4.0.0-rpi2/output/target/usr/lib/python2.7/site-packages/configgen/emulatorlauncher.py", line 137, in <module>
    command = generators[system.config['emulator']].generate(system, args.rom, playersControllers)
  File "/usr/lib/python2.7/site-packages/configgen/generators/moonlight/moonlightGenerator.py", line 15, in generate
    gameName = self.getRealGameName(rom)
  File "/usr/lib/python2.7/site-packages/configgen/generators/moonlight/moonlightGenerator.py", line 33, in getRealGameName
    f = open(recalboxFiles.moonlightGamelist, 'r')
IOError: [Errno 2] No such file or directory: '/recalbox/share/system/configs/moonlight/gamelist.txt'

et voila, grosso modo, moonlight est installé correctement dans recalbox, accessible par le menu mais des que l'on veut lancer steam, ca revient systématiquement dans le menu de recalbox

merci d'avance pour votre aide

**Comment by substring** [comment]
tu n'as pas à fair le mapping des pads sous la 4.0.0 puisque (comme je te l'ai dit sur IRC :p) la config de ES est reprise automatiquement.

Pour les autres messages d'erreur, les lvl0 sont liés à ES, rien de grave

Le gamelist.txt est absent à cause d'un probleme de chemin dans le Moonlight.sh. Je fais une correction. Une fois la correction embarquée, juste à faire la mise à jour de recalbox, refaire le pair et le init, et ca sera bon

**Comment by sarsel33** [comment]
salut subs j'ai appliqué ce que tu m'as dit mais voila ce que je vois sous putty :+1:
lvl0: Tried to use unset setting DefaultRomsPath!

lvl0: Tried to use unset setting DefaultRomsPath!
lvl0: Tried to use unset setting DefaultRomsPath!
lvl0: System "favorites" is missing name, path, extension, or command!
lvl0: Error loading sound "/etc/emulationstation/themes/simplelight/moonlight/ ../sounds/scroll.wav"!
Mix_LoadWAV_RW with NULL src
lvl0: Tried to use unset setting INPUT P1NAME!
lvl0: Tried to use unset setting INPUT P1GUID!
lvl0: Tried to use unset setting INPUT P2NAME!
lvl0: Tried to use unset setting INPUT P2GUID!
lvl0: Tried to use unset setting INPUT P3NAME!
lvl0: Tried to use unset setting INPUT P3GUID!
lvl0: Tried to use unset setting INPUT P4NAME!
lvl0: Tried to use unset setting INPUT P4GUID!
Traceback (most recent call last):
File "/var/lib/jenkins/workspace/recalbox-4.0.0-rpi2/output/target/usr/lib/pyt hon2.7/site-packages/configgen/emulatorlauncher.py", line 137, in
command = generators[system.config['emulator']].generate(system, args.rom, p layersControllers)
File "/usr/lib/python2.7/site-packages/configgen/generators/moonlight/moonligh tGenerator.py", line 15, in generate
gameName = self.getRealGameName(rom)
File "/usr/lib/python2.7/site-packages/configgen/generators/moonlight/moonligh tGenerator.py", line 33, in getRealGameName
f = open(recalboxFiles.moonlightGamelist, 'r')
IOError: [Errno 2] No such file or directory: '/recalbox/share/system/configs/mo onlight/gamelist.txt'

ceci dit le gamelist.txt existe mais il est coté "user" et non coté "system"...peut être que le problème vient de là ?

merci encore pour ton aide

**Comment by substring** [comment]
@digitalLumberjack tu es sûr que tu compiles avec la bonne version de configgen ? mon recalboxFiles.py n'a pas grand chose à voir avec https://github.com/recalbox/recalbox-configgen/blob/4.0.0/configgen/recalboxFiles.py
Le reste sera résolu avec https://github.com/recalbox/recalbox-buildroot/pull/160

**Comment by substring** [comment]
il y a plus que juste le gamelist.yxy, j'ai été un peu vite
le moonlight.conf n'est pas répliqué dans son répertoire de destination
un chemin est faut dans un fichier de configgen
Si digi merge tout et corrige sa version de configgen, ca sera bon pour demain matin
il y a plus que juste le gamelist.yxy, j'ai été un peu vite
le moonlight.conf n'est pas répliqué dans son répertoire de destination
un chemin est faut dans un fichier de configgen
Si digi merge tout et corrige sa version de configgen, ca sera bon pour demain matin

**Comment by substring** [comment]
@rockaddicted @digitalLumberjack @sarsel33 à fermer puisque résolu

**Comment by substring** [comment]
@sarsel33 impossible de streamer big picture pour moi non plus. Meme de ma shield ca ne marche pas, donc je vais aller voir du côté de nvidia pk ca déconne, ca n'est pas un problème moonlight
