### ISSUE TITLE
Refresh gamelist without restart RPi

### ISSUE THREAD

**Issue by mgoulartBR** [recalbox/recalbox-os#646]
Hey guys,

It's a minor issue but when I send new games to Recalbox, I need to restart my RPi to show these games. Is there a way to refresh gamelists or restart Emulationstation without reset RPi?

**Comment by rockaddicted** [comment]
Done in 4.0.0 ;)

**Comment by mgoulartBR** [comment]
Wow fast one!!! Thanks!!!!!!!!!!!!

**Comment by rockaddicted** [comment]
With a 3.3.0 you can restart es in ssh `/etc/init.d/S31emulationstation restart`

**Comment by mgoulartBR** [comment]
I will tri it!!!!

**Comment by mgoulartBR** [comment]
Ops try
