### ISSUE TITLE
Autosave/Autoload

### ISSUE THREAD

**Issue by nadenislamarre** [recalbox/recalbox-os#647]
An option to add automatically in retroarchcustom.cfg
savestate_auto_save = "true"
savestate_auto_load = "true"

When you quit the game, it autosaves, when you replay, it continues where it were.
Add a hotkey to be able to reset the game then.

**Comment by mchtt** [comment]
#613

**Comment by rockaddicted** [comment]
added with : 
https://github.com/recalbox/recalbox-buildroot/commit/39f70fc1e4502a146ad82fc4a404934195cf50cb
https://github.com/recalbox/recalbox-configgen/commit/0e908dbcb101de52746448108fdaf072d22668b5
https://github.com/recalbox/recalbox-emulationstation/commit/32d3515766a60bc897d20953d91c10d0ece18b6b
