### ISSUE TITLE
add retroachivements to ES

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-os#649]

**Comment by mchtt** [comment]
really ? :-) this would be awesome ! ! !

**Comment by mgoulartBR** [comment]
OMG!!! This is amazing!!!
Can we suggests some achivements? Maybe a online achivements database !!!

**Comment by mchtt** [comment]
it already exists @mgoulartBR  , they just want to add support fo that i suppose... [Retro Achievments](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi7yqTHw9jKAhUBLhoKHWegDFYQFggkMAA&url=http%3A%2F%2Fretroachievements.org%2F&usg=AFQjCNHvZjCd9WnbxBFr8scuAox8JMME-A)

**Comment by rockaddicted** [comment]
Yes indeed, [retroarchievements's](http://retroachievements.org) support has been added to retroarch.
So we want to add an option to emulationstation  to have a friendly configuration of this feature in recalbox.
If you want to add/suggest any specific achivements, go on the retroachievements's website and look with their community. ;

**Comment by mgoulartBR** [comment]
@mchtt Awesome! I didn't heard about this site before!

**Comment by substring** [comment]
looks like chistmas is early this year : https://github.com/recalbox/recalbox-buildroot/pull/176

**Comment by mchtt** [comment]
what do you mean @substring  ? it is implemented in the latest build :-) :+1:  ?

**Comment by substring** [comment]
and https://github.com/recalbox/recalbox-emulationstation/commit/312d35415256a6951c099039f41b40e202d3a2b2

**Comment by substring** [comment]
YEs it is, and can be set in ES

**Comment by mchtt** [comment]
thx.
