### ISSUE TITLE
Switch all Sega cores to genesis-plus-gx by default on RPI2

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#651]
Hi

The RPI2 can play all sms, gg, md, mega-cd with genesis-plus-gx at full speed (except virtua racing md but why play this when the 32x version is much better?)

genesis-plus-gx is the best and most accurate sega emulator to date (more accurate than picodrive) so it should be the default core on RPI2 (and leave picodrive by default on RPI1/zero), except for 32x of course.

(For mega-cd the bios files needs to be renamed bios_CD_U.bin, bios_CD_E.bin and bios_CD_J.bin.)

**Comment by xbox360pad** [comment]
+1

**Comment by rockaddicted** [comment]
Hi we won't do that, because actually, libretro-genesisplusgx + retroachievements enabled = framerate problem with some games.
But you can now switch easily your default emulator as you want, using the advanced games options in emulationstation.
