### ISSUE TITLE
display Megadrive instead of Genesis by default in emulationstation

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#652]
Megadrive should be the default name (it's the original name of the console, Genesis was only used in North America because trademark issue there).

(from the retropie wiki https://github.com/retropie/RetroPie-Setup/wiki/Genesis-Megadrive)

<system>
    <name>megadrive</name>
    <fullname>Sega Mega Drive / Genesis</fullname>
    <path>~/RetroPie/roms/megadrive</path>
    <extension>.smd .bin .gen .md .sg .zip .SMD .BIN .GEN .MD .SG .ZIP</extension>
    <command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ megadrive %ROM%</command>
    <platform>megadrive</platform>
    <theme>megadrive</theme>
  </system>

**Comment by marvbloke** [comment]
I agree.

**Comment by rockaddicted** [comment]
Will be done on the new default theme

**Comment by digitalLumberjack** [comment]
Yes :)

Le mer. 9 mars 2016 à 11:29, rockaddicted <notifications@github.com> a
écrit :

**Comment by paradadf** [comment]
FYI, there are nearly 750 genesis games against around 480 megadrive games released. Megadrive might be the original name, but Genesis is around the world the most popular one (and I live in Europe). Imho, it would be better to use Genesis instead.

**Comment by mcmasterp** [comment]
how to change it back to genesis for us US'ers?
