### ISSUE TITLE
PS3 drivers

### ISSUE THREAD

**Issue by c4store82** [recalbox/recalbox-os#657]
Hi just got some GASIA controllers and im having trouble changing the drivers in recalbox.conf.  What do I type or how can I edit the line I need to.

**Comment by paradadf** [comment]
Looking at the wiki in the first place always helps...

https://github.com/recalbox/recalbox-os/wiki/PS3-controllers-drivers-%28EN%29

**Comment by c4store82** [comment]
I followed the wiki.  I logged on as root.  I used the dmesg to figure out which driver.  I just don't know how to modify the driver line to GASIA.  
I've tried 
controllers.ps3.driver=GASIA 
but it isn't a command.  What do I type to change it.  I want to play two player contra!

**Comment by c4store82** [comment]
I followed the wiki.  I logged on as root.  I used the dmesg to figure out which driver.  I just don't know how to modify the driver line to GASIA.  
I've tried 
controllers.ps3.driver=GASIA 
but it isn't a command.  What do I type to change it.  I want to play two player contra!

**Comment by substring** [comment]
This is not the place for support. Please use the forum on www.recalbox.com, or join IRC (you'll get information on how to each us on IRC on the forum)

**Comment by paradadf** [comment]
it should be written in lower case letters, exactly as the wiki shows!
`controllers.ps3.driver=gasia`

**Comment by rockaddicted** [comment]
As @substring said, github is not a support place.
Please to use forum the next time you need support.
