### ISSUE TITLE
PS3 wireless Controller - please some help

### ISSUE THREAD

**Issue by edward-turner** [recalbox/recalbox-os#658]
Hi,

I am nearly to give up. Please please, help me somehow..
I got two PS3 Controller (CECHZC2E A1) and can´t get them to work.
There are 3 bluetooth dongles. All seem to work (running) but I can´t find the controller.They are fully charged and just blinking when hit the middle button.

What can I do? Latest recalbox and apt-get update / upgrade is done.
hcitool scan does not find the controller.
Did the guide:
https://dhoium3009.wordpress.com/raspberry-pi-connecting-multiple-ps3-controllers-via-bluetooth/
and
http://www.raspians.com/Knowledgebase/ps3-dualshock-controller-install-on-the-raspberry-pi/

But I get error with the bin/sixad-bin location...

Please help me somehow..

**Comment by kryptto** [comment]
@edward-turner please place this request for help in the forums under troubleshooting.


On Feb 2, 2016, at 4:56 PM, edward-turner <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I am nearly to give up Please please, help me somehow
I got two PS3 Controller (CECHZC2E A1) and can´t get them to work
There are 3 bluetooth dongles All seem to work (running) but I can´t find the controllerThey are fully charged and just blinking when hit the middle button

What can I do? Latest recalbox and apt-get update / upgrade is done
hcitool scan does not find the controller
Did the guide:
https://dhoium3009wordpresscom/raspberry-pi-connecting-multiple-ps3-controllers-via-bluetooth/
and
http://wwwraspianscom/Knowledgebase/ps3-dualshock-controller-install-on-the-raspberry-pi/

But I get error with the bin/sixad-bin location

Please help me somehow

**Comment by edward-turner** [comment]
Do you mean the forum on http://blog.recalbox.com/forums ?

**Comment by substring** [comment]
yes sir
