### ISSUE TITLE
Slow power off / shutdown

### ISSUE THREAD

**Issue by schnirpf** [recalbox/recalbox-os#659]
I have alot of roms. Shuting down from ES takes sometimes 10 minutes. Strangely a reboot just takes a couple of seconds.

Roms are on external USB HD.

Any ideas?

**Comment by substring** [comment]
Emulationstation writes data about known roms. So if you have really many roms, it can take some time, yes

**Comment by schnirpf** [comment]
Ok, thanks for your answer. Will try to minimize the number of roms:-)

**Comment by substring** [comment]
I think the speed should be improved in 4.0.0

**Comment by schnirpf** [comment]
Yes, shutdown in v4 is compared to v3 lightning fast (with same amount of roms).
