### ISSUE TITLE
4.0.0-nightly-build-126 N64 Full Screen

### ISSUE THREAD

**Issue by mchtt** [recalbox/recalbox-os#662]
When launching an N64 game, the video is not stretched anymore and is bottom left "centered" ?
Was working on 122.

**Comment by rockaddicted** [comment]
which plugin are you using ?
video mode ?

**Comment by mchtt** [comment]
Default settings. They were fresh installs

**Comment by mchtt** [comment]
If i 122 then update it keeps the proper displaying...

**Comment by rockaddicted** [comment]
On ES go in games options, advanced settings, then nintendo 64, and set `emulator` on mupen64plus then `core` on `gliden64`.

**Comment by mchtt** [comment]
![img_0483](https://cloud.githubusercontent.com/assets/7107299/12865888/60246cd2-ccba-11e5-9bf6-391f4af9bdfb.JPG)
nope. the problem is that it was working flawlessly in 122 ;-)

**Comment by mchtt** [comment]
![img_0486](https://cloud.githubusercontent.com/assets/7107299/12865919/f31bb2b0-ccbb-11e5-893a-5fa19da8c3ee.JPG)
122.

**Comment by mchtt** [comment]
![img_0488](https://cloud.githubusercontent.com/assets/7107299/12865947/f722cb5e-ccbc-11e5-8461-6a17e10147e3.JPG)
123. Looks like we got the guilty ;-)

**Comment by nosfay** [comment]
I tried all video plugin and same problem with the last nightly!

**Comment by rockaddicted** [comment]
edit your `/recalbox/share/system/configs/mupen64/mupen64plus.cfg` file then, switch this setting from `False` to `True`.
```
# Use fullscreen mode if True, or windowed mode if False
Fullscreen = False
```
We turned this off because, if it is enabled, you have a blackscreen with de plugins combo :    `audio-sdl + video-rice`

**Comment by rockaddicted** [comment]
So if you want to use rice plugin, set in your recalbox.conf file, the `n64.videomode=` on `DMT 4 HDMI` or `CEA 1 HDMI` (640x480)

**Comment by mchtt** [comment]
So from now we don't have native full screen on N64 ? it is a step backward no ?

**Comment by rockaddicted** [comment]
Ok so, actually on recalbox, to fix the freeze problem with mupen64plus, we switched the audio plugin from `omx` to `sdl`. But with this new audio plugin enabled, a new problem merged. You can no more use the video plugin `rice`... So to fix that, we removed the fullscreen option in mupen64plus, and `rice` is now usable.
But, actually, by defaut, in your `~/configs/mupen64/mupen64plus.cfg` file mupen64plus is set to display a screen with a resolution of `640x480`, and in your `~/recalbox.conf` file, the `n64.videomode=` is set by default on `DMT 9 HDMI`, corresponding to a resolution of `800x600`.
The option to strech the screen being disabled, you have a fullscreen problem. :-/   

So you have 3 ways to fix this problem : 
- Edit your `~/recalbox.conf` file, then switch the `n64.videomode=` on  `DMT 4 HDMI` or `CEA 1 HDMI`. You'll have the same resolution in mupen64plus as your tv mode (640x480) so fullscreen. (This option will be added to recalbox).
I'm using this setup on my recalbox, so I didn't see this fullscreen problem ...   

- Edit your `~/configs/mupen64/mupen64plus.cfg` file, then switch your resolution : 
from 
```
# Width of output window or fullscreen width
ScreenWidth = 640
# Height of output window or fullscreen height
ScreenHeight = 480
```
to
```
# Width of output window or fullscreen width
ScreenWidth = 800
# Height of output window or fullscreen height
ScreenHeight = 600
```
You'll use the same resolution than your video mode defined in your `~/recalbox.conf` file `n64.videomode= DMT 9 HDMI`.   

- or Edit your `~/configs/mupen64/mupen64plus.cfg` file, and enable the fullscreen option : 
```
# Use fullscreen mode if True, or windowed mode if False
Fullscreen = False
```
to
```
# Use fullscreen mode if True, or windowed mode if False
Fullscreen = True
```
BUT you won't be able to use the video plugin `rice`, so I don't recommend this third option.

**Comment by mchtt** [comment]
THX a lot for those explanations. :+1:

**Comment by digitalLumberjack** [comment]
We should set 800*600 by default for n64 video no ? So no mode 640*480 issues, and the mode is ok on all tvs @rockaddicted ?

**Comment by substring** [comment]
By default :
n64.videomode=DMT 9 HDMI

Which is :
hdmi_mode=9    800x600    60 Hz

So it's already the case @digitalLumberjack

**Comment by digitalLumberjack** [comment]
I mean ~/configs/mupen64/mupen64plus.cfg

**Comment by substring** [comment]
should be fine with the commit referred above once merged

**Comment by mchtt** [comment]
will try :+1:

**Comment by substring** [comment]
should be solved with the latest build
Dont try playing it in Full HD : 3D graphics will look great, bitmaps plain awful ... but it will run so sloooooooow

**Comment by substring** [comment]
@mchtt is it of for you ?

**Comment by mchtt** [comment]
don't have time to test :-( maybe @nosfay ?

**Comment by rockaddicted** [comment]
it is ok dude we can close it

**Comment by mchtt** [comment]
yes :-) milestone almost complete !

**Comment by fonkdoctor** [comment]
Hi team !
same problem here... i had set emulator on mupen64plus then core on gliden64.
i've modified this
# Use fullscreen mode if True, or windowed mode if False
Fullscreen = True


but always the same problem... the game is windowed.
I don't understand why...

thanks a lot ! :)

**Comment by bpvarsity** [comment]
I have the same issue. I have fullscreen= True but its still windowed. Anyone here to help?
