### ISSUE TITLE
[4.0.0] Twin USB joystick for mupen64

### ISSUE THREAD

**Issue by nosfay** [recalbox/recalbox-os#663]
Hi,

I can't launch mupen64plus if I use my "Twin USB Joystick", it's an USB to PSX controller adaptator with 2 output. Both controllers work fine on RetroArch.

EmulationStation Log:
`lvl2:           python /usr/lib/python2.7/site-packages/configgen/emulatorlauncher.pyc -p1index 0 -p1guid 03000000100800000100000010010000 -p1name "Twin USB Joystick" -p1devicepath /dev/input/event0 -p2index 1 -p2guid 03000000100800000100000010010000 -p2name "Twin USB Joystick" -p2devicepath /dev/input/event1  -system n64 -rom /recalbox/share/roms/n64/All-Star\ Baseball\ 2000\ \(E\)\ \[\!\].z64 -emulator default -core default 
lvl1:   ...launch terminated with nonzero exit code 256! `

EmulastionStation --debug:
`ConfigParser.DuplicateSectionError: Section 'Twin USB Joystick' already exist`

**Comment by nadenislamarre** [comment]
it's a bug specific to configen for n64 :
i guess that there is a .ini, one section by joystick, and when a joytick is available 2 times, it fails.
Subs, is it for you ?

'/recalbox/share/system/configs/mupen64/InputAutoCfg.ini
Config.add_section(section)
# python /usr/lib/python2.7/site-packages/configgen/emulatorlauncher.pyc -p1index 0 -p1guid 03000000100800000100000010010000 -p1name "Twin USB Joystick" -p1devicepath /dev/input/event0 -p2index 1 -p2guid 03000000100800000100000010010000 -p2name "Twin USB Joystick" -p2devicepath /dev/input/event1 -system n64 -rom /recalbox/share/roms/n64/All-Star\ Baseball\ 2000\ \(E\)\ \[\!\].z64 -emulator default -core default
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/recalbox-4.0.0-rpi2/output/target/usr/lib/python2.7/site-packages/configgen/emulatorlauncher.py", line 137, in <module>
    command = generators[system.config['emulator']].generate(system, args.rom, playersControllers)
  File "/usr/lib/python2.7/site-packages/configgen/generators/mupen/mupenGenerator.py", line 17, in generate
    mupenControllers.writeControllersConfig(playersControllers)
  File "/usr/lib/python2.7/site-packages/configgen/generators/mupen/mupenControllers.py", line 38, in writeControllersConfig
    writeToIni(player, config)
  File "/usr/lib/python2.7/site-packages/configgen/generators/mupen/mupenControllers.py", line 122, in writeToIni
    Config.add_section(section)
  File "/usr/lib/python2.7/ConfigParser.py", line 264, in add_section
    raise DuplicateSectionError(section)
ConfigParser.DuplicateSectionError: Section 'Twin USB Joystick' already exists
#

**Comment by substring** [comment]
Yup for me. I think mupen doesn't like having twice thé same controller defined in its conf file. Already assignés to me ;)
