### ISSUE TITLE
4.0.0 Show no disk space

### ISSUE THREAD

**Issue by kryptalivian** [recalbox/recalbox-os#668]
How do you expand your disk?

**Comment by Laddyacris** [comment]
Hello thanks to use forum for your request.

**Comment by substring** [comment]
Hello,

Could you provide more information about your issue ? I just quite don't understand what you mean

**Comment by mchtt** [comment]
@kryptalivian on recalbox it auto expands ;-) if not try a clean re-install of the OS to replicate the issue.

**Comment by kryptalivian** [comment]
I'm on the developer version 4.0.0 . that one is an image that you write to the SD card, not the normal image you copy over. It doesn't auto expand. My 32GB flash drive shows full and I have no roms

**Comment by substring** [comment]
How do you know it's full ? My 4.0.0 reports free space without a hich

**Comment by mchtt** [comment]
Like @substring i have no issues. You tried with a different card (size) ?

**Comment by kryptalivian** [comment]
Keeps saying not enough room when I transfer a few snes roms. Currently no roms on device. I'll check again tonight

**Comment by substring** [comment]
c

**Comment by substring** [comment]
@kryptalivian 
can you SSH to it and type "df -h" and paste the result here please ?

**Comment by kryptalivian** [comment]
http://archive2.recalbox.com/4.0.0/last/rpi1-unstable/ 

I took the image and used Win32DiskImager to write the image. Should I have thrown the image into noobs? I'll SSH into it tonight(Last night got super busy).

**Comment by substring** [comment]
Rpi1 or 0 then ? I'll check on mine.
Normally when using thé img, recalbox will use thé free space to create à 3rd partition mounted as /recalbox/share_init

**Comment by nadenislamarre** [comment]
mounted on /recalbox/share

**Comment by kryptalivian** [comment]
I used the RP1 image for the Zero. I'll take some Pix of the settings page, as well as the results of df -h.

**Comment by substring** [comment]
just tested on my Pi, not fully translated in french, but this one is in english. The message is quite confusing. It says **SPACE LEFT 0GB/6GB (0%)** when it means "SPACE USED". And `df -h` reported : 
# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root               936.0M    723.3M    148.4M  83% /
devtmpfs                118.1M         0    118.1M   0% /dev
tmpfs                   122.2M         0    122.2M   0% /dev/shm
tmpfs                   122.2M      4.0K    122.2M   0% /tmp
tmpfs                   122.2M      2.8M    119.5M   2% /var
tmpfs                   122.2M     68.0K    122.2M   0% /run
/dev/mmcblk0p1           63.0M      6.6M     56.4M  10% /boot
/dev/mmcblk0p3            6.2G     70.2M      5.8G   1% /recalbox/share

**Comment by substring** [comment]
hey @kryptalivian did you check if it works correctly ?

**Comment by substring** [comment]
@kryptalivian could you try reinstalling v4 with build 137 or later ?

**Comment by kryptalivian** [comment]
Sorry been busy :-( I'll try this weekend. On a better note, I somehow ended up buying 9 pi zeros at microcenter

**Comment by kryptalivian** [comment]
Guess sd cards were swapped and I formatted it :-(

**Comment by kryptalivian** [comment]
I think I'm going to wait for official 4.0

**Comment by Bigtalljosh** [comment]
I have this issue on my Pi Zero too. This third partition is not created. The ~30gb of free space I should have is just non existence.

**Comment by digitalLumberjack** [comment]
@Bigtalljosh Are you sure of that ? Did you tried to run a `mount` and `df` on cli ?

**Comment by nadenislamarre** [comment]
kryptalivian, do you confirm we can close this one ?

**Comment by kryptalivian** [comment]
Yes, It was a one time error for me
