### ISSUE TITLE
Raphnet 4nes4snes support

### ISSUE THREAD

**Issue by leberrem** [recalbox/recalbox-os#67]
I use 4nes4snes Raphnet controller.
http://www.raphnet-tech.com/products/4nes4snes/index.php

It's the perfect controller for a multiplayer games.
Now only the first controller is configurable.

Do you think i's going to be possible to map 4 controller with only one USB controller with 8 axis and 32 buttons.

Thank you so much.

PS : I'm going to try to map it manually in configuration files. maybe an idea to do this?

**Comment by digitalLumberjack** [comment]
Won't be fixed right now in emulationstation. But the new config system will allow you to override automatic controller configuration.

**Comment by leberrem** [comment]
I'm going to test your modification in next release.
Thank you so much.

**Comment by digitalLumberjack** [comment]
The next issue is that if the 4nes4snes create only one joystick, you will
have to configure it directly in retroarchcustom.cfg, and you won't be able
to use autoconfiguration tools. But it should work.

**Comment by digitalLumberjack** [comment]
closed with #206
