### ISSUE TITLE
[3.3.0-beta17] Some issues regarding Xbox 360 wired controller and kodi

### ISSUE THREAD

**Issue by D179401993** [recalbox/recalbox-os#670]
Hi! 

First of all great project, thank you! I just tested 3.3.0-beta17 with a wired xbox 360 controller on my rpi2 and noticed a few issues: 

 - when in kodi i can completly navigate with the controller but cannot activate any options in context-menus, this includes items in the power off dialog and the "resume from 05:12" kind of dialogues
- When im playing back videos with the controller connected, the video is randomly fast forwarding (some issue with the analogue stick?) and some kind of speaker symbol is flashing in the upper right corner in kodi
 - from kodi when i want to return to emulation station and hit "exit", the tv goes black but i can hear the menu-music from emulation station, same for the "shut down" option in kodi, only "restart" will bring me back reliably. 

Just for the sake of completness the controller is working in emulation station and in games like it should.

Best regards
 - Stefan

**Comment by D179401993** [comment]
Ok, enabling the xboxdrv in the recalbox.conf got the first issue working, the second one still persists.

**Comment by rockaddicted** [comment]
Thanks to read the recalbox's wiki : https://github.com/recalbox/recalbox-os/wiki/Kodi-on-recalbox-%28EN%29#power-management-with-hdmi-cec

**Comment by mchtt** [comment]
@D179401993  u should try a 4.0.0 test build, all my xbox 360 issues are gone with it.

**Comment by substring** [comment]
4.0.0 is not yet in a stable release, please don't recommend it to solve problems.

**Comment by mchtt** [comment]
ok sorry.

**Comment by D179401993** [comment]
Thx a lot, all issues resolved with the wiki. Sry for the inconvenience, the wiki is really a must read :D
