### ISSUE TITLE
SegaCD Roms Issue

### ISSUE THREAD

**Issue by danielpolsky** [recalbox/recalbox-os#673]
First off, let me just say thanks and well done. This is an awesome project. When downloading the roms from planetemu for SegaCD as recommended in the segacd rom folder, I can't get them to work. The forums all talk about needing to use bin/cue but the roms downloaded from planetemu aren't that format. I'm using a mac to do all this, but don't know if that's the issue and have been transferring them to recalbox through finder over the network. Is there something I need to do to convert them? Any thoughts?

Cheers.

**Comment by kryptto** [comment]
This needs to be asked on the forums, this is used for development and bug reporting.

http://blog.recalbox.com/forums/

Thanks

Sent from my iPad

On Feb 8, 2016, at 6:44 PM, danielpolsky <notifications@github.com<mailto:notifications@github.com>> wrote:


First off, let me just say thanks and well done This is an awesome project When downloading the roms from planetemu for SegaCD as recommended in the segacd rom folder, I can't get them to work The forums all talk about needing to use bin/cue but the roms downloaded from planetemu aren't that format I'm using a mac to do all this, but don't know if that's the issue and have been transferring them to recalbox through finder over the network Is there something I need to do to convert them? Any thoughts?

Cheers

**Comment by danielpolsky** [comment]
Sorry. My bad.
