### ISSUE TITLE
[4.0.0-beta1] change paths for the internal scraper

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-os#676]
As 4.0.0 will handle usb keys, the internal scraper should not xrite data to ~/.emulationstation but rather to the rom folder
The suggestion is to :
- write the gamelist.xml to /recalbox/share/roms/_system_
- save images to /recalbox/share/roms/_system_/imag

**Comment by kryptto** [comment]
As a person who has scraped thousands of games, my folders have huge data collected.  Moving to the fat32 share for ROMS will make it easier for people to backup their files in one place making a fresh install easier to keep your personalized settings and work.  Thanks!

Sent from my iPad

On Feb 10, 2016, at 6:05 AM, Subs <notifications@github.com<mailto:notifications@github.com>> wrote:


As 4.0.0 will handle usb keys, the internal scraper should not xrite data to ~/.emulationstation but rather to the rom folder
The suggestion is to :

  *   write the gamelist.xml to /recalbox/share/roms/system
  *   save images to /recalbox/share/roms/system/imag

**Comment by paradadf** [comment]
+1

**Comment by mxjoe** [comment]
+1

**Comment by digitalLumberjack** [comment]
should be ok with https://github.com/recalbox/recalbox-emulationstation/pull/77

**Comment by digitalLumberjack** [comment]
to test on next build

**Comment by digitalLumberjack** [comment]
@substring @rockaddicted @sveetch are we ok with that ?

**Comment by rockaddicted** [comment]
tested with snes roms, ok for me.

**Comment by substring** [comment]
@digitalLumberjack 
not ok. Images are in downloaded_images/system instead of downloaded_images/

**Comment by rockaddicted** [comment]
** rockaddicted clean his glasses **
haha indeed `downloaded_images/system`

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-emulationstation/pull/81

**Comment by substring** [comment]
Perfect !
