### ISSUE TITLE
Old computers support

### ISSUE THREAD

**Issue by adolfobenjaminv** [recalbox/recalbox-os#677]
Please, add this, computers like commodore 64, and zx spectrum had amazing games and are part of the retro game comunity, please and support for those great machines

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-os/issues/331
https://github.com/recalbox/recalbox-os/issues/305
https://github.com/recalbox/recalbox-os/issues/232
https://github.com/recalbox/recalbox-os/issues/158

**Comment by adolfobenjaminv** [comment]
Im sorry....so...this is a yes...?
