### ISSUE TITLE
Better Psx and Cd Engine Compatibility

### ISSUE THREAD

**Issue by adolfobenjaminv** [recalbox/recalbox-os#679]
I actually can't make work any of the cd engine games, i tried with a lot (i installed the bios that said in the read- me document and checked the checksum and everything but.....it just doesnt work.
Please, i really want to play Chi No rondo on the Raspberry

**Comment by rockaddicted** [comment]
If your bios are ok, please try an other iso.
This game work very well on my recalbox.

If you have other issues, please use the recalbox's forum to ask help. http://blog.recalbox.com/forums/
Github is a place reserved to talk about dev issues.
