### ISSUE TITLE
[4.0.0][3.3.0-beta17] Sound setting bug

### ISSUE THREAD

**Issue by renaiku** [recalbox/recalbox-os#680]
I don't know if it still happens in the v4 but here we go:

Start -> Sound Settings -> Button Back -> repeat.

The system sound loose 1% each time.

So to set the volume to 60, you have to set iot to 61 before hitting back.

**Comment by substring** [comment]
confirmed on 4.0.0

**Comment by nadenislamarre** [comment]
fixed. Can somebody confirm and close ?

**Comment by renaiku** [comment]
Closing ...
That was a quick fix !
