### ISSUE TITLE
[3.3.0-beta17] n64 games failed to start - return to ES with changed resolution

### ISSUE THREAD

**Issue by fetenete** [recalbox/recalbox-os#681]
Hi guys,
I’ve recently been setting my Raspberry 2 (overclocked) up with Recalbox. 
I tried adding some N64 roms, and all four will not play; instead, when selected, the screen blacks out for ~5 or so seconds, then it goes back to the ES like it didn’t run, but the resolution of my display changed accordingly to the resolution I configured in recalbox.conf
I tried all 3 core-plugins (gliden64,n64,rice). My monitor is supporting the video mode DMT 9 HDMI (checked that one with "tvservice" ). Nevertheless I tried different resolutions... none of them worked.
I also tried several roms from different sources.. same result.
Do you have an idea of what else could I try?

Thanks

**Comment by rockaddicted** [comment]
weird...
have you unzipped your roms ?

**Comment by fetenete** [comment]
Yes I have unzipped the roms.. I tried .n64 and .v64 both were not working

**Comment by rockaddicted** [comment]
so should work.
can you try others roms, from others sources.

**Comment by fetenete** [comment]
I already did but I can continue to try. Can you recommend a site from where one get properly working roms?

**Comment by rockaddicted** [comment]
I'm using roms from no-intro romset.

**Comment by fetenete** [comment]
Okay thanks for that! I will try this.
In the meantime - can you tell me if there are any logs written as I'm starting a n64 game? Maybe I can do a little root cause analysis

**Comment by substring** [comment]
You can check recalbox.log and ~/.emulationstation/es_log.txt

**Comment by fetenete** [comment]
Here is an output of the es_log.txt (As I am trying to start a N64 game)

lvl2:   SDL AUDIO Initialized
lvl2:   playing
lvl2:   Attempting to launch game...
lvl2:   Shutting down SDL AUDIO
lvl2:   No config for player 0
lvl2:   No config for player 1
lvl2:   No config for player 2
lvl2:   No config for player 3
lvl2:   Configure emulators command :
lvl2:   Controllers config :
lvl2:           python /usr/lib/python2.7/site-packages/configgen/emulatorlauncher.pyc  -system n64 -rom /recalbox/share/roms/n64/Diddy\ Kong\ Racing.n64
lvl1:   ...launch terminated with nonzero exit code 256!
lvl2:   Creating surface...
lvl2:   Created window successfully.
lvl2:   Added unconfigured joystick Microsoft Microsoft® 2.4GHz Transceiver v7.0 (GUID: 030000005e0400004507000011010000, instance ID: 0, device index: 0).
lvl2:   SDL AUDIO Initialized
lvl2:   playing

Here you can see that the emulator launcher script throws an exit code 256.
I am using my keyboard as a temporary controller.. maybe this is related to the exit code in some way.. 
Do you have experience with configgen scripts?
What do you think could be my problem?

**Comment by substring** [comment]
I write configgen scripts, that's why i would need the recalbox.log
Mario 64 works fine (Europe and US, for sure)

**Comment by fetenete** [comment]
Issue can be closed!
After some hours of searching I took a look at the roms itself...
I think one of my udev-rules messed up the rights -.- fuuuuuuuuuuuuuuuu 
After a chmod 644 everything worked as it should. 
The problem always sits in front of the monitor... :rage:
