### ISSUE TITLE
Fails to boot - Nightly [4.0.0] RPi 2 - 14.2.16

### ISSUE THREAD

**Issue by mspacemedia** [recalbox/recalbox-os#686]
Updated to nightly - 14.2.16 and now on restart I am shown the colour gradients and nothing more. I had also changed the overclock setting to 1100mhz so cannot be sure whether that is in play too. Is there a way to change the overclock/recover the install by mounting the SDCard on a Linux box?

**Comment by substring** [comment]
Sure you can. Edit /boot/config.txt and manually restore original frequencies. I don't have them at hand for now, but tell me if you need

**Comment by mspacemedia** [comment]
Thanks @substring I'll take a look and see - hopefully setting it back to 900mhz will fix the boot issue when I find it in the config.txt :D

**Comment by mspacemedia** [comment]
@substring unfortunately having reset the default clock speeds and frequencies, it still gets stuck on the colour gradient. Very frustrating!

**Comment by substring** [comment]
I can only suggest you to get the last nightly and burn it again on your sd. You'll lose all your data but hey ! It's not a stable version yet ! Enjoy the thrill of the development stage ;)

**Comment by mspacemedia** [comment]
@substring indeed :D
