### ISSUE TITLE
Trust 17772 Bluetooth

### ISSUE THREAD

**Issue by burnziii** [recalbox/recalbox-os#688]
Could you please add support for the trust 17772 bluetooth 3.0 nano adapter?
You need to add ath3k-1.fw for atheros based bt adapters then it will be supported and works fine..

**Comment by rockaddicted** [comment]
Do your have a link to add this firmware ?

**Comment by burnziii** [comment]
you should find further information there..

https://wireless.wiki.kernel.org/en/users/drivers/ath3k

i downloaded it from there: https://forum.ubuntuusers.de/topic/bluetooth-laesst-sich-nicht-einschalten-4/2/

but the kernel.org link should work too

**Comment by rockaddicted** [comment]
did you try on recalbox 4.0.0 ?

**Comment by burnziii** [comment]
Not yet.. But maybe at the weekend

Von meinem iPhone gesendet

**Comment by nadenislamarre** [comment]
the driver is in the 4.1.

**Comment by nadenislamarre** [comment]
the ./ath3k-1.fw firmware
