### ISSUE TITLE
[4.0.0 theme] Music playlist

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#689]
When a theme doesn't have a music tag in its xml, i need the musicmanager to seek for musics in a directory and play random music.

**Comment by mgoulartBR** [comment]
Could add a option to disable bg music on ES? My wife hates it! lol

I installed a custom theme called Eudora just because there are no bg music!

**Comment by digitalLumberjack** [comment]
@mgoulartBR there is an option since the v3.1 in soud settings :P

**Comment by mgoulartBR** [comment]
I miss that one! lol

I will check it!

On Mon, Feb 15, 2016 at 9:12 PM, digitalLumberjack <notifications@github.com

**Comment by digitalLumberjack** [comment]
add support for mp3 and ogg

**Comment by digitalLumberjack** [comment]
done
