### ISSUE TITLE
Can't SSH onto recalbox via Cyberduck or Transmit on a mac

### ISSUE THREAD

**Issue by Nutcasey** [recalbox/recalbox-os#69]
This doesn't allow me to connect via the above GUI clients on a mac. I can connect via the terminal though.

**Comment by hstampfl** [comment]
the error message we get is: EOF while reading packet.

**Comment by Nutcasey** [comment]
Yeah that is what I always see if I use Cyberduck. With other clients I can't even connect.

**Comment by Nutcasey** [comment]
Is there any update on this? I still can't use SSH on a Mac with any client.

**Comment by hstampfl** [comment]
you mean the filetransfer stuff, don't you? 
vSSH for the SSH terminal is working fine for me

**Comment by hstampfl** [comment]
but no,, there are no updates. I read some comments in forums,, that this also can be on the client side.... but I am more investigating it over the weekend

**Comment by hstampfl** [comment]
it looks that there is no sftp-server implemented. 
- - -
MacBook-Pro-2:~ hstampfl$ sftp root@192.168.12.182:/etc/init.d/S60nfs .`
root@192.168.12.182's password:
sh: /usr/libexec/sftp-server: not found
Connection closed
- - -
when I use `scp root@192.168.12.182:/etc/init.d/S60.nfs .` it works and I do get the file downloaded

**Comment by substring** [comment]
The sftp server has been implemented in 4.0.0 https://github.com/recalbox/recalbox-buildroot/commit/1f1e8378bbc7691c801dfa6e40ae01a8efcca040

@rockaddicted @digitalLumberjack issue can be closed

**Comment by rockaddicted** [comment]
:+1:
