### ISSUE TITLE
When comes Kodi Isengard?

### ISSUE THREAD

**Issue by bogi1102** [recalbox/recalbox-os#695]
When comes Kodi Isengard or there is already a possibility to update manuel? In the last post we have spoken that it should come from 3.3.1.
And we have supported the NES30Pro in Kodi?

**Comment by substring** [comment]
@bogi1102 Kodi 15.2 is in recalbox v4.0.0
I guess nes30pro works with it

**Comment by bogi1102** [comment]
What firmware from NES30 Pro currently supports Reclabox
