### ISSUE TITLE
EmuX?

### ISSUE THREAD

**Issue by mgoulartBR** [recalbox/recalbox-os#696]
Guys,

I saw a libretro core for EmuX. I tried to find some informations about it but I didn't find anything relevant. My question is if this core can bring new systems to Recalbox?

https://github.com/libretro/emux

**Comment by substring** [comment]
@mgoulartBR I don't really see the difference between EmuX and retroarch. Could you  tell us more ?

**Comment by mgoulartBR** [comment]
I don't know if there are major differences between both of them. I tried to find some emulable systems on EmuX that it's impossible to emulate on RetroArch but i didn't find anything about it. I will close it for while
