### ISSUE TITLE
add a virtual keyboard to ES

### ISSUE THREAD

**Issue by bogi1102** [recalbox/recalbox-os#697]
pop up window data at input the Wifi?
to enter here with the controller, the data can.

**Comment by substring** [comment]
I'm not sure i understood exactly what you meant. English is not your native tongue i guess ?

**Comment by bogi1102** [comment]
That would be a suggestion here. A pop-up window in the Recalbox when entering the login information for the Wi-Fi. So you need here no keyboard but it may be the same enter with a controller.
The code for this is not very complicated.

**Comment by digitalLumberjack** [comment]
@bogi1102 are you talking about a virtual keyboard ?

**Comment by substring** [comment]
And how would you type your ssid and your password ?

**Comment by bogi1102** [comment]
Yes a virtual keyboard

**Comment by bogi1102** [comment]
As already written to the controller is connected. It was just a suggestion if this is possible

**Comment by substring** [comment]
Need to code a virtual keyboard, define it according to locales, make it browsable for the pad etc ...
Whereas you can just edit your recalbox.conf file to setup your wifi ! Or you can just connect to recalbox manager and edit the file from there
So I guess that's something that we won't add yet

**Comment by roba91** [comment]
paradadf found a [fork](https://github.com/jacobfk20/EmulationStation-RPiE) of ES that has an onscreen keyboard (OSK) implemented (s. [forum post](https://forum.recalbox.com/topic/3482/virtual-keyboard/13)). Maybe you can copy the implementation of the OSK or even more as this fork seem to have a bunch of nice features.

**Comment by rockaddicted** [comment]
done

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-emulationstation/pull/154
