### ISSUE TITLE
[4.0.0] Loopback is not started

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-os#698]
I couldn't ping or curl on localhost. And guess what ? ifconfig doesn't report the loopback interface. Doing an `ifup lo` brings it up. But it should be started by default whether you have network (let it be ethernet or wifi) or not.

**Comment by nadenislamarre** [comment]
yes, that's true.
i guess it's my fault.
I replaced something like :

ifup -a
ifup eth0
ifup wlan0

by

ifup eth0
ifup wlan0

it should be added in teh S4xnetwork at the top.

**Comment by substring** [comment]
solved with the above PR
