### ISSUE TITLE
Kodi + Manette PS4

### ISSUE THREAD

**Issue by St4lker** [recalbox/recalbox-os#707]
Bonjour,

Lorsque ma manette de PS4 branchée en usb sur le pi 2 je n’ai aucun problème à jouer aux jeux sur recalbox. Par contre quand je switch sur Kodi j’ai le volume qui descend tout seul et la barre reste tout le temps affichée comme si j’avais un bouton de bloqué …

J’ai essayé avec ma manette de Xbox 360 et je n’ai pas ce problème.

Merci pour Recalbox !

**Comment by nadenislamarre** [comment]
quelle version de recalbox ? peux tu essayer avec la version en cours de
dev 4.0.0 ?

**Comment by St4lker** [comment]
J'ai la version 3.3.0. Je vais essayer avec la 4.0.0 rapidement et je vous fais un retour.

Merci

**Comment by rockaddicted** [comment]
la beta1 de la 4.0.0 vient tout juste de sortir : https://github.com/recalbox/recalbox-os/releases/tag/4.0.0-beta1

**Comment by St4lker** [comment]
Merci rockaddicted, je teste ça rapidement

**Comment by mxjoe** [comment]
I don't understand any French, but if the idea is to use the PS4 Controller for controlling Kodi, I like the idea! ;-)

**Comment by St4lker** [comment]
Des nouvelles concernant ce problème pour ceux qui le suivent.

J'ai testé la version 4.0.0 beta 1 et là le problème est tout autre. Lorsque je lance kodi sans manette branchée, il se lance correctement par contre dès que je branche ma manette PS4, je repasse sur la station d'émulation et impossible de relancer Kodi (Affichage du logo puis retour sur la station d'émulation).

Je suis les sujets suivant qui traite de ce souci:
https://github.com/recalbox/recalbox-os/issues/726

**Comment by nadenislamarre** [comment]
duplicated with #726.
status updated in #726 for tests.
