### ISSUE TITLE
Final Fantasy 3/6 Music is wrong (SNES emulator)

### ISSUE THREAD

**Issue by Nutcasey** [recalbox/recalbox-os#71]
When playing this the sound seems off compared to other emulators that I have tried before. Is this to do with the chosen core that is being used?

**Comment by rockaddicted** [comment]
Try to switch snes emulator with the recalbox.conf file https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-%28EN%29
Tell us if it is ok when you are using snes9x or catsfc as snes's emulator.

**Comment by nadenislamarre** [comment]
no feedback after monthes => i close.
