### ISSUE TITLE
Add power on/off script 

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#710]
PIN 5/6 can power on a sleeping rpi. The script would use the pin 5/6 to detect an edge, shutdown, and then the next press on the button would wake up the rpi

**Comment by LaurentMarchelli** [comment]
I'm working on a script that will support several switch off buttons, this feature could be added to it.

**Comment by ziviani** [comment]
The best way is use 'PIN5/6' aka 'GPIO3' and 'GROUND' to shut down and power on the RPi safely, as described here:
http://www.philtopia.com/?p=1823
I tested this script: https://github.com/CrazySpence/Adafruit-Retrogame/blob/master/retrogame-xbmc.c successfully. 
I really want to use this in Recalbox, but it's not possible since there is no way to compile in a buildroot system.
Is there a way to help me out?

**Comment by LaurentMarchelli** [comment]
I guess it is not that simple.
- You have to check if the SDL 2.0 version we use in the same.
- Check if the SDL 2.0 patch is already applied on our buildroot. 
- Check if uinput is a part of the current buildroot config.
- As your module is specific to a hardware, it not should be lauched systematically from the boot, so you have to find a way to detect the configuration before launching it.
- You have to check if there is no side effects on others components (EmulationStation, others emulators, ...)
- You have to define a buildroot package, as the makefile is simple, it is mainly the easier part.

On which hardware did you test it ?

**Comment by digitalLumberjack** [comment]
https://github.com/g0to/misc_scripts/blob/master/raspi_gpio_actions.sh
This is suffisent. It can be modified to use wiringpiu or Python GPIO.Rpi.
The only thing is that we have to code for 2 type of buttons : 
The press button (that switch the gpio state to 0 for just a time)
The on / off state button, that is always connecting the gpio to the ground while running, and "disconnect" the contact when the user want to shutdown. (so we must use the internal pullups of the gpio)

**Comment by ziviani** [comment]
I tested in a Raspberry Pi 1 Model B and in a Raspberry 2, using Retropie as a distro. It was so simple, and it works.

Enviado do Outlook Mobile<https://aka.ms/xp9y6l>

De: Laurent Marchelli
Enviado: sexta-feira, 25 de mar?o 06:33
Assunto: Re: [recalbox-os] Add power on/off script  (#710)
Para: recalbox/recalbox-os
Cc: Ziviani

I guess it is not that simple.

You have to check if the SDL 2.0 version we use in the same.Check if the SDL 2.0 patch is already applied on our buildroot. Check if uinput is a part of the current buildroot config.As your module is specific to a hardware, it not should be lauched systematically from the boot, so you have to find a way to detect the configuration before launching it.You have to check if there is no side effects on others components (EmulationStation, others emulators, ...)You have to define a buildroot package, as the makefile is simple, it is mainly the easier part.

On which hardware did you test it ?

-

**Comment by LaurentMarchelli** [comment]
I guess it was, retropie is not recalbox.
Retropie is a raspian, with installation scripts.
Recalbox is a Linux built from build root.
In recalbox, we select with buildroot, only what we need, to have the most optimized system.

**Comment by ziviani** [comment]
Thanks digitalLumberjack!!!




________________________________
De: digitalLumberjack <notifications@github.com>
Enviado: sexta-feira, 25 de março de 2016 12:46
Para: recalbox/recalbox-os
Cc: Ziviani
Assunto: Re: [recalbox-os] Add power on/off script (#710)


https://github.com/g0to/misc_scripts/blob/master/raspi_gpio_actions.sh

[https://avatars0.githubusercontent.com/u/4366508?v=3&s=400]<https://github.com/g0to/misc_scripts/blob/master/raspi_gpio_actions.sh>

g0to/misc_scripts<https://github.com/g0to/misc_scripts/blob/master/raspi_gpio_actions.sh>
github.com
misc_scripts - A humble collection of tiny programs written in scripting languages. A small, home brewed Swiss knife for the daily needs and task automation



This is suffisent. It can be modified to use wiringpiu or Python GPIO.Rpi.
The only thing is that we have to code for 2 type of buttons :
The press button (that switch the gpio state to 0 for just a time)
The on / off state button, that is always connecting the gpio to the ground while running, and "disconnect" the contact when the user want to shutdown. (so we must use the internal pullups of the gpio)

-

**Comment by ziviani** [comment]
It's not necessary to explain me the obvious. I just intended to get a feature that I think some people would like to have in RecalboxOS.


________________________________
De: Laurent Marchelli <notifications@github.com>
Enviado: sexta-feira, 25 de março de 2016 19:24
Para: recalbox/recalbox-os
Cc: Ziviani
Assunto: Re: [recalbox-os] Add power on/off script (#710)

I guess it was, retropie is not recalbox.
Retropie is a raspian, with installation scripts.
Recalbox is a Linux built from build root.
In recalbox, we select with buildroot, only what we need, to have the most optimized system.


> Le 25 mars 2016 à 23:15, Ziviani <notifications@github.com> a écrit :
>
> I tested in a Raspberry Pi 1 Model B and in a Raspberry 2, using Retropie as a distro. It was so simple, and it works.
>
> Enviado do Outlook Mobile<https://aka.ms/xp9y6l>
>
> De: Laurent Marchelli
> Enviado: sexta-feira, 25 de mar?o 06:33
> Assunto: Re: [recalbox-os] Add power on/off script (#710)
> Para: recalbox/recalbox-os
> Cc: Ziviani
>
> I guess it is not that simple.
>
> You have to check if the SDL 2.0 version we use in the same.Check if the SDL 2.0 patch is already applied on our buildroot. Check if uinput is a part of the current buildroot config.As your module is specific to a hardware, it not should be lauched systematically from the boot, so you have to find a way to detect the configuration before launching it.You have to check if there is no side effects on others components (EmulationStation, others emulators, ...)You have to define a buildroot package, as the makefile is simple, it is mainly the easier part.
>
> On which hardware did you test it ?
>
> -
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub<https://github.com/recalbox/recalbox-os/issues/710#issuecomment-201220477>
>
>
> -
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
>

-
