### ISSUE TITLE
Add a progress bar during the upgrade

### ISSUE THREAD

**Issue by neolao** [recalbox/recalbox-os#711]
It would be nice for slow internet connections

**Comment by Laddyacris** [comment]
Salut
lors du téléchargement c est noté en cours sous ES c'est vrai qu une progress bar serait mieux.
Pour info au redémarrage pour la mise à jour , tu as le pourcentage en haut à gauche de l écran.

**Comment by mxjoe** [comment]
I also like the idea of a progress bar. It's not very important but nice to have.

+1

**Comment by codingHahn** [comment]
+1

**Comment by fouroh3** [comment]
+1

**Comment by substring** [comment]
please use the new github option to show you like this instead of posting new comments

**Comment by paradadf** [comment]
Duplicate: https://github.com/recalbox/recalbox-os/issues/195

**Comment by rockaddicted** [comment]
ok so I close this one, thx
