### ISSUE TITLE
Allow recalbox to connect to hidden SSIDs

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-os#712]
Hidden SSIDs WIFI require `scan_ssid=1` in `/etc/wpa_supplicant/wpa_supplicant.conf`

Maybe the best is to activate it by default ? I don't think it will have an impact on performances

**Comment by nadenislamarre** [comment]
yes. it just require a test.

**Comment by nadenislamarre** [comment]
substring, can you do a test in 4.1 please and make a feedback ?

**Comment by silentflight15** [comment]
Is there a work-around for now regarding hidden SSIDs?

**Comment by nadenislamarre** [comment]
to be tested in 4.1 while it uses connman now to connect.

**Comment by nadenislamarre** [comment]
@substring can you test if that works for you in 4.1 or i close. (it is supposed to work)
