### ISSUE TITLE
Autoconnection of WiFi at startup fails

### ISSUE THREAD

**Issue by mxjoe** [recalbox/recalbox-os#713]
Since Recalbox my Realtek R8188EU based WiFi dongle is correctly recognized, thank you! Great job!

BUT ;-) autoconnect to my WiFi network after startup is not working.
I can connect Recalbox via the WiFi dongle to my network but when I restart it cannot connect automatically. I need to disable and enable the WiFi of Recalbox after every startup to make it connect to my WiFi network.

I consider this as a bug.

Below the data of recalbox.log:

[       20.35] : starting new log
[       20.38] : converting dos to unix carriage return characters
[       21.10] : setting hostname to RECALBOX
[       21.12] : setting audio volume to 90
[       21.14] : setting audio to auto
---- recalbox-config.sh ----
---- recalbox-config.sh ----
[       21.23] : setting audio volume : 90
[       21.25] : setting audio output mode : auto
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
  : values=0
Simple mixer control 'PCM',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback -663 [90%] [-6.63dB] [on]
[       21.39] : setting keyboard layout to en
[       22.03] : starting emulationstation with lang = en_US
[       22.06] : Starting emulationstation with command : 
[       22.08] : HOME=/recalbox/share/system LANG="en_US.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation; [ -f /tmp/shutdown.please ] && (rm /tmp/shutdown.please; shutdown -h now);[ -f /tmp/reboot.please ] && (rm /tmp/reboot.please; shutdown -r now)
---- recalbox-config.sh ----
udhcpc (v1.24.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, failing
---- recalbox-config.sh ----
[       36.74] : wlan0 be used as wifi interface
---- recalbox-config.sh ----
[       39.88] : Starting S94manager
Will not start pm2 : system.api.enabled is set to 0
Powering on HDMI with explicit settings (CEA mode 4)
[        3.40] : starting new log
[        3.42] : converting dos to unix carriage return characters
[        4.17] : setting audio to auto
[        4.18] : setting hostname to RECALBOX
---- recalbox-config.sh ----
[        4.26] : setting audio volume to 91
[        4.29] : setting audio output mode : auto
---- recalbox-config.sh ----
[        4.37] : setting audio volume : 91
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
  : values=0
Simple mixer control 'PCM',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback -557 [91%] [-5.57dB] [on]
[        4.50] : setting keyboard layout to en
[        5.13] : starting emulationstation with lang = en_US
[        5.16] : Starting emulationstation with command : 
[        5.18] : HOME=/recalbox/share/system LANG="en_US.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation; [ -f /tmp/shutdown.please ] && (rm /tmp/shutdown.please; shutdown -h now);[ -f /tmp/reboot.please ] && (rm /tmp/reboot.please; shutdown -r now)
---- recalbox-config.sh ----
udhcpc (v1.24.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, failing
---- recalbox-config.sh ----
[       20.79] : wlan0 be used as wifi interface
---- recalbox-config.sh ----
---- recalbox-config.sh ----
[       24.06] : Starting S94manager
---- recalbox-config.sh ----
Will not start pm2 : system.api.enabled is set to 0
---- recalbox-config.sh ----
[       65.98] : wlan0 be used as wifi interface
[       66.01] : enabling wifi
[       66.04] : creating network entry in /var/lib/wpa_supplicant.conf
[       66.09] : starting wifi
Successfully initialized wpa_supplicant
Line 5: Invalid passphrase length 0 (expected: 8..63) '"'.
Line 5: failed to parse psk '""'.
Line 6: failed to parse network block.
Failed to read or parse configuration '/var/lib/wpa_supplicant.conf'.
Successfully initialized wpa_supplicant
Line 5: Invalid passphrase length 0 (expected: 8..63) '"'.
Line 5: failed to parse psk '""'.
Line 6: failed to parse network block.
Failed to read or parse configuration '/var/lib/wpa_supplicant.conf'.
udhcpc (v1.24.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, failing
---- recalbox-config.sh ----
---- recalbox-config.sh ----
[      171.10] : Stopping S94manager
[        3.03] : starting new log
[        3.05] : converting dos to unix carriage return characters
[        3.79] : setting audio to auto
[        3.79] : setting hostname to RECALBOX
[        3.80] : setting audio volume to 91
---- recalbox-config.sh ----
---- recalbox-config.sh ----
[        3.90] : setting audio output mode : auto
[        3.94] : setting audio volume : 91
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
  : values=0
Simple mixer control 'PCM',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback -557 [91%] [-5.57dB] [on]
[        4.12] : setting keyboard layout to de
Loading /usr/share/keymaps/i386/qwertz/de.map.gz
[        4.75] : starting emulationstation with lang = de_DE
[        4.77] : Starting emulationstation with command : 
[        4.80] : HOME=/recalbox/share/system LANG="de_DE.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation; [ -f /tmp/shutdown.please ] && (rm /tmp/shutdown.please; shutdown -h now);[ -f /tmp/reboot.please ] && (rm /tmp/reboot.please; shutdown -r now)
---- recalbox-config.sh ----
udhcpc (v1.24.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, failing
---- recalbox-config.sh ----
[       20.37] : wlan0 be used as wifi interface
[       20.61] : starting wifi
---- recalbox-config.sh ----
udhcpc (v1.24.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, failing
[       53.47] : Starting S94manager
Will not start pm2 : system.api.enabled is set to 0
---- recalbox-config.sh ----
[      260.04] : wlan0 be used as wifi interface
[      260.07] : enabling wifi
[      260.10] : creating network entry in /var/lib/wpa_supplicant.conf
[      260.15] : starting wifi
Successfully initialized wpa_supplicant
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
wlan0: Failed to initialize driver interface
Successfully initialized wpa_supplicant
ioctl[SIOCSIWAP]: Operation not permitted
wlan0: Trying to associate with 34:31:c4:62:22:46 (SSID='JFB' freq=2462 MHz)
wlan0: Associated with 34:31:c4:62:22:46
wlan0: WPA: Key negotiation completed with 34:31:c4:62:22:46 [PTK=CCMP GTK=CCMP]
wlan0: CTRL-EVENT-CONNECTED - Connection to 34:31:c4:62:22:46 completed [id=0 id_str=]
udhcpc (v1.24.1) started
Sending discover...
Sending select for 192.168.178.29...
Lease of 192.168.178.29 obtained, lease time 864000
deleting routers
adding dns 192.168.178.1
          inet addr:192.168.178.29  Bcast:192.168.178.255  Mask:255.255.255.0
PING recalbox.com (94.23.55.163): 56 data bytes
64 bytes from 94.23.55.163: seq=0 ttl=57 time=14.394 ms

--- recalbox.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 14.394/14.394/14.394 ms
---- recalbox-config.sh ----
no update available
lo IP Address 127.0.0.1
lo IP Address ::1
lo IP Address 127.0.0.1
wlan0 IP Address 192.168.178.29
[      285.06] : Stopping S94manager
wlan0: CTRL-EVENT-DISCONNECTED bssid=34:31:c4:62:22:46 reason=3 locally_generated=1
ioctl[SIOCSIWAP]: Operation not permitted
wlan0: CTRL-EVENT-TERMINATING 
[        2.97] : starting new log
[        3.00] : converting dos to unix carriage return characters
[        3.78] : setting audio to auto
[        3.82] : setting hostname to RECALBOX
---- recalbox-config.sh ----
[        3.86] : setting audio volume to 91
[        3.91] : setting audio output mode : auto
---- recalbox-config.sh ----
[        3.98] : setting audio volume : 91
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
  : values=0
Simple mixer control 'PCM',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback -557 [91%] [-5.57dB] [on]
[        4.10] : creating network entry in /var/lib/wpa_supplicant.conf
[        4.15] : updated wifi settings : ssid=JFB key=XXX
[        4.17] : setting keyboard layout to de
Loading /usr/share/keymaps/i386/qwertz/de.map.gz
[        4.74] : starting emulationstation with lang = de_DE
[        4.77] : Starting emulationstation with command : 
[        4.79] : HOME=/recalbox/share/system LANG="de_DE.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation; [ -f /tmp/shutdown.please ] && (rm /tmp/shutdown.please; shutdown -h now);[ -f /tmp/reboot.please ] && (rm /tmp/reboot.please; shutdown -r now)
---- recalbox-config.sh ----
udhcpc (v1.24.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, failing
---- recalbox-config.sh ----
[       19.49] : wlan0 be used as wifi interface
[       19.73] : starting wifi
---- recalbox-config.sh ----
udhcpc (v1.24.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, failing
[       53.26] : Starting S94manager
Will not start pm2 : system.api.enabled is set to 0
---- recalbox-config.sh ----
---- recalbox-config.sh ----
---- recalbox-config.sh ----
[       71.52] : wlan0 be used as wifi interface
---- recalbox-config.sh ----
[       75.56] : wlan0 be used as wifi interface
[       75.58] : enabling wifi
network={
[       75.65] : starting wifi
Successfully initialized wpa_supplicant
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
wlan0: Failed to initialize driver interface
Successfully initialized wpa_supplicant
ioctl[SIOCSIWAP]: Operation not permitted
wlan0: Trying to associate with 34:31:c4:62:22:46 (SSID='JFB' freq=2462 MHz)
wlan0: Associated with 34:31:c4:62:22:46
wlan0: WPA: Key negotiation completed with 34:31:c4:62:22:46 [PTK=CCMP GTK=CCMP]
wlan0: CTRL-EVENT-CONNECTED - Connection to 34:31:c4:62:22:46 completed [id=0 id_str=]
udhcpc (v1.24.1) started
Sending discover...
Sending select for 192.168.178.29...
Lease of 192.168.178.29 obtained, lease time 864000
deleting routers
adding dns 192.168.178.1
          inet addr:192.168.178.29  Bcast:192.168.178.255  Mask:255.255.255.0
PING recalbox.com (94.23.55.163): 56 data bytes
64 bytes from 94.23.55.163: seq=0 ttl=57 time=16.056 ms

--- recalbox.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 16.056/16.056/16.056 ms
---- recalbox-config.sh ----
no update available

**Comment by nadenislamarre** [comment]
on my todo list i have to check about network manager to get a bztter
connectivity

**Comment by mxjoe** [comment]
Thanks nadenislamarre, sounds good. If I can assist with anything please let me know.

**Comment by nadenislamarre** [comment]
Just, it's not for now except if somebody takes it before  ; i've several
things before in my todo list

**Comment by substring** [comment]
Wifi used to work fine on my pi0 so far, or i couldn't ssh to it. Knowing there is just 1 usb port ...

**Comment by nadenislamarre** [comment]
ssh -E -F -p 1234 gives an error ?

**Comment by substring** [comment]
i guess i wan't clear on my last comment. Wifi works perfect on my Pi0, and reconnects at boot. No issue

**Comment by nadenislamarre** [comment]
should be ok in 4.1 with the new network configuration manager.
Wait 4.1 beta and make a feedback please, so that we can close this one.

**Comment by mxjoe** [comment]
Thanks, I'll keep you updated.

**Comment by Tony322** [comment]
I have the same issue. Fresh install on a RPI 3 model B. Version 4.0.2. 
I was this was posted in 2016, and it's 2017 now and I can't find the 4.1 version on the github.
