### ISSUE TITLE
[FIXED][4.0.0]Audio Jack Problem

### ISSUE THREAD

**Issue by Androsyn31** [recalbox/recalbox-os#714]
In the last release, 
no sound output jack , also the system volume starts systematically 0

**Comment by nadenislamarre** [comment]
Hum, can you check the /boot/config.txt please.
In last releases, hdmi is forced, so for jack output you've to configure it.
I've used it recently, so, i guess it works with the correct configration.

**Comment by digitalLumberjack** [comment]
Yes must be corrected for 4.0.0. We lost a feature by forcing hdmi.

**Comment by nadenislamarre** [comment]
Which feature did we lost ?
Le 24 févr. 2016 19:08, "digitalLumberjack" <notifications@github.com> a
écrit :

**Comment by digitalLumberjack** [comment]
setting the jack output in es :)

**Comment by nadenislamarre** [comment]
You mean you have to reboot once force hdmi is removed ?
Le 24 févr. 2016 19:15, "digitalLumberjack" <notifications@github.com> a
écrit :

**Comment by digitalLumberjack** [comment]
i mean the feature do not work now, and i don't know how to correct that. If we set the hdmi_force on/off when the user is changing this setting, that may break it's configuration (i would set hdmi_force to 0, but it would be set to 1)

**Comment by substring** [comment]
it does work on my beta with `amixer cset numid=3 1`
see https://www.raspberrypi.org/documentation/configuration/audio-config.md

**Comment by Androsyn31** [comment]
I think I identify the problem .The problem  Appear if pass the storage in external . Once selected external storage, all parameters recovers by default and no changes are 
taken into account

**Comment by substring** [comment]
Mmhhh gotra check that ... It would mean your usb device is mounted too late and the system can't setup itself according to your recalbox.conf

Anyway, well done for troubleshouting dude :)

**Comment by substring** [comment]
Final word : @Androsyn31 was using a USB dock with sound.
