### ISSUE TITLE
[4.0.0] Scraper does not recognize any games

### ISSUE THREAD

**Issue by Niehztog** [recalbox/recalbox-os#715]
Hello,

I just made a fresh install of the new 4.0.0 beta1 on my raspberry pi 2. I copied all roms on the sdcard via smb share. But the scraper function in emulationstation does not find any games. I can see the rom filenames only.

This always worked in the latest v3.3.0-beta-17. Mus be a new bug?

**Comment by rockaddicted** [comment]
Hello, the website http://thegamesdb.net used to scrape is down since a few days. Must be patient...
