### ISSUE TITLE
In es ,can not input any letter

### ISSUE THREAD

**Issue by tlanks** [recalbox/recalbox-os#717]
Once  setup wifi ssid in es , U can not input any letter

**Comment by paradadf** [comment]
Had the same problem. After entering Kodi and going back to ES, it worked.

**Comment by substring** [comment]
@tlanks what recalbox version are you using ? I've had the same problem a few times without being able to reproduce it as i'd wished

**Comment by tlanks** [comment]
4.0-b1

**Comment by nadenislamarre** [comment]
fixed for the next nighly.
It's a ttry issue.
Please don't close, i would like to find the program is causing the issue to be sure there is no other problem to fix.

**Comment by digitalLumberjack** [comment]
@paradadf is it ok with the beta 2 ?

**Comment by digitalLumberjack** [comment]
@tlanks ?

**Comment by paradadf** [comment]
@digitalLumberjack yes, it works now ootb

**Comment by digitalLumberjack** [comment]
so we can close :) thanks @nadenislamarre 
and thanks everyone
