### ISSUE TITLE
Some Games didn't work on playstation plataform

### ISSUE THREAD

**Issue by topete2** [recalbox/recalbox-os#718]
I would like to know why some games dont work on playstation plataform, like diablo ( the controllers dont work, start botton dont work to star the game) and Gran Turismo 2 ( freeze on the start screen)...
What are the best forms to work the major of Roms of ARCADE (MAME and others)? some roms works but, others dont works. Thanks a lot, and congratulations for You do the joy of us,addicted to games.

**Comment by Laddyacris** [comment]
Hello
please use forum for your problems,
