### ISSUE TITLE
Playstation music tracks

### ISSUE THREAD

**Issue by KroKis27** [recalbox/recalbox-os#721]
In recalbox 3.3 beta 17 sleedstorm music tracks works and sounds, but in recalbox 4.0 music tracks don't sound, only fx game sounds.

**Comment by substring** [comment]
@KroKis27 could you tell me which game, and which format (cue/bin or iso or ...)
As far as we have tested it was working fine

**Comment by KroKis27** [comment]
Hi

 Game is "Sleed Storm" in CUE/BIN format. Recalbox 3.3 play game soundtrack perfect, 
In recalbox 4.0 only sounds FX, soundtracks don't play...

**Comment by ElMeteK** [comment]
Same prob here with Destruction Derby 2 BIN/CUE.

**Comment by rockaddicted** [comment]
@KroKis27 : you are using files with extension in uppercase (.BIN/.CUE), right ?
Can you try to rename your files with an extension in lowercase, (.bin/.cue), then retry.

**Comment by KroKis27** [comment]
Yes, i rename CUE/BIN to lowercase and now music tracks works perfects!!! 
@rockaddicted THANKS!!!

**Comment by rockaddicted** [comment]
same bug than https://github.com/recalbox/recalbox-os/issues/722

**Comment by digitalLumberjack** [comment]
There is no possibility to change that, as the internal ext4 partition is case sensitive (and will be, we won't change that as it would bring more bugs thant it would correct)
So the solutions are : change the .cue files to point to the good files, or use an external storage in FAT32.
