### ISSUE TITLE
Adding Genre Support

### ISSUE THREAD

**Issue by Twitch0815** [recalbox/recalbox-os#724]
Games are sorted by system, but would like to see ability to sort by Genre. 
Something like when pressing select to jump to a hot letter add the ability to sort games in the system by metadata variable fighting game, platformer, puzzle, rpg etc.

**Comment by rockaddicted** [comment]
+1

**Comment by digitalLumberjack** [comment]
+1

**Comment by mgoulartBR** [comment]
+1

**Comment by Laddyacris** [comment]
+++111

**Comment by Colir** [comment]
+1 - but i see this more like the favorites = creation of a "virtual système"...

**Comment by rockaddicted** [comment]
games in a system can now be sorted by genre, number of players, developer's name
https://github.com/recalbox/recalbox-emulationstation/pull/160
