### ISSUE TITLE
[v.4.0.0 beta 1] 8bitdo controllers not working

### ISSUE THREAD

**Issue by paradadf** [recalbox/recalbox-os#725]
I was able to pair the 8bitdo NES30 PRO and 8Bitdo Zero but Recalbox doesn't responds to them afterwards.

**Comment by digitalLumberjack** [comment]
DId you follow the wiki instruction ? https://github.com/recalbox/recalbox-os/wiki/8bitdo-on-recalbox-(EN)
Is your controller up to date ?

**Comment by wjanes** [comment]
Hi. My 8bitdo NES30 ( not pro ) works with this version. I paired it with START + R (RIGHT)

**Comment by manuclementz** [comment]
My SNES30 also works in the latest beta. I had some trouble initially, but I realized I wasn't starting the controller correctly (with START+R) when pairing.

**Comment by digitalLumberjack** [comment]
I tested SNES30, NES30, NES30pro and zero before releasing the beta, it all worked. If it doesn't work @paradadf with up to date controller, did you tried to reconfigure it ?

**Comment by paradadf** [comment]
Problem solved. I had the lastest firmware but yesterday it just wouldn't work. I just tried it again and works.
