### ISSUE TITLE
Add configuration files to webclient to be editable

### ISSUE THREAD

**Issue by Twitch0815** [recalbox/recalbox-os#727]
For example, files like /boot/config.txt  a user might need access to switch output to composite tv.  
Or maybe need access to noobs information to change partition boot order.   
So I would ask there be some either super user or ability to edit these files in the web client for when a change has to be made.

**Comment by rockaddicted** [comment]
Can you check on recalbox-manager repo if an issue is open about that, and open one if not ? https://github.com/recalbox/recalbox-manager/issues
