### ISSUE TITLE
[4.0.0] Use screenscraper instead of thegamedb.net

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-os#730]
TGDB.net has been shut down, no ETA for a return of the service.

that's a good reason to switch to screenscraper as it has a TGDB.net compatible API

URL example : http://www.screenscraper.fr/api/thegamedb/GetGame.php?devid=xxx&devpassword=yyy&softname=zzz&name=3%20Ninjas%20Kick%20Back%20(USA).zip

**Comment by mxjoe** [comment]
As far as I understood thegamesdb.net is just temporarily down. So I don't think we should work on replacing it right now.

**Comment by digitalLumberjack** [comment]
I was thinking about letting the use choose the scrapper mirror.

**Comment by paradadf** [comment]
FYI TGDB is back online again :)

**Comment by rockaddicted** [comment]
done https://github.com/recalbox/recalbox-emulationstation/pull/159
