### ISSUE TITLE
8Bitdo NES30 Pro digipad won't work with Kodi

### ISSUE THREAD

**Issue by DaVinnci** [recalbox/recalbox-os#733]
Today i got a RPi2 and a 8Bitdo NES30 Pro gamepad.
I installed recalboxOS-4.0.0-beta1. Everything seems fine so far.
Except for the controller and Kodi.
I can't navigate through Kodi with the digipad. Only with the right analog stick. But the problem is, only up and left are working.

I would love to use Kodi with the digipad, but I don't know how.

I configured the controller in recalbox with the assistant. And everything there and in the games works perfect. But not in Kodi.

I hope someone can help me or confirm if this is a bug.

Thank you

**Comment by nadenislamarre** [comment]
Hi,

Please run /recalbox/scripts/recalbox-support.sh under ssh after having launch kodi
and send me the output file please which is in /recalbox/share/saves

**Comment by DaVinnci** [comment]
Ok, [recalbox-support-20160228140245.tar.gz](https://github.com/recalbox/recalbox-os/files/149907/recalbox-support-20160228140245.tar.gz)

**Comment by TeenTin** [comment]
My 8Bitdo SFC30 gamepad has the same issue.  Only the up and left are working.

**Comment by DaVinnci** [comment]
Any news on this issue? Still doesn't work. Thought it would be fixed with the new version of recalbox.

The changelog mentions: "Updated 8bitdo gamepads"

But I'm guessing this is for something else :-/

**Comment by substring** [comment]
The update only concerned some special new codes added to pad configuration in ES,  nothing to do with bluetooth or 8bitdo device drivers

**Comment by nadenislamarre** [comment]
i guess this is the same problem as #726
can you confirm ?

**Comment by tchernobil** [comment]
I have a 8bitdo snes30 and the d-pad doesn't work at all in Kodi. I am on recalboxOS-4.0.0-beta2. I suppose it's the same problem... ?

**Comment by tchernobil** [comment]
I try it again with recalboxOS-4.0.0-beta3 last night. I have the same problem. No d-pad.

**Comment by DaVinnci** [comment]
Are you sure? Thankfully I tried it myself today and updated. And I'm surprised, because it works now with beta 3. Finally. Thanks to all who fixed it.

Maybe try to reconfigure the controller in emulation station before launching Kodi. All my joysticks and most important the d pad are working now.

**Comment by tchernobil** [comment]
I tried it again. I uninstall (forget bluetooth controllers) and reinstall my 8bitdo snes30 in controllers settings. It works fine in Emulation Station without configuration. But not in Kodi.
When I try to map the buttons, it doesn't work because when I press down, it skip the "down button" configuration.
It's working fine with my wireless Xbox360 controller. But I buy 8bitdo snes30 just for Recalbox. :(

**Comment by digitalLumberjack** [comment]
Do you start the snes 30 with start + r ?

Le jeu. 21 avr. 2016 à 01:28, tchernobil <notifications@github.com> a
écrit :

**Comment by tchernobil** [comment]
I tried to start with start + r. I can pair my controler but nothing is recognized. I cannot configure the inputs.
I tried to start with start + b, the keyboard mode, I can configure the inputs but it doesn't work in Kodi. And I lost my keyboard.

**Comment by tchernobil** [comment]
Sorry, I retried start+r on a fresh install and it's working in Emulation Station and Kodi
Thank you verry much.

**Comment by substring** [comment]
Can we close the issue then ? :)
