### ISSUE TITLE
Suggest new chatroom 

### ISSUE THREAD

**Issue by Twitch0815** [recalbox/recalbox-os#734]
ICQ is awesome and not suggesting we ditch it completely but would anyone mind if we setup a different chat client?  Something like HipChat, Slack, or Discord.  Maybe have a vote.  All of those clients have much better mobile support, history search, ability to ping If we have one central hipchat you can even make rooms like /dev  /users  /troubleshooting 
We could promote and sticky the location for this on the subreddit and in the central site
Heck Discord even has voice functionality better then ventrillo and it would be a cool place to talk games when were not troubleshooting problems.

**Comment by menelkir** [comment]
Why not irc?

On Fri, Feb 26, 2016 at 8:27 PM, Twitch0815 <notifications@github.com>
wrote:

> ICQ is awesome and not suggesting we ditch it completely but would anyone
> mind if we setup a different chat client? Something like HipChat, Slack, or
> Discord. Maybe have a vote. All of those clients have much better mobile
> support, history search, ability to ping If we have one central hipchat you
> can even make rooms like /dev /users /troubleshooting
> We could promote and sticky the location for this on the subreddit and in
> the central site
> Heck Discord even has voice functionality better then ventrillo and it
> would be a cool place to talk games when were not troubleshooting problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/recalbox/recalbox-os/issues/734>.
>



-- 
Daniel de Oliveira

**Comment by Twitch0815** [comment]
Everytime I have tried IRC i have never seen someone respond, 
Hipchat has the ability to create rooms (Imagine a room for dev, users, troubleshooting etc
Hipchat has better mobile support with push notifications
Hipchat has screen sharing
HIpchat has better ability to search history
Hipchat can sync between clients.
Hipchat has better image support

Virtually all the same for slack and Slack can be accessed with an IRC client. 

Discord has voice integration, Better moderation tools like mod colors know someones role by view
Discord has youtube and twitch integration
Discord has a site widget

Development of features and tools for more modern communication platforms like slack, hipchat, or discord is more current as opposed to a more obsolete tech like IRC new features are released to all of those clients monthly.  Hipchat and slack are what major tech companies are using to keep connected.   All of them are free and remote hosted.

**Comment by menelkir** [comment]
In other hand, irc servers like freenode you have thousands of channels
related to development, opening one client and connecting to a bunch of
other channels related (or unrelated to the same project). Instead of
opening a new app to connect exclusively to a project.
IRC is being used for years to developer's networks (freenode or gimp.org
and many many many other servers), almost all open source and even closed
source projects use irc for communication, I mean, thousands of people
always used irc for projects.

About waiting to respond, you know, people are working on projects for
free, most of time (like me) are working with real life jobs while
connected on irc. Most of people doesn't make money with some sort of
projects. You can pay for the support with donation, btw.

IRC isn't obsolote. The lack of voice integration and twitch and youtube
and image are all features IMHO, personally I would hate to see a bunch of
people making a load of spam in a developer channel.


On Fri, Feb 26, 2016 at 8:48 PM, Twitch0815 <notifications@github.com>
wrote:

> Everytime I have tried IRC i have never seen someone respond,
> Hipchat has the ability to create rooms (Imagine a room for dev, users,
> troubleshooting etc
> Hipchat has better mobile support with push notifications
> Hipchat has screen sharing
> HIpchat has better ability to search history
> Hipchat can sync between clients.
> Hipchat has better image support
>
> Virtually all the same for slack and Slack can be accessed with an IRC
> client.
>
> Discord has voice integration, Better moderation tools like mod colors
> know someones role by view
> Discord has youtube and twitch integration
> Discord has a site widget
>
> Development of features and tools for more modern communication platforms
> like slack, hipchat, or discord is more current as opposed to a more
> obsolete tech like IRC new features are released to all of those clients
> monthly. Hipchat and slack are what major tech companies are using to keep
> connected. All of them are free and remote hosted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/recalbox/recalbox-os/issues/734#issuecomment-189529431>
> .
>



-- 
Daniel de Oliveira

**Comment by substring** [comment]
Recalbox is all about retrogaming ... And retro support ;)

Joke aside, we are 2 to 5 devs on IRC from dusk till dawn (almost) on Central Europe Time, which makes support a little complicated for far away countries.

And there is the forum too.

Github is a dev tool and shouldn't be used for support, which some people don't respect.

With the release of 4.0.0, we have spent a huge time helping users and collecting (often false positive) bugs. 

So i think we are quite available on the current "support channels" and can't be everywhere at once

**Comment by Twitch0815** [comment]
Honestly been trying to be as active and possible  contributing as a person with linux admin background not development background both on the forums and on reddit.com/r/recalbox 
as I was suggesting was more a self support forum for users not so much dev, it would be cool if the devs were on there but far from suggesting they have any obligation too, just think we could get a bunch of admin/power users types and newbies centralized in something like hipchat and get some other cool discussions on projects, ideas new things as well as supporting each other hopefully taking some of the strain off the devs and fueling more ideas and doumentation.

**Comment by rockaddicted** [comment]
The team is actually working on a new forum, with more sections. So the new forum won't be more only a "support forum" and I think will become a great tool for recalbox.
So in a first I think let's try this  combined to irc for a live chat, and if we need more in the future, why not add a hipchat or slack.

**Comment by MikaXII** [comment]
Why not use gitter to ? Currently we trying this option.
It's good idea to create dev-chan but for support, the best is the forum.
IRC is pretty good too.

**Comment by Twitch0815** [comment]
As I see it, there is Three areas for support
Forums, Irc, Reddit.com/r/recalbox
2 areas for devs irc and github

I would imagine a Hipchat chatroom to be more for power users,  self supporters, admin types, tinkerers, and just enthusiasts who want to talk about what they use it for projects there working on etc.   So rolling a hipchat implementation would keep those guys out of the devs way and let a community of users grow up.  Same kind of thing happening at the recalbox subreddit just think hipchat would complement that well.

**Comment by gregms** [comment]
I'm currently running both Hipchat and Slack, but my vote would be for
Slack.

**Comment by MikaXII** [comment]
They have already IRC/Forum we trying to launch gitter chatroom without great success according to me... If we open slack's rooms or Hipchat we must be sure a lot of people comming in. We didn't have enought time to stay in many place, to do the same things.

**Comment by nadenislamarre** [comment]
can i close this one ?
