### ISSUE TITLE
[4.0.0-beta1] Controller mapping problems with Moonlight

### ISSUE THREAD

**Issue by steak3** [recalbox/recalbox-os#738]
- RPI: Make a fresh install of the 4.0.0 beta1 in Raspberry PI 2
- PC: Run the PC with GFE installed (v2.10.2.40). Windows 10 64bits with GTX660.
- RPI: Add a bluetooth dongle
- RPI: Plug a PS3 controller in a USB port for 5sec, then unplug it and press Home -> Works great
- RPI-SSH: Run `./Moonlight.sh pair`, enter the code on PC -> OK
- RPI-SSH: Run `./Moonlight.sh init` then refresh the games in emulstation -> Great
- RPI: Run a game-> The game is displayed, nice!

The problem is that only 2 inputs are working (the analogic right stick, only west and east) for any game.
I noticed that a `system\configs\moonlight\mappingP1.conf` is created or overwritten after each game launch, which contains:

```
# Device name = PLAYSTATION(R)3 Controller (00:19:C1:3A:F5:9E)
# SDL2 GUID   = 060000004c0500006802000000010000
# Event path  = /dev/input/event0
btn_west = None
btn_tl2 = None
btn_dpad_left = None
abs_dpad_y = -1
abs_dpad_x = -1
reverse_dpad_y = false
reverse_dpad_x = false
btn_dpad_down = None
btn_dpad_up = None
abs_rz = -1
abs_ry = None
abs_rx = None
btn_south = None
btn_start = None
btn_dpad_right = None
reverse_ry = true
reverse_rx = false
btn_mode = None
abs_x = None
abs_y = None
abs_z = -1
abs_deadzone = 4
btn_tr2 = None
reverse_x = false
reverse_y = true
btn_thumbl = None
btn_east = None
btn_select = None
btn_tr = None
btn_north = None
btn_tl = None
btn_thumbr = None
```

I wasn't able to make the `./Moonlight map` work over BT.
And if I write the mapping.conf manually, it is overridden.

I BRIEFLY tried with a PS4 controller:
- USB: works well for emulationstation in general, but It returns to menu when I try to launch a moonlight game
- BT: Not tested

And a microsoft USB controller (emulated by an adaptateur for PS1):
- USB: works well for emulationstation in general, but It return to menu when I try to launch a moonlight game

**Comment by substring** [comment]
hi, dear first of the firsts moonlight contributer of the project ;)

Have you read the wiki https://github.com/recalbox/recalbox-os/wiki/Setup-moonlight-%28EN%29#a-version--400-beta1 ? Most of your answers are there

1. There is a bug in the Moonlight.sh script with moonlight 2.3. It will be corrected for the next beta. You know how to check commits ? see https://github.com/recalbox/recalbox-buildroot/pull/206 uoou can edit the Moonlight.sh file by yourself if you wish.

2. The moonlight pad auto configuration required an update in SDL2 + ES to add the expected event codes for moonlight. Some pads are okay, some don't have their configuration updated for moonlight. So : just reconfigure your pads in ES, it should solve the pads configuration problem

3. Can't say GFE2.10 are good for moonlight, the video streaming quite often crashes. GFE 2.9 is strongly advised

**Comment by steak3** [comment]
Oh you remember me haha, nice work btw!

Yeah I read this wiki part and, despite of the bugs you are refering, I was surprised that it works pretty well with the script and the GFE2.10 (for me).

It seems it only misses this controller part. I will try your solution with the configuration of the pad in ES, thanks! I'll tell you if it succeed

**Comment by substring** [comment]
@steak3 have you tested ? should the issue be closed ?

**Comment by steak3** [comment]
Not yet but you can close it

**Comment by steak3** [comment]
Just to say: as you suggested, the manual configuration thru recalbox menu worked. (However, I had to invert X/Y and A/B to get it mapped well like a xbox gamepad).

Thank you I can play my PC games in my TV room! Let's try it on rapsberry zero now

**Comment by substring** [comment]
great :)
Buttons are set according to how you configured them in ES. And remember, in ES, it's a SNES Pad, not an XBox one ;)

**Comment by steak3** [comment]
I thought about the SNES pad, but it asked for R2 L2 and sticks mapping like xbox, that's why I was confused.
Anyway, I stop reviving this tread hehe

Thanks again :p
