### ISSUE TITLE
[4.0.0-beta1] Static netwkork not possible

### ISSUE THREAD

**Issue by djpostka** [recalbox/recalbox-os#741]
I mouting "/" in RW with this command "mount -o remount, rw /" and i edit "/etc/network/interfaces" for configure my static IP.

I run "ifdown eth0 && ifup eth0" and my static ip confifuration is ok, but after rebooting, my configuration turn back from DHCP.

**Comment by djpostka** [comment]
Ok, i have the solution, the file "interfaces" on "/etc/network" is regenered from "/etc/network/interfaces.base". Edit this file and it's OK !

**Comment by nadenislamarre** [comment]
hehe, good idea, i ddin't think to it.
we generate the file because "sometimes", the ethernet card is not eth0 but
eth1 for an unknown reason. Idem for wlan0 and wlan1.
so, we sed eth0 and wlan0 to generate this file.

A wiki entry is welcome ;-)

**Comment by nadenislamarre** [comment]
digit,
to avoid people modifiying / or to keep data after upgrade,
1) we can add a file /recalbox/share/system/interface.base and copy it at boot before the network
2) or add values in the recalbox.conf

1 allows more things
2 is more consistant : all in one file.

**Comment by substring** [comment]
hey @djpostka you don't have a dhcp where you could add a static IP ?

**Comment by djpostka** [comment]
My network is on 192.168.1.x and I have an wifi relay on my network and it generates a second network on 192.168.10.x with his own DHCP (it should not but it is shit)

The static IP need to be edit in the device not on the box, the DCHP on my wifi relay responds faster than my box.

**Comment by nadenislamarre** [comment]
Please wait 4.1 beta to test and close.
The network management system is changed and will allow this.

**Comment by nadenislamarre** [comment]
@djpostka can you make a test in 4.1 or i close.
