### ISSUE TITLE
[4.0.0-beta1] N64 games always in widescreen

### ISSUE THREAD

**Issue by Voljega** [recalbox/recalbox-os#743]
When launching Super Mario 64, it is in fullscreen mode, taking all the screen and thus the image and characters are horizontaly deformed

I didn't touch the recalbox.conf so global ratio is auto and N64 mode is CEA 4 

When adding n64.ratio=4/3 the image is now in a 4/3 container but still displayed inside that container as widescreen, with an image too large horizontaly (compared to vertical), and black bars above and below it

**Comment by substring** [comment]
The default mode for N64 is supposed to be DMT 4 HDMI. Works fine for everyone who tested it so far. Switch to DMT 9 if your monitor/TV doesn't handle DMT 4

CEA is mostly 16/9 video modes, mupen had to be forced to the screen resolution because of a conflict between sound and video plugins.

**Comment by Voljega** [comment]
Yeah sorry made a mistake, it was using DMT 4 HDMI allright but my TV says it detect 640*480 AND 16/9 picture... and it displays full screen picture.

I noticed after a while that my TV (sorry I juste changed it) was set to display 16/9 ratio whereas I could choose Automatic or 4/3 also

But :
- DMT 4 HDMI + Automatic on my TV : detects a 4/3 then goes to 16/9 and displays the image full screen. During game TV refuses to change aspect ratio sayinf it's impossible for this kind of image
- DMT 4 HDMI + 4/3 on my TV : ES is effectively displayed in 4/3 but as as soon as the game launches, TV detects 16/9 again and display full screen, and once again refuses to change aspect ratio during game
- Even with a forced 16/9 on my TV every other emulators is rightky displayed in 4/3

Whereas no matter what I do DMT 4 HDMI is always displayed full screen

I tried CEA 4 HDMI (detected as standard 720p 60Hz) and this one allow me to change ratio during game to 4/3 without trouble

DMT9 causes the emulator to crash and return to ES

So ok my TV seems to cause trouble but there's also something fishy because all the other emulators are working fine

**Comment by substring** [comment]
don't change the N64 ration
Stay on `n64.videomode=DMT 9 HDMI` if your TV doesn't support DMT 4
And I'm sure it will work fine

**Comment by Voljega** [comment]
Well as I said DMT 9 HDMI causes the emulator to go back to ES after a dark screen
DMT 4 is displayed in widescreen

But It must be my TV because it does'nt seem very logical and nobody else seems to have the problem maybe it's because it's a 4K or some other problem

You can close the issue if you want

**Comment by rockaddicted** [comment]
Currently I'm using my recalbox on a pc monitor. And if I don't activate an option in my screen menu to respect the "input format" my game is displayed in 16/9. But once activated this option, my screen respect the ratio 4/3.
So I think too that is a setting/problem with your TV.

I'll test on my TV screen during the day, and if I have no problem on it, I'll close this issue, ok ?
