### ISSUE TITLE
[4.0.0-beta1] [gba] gpsp core works fine but mgba freezes

### ISSUE THREAD

**Issue by Depado** [recalbox/recalbox-os#744]
When using the mgba core (default one in v4) the 5 games I tried simply freezed after a few seconds/minutes of game. (Freezing the raspberry completely)

As a side note, I have the retroachievements options activated and didn't try without it.

**Comment by rockaddicted** [comment]
Let's try to update this core

**Comment by rockaddicted** [comment]
done with https://github.com/recalbox/recalbox-buildroot/pull/278
