### ISSUE TITLE
New Super Nintendo Emulator 

### ISSUE THREAD

**Issue by kryptalivian** [recalbox/recalbox-os#746]
I see that we have a copy of SNES9X_NEXT as an emulator option, but could we have the plain SNES9X as an option. Retroarch crew said that this core would support Achievements.

**Comment by rockaddicted** [comment]
No problems with curent snes9x_next core and retroactivement.

**Comment by kryptalivian** [comment]
everytime I try to play a super nes game, it says this game doesn't support achievements. I know donkey kong country supports achievements.

**Comment by Laddyacris** [comment]
compatibility list game : http://retroachievements.org/gameList.php?c=3

**Comment by rockaddicted** [comment]
retroachievements are working well with snes9x_next core included to recalbox 4.0.0 beta1.
So i'm closing this issue.

**Comment by kryptalivian** [comment]
I'm using a no intro romset for snes. I'll test a copy from a rom site and see if it has something to do with my rom set :-) Thanks for confirming its working on your end @rockaddicted

**Comment by rockaddicted** [comment]
But I'm curious @kryptalivian in an other issue on libretro github.
You said that retroachievements was working on genesis for you ?
So, is it ok for you on recalbox? Which recalbox version, core are you using ?
I tested it, and retroachievement see my game, and activate it on the website. But I can't validate any achievements.

**Comment by kryptalivian** [comment]
Correct, I found the same findings as you. Everything is seen on RetroAchievements, but unable to unlock achievements. 

I'm using 4.0.0 beta. I'm not sure of which core, but can check this evening.

**Comment by kryptalivian** [comment]
I can confirm that the issue is the snes no intro rom set. I was able to download a different copy of Donkey Kong Country, and it worked like a charm.
