### ISSUE TITLE
Add Raspberry Pi 3 Support

### ISSUE THREAD

**Issue by Northwave** [recalbox/recalbox-os#748]
The Raspberry Pi 3 is launched and I would like to see the Recalbox OS on it :)

New features are onboard Wi-Fi, Bluetooth 4.1, and the new Cortex-A53 CPU

**Comment by substring** [comment]
So do we ;)

**Comment by Djiit** [comment]
I'm so excited to see how n64 or newer platforms will perform on this RPi3 !!

**Comment by digitalLumberjack** [comment]
Sadly the videocore is still the same, a little bit overcocked.

There will not be huge performance boost i think.

But the wifi + bluetooth integrated is just perfect for the recalbox :)

I bought one, if the seller dosen't fail like it often does , i can work on in this weekend

**Comment by brunosxs** [comment]
Aside from the drives for wifi and bluetooth, recallbox will work with no issues on rasp3... They're completely compatible.

If you're talking about 64bit support, this is dependable on the emulators themselves.

**Comment by kryptalivian** [comment]
So the bottleneck for running Dreamcast games, wasn't the CPU, but the GPU?

**Comment by Northwave** [comment]
I think its more an emulator problem than a GPU problem but the weak GPU is doing the rest. When you have enough power you can emulate allmost anything also with a bad emulator. The reicast emulator for Sega Dreamcast runs on Raspberry Pi 2 but many games are'nt running well. Maybe test it @kryptalivian ?

**Comment by Northwave** [comment]
@digitalLumberjack I ordered a Raspi 3 ,too. I will test the 4.0.0b1 release as soon as I can. Maybe it works without a change like brunosxs is saying.

**Comment by digitalLumberjack** [comment]
I don't think it will work ootb, and even if it does, we would have armv7 32bit binaries so we would not use th full power of the rpi3. We will release a rpi3 version as soon as i receive the beast :)

**Comment by kryptalivian** [comment]
@Northwave , I'll deff check it out as soon as my Micro Center gets them in. 

I'm going to be broke, or end up dead at my girlfriends hands lol. I have a second Pine 64 in the mail, along with a CHIP, and then will have ODROID C2 and Pi 3 Soon.

**Comment by AstonBlitz** [comment]
Rpi3 doesnt boot up recalbox 4.0.0 beta 1... at least for me :(

**Comment by rockaddicted** [comment]
predictable :wink:

**Comment by Northwave** [comment]
Okay, the developer was right :smiley:  

I wait for my Pi which is delivered tomorrow and you guys, to make it work :)

**Comment by jammet** [comment]
Okay, I got mine, but I'm hesitant to just use the SD card from the RPi2 version in that, it already didn't work with my ELEC card (Kodi), are you sure this will actually boot and work, and not self destruct? ;)

In any case, I would love to see that PSP emulator. I've seen videos of it doing a fine job on Raspberry Pi 2, on Youtube. If these videos were not fakes, it should be possible to emulate that just about perfectly.

**Comment by substring** [comment]
The current version of recalbox can't boot on Pi3. It requires some work as it's a slightly new architecture. So pleaaaaaaaaaaaaaaase please please please let us put our hands on our Pi3 first :)

**Comment by jammet** [comment]
Of course ^^. <3 I'm just piling up love and devotion ontop of everyone doing the amazing work on that.

**Comment by Voljega** [comment]
@jammet
Forget PS2, PCSX2 isthe best emulator on PC but on my i5 with a good graphic card (able to launch Bioshock Infinite or Star Wars Battlefront in 1080p flawlessly), PCSX2 isn't able to make games work at full speed.
So Pi is entirely out for at least ten years :D

**Comment by marcosmontero** [comment]
@digitalLumberjack  Any chance RPi3 support could be added to latest stable (3.3.0 I believe) instead on just 4.0beta pleease? I don't intend to install the beta just yet as I'm very happy with 3.3.0 but got my Rpi3 today and can't wait!

**Comment by Twitch0815** [comment]
Adding on to this along with support can we add a proper overclock setting for the raspi 3.  

I have the correct power 5v 2500 ma 
I have standard heatsinks applied with thermal paste
and a well ventilated case with an active fan.

Can anyone suggest a starting point for overclock and how to test I can see what I can get mine table to then share that overclock. And then maybe that could be added to the automatically configurable settings in retropie?

**Comment by mvw** [comment]
4.0.0-beta1 is not booting on the Pi 3. I then put a copy of the Pi 2 files as Pi 1 os, in case it booted as Pi 1, but that switch was not sufficient.

**Comment by Duglim** [comment]
@digitalLumberjack Did you already recieve your Pi3? Any idea on the needed workload to make recalbox4.0 working? No pressure, just asking for curiority. :)

**Comment by Northwave** [comment]
@Duglim I think he did ;)

https://github.com/recalbox/recalbox-buildroot/pull/233

But I'm waiting too :smile:

**Comment by digitalLumberjack** [comment]
Yeah i'm stucked with the support of the new wifi and bt chip.
Everything is ok except that.

**Comment by mvw** [comment]
Raspbian got an update in the last couple of days which made it recognize wifi and bt.
What is the base system of recalbox?

**Comment by digitalLumberjack** [comment]
Not at all, we're a linux from scratch, but i bumped all versions to the last commits yesterday. I'm trying again :)

**Comment by rockaddicted** [comment]
Everything is configured and builded from scratch using buildroot. We are not using a debian.

**Comment by digitalLumberjack** [comment]
hoho

**Comment by rockaddicted** [comment]
Haha

**Comment by mvw** [comment]
Hihi

**Comment by Northwave** [comment]
So ... This is a good hoho ? 😁

**Comment by nadenislamarre** [comment]
what does lsmod return on debian ?

**Comment by digitalLumberjack** [comment]
Have the very same modules loaded dude.

**Comment by 2Fake** [comment]
> Have the very same modules loaded dude. 

What does that mean?

**Comment by digitalLumberjack** [comment]
That i have the sames modules loaded in recalbox and raspbian on rpi3.

**Comment by 2Fake** [comment]
So you got it running?

**Comment by digitalLumberjack** [comment]
didn't you see : 

> Yeah i'm stucked with the support of the new wifi and bt chip.
> Everything is ok except that.

**Comment by 2Fake** [comment]
thought you had the support working. because of the "hoho" ;)

**Comment by jammet** [comment]
(Quietly pets the RPi3 sitting next to him on the desk, waiting for assemply, a case, and a micro SD card) ...

**Comment by 2Fake** [comment]
;) how do you know?

**Comment by jammet** [comment]
I'm waiting patiently :), like everybody else. But I'm being a little silly.

**Comment by Northwave** [comment]
at which point is this problem ? @digitalLumberjack

**Comment by MikaXII** [comment]
@Northwave Big problem no ? If we can't use the most popular feature on pi3 no ??

**Comment by Northwave** [comment]
@MikaXII ... sorry I meant what the actual problem is to make it work. And if he have a clue what causes the problem. My english isn't very well :(

**Comment by digitalLumberjack** [comment]
lol i understood you @Northwave,
i don't know yet. The modules are loaded, but nothing happens with the bt +wireless chip.
I really do not understand when it can comes from. Like the dtb is not loaded, or the hardware not detected... 
Could be udev, dtb, kernel configuration...

**Comment by kryptalivian** [comment]
Bad board?

**Comment by Northwave** [comment]
I will test the build `recalbox4.0.0-rpi3-v7.img.zip` from archive2 on my raspberry pi3. Maybe its really the board ? is this the actual build you use ?

**Comment by substring** [comment]
I can already tell you it doesn't work at 100%. Tjat's an internal try-out, not a release. Still not functionnal

**Comment by Northwave** [comment]
oh :(

**Comment by mvw** [comment]
dtb = device description. Is there a BCM43438 driver or does it need to be added / updated as well?

**Comment by jammet** [comment]
I don't think this is the board, as he mentioned he'd booted raspbian already as well, where it did functioned fine. :)

**Comment by substring** [comment]
It's a driver issue, but we we're getting closer ^^

**Comment by jlerouge** [comment]
Do you guys have any idea of how much work / time it will need to overcome the drivers problem ?
Seems that RP3 + RecalBox will be the perfect retrogaming platform.

**Comment by substring** [comment]
Haha no ETA ^^

Or a usual : "when it's done" ;)

Looks like we have a few clues for the remaining problems, so let's cross fingers and hope we'll sort it out ^^

**Comment by jlerouge** [comment]
Nice :) I'm waiting for it. Anyway good job for this nice piece of software.

**Comment by Otacon32** [comment]
Really looking forward to it. I wish i could help but im a noob :)

**Comment by Coreldrew** [comment]
my Pi3 delivered, getting excited about Pi3+Recalbox.
No rush, I'm still enjoying v4.0 beta1 on my Pi2
Thanks for the hard-working, guys!

**Comment by AntsInThePants** [comment]
Although i'm still a bit of a newbie i would like to help you guys! Is there anything that i could do?

**Comment by tonianer** [comment]
Waiting too :)

**Comment by Zandare** [comment]
Desperate to get my pi 3 to play games :)

**Comment by digitalLumberjack** [comment]
Desperate not to be notified each minute of the day by desperate people :)

**Comment by Duglim** [comment]
See, no one commented for hours. :)

**Comment by digitalLumberjack** [comment]
Oh yes I had questions :( emails and irc pm. I'm just kidding being angry
about that, we're just impressed how much people do not read our messages :D

**Comment by Zandare** [comment]
We do read, but want to give your project and this feature the attention it deserves :)

**Comment by kryptto** [comment]
(Clapping) @Zandare and others that insist on demanding PI3 support now... I am so glad you read all the posts but you are doing a great job alienating the developer team from wanting to support this project.

These folks have spent thousands of hours making the best classic game emulator.  So instead of allowing them to work on 4.0 beta and get people's issues up and running.  The adaption to newer hardware will be lower on the priority list.  Fix current bugs now.  

So since everyone that is demanding and reading posts and hearing DL and others saying give us time, you are making them decide if it's al worth it.  Your pleading seems like a compliment but gets annoying.

If you want PI3 support now, then keep reading, there are very well written instructions on how to compile this project I suggest you read them and start donating your time to make things run at the pace of your expectations.

Kryptto

**Comment by 2Fake** [comment]
Retropie has provided an update for the rpi3. Isn't retropie the base from recalbox? Is there any opportunity that i can help you? Thank you for your work!

**Comment by digitalLumberjack** [comment]
nope @2Fake we h

**Comment by Duglim** [comment]
Thx for your hard work! I'll check beta2 on my Pi3 in a few minutes. :) wohooo!

**Comment by AstonBlitz** [comment]
Finally! <3 even without bluetooth works like charm. Thank you

**Comment by Northwave** [comment]
Thank you for your hard work !
I make a donation at the end of the week :)

**Comment by jammet** [comment]
The integrated upgrade went through, and after that, I cannot boot on a Pi
3 -- the bright colourful screen appears and stays on, permanently :). Do I
need to make manual adjustments? These "overclock" changes, is this
something I need to do, myself?

**Comment by rockaddicted** [comment]
Are you trying to use a rpi2 beta1 version updated to beta2 on your rpi 3?

**Comment by jammet** [comment]
Yes, that's what I did. I just assumed it would encompass all the changes,
but if it doesn't, that is okay :). I can start over.

**Comment by digitalLumberjack** [comment]
I close this one.
See https://github.com/recalbox/recalbox-os/issues/796

**Comment by rockaddicted** [comment]
We have 3 specific recalbox builds. rpi0/1 , rpi2 and rpi3.
So you can't use a rpi2's build on a rpi3 etc...
You must have 2 differents sd card to use recalbox on rpi2 and rpi3.

My advice is to put share partition on an external usb support, using the option in emulationstation. And using this external devise on your differents rpis.

**Comment by digitalLumberjack** [comment]
Just remember that the recalbox.conf is on share, so you will have the configuration for all your tpi (may be bad for specific emulator configuration on rpi1)

**Comment by jammet** [comment]
Thanks guys <3
