### ISSUE TITLE
Can't find Atari ST tos.img with provided checksum

### ISSUE THREAD

**Issue by widgetfonda** [recalbox/recalbox-os#750]
Hi !

I can't find Atari ST tos.img with provided checksum in readme.txt
There's many different tos.img files and I've tried a few of them, with no luck.

The checksum is correct in the readme.txt file ?

Thanks !

**Comment by rockaddicted** [comment]
Yep it is correct. Tos image UK 1.02 but I think others versions should work too. But your file must be named tos.img

**Comment by widgetfonda** [comment]
Merci beaucoup !

Votre travail est fantastique, merci infiniment !
