### ISSUE TITLE
GPIO controller gives me a sh: can't access tty; job control turned off

### ISSUE THREAD

**Issue by schnirpf** [recalbox/recalbox-os#751]
Had the pins already prepared, meaning connected with short cables.
Soldered some extension cables to make it long enough to reach the joystick and buttons in my bartop.

Now if I boot, it gives me a "sh: can't access tty; job control turned off".

Adding disablesafemode in recovery.cmdline gives me at least the possibility to boot into recalbox. 
But running jstest gives me this picture:
jstest /dev/input/js0
Driver version is 2.1.0.
Joystick (GPIO Controller 1) has 2 axes (X, Y)
and 9 buttons (BtnX, BtnY, BtnTL, BtnTR, BtnTR2, BtnSelect, BtnThumbL, BtnThumbR, ?).
Testing ... (interrupt to exit)
Axes:  0:     0  1:     0 Buttons:  0:on   1:off  2:off  3:off  4:off  5:off  6:Axes:  0:     0  1:     0 Buttons:  0:on   1:on   2:off  3:off  4:off  5:off  6:Axes:  0:     0  1:     0 Buttons:  0:on   1:on   2:on   3:off  4:off  5:off  6:Axes:  0:     0  1:     0 Buttons:  0:on   1:on   2:on   3:on   4:off  5:off  6:Axes:  0:     0  1:     0 Buttons:  0:on   1:on   2:on   3:on   4:on   5:off  6:Axes:  0:     0  1:     0 Buttons:  0:on   1:on   2:on   3:on   4:on   5:on   6:Axes:  0:     0  1:     0 Buttons:  0:on   1:on   2:on   3:on   4:on   5:on   6:Axes:  0:     0  1:     0 Buttons:  0:on   1:on   2:on   3:on   4:on   5:on   6:Axes:  0:     0  1:     0 Buttons:  0:on   1:on   2:on   3:on   4:on   5:on   6:Axes:  0:     0  1:     0 Buttons:  0:on   1:on   2:on   3:on   4:on   5:on   6:Axes:  0:     0  1:     0 Buttons:  0:on   1:on   2:on   3:on   4:on   5:on   6:on   7:on   8:off

Connecting a button gives no signal, meaning it does not switch from on to off or versa.

Any ideas?

**Comment by Twitch0815** [comment]
I would take this to the forum, as it is a support issue not a development issues.  And when you open it in the forum include as much pertinent detail like what version you are on, what you have tried already etc.

**Comment by schnirpf** [comment]
Sorry, will do that.
