### ISSUE TITLE
Change in the button preconfiguration and and wasy way to change button config:

### ISSUE THREAD

**Issue by adolfobenjaminv** [recalbox/recalbox-os#752]
Using a 4 buttons joystick to play a two buttons system is terrible, why? because the button configuration.
Is a lot more easy to use
![2784571-2261042175-snes-c](https://cloud.githubusercontent.com/assets/17162641/13413791/b65c803c-df23-11e5-80de-001f21e4adc3.jpeg)

That use 
![2784571-2261042175-snes-c](https://cloud.githubusercontent.com/assets/17162641/13413800/c85ca2bc-df23-11e5-8ada-734495718a1b.jpg)

Just think about Super mario world, super mario all stars, all of them used this configuration for run and jump.
Also, is there a way to make easy the button configuration per core?

**Comment by Twitch0815** [comment]
+1 problem is that if you do that you break fighters like 
Super Street Fighter 2  which on a 6 button layout is exactly correct.  All of the punches and kicks are in the exact same place.  Only problem I ahve found is on super mario games that y is where a should be.  If there was a way to set a custom config per game like on mame that would be nice.

**Comment by substring** [comment]
If you are unhappy with the configuration, you can create a custom config file. But such a request means checking for 2 or 4 or 6 buttons game, which is not on the todo list. As for me who played NES in my youth, I wan't to play it "retro style", which is how it's mapped for now, and not the modern version you suggest ;)

**Comment by rockaddicted** [comment]
Please read this wiki : https://github.com/recalbox/recalbox-os/wiki/Custom-controller-mapping-for-specific-system-%28EN%29
And if you need more help, use the forum to ask support :wink:
