### ISSUE TITLE
Can't access /root/.emulationstation

### ISSUE THREAD

**Issue by d3bugu** [recalbox/recalbox-os#753]
Hi there, I've tried to access the emulationstation folder but wasn't able to enter

I use WinSCP, and 
fileprotocol: SCP, 
Hostname: recalbox, port:22, 
user name: root, 
password: recalboxroot, 

I then Navigate to the root folder, right click and GO TO -> Open Directory, and type « /root/.emulationstation/ «  and press ok.

It then returns me with the following error
**_/root/.emulationstation"'
failed with return code 1 and error message
-sh: line 114: cd:  /root/.emulationstation: No such file or directory.﻿_**

What could i be doing wrong?

Please advice =)

**Comment by paradadf** [comment]
Please, go into IRC or the forum for support. Github is only for development issues.

**Comment by MikaXII** [comment]
`cd ~/.emulationstation` 
since the v4.0 the folder as been moved into share directory
