### ISSUE TITLE
Bring back SSEPH scraper functionalty

### ISSUE THREAD

**Issue by Twitch0815** [recalbox/recalbox-os#755]
On the last version of Recalbox I was able to use SSEPH scraper internally to do all artwork scraping using the following steps. 

wget https://raw.githubusercontent.com/substring/fullscrape/master/fullscrape.sh && chmod u+x ./fullscrape.sh

./fullscrape.sh snes -no_thumb=true -max_width=375

However on 4.0 this is broken because of the changes of the location of gamelist.xml as well as the downloaded_images directory.   SSEPH scraper is downloading to the old locations.

Not sure if forking SSEPH and updating it to your new used locations is the right way or if you would just create symlinnks between the old dirs and new ones.  But anything that can reduce the steps and ease of getting the artwork in would be great. 

Also could look at including sseph in the build like it is done for retropie and piassist
https://github.com/Death259/PiAssist

**Comment by substring** [comment]
that issue has nothing to do with this recalbox project, but with fullscrape (which is my coding). Posts such issue on the fullscrape project rather.

anyway, that issue has no meaning beause fullscrape is already ready for recalbox 4.0.0. Just use https://raw.githubusercontent.com/substring/fullscrape/4.0.0/fullscrape.sh instead

I'll focus on a "single shell" for both 3.3.0beta or 4.0.0 later, time for now is to correct BETA bugs

**Comment by kryptalivian** [comment]
Do you type wget followed by the hyperlink. Then access the folder it's in and type ./full scrape.s h?

**Comment by substring** [comment]
Dude, there is a 4.0.0 branch that is (as its name states it) recalbox 4.0.0 compliant. The forum has been updated long ago with this info. Could you check ?

**Comment by kryptalivian** [comment]
@substring No need to get hasty my friend. I only ask because I've already looked and had issues with scraping using my pc. The Mac portion wasn't working, and I saw you gave someone some advice, wanted to make sure I was executing the commands correctly.

**Comment by kryptalivian** [comment]
Sorry was looking at wiki not forum

**Comment by substring** [comment]
All.my apologies ... Didn't want to sound rude :/ but there is a specific branch of fullscrape for 4.0.0 that handles everything as intended. Check my repo :) you need to replace master by 4.0.0 in the wget url :)

**Comment by substring** [comment]
@kryptalivian @Twitch0815 here is the official link : http://blog.recalbox.com/forums/topic/tuto-scraper-ses-roms-depuis-sa-recalbox-en-shell/
