### ISSUE TITLE
8bitdo zero Mapping Issue

### ISSUE THREAD

**Issue by kryptalivian** [recalbox/recalbox-os#756]
I cannot get Recalbox to recognize the left D-Pad. It always tells me already taken, even though I never used it. Is there a way to manually upload a config file with it already set?

**Comment by Twitch0815** [comment]
Github is a tool for development issues feature requests and such. 
For support please close this issue and open an issue in the support forum.
http://blog.recalbox.com/forums/forum/english/troubleshooting/

Also please include as much information to help those who would help.
Recalbox version you are using.
Which model controller you are using. 
What steps have you taken to get it to work ( Plugged into different port, used js test, etc etc)

**Comment by rockaddicted** [comment]
Yes please, use the forum to ask support :wink:
