### ISSUE TITLE
PSX games doesn't load

### ISSUE THREAD

**Issue by afsadilson** [recalbox/recalbox-os#757]
Hello,

I'm using recalbox version 4.0.0-build-10 and I just start my new raspberry pi 2 with recalbox and test SNES game and it's ok.

I have downloaded a PSX bios and put it on the bios folder, the name and the md5 is the same as sad on _readme.txt (scph1001.bin).

When I start the game the screen fade por a second and then back to the game list. I have tried with 2 differents roms (.img/.bin). I'm listening the file recalbox.log and show nothing.

Can anyone help me? Thnks

**Comment by digitalLumberjack** [comment]
Please post on the forum for this kind of request. Thanks :)
