### ISSUE TITLE
[4.0.0 beta1] Impossible to change Roms folder to a NAS folder

### ISSUE THREAD

**Issue by Raulval82** [recalbox/recalbox-os#758]
Hi!

I have all my roms in a Synology NAS, it was working awesome with Recalbox 3.3.0 beta17, but with the new version I had no luck... The tutorial in the wiki is not working for v4.0, something changed:

The fstab is different, there is no line for share folder:
/dev/sda1       /recalbox/share ext4    defaults,rw       0      0

I think that now the system is looking in other side for this info...

And other issue, I was not able to modify anithing using SSH and root user... 

Thanks in advance for all your efforts!

**Comment by substring** [comment]
Hey @Raulval82 
This is no issue, just a misknowledge of how v4.0.0 works ;) Please post your subject on the forum or join us on IRC, github is only for issues, we don't do support here
Thank you for your understanding :)

**Comment by Laddyacris** [comment]
https://github.com/recalbox/recalbox-os/wiki/Load-your-roms-from-a-network-shared-folder-%28EN%29

**Comment by nadenislamarre** [comment]
I've a patch in progress but that's not as simple.
The network is started lately in V4, and with mounts, it must be started
before es starts.
Please just be patient.
