### ISSUE TITLE
[4.0.0-beta1] SSID editing issue

### ISSUE THREAD

**Issue by TeenTin** [recalbox/recalbox-os#760]
The SSID cannot be edited most of the time.  I can enter the edit mode by pressing button B of gamepad, but can input nothing by typing any characters from keyboard.  However, it sometimes works, very rare, I can't figure out the pattern.

A workaround is entering KODI and then quit back to ES, then SSID can be edited normally.  This seems always working.

P.S. 3.3 beta 17 has no such issue at all.

May I ask a question, not concerning the above issue, that is 4.0 supposed to support open wifi (i.e. without password) ?

Thx a lot !

**Comment by rockaddicted** [comment]
This bug is known. Thanks for the report.
An other issue about the same bug is already open.
So let's continue there : https://github.com/recalbox/recalbox-os/issues/717
