### ISSUE TITLE
board/recalbox/recalbox-patch-target.sh: line 38: convert: command not found

### ISSUE THREAD

**Issue by cscm** [recalbox/recalbox-os#762]
Hi,

I'm trying to build recalbox on Ubuntu 15.04 LTS fallowing instructions on this page : 

https://github.com/recalbox/recalbox-os/wiki/Compilation-%26-Modifications-%28EN%29

And I'am getting an error with convert missing : 
` 
>>>   Executing post-build script board/recalbox/recalbox-patch-target.sh
board/recalbox/recalbox-patch-target.sh: line 38: convert: command not found
Makefile:596: recipe for target 'target-finalize' failed
make[1]: *** [target-finalize] Error 1
Makefile:36: recipe for target '_all' failed
make: *** [_all] Error 2
test@raspi:~/recalbox-buildroot-rpi2$ Write failed: Broken pipe
`
Best Regards,

**Comment by nadenislamarre** [comment]
Hi,

please use the forum for this kind of issue.
Type "convert" into the shell, ubuntu will tell you which imagemagik
package to install.
Please update the wiki in consequence.

Nicolas

**Comment by rockaddicted** [comment]
the wiki has been update 3 days ago. I'm closing this issue.
