### ISSUE TITLE
Official support for Hardkernel ODROID-C1+ and ODROID-C2?

### ISSUE THREAD

**Issue by Hedda** [recalbox/recalbox-os#763]
Any plans by the Recalbox team to officially support Hardkernel's ODROID-C1 and/or ODROID-C2?

I would think that supporting ODROID-C1+ and ODROID-C2 would not be that much different than Raspberry Pi devices?

Maybe the Recalbox team could get a sponsoring deal with Hardkernel?

What makes these very attractive devices to RetroPie users is they offer more power at same price as Raspberry Pi.

If too late to begin supporting the Amlogic S805 based ODROID-C1+ then ODROID-C2 is Amlogic S905 based.

**Comment by kryptalivian** [comment]
digitalLumberjack commented 22 days ago
I'm ok for this kind of work. But this effort should be done when the 4.0.0 is release and some backlogs issues are treated.
Maybe we could have a 4.1.0 with a port to one of the boards. here is the lakka compatibles board for exemple : 
https://github.com/libretro/Lakka/tree/lakka/projects

We must choose one board to begin, to my opinion it must be an already released board, mainstream. I would vote for an odroid that bring a new power level to recalbox and a new "user experience" like the odroid ODROID-XU4 that would likely run n64, dreamcast and all games 100%fps.

**Comment by kryptalivian** [comment]
Might read through this https://github.com/recalbox/recalbox-os/issues/674

**Comment by Twitch0815** [comment]
Just going to leave this here, as a temporary alternative till the guys have the ability to port to odroids.  
http://forum.odroid.com/viewtopic.php?f=114&t=16520

**Comment by Hedda** [comment]
Strongly recommend ODROID-C2 for mainstream support even if the price is a little higher since the ODROID community as well as the Hardkernel company offers much better then something from a Chinese company like Pine 64 which is based on an Allwinner SoC who has a horrible track record with open source projects. ODROID-C2 is based on an Amlogic SoC which has a great track record with open source projects (such as example Kodi/XBMC and OpenELEC).

**Comment by matthuisman** [comment]
This might help
https://github.com/hardkernel/buildroot

**Comment by xprmntlarcade** [comment]
YES!, I would also recommend  ODROID-C2. Very excited for this new build as it would bring real implementation for the Retroarch NETPLAY p2p feature. Gigabit Ethernet is one of its advantages over the limited ethernet in Rpi.

**Comment by substring** [comment]
Guyz, we are already porting to xu4, it's already a real pain despite the huge progress made by the guy in charge of that. So let's finish that port first before thinking about something else ok ?

BesideS no one in the team has a C2 ...

Gigabit ethernet has definitely no impact on retroarch netplay.

**Comment by NickDG** [comment]
Can I please get the latest version of Recal image for odroid-xu4

**Comment by nadenislamarre** [comment]
There is no official version.
You can get my own build on http://recalbox.remix.free.fr

**Comment by Hedda** [comment]
Good with progress on XU4 port, however please note that this request is for ODROID-C2 support.

I think that ODROID-C2 is more interesting because it is much cheaper (even if less powerful).

ODROID-C2 is something that almost everyone can afford, at half the price of ODROID-XU2.

**Comment by nadenislamarre** [comment]
Yes, and the c2 has an other interest thing compare to the xu4 : it is arm8. In other word, it would make the dolphin gamecube emulator working (which requires arm8 or x86).
xu4 is more powerfull (according to hardkernel, because for our case, seeing the specification, it should not change a lot while the number of cpu and the gpu is not the most important), but the ratio price/power is really lower than the c2 for the recalbox.
I plan to do the port if somebody send me one ;-)

**Comment by sylvain-perez** [comment]
Hi Dennis, what if I send you the money so you can buy one ;-)

**Comment by nadenislamarre** [comment]
i can give you my adresse if you want to send me one.
just ask me by email.

**Comment by sylvain-perez** [comment]
it may be obvious but I cannot find your email from your profile page neither can I find a way to send you a PM...

**Comment by nadenislamarre** [comment]
nicolas dot adenis dot lamarre at gmail dot com

**Comment by sylvain-perez** [comment]
thank you but it seems that this email address does not work: nicolas dot adenis dot lamarre at gmail dot com...
Just kidding :) I dropped you a message to get your shipping address
Thanks

**Comment by nadenislamarre** [comment]
Port Recalbox to Pine 64: #997
Port Recalbox to Odroid c2: #998
Port Recalbox to x86: #999

not interested for c1. any arguments for it.
