### ISSUE TITLE
X-Arcade Support

### ISSUE THREAD

**Issue by Wisermerill** [recalbox/recalbox-os#764]
Hello,

Can you add to the mapping of te X-Arcade the keys 8,6,2,4 from the numpad (joystick 1, like the Arrows Keys) for the 2 older models of X-Arcade. 

In Fact the mapping between the old and the new model is the same except the joystick 1 mapping.

Thanks,

**Comment by Twitch0815** [comment]
I would say this belongs on the forum as it is not a specific dev request. Take a look at this 
https://github.com/recalbox/recalbox-os/wiki/XArcade-configuration-%28EN%29

**Comment by substring** [comment]
@Wisermerill the answer is quite simple : it supports only 3rd gen xarcade sticks for now. If the 1st or 2nd gen mapping (which i have no resource for, wouldn't mind getting some + a way to distinguish them as linux devices) doesn't conflict with the current one, i may add them

**Comment by Wisermerill** [comment]
Thanks for your answer. i join you the mapping for the 1st and 2nd gen mapping if that can help.

@Twitch0815 sorry if i missed the right section for this request.

Best regard,


![pc-mac_layout_mode1 cropped](https://cloud.githubusercontent.com/assets/8946269/13512588/e57ab03a-e19b-11e5-996b-2daa1b95a676.JPG)

**Comment by substring** [comment]
@Wisermerill
I would also need the output of `ls -l /dev/input/by-id` when your xarcade is plugged

**Comment by Wisermerill** [comment]
ok Subs i search how to give you this information and i post it asap ;) Thx

**Comment by Wisermerill** [comment]
Voila les infos que tu m'as demandé sachant qu'a cet instant j'avais le X-arcade et un clavier usb de connecté ;)

login as: root
root@recalbox's password:
# ls -1 /dev/input/by-id
usb-CHICONY_USB_Keyboard-event-if01
usb-CHICONY_USB_Keyboard-event-kbd
usb-XGaming_X-Arcade-event-kbd

Merci de ton aide

**Comment by substring** [comment]
just to be clear : can't promise anything. Nor on which version it's out. The main problem for now is to make the difference between xarcade generations, if it can be done automatically or not. And the fact that i can't test it by myself as i don't own any of those sticks

**Comment by Laddyacris** [comment]
@substring , est ce que le idvendor et idproduct pourraient ils différencier les différentes générations de xarcade ?

**Comment by substring** [comment]
Oh oui sûrement. J'esperais juste qu'on puisse s'en sortir simplement avec le nom de périphérique parce que xarcade2jstick se base là dessus

**Comment by Laddyacris** [comment]
peut etre que xarcade2jstick peut etre modifié pour se baser sur ça ?

**Comment by Wisermerill** [comment]
Mais si les noms sont les mêmes, et que le mapping est juste différents pour le joystick 1, serait il possible de mettre les deux configurations du joystick 1 sans créer de conflit ?

**Comment by substring** [comment]
@Laddyacris : oui. Et de toute facon c'est surement mieux de procéder de la sorte

@Wisermerill : t'inquiètes, j'ai des idées en stock ;) un switch genre -o pour dire "old" :p

Mais ca n'est pas.top priorité pour le moment

**Comment by Wisermerill** [comment]
Oui je comprend pas de soucis je bricole dessus en attendant ;) Merci beaucoup en tout cas ^^ pour infos je viens de voir que le problème kodi qui ne se lance pas est réglé quand je débranche la commande PS4 mais tu le sais surement déja ;)

**Comment by Wisermerill** [comment]
@substring je viens de me rendre compte que le X-arcade fonctionnait mal en raison de la présence du controleur PS4 simultanément (la conf clavier était aussi en US au lieu de FR, je ne sais pas si ça jouait). 
Une fois celui ci débranché, le X-Arcade fonctionne à merveille, même mon ancien modèle. Ce thread n'a donc plus lieu d'être et désolé pour ça.

Il ne me reste plus qu'a trouvé comment reconfigurer les boutons car actuellement le bouton "B" se situe au dessus du bouton "A" et non à sa droite comme il devrait logiquement.

Encore merci à vous pour votre aide et pour l'incroyable travail fourni ;)

Cordialement,

**Comment by substring** [comment]
Attention, pad snes !!! Pas pad xbox !

**Comment by Wisermerill** [comment]
@substring Désolé que veux tu dires par ton dernier message ?

**Comment by substring** [comment]
pour la disposition des boutons
rangée du haut : Y X L1
rangée du bas : B A R1

**Comment by Wisermerill** [comment]
@substring ok merci ;)
