### ISSUE TITLE
Kodi with PS4 usb controller issue

### ISSUE THREAD

**Issue by d3bugu** [recalbox/recalbox-os#765]
When I launch Kodi from Recalbox 4.0 with my PS4 controller plugged in to the USB.. it shows the splash screen and then kick me back to ES. But if i do it again but unplug the controller.. it will load successfully into Kodi.

Some kind of controller bug?

**Comment by rockaddicted** [comment]
haha all these issues are talking about the same bug : 
https://github.com/recalbox/recalbox-os/issues/707
https://github.com/recalbox/recalbox-os/issues/726
https://github.com/recalbox/recalbox-os/issues/733
https://github.com/recalbox/recalbox-os/issues/761

So please, the next time check on github before opening a new one.
