### ISSUE TITLE
[4.0.0-beta1] Upgrade mame2003 for custom configuration not saved on exit

### ISSUE THREAD

**Issue by Voljega** [recalbox/recalbox-os#766]
Apparently this issue in mame2003 wich is often asked about in the forum has been corrected a few days ago :
https://github.com/libretro/mame2003-libretro/issues/11

Related save folders seems to be saved in the rom folders so It would also be simple for user to backupo and reuse out-of-the-box

This would presumably also resolve a lot of other issues regarding custom conf on mame2003

Would be nice to have it in a future version !

**Comment by dh04000** [comment]
This is for native mame menu changes to not be lost on mame exit or recalbox reboot, correct? Yes, this affects me as well.  I would like to be able to set my arcade controls, which is a keyboard emulator, to custom settings in mame.

**Comment by substring** [comment]
@dh04000 which keyboard emulator do you have ? Recalbox v4.0.0 has a new keyboard emulator support. Made it work sucessfully with several IPAC generations so far. Please make a forum post a poke me there

**Comment by rockaddicted** [comment]
For me : O3->O2

**Comment by nicolas-van** [comment]
This is still a problem for me in 4.0.0-beta4. I can edit my mame configuration using the mame menu (AKA the "tab" menu) but nothing is saved on exit. I can't find any configuration file related to the mame configuration on my filesystem.

Maybe it's just a matter of clearly passing to retroarch the correct folder to store mame-related configuration? There seems to be some documentation about that on libretro's website ( http://www.libretro.com/index.php/mamemessume-cores/ ) and it seems like retropie users had a solution to fix that problem.

**Comment by rockaddicted** [comment]
this core need an update to support this feature.

**Comment by nicolas-van** [comment]
Is it more complicated than updating the mame2003-libretro's version in [this file](https://github.com/recalbox/recalbox-buildroot/blob/22d4649ddc761f71a3db9c2971adc7efa3e7f368/package/libretro-mame2003/libretro-mame2003.mk)?

If that's all needed to be done I don't mind testing it and making a merge proposal.

**Comment by dankcushions** [comment]
FYI the current latest version of mame2003, samples don't work... i have a fix for that and also mouse/trackball/analogue support coming in the next week :)
