### ISSUE TITLE
xbox360 gamepads blinking if xboxdrv disabled

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-os#767]
kernel patch don't work anymore in 4.0.0
https://github.com/recalbox/recalbox-buildroot/blob/rb-4.0.X/board/recalbox/kernel_patches_4.1/linux-xpad_blink.patch

**Comment by LipkeGu** [comment]
Missing kernel module... 

```
CONFIG_JOYSTICK_XPAD=y
CONFIG_JOYSTICK_XPAD_FF=y
CONFIG_JOYSTICK_XPAD_LEDS=y <--- Add this
```

**Comment by rockaddicted** [comment]
I've a xpad patch including xboxone S/Elite gamepads's compatibility , fixing LEDS ready to be push.
I'll do that when I'll have a moment.
