### ISSUE TITLE
Recalbox 4.0 is a nightmare

### ISSUE THREAD

**Issue by djcyber20018** [recalbox/recalbox-os#768]
1-8BitDo this unusable
2 keyboard configuration is a nightmare
3- You can not edit the SSID of wifi
4- you can not edit the password
5- kodi leaving the screen go black
6- could not verify more failures because the system can not use this is in Chinese

**Comment by digitalLumberjack** [comment]
This is recalboxOS **v4.0.0-beta1**, what did you expect ?
All issues are already reported. This post is useless and kind of rude, i close, please be more useful next time.
