### ISSUE TITLE
[4.0.0] PSX game list 

### ISSUE THREAD

**Issue by showinfo** [recalbox/recalbox-os#772]
RPI2 model B and recalbox 4.0.0 beta1

My PSX rom consisted of gamename.bin and gamename.cue

that is two files, Only One game!

But PlayStation gamelist print two same GameName in ES

![20160304_121056](https://cloud.githubusercontent.com/assets/17563094/13516983/6a67a7a6-e202-11e5-8224-c7da2ddc5ffd.jpg)

I think need fix so.

**Comment by MikaXII** [comment]
Hi, check this issue #290

**Comment by showinfo** [comment]
@MikaXII first thanks. 
i understood that, but impossible  /recalbox/share_init/system/.emulationstation/es_systems.cfg file.
(Chaged .emulationstation folder for 4.0.0)
because read-only filesystem

**Comment by MikaXII** [comment]
Connect to recalbox (ssh or putty) and `mount -o remount,rw /`. after that you'll be able to update everything you want.

**Comment by showinfo** [comment]
@MikaXII thanks 
I edit es_systems.cfg follow that and reboot, gamelist reloaded
<extension>.img .IMG .pbp .PBP .bin .BIN .iso .ISO</extension>

but gamelist is duplicate too

**Comment by Northwave** [comment]
You have to delete the `.bin .BIN` extension. Then it should be fine :)

**Comment by showinfo** [comment]
@Northwave ok.. i deleted .bin, BIN in extension and reboot 
but duplicate too :(

![cap 2016-03-04 18-21-16-968](https://cloud.githubusercontent.com/assets/17563094/13522978/eec2226e-e235-11e5-971f-bfc1659e7d3e.png)

**Comment by rockaddicted** [comment]
haha if he delete .cue +.bin extension, no more games bin/cue will be displayed.
nope the problem if that ES has written informations about your files in the /roms/psx/gamelist.xml
So you have to edit this file : 
- once on recalbox, kill ES (F4 with a keyboard plugged on recalbox or killall emulationstaion in ssh)
- edit your gamelist.xml removing unnecessary informations.
- save and reboot

**Comment by showinfo** [comment]
@rockaddicted oh my god! Successed remove gamelist.xml and reboot
thanks

**Comment by rockaddicted** [comment]
you are welcome

**Comment by Northwave** [comment]
Thx @rockaddicted, I didn't know that the informations are cached in this file :) Maybe add this instructions to the wiki?

**Comment by LipkeGu** [comment]
maybe also add a howto to create the cue files too?

**Comment by rockaddicted** [comment]
You can add an howto text file inside psx's roms folder and/or create a [wiki page](https://github.com/recalbox/recalbox-os/wiki/Mini-How-To-%28EN%29).

**Comment by faonbr** [comment]
Actually, I only use .bin, .img, .mdf files.
not cue.
