### ISSUE TITLE
[4.0.0-beta1] Pre-boot splash not available

### ISSUE THREAD

**Issue by dsearle2** [recalbox/recalbox-os#773]
Option to enable pre-boot splash not in config, doesn't work after adding either.

**Comment by rockaddicted** [comment]
Hello,
are you talking about the rainbow splash screen ?
It is disabled by default in this file : https://github.com/recalbox/recalbox-buildroot/blob/rb-4.0.X/package/rpi-firmware/config.txt#L28

**Comment by dsearle2** [comment]
No, in the previous builds there was an option to replace the black screen that contained the build number with a recalbox splashscreen, however it I cant seem to enable it

**Comment by nadenislamarre** [comment]
the boot splash is completly different in 4.1.
We should close this one.

**Comment by nadenislamarre** [comment]
digit, you confirm we can close ?

**Comment by dsearle2** [comment]
Yes
