### ISSUE TITLE
Upgrade moonlight seperately

### ISSUE THREAD

**Issue by LOSSLOSS** [recalbox/recalbox-os#774]
Testing the 4beta over here. So some thoughts on implementations.

I read about problems concerning GFE 2.10 not working well with moonlight 2.1.3. Rather quickly a patch for it was made for it. To bad recalbox doesn't have a packagemanager. I could not update it.

Since Nvidia is changing their software frequently it might be an idea to implement an option to upgrade moonlight seperatly from the OS.

Love to hear your thoughts on this.

**Comment by substring** [comment]
Hi @LOSSLOSS 
See recalbox as a ROM, a whole OS that wasn't built for tiny updates. I get your point with moonlight, and the patches are already set : https://github.com/recalbox/recalbox-buildroot/pull/206

You can get the Moonlight.sh by yourself and update it in your recalbox if you wish

**Comment by LOSSLOSS** [comment]
Hey @substring 

Thanks for your answer.

I do understand this and love the fact it is dedicated for one purpose. It makes it a lean mean gamingmachine.

So you say I can upgrade just by replacing the changed lines of code given when I open your link?

**Comment by substring** [comment]
yeah, tested with a few people already. You need to `mount -o remount,rw /` then replace /recalbox/scripts/moonlight/Moonlight.sh with the patched one. Dunno how skilled you are on Linux ...

Or wait for beta2 ;)

**Comment by nadenislamarre** [comment]
digit cant we release beta 2 for that kind of fix even if some major bugs
remain ?

**Comment by LOSSLOSS** [comment]
@substring 

Yes I've mounted it already as RW because I had to edit fstab to get roms on my NAS working.

Oh patch the entire file? Well I could not find it available for download. 
I'm kinda referring to the new moonlight version: [click](https://github.com/irtimmer/moonlight-embedded/releases/tag/v2.1.4)

And no I'm not that skilled yet as I bought a RPI last December. But I'm building my skillset gradually and liking it. Reading and learning a lot.

**Comment by substring** [comment]
@LOSSLOSS ok, let me do it for you :
``` shell
mount -o remount, rw /
cd /recalbox/scripts/moonlight
wget https://raw.githubusercontent.com/recalbox/recalbox-buildroot/rb-4.0.X/board/recalbox/fsoverlay/recalbox/scripts/moonlight/Moonlight.sh -O Moonlight.sh 
```

**Comment by LOSSLOSS** [comment]
@substring you've been the nicest while I'm just noobing around. Thanks a lot. 

I will try to contribute to the recalboxproject when I can.

**Comment by substring** [comment]
@LOSSLOSS if it works, close your issue ;) It has nothing to do with noobing around, just giving you a taste of beta2

**Comment by LOSSLOSS** [comment]
Thanks. Well it doesn't solve my Dynamic res problem with GFE 2.10 but I'm patient enough to wait for the next release.

Closing.

**Comment by substring** [comment]
2.1.4 doesn't solve it either i'm afraid. I've tried it, keeps crashing on the intro of Ultra Street Fighter 4. Don't know if it's linked to fynamic resolution, but that problem is not solved
