### ISSUE TITLE
[4.0.0-beta1][ES] ZX Spectrum games won't launch when Rewind is activated

### ISSUE THREAD

**Issue by wouaco** [recalbox/recalbox-os#776]
When option Rewind is activated, ZX Spectrum games won't launch.

Deactivating the Rewind option can be used as a warkaround until this issue can be fixed.
----------------------------------------------------------------------------------------------------------------
Lorsque l'option Rembobinage est activée, les jeux ZX Spectrum ne se lancent plus.

En attendant le correctif, il suffit de désactiver l'option pour que les jeux se lancent.

**Comment by rockaddicted** [comment]
use kempston joystick as default

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-configgen/pull/57 fixes the joysticks
https://github.com/recalbox/recalbox-buildroot/commit/7851887cac1394210caf78ed91451490f95d30d4
