### ISSUE TITLE
[4.0.0] [retroachievments] long time to start a game when no network and archievements is on

### ISSUE THREAD

**Issue by nadenislamarre** [recalbox/recalbox-os#777]
### What happened
i plug my raspberry on a no network environment
i run a psx game and the screen stay black
after several tries (i reboot thinking about a recalbox crash) i see it just takes a very very long time

### What should have happened
perhaps have a shorter timeout for retroachivement if possible
i guess some other people would report this as a bug later without seeing the time is long just as i did.

### How to reproduce the bug
- unplug the network
- configure retroachivement
- start a game

**Comment by nadenislamarre** [comment]
or don't enable retroachievement when there is no network.

**Comment by rockaddicted** [comment]
We can too enable this option only with core supporting it, by adding this kind of switches in recalbox.conf, as we are doing with rewind option : 
`psx.retroachievements=0`
Retroarch won't calculate hash of the game during the start sequence.

**Comment by substring** [comment]
@rockaddicted i think it's solved with beta2 ?

**Comment by rockaddicted** [comment]
should be ok @nadenislamarre can you confirm ?
