### ISSUE TITLE
[4.0.0-beta1]
PRBOOM Music Issue

### ISSUE THREAD

**Issue by Death259** [recalbox/recalbox-os#778]
Music playing in prboom, doesn't appear to be working out of the box the way I believe it is intended to.

With a fresh install of 4.0.0-beta1 there is a readme file in the game-musics folder underneath the prboom folder that says to place music in the game-musics folder. Upon running prboom for the first time, the prboom.cfg gets created and it lists out the music files expected. If you place the music in the game-musics directory you, however don't get any music. This is caused by the prboom default config looking for music in the same directory that the prboom.cfg file is in. Upon further inspection, I was able to add ./game-musics/ in front of each mp3 filename and now they work in the expected directory.

**Comment by paradadf** [comment]
This is not an issue. There is an readme.txt inside the music folder explaining exactly what you wrote before.

**Comment by Death259** [comment]
Ahh, then I must have misunderstood what the readme was wanting. Please
forgive my stupidity.
