### ISSUE TITLE
[4.0.0-beta1] 8BitDo Nes30 s'appaire mais config impossible

### ISSUE THREAD

**Issue by SebDis** [recalbox/recalbox-os#780]
Salut à tous, j'ai un problème avec ma NES30 en bluetooth et la v4.0 beta1, la manette s'appaire bien (en mode start + r) le menu d'appairage fonctionne correctement, mais ensuite impossible de la paramétrer pour les boutons et aucun bouton ne réagis dans le menu.
Adresse mac + nom manette parfaitement reconnu.

Sur la version 3.3.0 beta17 aucun souci. Appairage + Utilisation nickel.

Config: Pi 2/B+ / Nes30 - 8BitDo (v2.65) / Dongle Bluetooth Logilink BT0007a

(Fonctionne parfaitement sous V3.3.0 - beta17)

Suis je le seul ?
Je ne suis pas un grand informaticien....

**Comment by ptitomgab** [comment]
Salut

Problème identique avec une manette 8bitdo Zero appairage OK avec la V4.0 b1 mais aucune commande ne fonctionne en mode Start+R. En mode Start la croix directionnel fonctionne pas les bouton.
Sur la version 3.3.0 B17 la manette fonctionne parfaitement

Testé sur PI 1B et PI 2B / Dongle Bluetooth CSL - USB micro Adaptateur Bluetooth- V4.0

**Comment by SebDis** [comment]
Je me sens moins seul du coup. Je pensais que c'était que moi mais apparemment non. Je ne sais pas si la nouvelle version (bêta 2) corrige ce problème. Je regarde ca demain.

**Comment by SebDis** [comment]
Après avoir tester la beta 2 la manette fait exactement la même chose elle s'appaire mais aucune config possible.

**Comment by appt164** [comment]
Bonjour SebDis,

Pour ma part je n'ai pas eu le même comportement (NES 30 Pro + FC30 Pro).
1 seule manette en mode JoyStick fonctionne très bien.
Cependant j'ai eu des soucis lorsque j'allumais les 2 (en mode keyboard 1/2), Elles fonctionnent dans EmulationStation mais pas dans les jeux.

Je fais un test ce soir sur la 4.0 Beta 2

**Comment by ptitomgab** [comment]
Avec la Beta 2 ma manette fonctionne correctement sur emulationstation
Pas encore testé sur les jeux mais c'est beaucoup déja beaucoup mieux

**Comment by SebDis** [comment]
Bah moi ça veut pas. Vous allumer la manette en mode start + r ?

En mode keyboard (Start) juste le pavé directionnel qui fonctionne aucun bouton ne réagis...

Avez vous touché au fichier recalbox.conf ?

**Comment by rockaddicted** [comment]
Alors déjà en mode keyboard, ça ne fonctionnera jamais sous recalbox. Il faut démarrer la manette en mode gamepad.
Si vous êtes passé d'une 4.0.0 beta1 à une beta2 via le système d'update, sans refaire une installation, pourriez vous exécuter cette ces commandes en SSH, puis refaire un test ?
```
cp /recalbox/share_init/system/.emulationstation/es_input.cfg /recalbox/share/system/.emulationstation/es_input.cfg
```
puis
```
reboot
```
Une fois les commandes et reboot ok, refaite l'appairage de votre manette **SANS** refaire de mapping de cette dernière, puis testez.

**Comment by nadenislamarre** [comment]
ou meme mieux :
rm /recalbox/share/system/.emulationstation/es_input.cfg

**Comment by SebDis** [comment]
Ca fonctionne merci.
Par contre qu'est ce que cela change de copier la config dans le dossier share plutôt que de le laisser dans le dossier share_init ?

**Comment by rockaddicted** [comment]
c'est le fichier contenant les mapping de chaque manette, et celui présent dans `/share` n'est pas mis à jour lors d'une mise à jour système, contrairement à celui dans `/share_init`.
Donc manettes ok avec le nouveau mapping inclus dans la beta2 ?

**Comment by SebDis** [comment]
Oui ça fonctionne nickel. Ok pour le fichier. Par contre j'avais le problème dans la bêta 1 déjà. Donc je sais pas si le fichier de base était bon. La j'ai fait une install complète depuis la bêta 1 puis mise à jour et la manip que tu m'avais donné. Et la ca marche nickel. Merci encore.

**Comment by rockaddicted** [comment]
ok je ferme alors
