### ISSUE TITLE
[4.0.0-beta1][ES] RPi2, overclock option EXTREME results in crash after reboot

### ISSUE THREAD

**Issue by gr3y5had0w** [recalbox/recalbox-os#782]
### What happened
Crash on start after reboot because changing Overclock-Option to EXTREME. Turbo and high are working.
### What should have happened
Not crash obviously.
### Enumerate your devices
Raspberry Pi 2
MS XBox360 Controller
Ethernet
### How to reproduce the bug
Change Overclock-Option to EXTREME on RPi2. Not able to test on RPi1.

**Comment by digitalLumberjack** [comment]
Hi, yes the rpi2 extrem overclock may be unstalbe on 20% rpi2.
We will add a popup saying it's not a good idea to do that except if you know what to do :)

Thank you for the report :)
https://github.com/recalbox/recalbox-os/issues/692
