### ISSUE TITLE
Wii classic controller problems

### ISSUE THREAD

**Issue by elpaulo** [recalbox/recalbox-os#783]
### What happened

I successfully paired a wiimote with a classic controller plugged in, i can map the buttons from the wiimote except the R button of the classic controller.

Then i lauch a snes game, and no buttons of the classic controller are working, but the wiimote buttons are ok.

### What should have happened

I should have mapped the R key of the classic controller, and the keys sloud work ingame.

### Enumerate your devices

Raspberry pi 2B, Nintendo Wiimote and Nintendo Classic controller

**Comment by nadenislamarre** [comment]
can you confirm its on recalbox 4 ? can you tell if thats an official
remote ? can you run /recalbox/script/recalbox-support.sh and send the file.
works with my 2 wiimotes+controller. hope the report will help.

**Comment by nadenislamarre** [comment]
do you have understood that it wors zs 2 pad : you can play at 2 players.
you can force the coltroller to player1 in the coltroller menu

**Comment by elpaulo** [comment]
Yes i got the latest release of recalbox, and the wiimote and the classic controller are official.

I will send you the file tomorrow and try to force player one thanks.

**Comment by nadenislamarre** [comment]
no feedback ?
i will close considering it's ok.

**Comment by nadenislamarre** [comment]
file never received.
Works for me.
I close.
