### ISSUE TITLE
[4.0.0-beta1] Wifi configuration error

### ISSUE THREAD

**Issue by paradadf** [recalbox/recalbox-os#788]
### What happened

Wifi would ramdomly (but too often) not connect at all. It shows an IP Adress that looks like fe##:ea#e:##:fe#b:###e. Restarting Recalbox would sometimes solve the issue, normally it doesn't. Turning the wifi off, going back to the main menu, entering the network settings again, turnig wifi on and hitting back, refreshes the conmection and also might help, but usually a "wifi configuration error" shows up. 
### What should have happened

I don't understand why the wifi works one day and another don't, but a few hours later it does! That behavior happens without touching anything.
### Enumerate your devices

Rpi 2 B, EDUP 8508GS Wifi adapter
### How to reproduce the bug

It's difficult to reproduce. It just happens and I don't know if other users are experiencing the same problem aswell.

**Comment by substring** [comment]
Looks like your wifi gets an IPv6 IP

**Comment by nadenislamarre** [comment]
its the automatic avahi config if ghe wifi takes too long to connect. i
increased the timeout when i got the issue. it could be the same issue.

**Comment by nadenislamarre** [comment]
Can you upgrade this 20s timeout

or better,
in this line https://github.com/recalbox/recalbox-buildroot/blob/rb-4.0.X/board/recalbox/fsoverlay/recalbox/scripts/recalbox-config.sh#L35

add a ligne just before return 1 :
echo "---- wifi timeout ----" >> $log

and when the problem occurs, check the log to confirm or not if that's a timeout issue.

https://github.com/recalbox/recalbox-buildroot/blob/rb-4.0.X/board/recalbox/fsoverlay/recalbox/scripts/recalbox-config.sh#L357

**Comment by nadenislamarre** [comment]
we should commit this line however for future issues

**Comment by paradadf** [comment]
Sorry I didn't understand the first part. Where exactly should I change a value to 20?
in this line? https://github.com/recalbox/recalbox-buildroot/blob/rb-4.0.X/board/recalbox/fsoverlay/recalbox/scripts/recalbox-config.sh#L26

**Comment by paradadf** [comment]
Excuse me please. but I don't understand where to change the 20.

**Comment by paradadf** [comment]
Same behavior with 30. But as I said before, sometime it connects directly and fast and sometimes it doesn't.

**Comment by paradadf** [comment]
Is not far at all... 10 meters at most.

**Comment by substring** [comment]
It could be a device issue, i never had a problem with wifi on v400b1

**Comment by paradadf** [comment]
I use OpenELEC with the same adapter and it works flawlessly.

**Comment by nadenislamarre** [comment]
i guess that openelec does several tries. We will do it when netmanager or
similar things will be used.

2016-03-11 19:34 GMT+01:00 paradadf <notifications@github.com>:

**Comment by substring** [comment]
@paradadf had the problem with my pi3, solved it by changing security to WPA2. Might be worth a try

**Comment by TeenTin** [comment]
I really hope that recalbox can support open wifi (i.e. wifi with no password protection).

**Comment by paradadf** [comment]
@substring my router has WPA2-PSK and AES currently for security :S

**Comment by rockaddicted** [comment]
@paradadf what is your wifi channel ?

**Comment by paradadf** [comment]
Channel 1

**Comment by rockaddicted** [comment]
can you try to switch an channel 10 please

**Comment by paradadf** [comment]
Same behaviour as before with channel 10. It's really random. If you think it's not something from recalbox but from my adapter, please close the issue. I don't hear people complaining about the same thing.

**Comment by substring** [comment]
@paradadf can you try `wpa_supplicant -B -iwlan0 -c/var/lib/wpa_supplicant.conf -d`, let it run a few seconds and make me a pastebin of the output ? Make sure you see the SSID in the list. If not, mention it

**Comment by paradadf** [comment]
http://pastebin.com/9LuFdFCQ

**Comment by nadenislamarre** [comment]
substring: in case of timeout/error, we should add a such command to the log, shouldn't we ?

**Comment by nadenislamarre** [comment]
network management upgrade in 4.1.
Should solve the issue.
A feedback is wanted (once 4.1 beta will be available)

**Comment by paradadf** [comment]
I'll do so, thanks.

**Comment by nadenislamarre** [comment]
@paradadf same issue in 4.1 or we can close ?

**Comment by paradadf** [comment]
I'll close it for you! It works wonderfully now! One of the best improvements by far XD, thanks a lot!

**Comment by HAL-XP** [comment]
FYI I had the issue on 4.0.2
(As far as I know 4.1 isn't out yet, isn't the 4.1 referenced above 4.0.1 instead?
