### ISSUE TITLE
Possible fix for RPi3 Bluetooth Support

### ISSUE THREAD

**Issue by matthuisman** [recalbox/recalbox-os#792]
Hi,

First of all, sorry about uploading the RPi3 build before you released it.
I saw it in you archive.recalbox directory, so thought it would be ok :(

Secondly, this commit here (from OpenELEC) might be of interest to get Bluetooth working...

https://github.com/OpenELEC/OpenELEC.tv/pull/4780/files

**Comment by substring** [comment]
hey @matthuisman 
It's not a good idea to release internal builds, you'd better wait for the official release for your side project ;)

Thank you for your investment concerning BT !

Talking about bluetooth, the topic is a little more complicated. We had it working but :
- no official relsea from the RPi foundation, just some"hey guyz, this is how it was patched for raspbian" ... ahem ...
- we had those patches already from https://github.com/raspberrypi/linux/issues/1314 but bluetooth only run at 115200 bauds, not full speed + using bluez5. So we preferred to release a first beta with pi3 support(which is fully compiled for pi3, it's not a pi2 patched version, and can only run on pi3 thus the increase of 200MB of the .zip release).

Now, let's enjoy the Pi3 support in beta2 and see how things turn from the RPiF about BT

**Comment by TeenTin** [comment]
Beta2 cannot be run on pi2 ?

**Comment by matthuisman** [comment]
@TeenTin 

It works fine on the Pi2.
When you download the release, there are 3x folders in the OS folder.
One for RPi1, one for RPi2, and one fore RPi3.

Simply use the RPi2 build :)

**Comment by TeenTin** [comment]
I see.  Thanks for the great work very very very much indeeeeeeed !!! :)

**Comment by matthuisman** [comment]
I hope your not thanking me, I'm just a humble user :)

**Comment by matthuisman** [comment]
I hope your not thanking me, I'm just an end user :)

**Comment by TeenTin** [comment]
Thanks for you prompt response, at least.  :)

**Comment by bigboo3000** [comment]
I saw this, can it be interesting for you or not at all?
https://www.pi-supply.com/make/fix-raspberry-pi-3-bluetooth-issues/?v=11aedd0e4327

**Comment by eddywebs** [comment]
why was this issue closed ?

**Comment by matthuisman** [comment]
Sorry. I must of closed accidentally :)

**Comment by substring** [comment]
may i close ? most discussions about pi3 BT are on #796

**Comment by matthuisman** [comment]
Yup. Closed now :)
