### ISSUE TITLE
[4.0.0-beta2] toujours même problème 8BitDo Nes30 s'appaire mais config impossible

### ISSUE THREAD

**Issue by SebDis** [recalbox/recalbox-os#795]
Salut a tous, je fais un retour de bug, ma manette 8BitDo NES 30 s'appaire correctement mais aucune config possible dans ES, le problème se posait deja en 4.00 beta 1 alors qu'en 3.3 b17 aucun souci de config tous fonctionne nickel.

Rpi 2/b+ - 8Bitdo NES 30 (v2.65) - Logilink BT007a

**Comment by rockaddicted** [comment]
pourquoi ouvrir un nouveau ticket alors que tu en as déjà ouvert un pour le même soucis https://github.com/recalbox/recalbox-os/issues/780
