### ISSUE TITLE
add hardcore mode in retroachievements

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-os#797]

**Comment by rockaddicted** [comment]
done with https://github.com/recalbox/recalbox-buildroot/pull/271

**Comment by Laddyacris** [comment]
Enable retroarchievements > hardcore > on

### What happened
hardcore is enable for all core libretro and 
impossible to use savestates and rewind.

### What should have happened
hardcore will be enable for libretro core only compatible with retroachievements.
NES, SNES, MEGADRIVE, GB/GBA And pc engine.

when hardcore is OFF in ES Menu, reboot rpi, hardcore is on in retroarch
Launch game and go to retroarch (hotkey+b) retroachievements menu > hardcore is ON again.

### Enumerate your devices
RPI2/3 - SNAKEBYTE IDROID GAMEPAD, MICROSD 8/16Go/
roms on usb key

### How to reproduce the bug
Enable hardcore in retroachievements Menu in EMULATIONSTATION
Play game psx 
Disable hardcore in retroachievements Menu in EMULATIONSTATION
Play game

**Comment by rockaddicted** [comment]
Thank you for your feedback @Laddyacris . I'll check that

**Comment by rockaddicted** [comment]
corrected
