### ISSUE TITLE
[4.0.0] Add Adafruit TFT Support

### ISSUE THREAD

**Issue by Cluf20** [recalbox/recalbox-os#805]
Is it be possible to integrate the repository adafruit for TFT screens in a future update recalbox ?
I'm trying to work on a handheld based in adafruit TFT screen and a raspberry pi 2. I got to make it all work under retropie , graphics rendering is not bad for a 3.5 "screen but retropie is definitely less good class so I would like to term recalbox my console running recalbox !
I 'm trying to draw the shell of the console ! When I have a little advance I would hand you the first images and if ca told someone I can share the plans then printed on a 3D printer.

The repository is the following address:
https://github.com/adafruit/Adafruit-PiTFT-Helper

**Comment by torch2424** [comment]
This would be awesome :)

I was working on a raspberry pi gameboy console, and Wanted to use recalbox over retropie. But I have an Adafruit 2.2 tft, so this would need to work. But I would be stoked if it was added!

**Comment by torch2424** [comment]
This seems to be being worked on in #915 :) I'd go there if you stumble across this!

**Comment by substring** [comment]
let's continue the discussion over at #915 :)
