### ISSUE TITLE
Rpi 3 overclock option.

### ISSUE THREAD

**Issue by slowmo310** [recalbox/recalbox-os#806]
Please enable overclock from frontend.

**Comment by substring** [comment]
This is no issue. There are hardly any pi3 that can be overclocked yet, and we still need some overall feedback on pi3 stability

**Comment by slowmo310** [comment]
In fact, it can be overclocked fine. I have one of mine running at 1.4 Ghz in Raspbian Jessie, aswell as in retropie.

**Comment by Laddyacris** [comment]
> Not for the moment, we need to practice stability tests before adding an overclock setting.
