### ISSUE TITLE
[4.0.0-beta2] [raspberry pi 3]Manette Xbox One not detect

### ISSUE THREAD

**Issue by K4ytan** [recalbox/recalbox-os#808]
Raspberry 3, Manette xbox One, Recalbox 4.0.0 Beta 2

Hello even by activating the driver my Xbox controller is not working

thank you in advance

**Comment by digitalLumberjack** [comment]
bluetooth ? usb ? 
The xbox one controller has never been specified like it is compatible with recalbox :)

**Comment by K4ytan** [comment]
Usb and bluetooh none works

**Comment by rockaddicted** [comment]
Yep this gamepad was compatible ... in the past ... but Microsoft had updated the firmware, and xbox one gamepad is no more supported.

So, can you test something ?
go in your `recalbox.conf` file, check if the xboxdrv driver is disabled : 
```
# ------------ D2 - XBOX Controllers ------------ #
## Xbox controllers are already supported, but xboxdrv can solve some compatibility issues 
## Enable xboxdrv driver, disable this if you enabled ps3 controllers (0,1)
controllers.xboxdrv.enabled=0
## Set the amount of controllers to use with xboxdrv (0..4)
controllers.xboxdrv.nbcontrols=2
```

Then always in this file, switch on nightlies updates : 
```
# ------------ G - UPDATES ------------ #
## Automatically check for updates at start (0,1)
updates.enabled=1
# default : stable ; set to beta to get the next version currently beeing tested. set to unstable at your own risk to get the developpment version.
updates.type=stable
```

Then save and reboot.
RecalboxOS will alert you than an update is available. Go in system options, then start update.
Once reboot, update process ok, plug your xbox one gamepad in USB, then try it.

**Comment by rockaddicted** [comment]
haha pas vu ton pseudo...
Le même K4ytan de forum.hardware qui vient de tester le patch ? :wink:

**Comment by K4ytan** [comment]
Oui Oui je suis celui du forum.hardware ^^

**Comment by rockaddicted** [comment]
je clôture alors
