### ISSUE TITLE
[4.0.0-beta2] RPI3 system settings 

### ISSUE THREAD

**Issue by bradyfox94** [recalbox/recalbox-os#809]
Every time i go to click on system settings the rpi3 always reboots and doesnt start back up. ive reinstalled it twice and checked in on my rpi2 and it seems to work fine so its just affecting rpi3. does anyone have a way to fix this.

**Comment by peterpan123123** [comment]
I did mess up the /boot/recalbox-boot.conf and had the very same problem, except the sd wasn't corrupted afterwords.
Does this happen even the first time you click on System Settings right after new Setup?

**Comment by bradyfox94** [comment]
Yea happens right after a fresh setup

**Comment by digitalLumberjack** [comment]
@peterpan123123 did you messed it up by editing by hand ?
@bradyfox94 can you try to format the sd card with an other tool ? Did you change anything (manually or not) after the install, and before going to the SYSTEM SETTING menu ?

**Comment by peterpan123123** [comment]
> @peterpan123123 did you messed it up by editing by hand ?
Yes. But the workaround https://github.com/recalbox/recalbox-os/issues/807 solved all my problem.

**Comment by mcaron1234** [comment]
This same thing is happening to me.  Fresh install.  I tried going into system setting immediately, even before I setup the network.  Freshly formated card using gparted. Instant crash to black screen with recalbox logo and version number.  I only need to change the storage to a usb thumbdrive, is there a file I can edit manually to make that change?

**Comment by mcaron1234** [comment]
@bradyfox94 I fixed this by editing the sharedevice in recalbox-boot.conf.  after I set that to my usb key I was able to go into the system settings.

**Comment by digitalLumberjack** [comment]
@nadenislamarre @rockaddicted any idea on what could have happen ?
@mcaron1234 what did you modify in recalbox-boot.conf ?

**Comment by nadenislamarre** [comment]
i just know that i've fixed a bug for the beta3.
otherwise, having a rpi3, just run the command and see ;-)

**Comment by digitalLumberjack** [comment]
@nadenislamarre you might have guessed that it does work at home if i asked if you have any idea.

**Comment by mcaron1234** [comment]
@digitalLumberjack I changed:
`sharedevice=INTERNAL` to
`sharedevice=DEV d9edd4d4-65e4-4a06-8f3c-24837adfe44f`

More info:

- Recalbox is installed in a dual boot noobs environment with osmc
- The usb key is formatted as ext4

**Comment by digitalLumberjack** [comment]
Fixed in beta3
