### ISSUE TITLE
Adding PinMame for support of pinball games

### ISSUE THREAD

**Issue by zico92** [recalbox/recalbox-os#810]
Is it possible to add the PinMAME emulator Recalbox for pinball support ??

**Comment by rockaddicted** [comment]
Is there an arm version comptible with raspberry?
Do you have a link to the source code? More informations about it ?

**Comment by zico92** [comment]
On peut se le faire en français, ça te dérange pas?? 

Bah pas spécialement, j'ai cherché un peu et j'ai trouvé ça:
https://github.com/mscottford/pinmame/blob/master/src/cpu/arm7/arm7core.c

Après j'ai posté une issue pour voir si c'est faisable ou pas, je pense que beaucoup de monde serait intéressé!!

**Comment by moriceh** [comment]
C'est vrai que ce serait super, mais alors vraiment génial !

**Comment by rockaddicted** [comment]
Yep but I didn't find ports of this on arm...
So I close this issue.
If you find an arm version working on rpi, reopen this issue and add a link.
