### ISSUE TITLE
[4.0.0-beta2] Roms partition isn't FAT32 anymore. I think it's EXT4?

### ISSUE THREAD

**Issue by gabrielcrowe** [recalbox/recalbox-os#815]
![diskutil list](http://i.imgur.com/X0cVqKq.png)

### What happened
I ran a normal install and everything came up as expected, i went to add roms by taking the sd card out and putting it in my computer like i always do.

### What should have happened
I should see it mounted because it should be FAT32

### How to reproduce the bug
I think this is done by the noobs installer of 4.0.0-beta2.

**Comment by substring** [comment]
Dude, that's no issue, that's something we decided on our own for a better survival to savage reboots. Quite much more stable since. Have you noticed also / and /boot are read-only now ? ;)

**Comment by gabrielcrowe** [comment]
:( this was a very useful feature. thanks for the info.

**Comment by substring** [comment]
I guess you have a Mac ?

**Comment by gabrielcrowe** [comment]
I do, and i installed paragon extfs to fix this problem and access the partition, solved. :)

**Comment by gabrielcrowe** [comment]
after some messing about i find that i cannot copy files to the sd card with my mac properly under any settings and I cant get a linux machine where i am.

I'm reverting to an older version of recalbox and probably abandoning it later since for me, this is an essential feature.

**Comment by nadenislamarre** [comment]
gabrielcrowe, note that you can use external usb key too in fat32/ntfs/hfs
