### ISSUE TITLE
Zip File Support for Games

### ISSUE THREAD

**Issue by symbios24** [recalbox/recalbox-os#816]
Is the Latest version Supporting Compressed  games/roms in "Zip" format?

**Comment by rockaddicted** [comment]
https://github.com/recalbox/recalbox-os/wiki/Manual-%28EN%29#a---add-your-games

.Zip files are supported on all systems, except, N64, scummvm.
Else, we don't recommand to use .zip format on every systems based on CD support. Your rpi should uncompress / write on SD, a large file, everytime that you start a CD game.

**Comment by rockaddicted** [comment]
Next time, please read tthe recolbox's documentation, and you the forum to ask support.
Github is a development tool.
