### ISSUE TITLE
[4.0.0-beta2][ES] add Logitech Wingman USB gamepad mapping

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#822]
<inputConfig type="joystick" deviceName="USB gamepad           " deviceGUID="030000001f08000001e4000010010000">
		<input name="a" type="button" id="1" value="1" code="289" />
		<input name="b" type="button" id="2" value="1" code="290" />
		<input name="down" type="axis" id="1" value="1" code="1" />
		<input name="hotkey" type="button" id="8" value="1" code="296" />
		<input name="left" type="axis" id="0" value="-1" code="0" />
		<input name="pagedown" type="button" id="5" value="1" code="293" />
		<input name="pageup" type="button" id="4" value="1" code="292" />
		<input name="right" type="axis" id="0" value="1" code="0" />
		<input name="select" type="button" id="8" value="1" code="296" />
		<input name="start" type="button" id="9" value="1" code="297" />
		<input name="up" type="axis" id="1" value="-1" code="1" />
		<input name="x" type="button" id="0" value="1" code="288" />
		<input name="y" type="button" id="3" value="1" code="291" />
	</inputConfig>

**Comment by rockaddicted** [comment]
done
