### ISSUE TITLE
[4.0.0-beta2][ES] add XiaoMi bluetooth gamepad mapping

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#823]
<inputConfig type="joystick" deviceName="XiaoMi Bluetooth Wireless GameController" deviceGUID="05000000172700004431000029010000">
		<input name="a" type="button" id="7" value="1" code="305" />
		<input name="b" type="button" id="6" value="1" code="304" />
		<input name="down" type="hat" id="0" value="4" code="16" />
		<input name="hotkey" type="button" id="16" value="1" code="314" />
		<input name="joystick1left" type="axis" id="0" value="-1" code="0" />
		<input name="joystick1up" type="axis" id="1" value="-1" code="1" />
		<input name="joystick2left" type="axis" id="2" value="-1" code="2" />
		<input name="joystick2up" type="axis" id="5" value="-1" code="5" />
		<input name="l2" type="button" id="14" value="1" code="312" />
		<input name="l3" type="button" id="19" value="1" code="317" />
		<input name="left" type="hat" id="0" value="8" code="16" />
		<input name="pagedown" type="button" id="13" value="1" code="311" />
		<input name="pageup" type="button" id="12" value="1" code="310" />
		<input name="r2" type="button" id="15" value="1" code="313" />
		<input name="r3" type="button" id="20" value="1" code="318" />
		<input name="right" type="hat" id="0" value="2" code="16" />
		<input name="select" type="button" id="16" value="1" code="314" />
		<input name="start" type="button" id="17" value="1" code="315" />
		<input name="up" type="hat" id="0" value="1" code="16" />
		<input name="x" type="button" id="10" value="1" code="308" />
		<input name="y" type="button" id="9" value="1" code="307" />
	</inputConfig>

**Comment by rockaddicted** [comment]
This gamepad is mapped using a snes style ?

**Comment by bigboo3000** [comment]
yep!

**Comment by rockaddicted** [comment]
ok done
