### ISSUE TITLE
FileName for recalboxOS.png in recalboxOS-rpi1 and recalboxOS-rpi3 folders

### ISSUE THREAD

**Issue by palmipode** [recalbox/recalbox-os#824]
Hi

recalboxOS.png in /os/recalboxOS-rpi1 folder and recalboxOS.png in /os/recalboxOS-rpi3 should be renamed as recalboxOS-rpi1.png and recalboxOS-rpi3.png 

We can't see icons in Noobs for instance.

Regards

**Comment by digitalLumberjack** [comment]
Thanks 
https://github.com/recalbox/recalbox-rescue/commit/4f5d1a10ba12ca9423495be30048ab593c5fb474
