### ISSUE TITLE
[Feature Request] Default support for NESPAD by Xgaming?

### ISSUE THREAD

**Issue by Hedda** [recalbox/recalbox-os#826]
Please consider adding default support for the "NESPAD", which is a new cross-platform gamepad in extended SNES/NES/N64 retro-style combo by Xgaming of X-Arcade fame.

http://shop.xgaming.com/products/nes-wireless-gamepad-ios-android-mac

I know that Shawn Walters <shawn@xgaming.com> from Xgaming donated an Tankstick (XArcade) to developers before and bet they donate NESPADs too if asked ;)

**Comment by rockaddicted** [comment]
hummm it is a 8bit-do NES30PRO gamepad...
http://8bitdo.com/nes30pro/

And it is allready supported in recalbox.

**Comment by MikaXII** [comment]
@Hedda check this link : [wiki compatibility](https://github.com/recalbox/recalbox-os/wiki/Compatibility-(EN)#pad-controller)

**Comment by substring** [comment]
@Hedda what what what ? i've been working for a few months on integrating xarcade stuff to recalbox, i wouldn't mind at all any gift from xgaming

**Comment by substring** [comment]
Xgaming confirmed me that it's just a partnership with 8bitdo. Closing
