### ISSUE TITLE
[4.0.0-beta2][msx] add .dsk support for msx (disk based games)

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#832]
Currently bluemsx (and i think fmsx too) has no support for .dsk (disk files) in recalbox (only rom files).
Could you add this support?

**Comment by kryptalivian** [comment]
This as simple as altering retroarch.cfg?

**Comment by bigboo3000** [comment]
I don't think so. If you just rename a .dsk to .mx2, the emulator will boot but it will go to the MSX basic.

**Comment by rockaddicted** [comment]
http://www.msxblue.com/manual/runningdsk.htm

BlueMSX needs his menu or hotkeys to start/switch games in .dsk format.
So to add .dsk support, the libretro core needs to support too these features from the standalone emulator.
Until someone work on this, we can't add it to recalbox.

So for the moment I close this issue, and if in the futur the support is added upstream, I'll reopen it, and add it in recalbox.
