### ISSUE TITLE
Favorites don't show scraped data

### ISSUE THREAD

**Issue by paradadf** [recalbox/recalbox-os#836]
Roms flagged as favorites on the top of the list don't show any description nor image.
The same happens inside the favorites theme.

**Comment by rockaddicted** [comment]
hummm weird, that is working perfectly on my setup.
I can't reproduce this issue.
Maybe a scrapping issue.
Did you check your gamelist.xml files ?

**Comment by paradadf** [comment]
Say you enter sega32x and see all games. After scrapping them, I see the images and information of everyone. Then, when I select any rom as favorite, a sort of "copy" with a star before it goes to the top of the list. That game flagged as a favorite, does not show any image nor information.
If any game is scrapped correctly (showing everything on screen), shouldn't the same one scrapped as a favorite show everuthing as well directly?

**Comment by substring** [comment]
Dude, if there is a template for issues that you purposedly deleted when you wrote down your problem, that's to have a guaranteed way to reproduce the bug 100%. So please, on next bug, read and fill in information we need

**Comment by paradadf** [comment]
@substring I'm sorry I didn't followed the template, but there is no need to be rude. I was, like always, just trying to help improving recalbox. I never demand something and if you don't appreciate that users, even if not always in the best possible way, do their best to contribute, then I will stop doing so.
There is a reason why I PURPOSEDLY, as you "kindly" stated, deleted the template. I thought that showing the scraped data on games flagged as favorites and the one showed on the favorites theme was't implemented at all. Asuming that would have been true, I think my explanation was more that accurate and enough to correct it, if the developers think that's an improvement.
Very often I read comments (demands) from users that sound rude, and they get rude answers as well. But if someone tries to contribute to the work you are doing, you should be more polite (and the way you answer wasn't).

**Comment by substring** [comment]
I didn't mean to be rude, all my apologies. English is not my native tongue, i do my best :/

I just wanted to point something quite easy : it's necessary to fill the template. Sorting out issues from support is time consumming. It's much easier when we have a way to reproduce the bug *from the start*, don't you think ?

I know you've been contributing quite much and also do your best to be as informative as possible. Please understand how we feel too : you raise an issue, we couldn't reproduce it unless you added some info. Things are done upside down !

**Comment by substring** [comment]
@paradadf this is what i've done :
- use the internal scraper for a game
- set it as favourite with Y
Scraping info is shown in both it's root system and favourites system.

Have i missed something in the steps to reproduce the bug ?

**Comment by paradadf** [comment]
Luckly I can't reproduce it either. I did a fresh install because a dual boot I have and now it works.
