### ISSUE TITLE
 [4.0.0-beta2][/boot/recalbox-boot.conf] Can' switch back from USB key to INTERNAL

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-os#840]
### What happened

I wanted to switch back share to INTERNAL. But it keeps staying on my USB key unless i remove it
### What should have happened

Switching to INTERNAL should work upon reboot
### How to reproduce the bug
- plug a key
- switch to it in system options
- reboot
- switch back to internal
- reboot

Please note : the recalbox-boot.conf looks like this :

```
internal=/dev/mmcblk0p8
sharedevice=DEV F936-1D44
sharedevice=INTERNAL
sharedevice=INTERNAL
```

I guess there should be only 1 sharedevice ;)

**Comment by nadenislamarre** [comment]
bug alrzady fixed. please use a rece t version ;+)

**Comment by substring** [comment]
Haha ! I'm not on unstable :p

But you can't use the recalbox-sync script when you set your share to a usb key :(

**Comment by nadenislamarre** [comment]
why ?

**Comment by substring** [comment]
It just lists the internal device, not the key

**Comment by nadenislamarre** [comment]
normal.
it list all but current while cuttent is the source. plug a 2nd key to save
on an other key fir example

**Comment by rockaddicted** [comment]
So can be closed guys ?

**Comment by nadenislamarre** [comment]
subs, can we close ?

**Comment by substring** [comment]
Does it mean i have to test on a nightly ?

**Comment by nadenislamarre** [comment]
yes, or wait beta3 if not already out.
there is no hurry.

**Comment by nadenislamarre** [comment]
@substring can we close ?
