### ISSUE TITLE
[4.0.0-beta1][Buildroot] Dependency issue compiling qtsixa-shanwan

### ISSUE THREAD

**Issue by D3m0n1q733rz** [recalbox/recalbox-os#843]
### What happened

Error:  Makefile:459: **\* linux-headers is in the dependency chain of qtsixa-shanwan that has added it to its _DEPENDENCIES variable without selecting it or depending on it from Config.in.  Stop.
Makefile:36: recipe for target '_all' failed
make: **\* [_all] Error 2
### What should have happened

Completed compilation of recalbox 4.0.0-beta2
### Enumerate your devices

1
### How to reproduce the bug

Configure Buildroot to use already compiled header files for arm with hard float point and GCC 5.3.  Run make.
Errors immediately.

**Comment by D3m0n1q733rz** [comment]
I managed to get it to skip the error by removing linux-headers from the dependencies list in the make file for both qtsixa-shanwan and qtsixa make files.  Even though the dependencies have been removed from the list, the header files are still usable and available for cross-compilation.

**Comment by D3m0n1q733rz** [comment]
This problem is still a problem though.  Even though I can change the configuration file to not check for the dependency, it still shouldn't be causing the problem it's causing when I try to compile.

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0
