### ISSUE TITLE
system.emulators.specialkey dont working

### ISSUE THREAD

**Issue by DarthNeo2** [recalbox/recalbox-os#844]
I'm trying to disable the special keys and the emulator menu in the system.emulators.specialkey,i set to none and to nomenu and save but nothing have changed in games. Im using 4.0 beta 2, i have tested in the last unstable 32 and the problem stay there.

**Comment by digitalLumberjack** [comment]
Hi @DarthNeo2 you still can access menu with hk + b ? All the shortcut (savestate etc) works ?

**Comment by DarthNeo2** [comment]
@digitalLumberjack 
Yes the hk + b stil works and the all shortcuts too.

**Comment by digitalLumberjack** [comment]
Hey :)
I just saw that the key is not the one configgen search : 
rename system.emulators.specialkey in system.emulators.specialkeys (keyssss) :)

**Comment by digitalLumberjack** [comment]
Anyone having beta2 or before, the recalbox.conf won't update. So just rename system.emulators.specialkey in system.emulators.specialkeys (keyssss) :)

**Comment by DarthNeo2** [comment]
I have build 33 and this not work for me, i use "system.emulators.specialkeys=none"" or "system.emulators.specialkeys=nomenu" and still not word :(

**Comment by digitalLumberjack** [comment]
system.emulators.specialkeys=none and system.emulators.specialkeys=nomenu works on my pi.
It is only used by libretro emulators. What system are you trying ?

**Comment by DarthNeo2** [comment]
I trying to use in SNES and NES, snes9x and nestopia cores.

**Comment by Laddyacris** [comment]
build 48 - system.emulators.specialkey=nomenu doesn't work
build 48- system.emulators.specialkeys=nomenu doesn't work
build-55 system.emulators.specialkeys=nomenu 
j 'ai du modifié le recalbox.conf pour corriger le s qui manquait. it's work now.

**Comment by DarthNeo2** [comment]
Im in build 35, where i can find this build 55?

**Comment by digitalLumberjack** [comment]
you must set the update system in recalbox.conf to unstable (or wait for the soon to come beta3)

**Comment by digitalLumberjack** [comment]
I close, reopen if it doesn't work :)
