### ISSUE TITLE
[4.0.X][Hatari] Can't play IPF disks.

### ISSUE THREAD

**Issue by pasnox** [recalbox/recalbox-os#845]
### What happened
Can't play IPF disks
### What should have happened
Play games
### How to reproduce the bug
Open Barbarian game from no-intro (2015)

**Comment by rockaddicted** [comment]
As said in the atarist readme.txt file, this emulator only support .st and .stx files.
So be careful when you use a .zip file to check ROM extension used inside.

IPF games aren't supported upstream. I'll give a look to add it in a next recalbox release.

**Comment by pasnox** [comment]
According to the received message, it s a build flag missing to support it.

**Comment by rockaddicted** [comment]
yep and capsimage libraby to add as dependency

**Comment by pasnox** [comment]
Ah right.

2016-03-30 8:55 GMT+02:00 rockaddicted <notifications@github.com>:

**Comment by rockaddicted** [comment]
done with https://github.com/recalbox/recalbox-buildroot/pull/445
