### ISSUE TITLE
[4.0.0beta2] Rewind on Mame breaks Taito games emulation

### ISSUE THREAD

**Issue by Voljega** [recalbox/recalbox-os#846]
### What happened

Trying to launch most of Taito games (Bubble Bobble, Light Bringer) with default mame on 4.0.0beta2. Warning "Left/right/OK" mame menu shows and then black screen and back to ES

### What should have happened

Bubble ! Jump On Enemy ! Go to Upper Platform ! Eat Giant Cake !

### Enumerate your devices

Happens on both Pi2 and Pi3

### How to reproduce the bug

Just try it with a standard installation.

### How to correct the bug

Adding mame.rewind=0 to recalbox.conf correct the issues, maybe it should be added to the default recalbox.conf, but this also may be some kind of regression I don't think it appeared in 3.3.0beta17 (but not 100% sure maybe mame.rewind=0 was in the conf file at the time ?)

**Comment by rockaddicted** [comment]
done https://github.com/recalbox/recalbox-configgen/pull/56
