### ISSUE TITLE
[4.0.0beta2] [RPI3 + belkin BT dongle + 8bitdo ZERO] no gamepad detected

### ISSUE THREAD

**Issue by rumpledan** [recalbox/recalbox-os#847]
Hey folks,
as this is my first post I'd like to say hello and THX for your hard work!

### What happened
I just wanted to connect my PI3 (4.0.0beta2) with my 8bitdo ZERO gamepad. 
As long as I connect the ZERO via USB, emulationstation tells me that it has found a bluetooth device ("bluetooth pairing" mode in input configuration) and shows up the gamepad's name as well as its name. After detection I push the back-button to configure the controller but now it tells me that no gamepad has been detected yet.
When trying to connect it just by using BT (with the supported Belkin BTdongle) without USB connection it doesn't even show up in the "bluetooth pairing" mode. 

Something similiar happens when I'm trying to connect my PS3 controller--> detection only via USB, not via BT, but here at least a gamepad configuration is possible...although not wirless with dongle...

I really don't know what to do now. I really tried everything possible to me (as I'm a total noob regarding this kind of projects)

**Comment by kryptalivian** [comment]
Mine will detect and pair, but then when configuring buttons. It registers as keyboard and won't allow me to finish assigning buttons.

**Comment by rumpledan** [comment]
same here... it registers as keyboard and I'm only able to configure the d-pad...no reaction with the buttons...
I've done some research on the 8bitdo forum too and it seems that it must be a bug in the firmware...I'm just asking myself why it works on a rp2 and not on a rp3?

**Comment by kryptalivian** [comment]
The Raspberry Pi 2 build wouldnt work on the Raspberry Pi 3. They ended up making a whole new build

**Comment by substring** [comment]
@rumpledan are you sure your BT dongle works with recalbox ? Do you know how to check it ?

If you get keys instead of buttons, it means you didn't start your pad holding START+R. This is stated in the recalbox wiki :)

Mind if I close the issue ? According to what I've read, it's not a recalbox problem. If the BT dongle needs a firmware, please find it, test it a provide a link if you want us to add it
