### ISSUE TITLE
How to make a few changes

### ISSUE THREAD

**Issue by kryptalivian** [recalbox/recalbox-os#850]
Was looking to make a few changes to:

https://github.com/recalbox/recalbox-buildroot/blob/c001ceaadb88f1742efae609d7d1aa74971cd17a/board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_systems.cfg

I wanted to add a few extensions that currently aren't included out of the box. 

I've downloaded a few Sega CD .img extensions. Was going to add .img and .IMG

**Comment by digitalLumberjack** [comment]
You can see on https://github.com/recalbox/recalbox-os/wiki/User-directory-(EN) that you just have to copy the file in /recalbox/share/system/.emulationstation/ to modify it as you want :)
The default file is in /etc/emulationstation (it's a link but you can cp it :)

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-os/wiki/Customizing-System-directory-(EN)

**Comment by digitalLumberjack** [comment]
tell me if it's clearer. If it's not feel free to ask me :)

**Comment by kryptalivian** [comment]
It's clear :-) I was looking to make the changes to the Github version and have you approve them. 

I've noticed .img has become more popular(at least that is the format my Sega CD games have been in recently)

**Comment by rockaddicted** [comment]
@kryptalivian can we close this issue ?

**Comment by kryptalivian** [comment]
Yup :-)
