### ISSUE TITLE
Error: Black screen when I star recalbox

### ISSUE THREAD

**Issue by Videoplayer98** [recalbox/recalbox-os#852]
I have been few months with my Rasp Pi 2 Mod B, with a Samsung Evo MB-MP16DA/EU with 16GB, and no problems. In the second month appeared this issue, I could not even go to the menu. So I format de SD and I install all again. This week the issue appeared again. 
Do you guys now what produce it and what can I do?

I have v3.3.0-beta17. ASUS USB-N10 Nano. 5 V, 2 A, 2000 mAh, MicroUSB charger.

Thanks in advance!

**Comment by Laddyacris** [comment]
Hello
please ask help in forum thanks : 
http://blog.recalbox.com/forums/forum/english/

**Comment by Videoplayer98** [comment]
Okay, I think that this page was for these problems.
Thanks

**Comment by Videoplayer98** [comment]
I have created a post in this forum:
http://blog.recalbox.com/forums/topic/error-black-screen-when-i-star-recalbox/
