### ISSUE TITLE
ZX Spectrum - Support No Intro Fullset

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#855]
No intro zx spectrum fullset rom format is ipf

**Comment by rockaddicted** [comment]
same that https://github.com/recalbox/recalbox-os/issues/845

**Comment by paradadf** [comment]
FYI https://github.com/libretro/fuse-libretro/issues/30
I don't know if fuse will ever get .ipf file support upstream

**Comment by rockaddicted** [comment]
Upstream support of the IPF format in fuse emulator is not implemented.
Won't be easy to add support, even if IPF library is now available in recalbox.

I close this issue, and I'll reopen it if fuse team add someday IPF support upstream.

**Comment by pak21** [comment]
[ I'm Philip Kendall, one of the primary authors of Fuse ]

If you want to track this upstream, there is now some reverse engineered IPF format documentation / code available, so there is at least a ticket for tracking this: https://sourceforge.net/p/fuse-emulator/feature-requests/105/ Not promising anything is going to happen with it any time soon though :-)
