### ISSUE TITLE
Hidden files reappear

### ISSUE THREAD

**Issue by Voljega** [recalbox/recalbox-os#861]
### What happened

I hid a file through Emulation Station the menu, the file is then hidden and disappear. On next boot though, it reappears again, as if gamelist.xml hadn't been updated

### What should have happened

File should stay hidden

### Enumerate your devices

PI3, share on external hard drive in FAT32

### How to reproduce the bug

Hide a file through Emulation Station and reboot

**Comment by digitalLumberjack** [comment]
Do you use the reboot option from the menu ?

**Comment by Voljega** [comment]
I'm not 100% sure I think I did a shutdown through the menu and then on next boot the file reappeared

**Comment by digitalLumberjack** [comment]
Can you retry by letting the recalbox normally shut down. The game lists
are saved on quit. If you hard reset the rpi neither the hidden metadata
nor any scraped info is saved.

**Comment by Voljega** [comment]
I'll retry if you want but I never hard reset the pi, I always use shutdown either from ES menu or poweroff in ssh with putty

**Comment by Voljega** [comment]
Well did exactly the same process as before but this time it seems to have worked ?
I close the issue, i will reopen and comment if it happens again
