### ISSUE TITLE
Impossible to rename files through samba share

### ISSUE THREAD

**Issue by Voljega** [recalbox/recalbox-os#862]
### What happened

I try to rename a rom file extension through samba share, changing it from upper case to lower case.
It says something like permission denied, when at the same time I can erase the file or copy one with the same name over it.

### What should have happened

Rom files have write permission so I expect to be able to rename them, maybe this forbidden by Emulation Station

### Enumerate your devices

Pi3, share on external hard drive with FAT32; 4.0.0
happened also on every version before with PI2

**Comment by digitalLumberjack** [comment]
Can you copy on you desktop, remove on remote, rename on your desktop and copy on remote ? 
Is it related to the uppercase or you just cannot rename anything ?

**Comment by Voljega** [comment]
Can you :
copy on you desktop : yes
remove on remote : yes 
rename on your desktop  and copy on remote : yes

But I'm using windows as a desktop not linux so no real right management on desktop side
On share side / recalbox I can see in putty or WinSCP that I have writing rights on rom files

Is it related to the uppercase or you just cannot rename anything : 
I can't rename at least the extension of the rom file, I'm not sure I ever tried with the main file name.
It's not related to the uppercase, because the bug has always been there since I started using Recalbox, so 3.3.0 beta9 or so

**Comment by torra87** [comment]
Did you stop the ES process before renaming?

`/etc/init.d/S31emulationstation stop`

**Comment by Voljega** [comment]
No but if ES allow me to remove rom files I don't know why it should forbid me to rename them.

**Comment by nadenislamarre** [comment]
works for me from a linux computer.
Voljega, which version of recalbox are you using ?
What is you os ?
Are you using a usb key device to store your roms ?
Which files are you trying to rename ?

**Comment by Voljega** [comment]
Well this bug has always been there for me so I can confirm that it happens on this :
- Pi2 with internal SD card and every 3.3.0 beta I tried, from beta9 to beta17
- Pi3 with external share on a hard drive (tried two different), 4.4.0 beta 1 and 2

The files I'm trying to rename are psx roms (cue or bin file ) or mame/fba bios files (zip) more specifically i'm trying to change the case of their extensiont (.CUE to .cue or .cue to .CUE, .zip to .ZIP, etc...)

The behaviour happens when trying to do this action on the samba share accessed through both Windows (standard Window Explorer) and Android (using ES Explorer)

**Comment by substring** [comment]
Indeed, if you rename by just changing the extension case, it doesn't work. I believe it's related to cifs or FAT32, or both at the same time (i didn't try on a ext4 share)

The workaround :

1. rename `foo.CUE` to `fooo.cue`
2. rename `foo.cue` to `foo.cue`

You can do the same trick with just the extension if you prefer : `foo.CUE` to `foo.cuee` to `foo.cue`
And voilà ! The trick is to make a REAL change in the complete filename, not just changing the case

**Comment by Voljega** [comment]
Hello Subs, thanks for the trick.

Well given that this way of doing is simple and easy enough to be used as a solution and that I seem to be the only one bothered (don't recall anyone on the forum asking about that bug), I close the issue.
