### ISSUE TITLE
[4.0.0-beta2] PS3 DS Controller Hotkey doesn't work

### ISSUE THREAD

**Issue by Ronnsens** [recalbox/recalbox-os#866]
Hey,

i just installed recalbox on my Pi 3 and configured the PS3 DS Controller.
For the hotkey i want to use the L3 button, in the setup the software recognized the button, 
but when i'm playing a game, the hotkey doesnt work.

I tried to change to hotkey to the select button, but there is the same issue.

**Comment by Voljega** [comment]
Try with the home button ?

**Comment by Ronnsens** [comment]
Same at the home button :(

**Comment by rockaddicted** [comment]
Can you [past](http://www.pastebin.com) your `/recalbox/fsoverlay/recalbox/share/system/.emulationstation/es_input.cfg` file, please ?

**Comment by paradadf** [comment]
Just to be sure... 

1. The Hotkey only works on controller 1, are you sure you are using it? If not, try pairing just one controller and configure all buttons again.
2. Is your controller an original dualshock 3?
3. Have you changed anything on recalbox.conf? Your ps3 driver is set to original (if that's your controller type) and you haven't activated the xbox controller driver at the same time?
4. Do you have other controller types which Hotkey is working?

**Comment by Ronnsens** [comment]
@rockaddicted 

Here it comes: 

http://pastebin.com/cixctfsM

@paradadf 

1) I'm just using one controller and one bt keyboard
2) yes it is a original sony ps3 ds 3 controller
3) no, i didnt changed anything in this file
4) no, the ps3 controller is the only controller which i'm using for the recalbox

**Comment by rockaddicted** [comment]
Thank you
So PS3 gamepad inputs don't have been updated in recalbox since the last SDL patch that add new input informations.
So the system create 2 inputs about the same controller in `es_input.cfg` file.

Can you edit your `/recalbox/share/system/.emulationstation/es_input.cfg`, then remove this section (this without `code="XXX"` at the end of each line) : 
```
    <inputConfig type="joystick" deviceName="PLAYSTATION(R)3 Controller (00:48:E8:D1:63:25)" deviceGUID="060000004c0500006802000000010000">
        <input name="a" type="button" id="13" value="1" />
        <input name="b" type="button" id="14" value="1" />
        <input name="down" type="button" id="6" value="1" />
        <input name="hotkey" type="button" id="16" value="1" />
        <input name="joystick1left" type="axis" id="0" value="-1" />
        <input name="joystick1up" type="axis" id="1" value="-1" />
        <input name="joystick2left" type="axis" id="2" value="-1" />
        <input name="joystick2up" type="axis" id="3" value="-1" />
        <input name="l2" type="button" id="8" value="1" />
        <input name="l3" type="button" id="1" value="1" />
        <input name="left" type="button" id="7" value="1" />
        <input name="pagedown" type="button" id="11" value="1" />
        <input name="pageup" type="button" id="10" value="1" />
        <input name="r2" type="button" id="9" value="1" />
        <input name="r3" type="button" id="2" value="1" />
        <input name="right" type="button" id="5" value="1" />
        <input name="select" type="button" id="0" value="1" />
        <input name="start" type="button" id="3" value="1" />
        <input name="up" type="button" id="4" value="1" />
        <input name="x" type="button" id="12" value="1" />
        <input name="y" type="button" id="15" value="1" />
    </inputConfig>
```
Save the config file, reboot, remap using emulationstation menu, then retry.

**Comment by Ronnsens** [comment]
Ok,

i deleted the entrys which you posted above, and remaped the controller again.
But this doesnt work

**Comment by substring** [comment]
Could you detail what doesn't work with hotkey ? Do you mean key combinations, or solely pressing hk ?

**Comment by Ronnsens** [comment]
Restarted and remapped the Pi again, and now it works.

Thanks for all :)

**Comment by rockaddicted** [comment]
Can you give us your `es_input.cfg` file, with you PS3 gamepad fully mapped with snes layout (A=O ; B=X ; etc...) and hotkey on HOME button, that I update it in recalbox, please.

**Comment by Ronnsens** [comment]
Sure,

here it is:

http://pastebin.com/Jpd4VgtU

**Comment by rockaddicted** [comment]
Thank you, but I can't add your mapping because the joysticks aren't completely mapped.
I have only `<input name="joystick2up" type="axis" id="0" value="-1" code="0" />`, and there is not `"joystick1left joystick1up joystick2left"` informations.

Can you remap your gamepad et give me the new es_input.cfg file ?
Thank you, but I can't add your mapping because the joysticks aren't completely mapped.
I have only `<input name="joystick2up" type="axis" id="0" value="-1" code="0" />`, and there is not `"joystick1left joystick1up joystick2left"` informations.

Can you remap your gamepad et give me the new `es_input.cfg` file ?

**Comment by Ronnsens** [comment]
Hey,

there is one problem while mapping the controller.
When I want to map the two sticks,
he is skipping the input.
When I press the left stick up it will be skipped.
Same in the left direction and with the right stick.

**Comment by kryptto** [comment]
I am having the exact same problem as described here.

Sent from my iPad

On Apr 5, 2016, at 8:26 AM, rockaddicted <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you give us your es_input.cfg file, with you PS3 gamepad fully mapped with snes layout (A=O ; B=X ; etc...) and hotkey on HOME button, that I update it in recalbox, please.

**Comment by Akamaru** [comment]
I am having the same problem with my Pi 3, but with an Xbox 360 Wireless Controller

**Comment by Akamaru** [comment]
I tested another Xbox 360 Controller and it does working now

**Comment by substring** [comment]
closing it that's a support request, not a recalbox issue anyway ;)
