### ISSUE TITLE
[4.0.0-build-16][ES] Special chars for passwords not working

### ISSUE THREAD

**Issue by Nachtgarm** [recalbox/recalbox-os#870]
### What happened
When trying to connect to WiFi while using special characters in the password (e.g. "#", "$", "%") the result is always a "WiFi configuration error" in ES, even though the password is stored correctly in the .conf. 

Example: The local WiFi uses "1234#$abCD" as WPA/WPA2 key (without the quotes). As stated above, a connection won't happen, due to the "WiFi Configuration Error" given out by ES.

Almost the same goes for retroarch (Retroachievements). When using an account with a password such as the above mentioned, the .cfg of retroarch cuts down the password (after it is entered via ES) to the last char before the first special char. In the above example this would be "1234" (without the quotes", since "#" would be the first special char. 

### What should have happened
It should be possible to use passwords with special chars in it, as it was on version 3.x.x

### Enumerate your devices
Raspberry Pi2 + recalboxOS v3.3.0-beta17 + Edimax WiFi Dongle
Raspberry Pi3 + recalboxOS 4.0.0-build-16
FritzBox 6490 (WPA/WPA2)

### How to reproduce the bug
Use any password with special chars such as #,$,% for the WiFi and for the retroachievements account, enter them via ES and try to connect to either on of it.

**Comment by Laddyacris** [comment]
add `\ `before special characters

```
## Wifi KEY (string)   
wifi.key=1234\#\$5678   
```

**Comment by Nachtgarm** [comment]
Thanks for the info. I haven't seen this info in the English FAQ/How-To/Debug. Issue will be closed

**Comment by digitalLumberjack** [comment]
Hop reopen, we need to tell people how it works in recalbox.conf
```
## Wifi KEY (string)  
## Escape your special chars (# ; $) with a backslash : $ => \$

**Comment by nadenislamarre** [comment]
need a test in 4.1 before closing while the network management is changed.
