### ISSUE TITLE
[4.0.0-beta2 (build 60)][Scummvm] 8bitdo Nes30 PRO wrong mapping

### ISSUE THREAD

**Issue by paradadf** [recalbox/recalbox-os#871]
### What happened
The buttons are mapped incorrectly in Scummvm. For example, R1 should be mapped to F5, but right now R1 works as R2 (on-screen keyboard appears). That happens only with my Nes30 Pro, my usb ps3 like controller responds as it should.
I updated updated the firmware of my Nes30 PRO to the latest beta2 of 1.70 published on the [forum](http://forum.8bitdo.com/forum.php?mod=viewthread&tid=1179).

### What should have happened
Same buttons should have the same actions

### Enumerate your devices
Rpi 2, 8Bitdo Nes30 PRO

### How to reproduce the bug
I'm not sure if this has something to do with the fact of using the latest (beta) firmware or the recently bumped version of scummvm to 1.8.0. Most likely the latter one, as the controller works perfectly on every other emulator.

**Comment by rockaddicted** [comment]
Hi, controls are hardcoded in scummvm. So the mapping is different on each gamepad.
Look this issue for more informations.
https://github.com/recalbox/recalbox-os/issues/828

**Comment by paradadf** [comment]
Ohh, didn't know that. Thanks and sorry!
