### ISSUE TITLE
[4.0.0-beta2][ES] Wrong keyboard mapping with Logitech K400r

### ISSUE THREAD

**Issue by mrclschstr** [recalbox/recalbox-os#879]
### What happened
I attached my keyboard Logitech K400r (german layout) to recalbox but the default key mapping is different than expected from the [wiki](https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29):

- Arrow keys, Start and Select work as expected.
- A = OK
- S = BACK

For NES games I have the following mapping:

- Arrow keys work as expected.
- Enter = START
- Shift (right) = SELECT
- Y = A
- X = B

### What should have happened
I expected the keyboard layout described in the [wiki](https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29).

### Enumerate your devices
- Raspberry Pi 3 with Recalbox 4.0.0-beta2
- Logitech K400r (german layout)

### How to reproduce the bug
Plug'n'play ;-)

**Comment by substring** [comment]
Hi @mrclschstr 
Recalbox isn't meant to be played with a keyboard. Having it working in ES is a way to ease configuration. But Recalbox handles joypads, not keyboards. If an emulator supports keyboard, it's because it's built-in, not because we made something.

**Comment by nadenislamarre** [comment]
yes, keyboard is not supported. pads only.
