### ISSUE TITLE
[4.0.0-beta2] Wireless conection fail whit static ip on RPi 3 Model B

### ISSUE THREAD

**Issue by nephente** [recalbox/recalbox-os#881]
I'm trying to connect to the wireless network while maintaining a fixed ip with a raspberry pi 3, model B.

First I connect the RPI from "Network Settings" setting the hostname, and the wifi ssid and key, once you save the changes and restart the device everything works correctly in DHCP.

Then I follow the instructions:

https://github.com/recalbox/recalbox-os/wiki/Manual-IP-settings-%28EN%29

to establish a fixed ip with some variations:

- Mount the file system whit write support, because if they will not let me change anything, using the command:
mount -o remount, rw /dev/root /
- Modify the file /etc/network/interfaces.base because to do directly in /etc/network/interface changes are not maintained after restarting the RPI.

RPI keep the static ip, but fails to connect to wifi and lose access to the network.

Removing the changes reconnects without any problem in DHCP.

**Comment by nadenislamarre** [comment]
advanced/custom network configuration arrives in 4.1 thanks to connman.
In 4.0, the support is very limited.
You'll be able to set static ip, vpn, multiple wifi connection, and ethernet wire plug/unplug is recognize.
