### ISSUE TITLE
moonlight in recalbox 4.0 beta 2

### ISSUE THREAD

**Issue by ibikku** [recalbox/recalbox-os#882]
Good all have a problem with moonlight and recalbox follow the instructions even introduce the code to match the pc but when I enter moonlight and steam the screen of my recalbox beta2 stays in black and pc starts streaming but I see no you hear anything on the black screen where my PI3 is connected by please see if anyone can help me solve this problem that brings me head.
Thank you

### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

**Comment by substring** [comment]
@ibikku sadly we don't speak spanish. Could you edit your post in english please ?

**Comment by ibikku** [comment]
Gfe thing was that it was not the appropriate version and is perfect
