### ISSUE TITLE
[Future Feature] Achievements Menu

### ISSUE THREAD

**Issue by kryptalivian** [recalbox/recalbox-os#884]
Would it be possible to build an option within the Recalbox Menu, that allows you to see the unlocked and locked achievements of games you played(RetroAchievements)? This would be similar to the achievements menu within Microsoft's Xbox Consoles.

Basically, it would grab your account information and show it on your pi vs looking in a web browser.

**Comment by Laddyacris** [comment]
Hello
achievement list  is available in retroarch
Menu retroarch (hotkey+B) > Quick Menu > Achievements List

**Comment by kryptalivian** [comment]
Good thinking on the retroarch menu, I didn't even think about that.

I was hoping to have it pull down the images just like on retroachievements, but like you said, if it cant be done, at least we have them in retroarch :-)
