### ISSUE TITLE
Issue with Xbox Controller

### ISSUE THREAD

**Issue by kryptalivian** [recalbox/recalbox-os#887]
### What happened

Everytime I turn on my official Xbox 360 controller, kodi loads up on its own.
### What should have happened

Controller comes on and I play games.
### How to reproduce the bug

Power on device and turn on xbox 360 controller

**Comment by kryptalivian** [comment]
I'm using the wireless dongle for the xbox 360 controllers

**Comment by svera** [comment]
Same here

**Comment by substring** [comment]
Could you try disabling X to start kodi in system options and try again ?

**Comment by digitalLumberjack** [comment]
The controller must send weird events, and the kodi combination (X, A) may be runned. As @substring said disable the X button for kodi, you dhould not have the issue anymore

**Comment by kryptalivian** [comment]
Awesome! Thanks guys! I'll try that when I get out of my day job. :+1:

**Comment by rockaddicted** [comment]
You can activate too xboxdrv driver in your recalbox.conf file. That will fix issues about xbox360 gamepads (kodi launch during boot, blinking LEDs, etc...)

**Comment by nadenislamarre** [comment]
hum, and i don't remember why this is not the defualt.

**Comment by digitalLumberjack** [comment]
xboxdrv add n joysticks on the system, even if no joysticks are plugged (because we did not manage to use the daemon mode) maybe we should take an eye

**Comment by kryptalivian** [comment]
*Workaround until fix*

I ended up disabling Kodi to semi fix the issue. When the controller turns on, it just brings up the menu instead of kodi.

**Comment by rockaddicted** [comment]
fixed on 4.1.0
