### ISSUE TITLE
An specific category for Cd engine?

### ISSUE THREAD

**Issue by adolfobenjaminv** [recalbox/recalbox-os#889]
It would be great, an specific category for cd engine, simmilar to sega megadrive, and sega cd.
Maybe this way Cd engine could work better. (i tred a lot but just dont work :/ )

**Comment by substring** [comment]
Hi !
To what kind of problem are you referring to ? There is a known bug with the case of .bin files and how they are referred in the .cue file. Otherwise pcecd works great. Adding a new system for pcecd is no no solution, and not a good idea to my opinion. There are already enough systems

**Comment by Laddyacris** [comment]
May be for last beta 
pcengine and pcengineCD are splitted with the new theme.
https://github.com/recalbox/recalbox-buildroot/tree/rb-4.0.X/board/recalbox/fsoverlay/recalbox/share_init/roms

ngp and ngpc too.(nintendo

**Comment by digitalLumberjack** [comment]
Done with the new theme, wait for the beta3
