### ISSUE TITLE
[4.0.0-beta2] ES - Options go to letter

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-os#891]
### What happened

Select button > option go to B or P or W 
What any letter

the selection does not choose the first rom in the list of the letters B, but the rom probably in the middle
### What should have happened

selection should select the first name of the letter B list
### Enumerate your devices

RPI2 recalbox 4.0.0beta 2 unstable 16.04.2016 theme recalbox
RPI3 recalbox 4.0.0beta 2 unstable 16.04.2016 theme recalbox
snakebyte gamepad bluetooth
### How to reproduce the bug

Select button > option go to 
choose a letter

**Comment by rockaddicted** [comment]
fixed
