### ISSUE TITLE
[4.0.0 beta 2] no internet connection when booting directly into Kodi

### ISSUE THREAD

**Issue by svera** [recalbox/recalbox-os#892]
When Recalbox runs Kodi at start, Kodi does not have access to the Internet, so anything relaying on it can't be used (newsfeeds, weather, install plugins, etc). If we exit Kodi back to ES and then go back into Kodi, Internet connection is available.

**Comment by nadenislamarre** [comment]
Are you sure of this behavior ?
I don't think it's possible ; and personnally, i don't get this behavior.

Perhaps what happend :
1) kodi start
2) the network in recalbox arrive at the end of the boot. If you don't wait
enough and got be to es, then go back to kodi, the network arrive at this
time.

Can you just wait once kodi is started ?
on my rpi, what happend :
1) i display the kodi hour (via options)
2) kodi starts and it's 1h00 1st january
3) i wait, and date switch to the correct date when the network arrives

**Comment by svera** [comment]
Sorry, my wrong, I've rebooted the rpi 3 and after booting straigth to Kodi, both time and weather information are shown. Before, time was shown but bith weather and newsfeed didn't update. Closing the issue, thanks for your answer!
