### ISSUE TITLE
[4.0.0- build-16] Joystick GPIO mapping problem

### ISSUE THREAD

**Issue by TokyoEyes** [recalbox/recalbox-os#893]
Hi !

First of all i apologies if this issue is a known one (searched for this but couldn't find anything revelant)

On a Rpi3, i connected my 2 8 ways joysticks and 15 buttons on the gpio using the gpio mapping (used the wiki one https://github.com/recalbox/recalbox-os/wiki/GPIO-controllers-%28EN%29).

It seems that the joystick are inverted, so i plugged the P1 joystick pins to the P2 joystick pins according to the gpio mapping. And the same for the P2 joystick pins to P1 joy map. It solved this problem.
But in games, diagonals (only up left and down right) won't work on both of the joysticks. up right and down left , the vertical and horizontal axis, the buttons works fine.

I mapped the joysticks in recalbox via the interface but only on the 4 ways joystick input as described. Tried games with a xbox pad, diagonals works fine.

Rpi 3
2 Zippy joysticks
Xbox pad
16GB sandisk micro SD
Recalbox 4.0.0-beta 2

Thx !

**Comment by substring** [comment]
I know the answer looks like necroing issues, but that's rather a support request y'oure doing fine. If you still face this problem, we'd be glad to help you on the forum, which is the real place to discuss about such topics :)

See ya on the forum then :)
