### ISSUE TITLE
[Feature Request]Recalbox web interface addons

### ISSUE THREAD

**Issue by daaa57150** [recalbox/recalbox-os#898]
Hi,

I'm on the Recalbox 4.0.0 beta2 and I'm using exclusively a joypad, no keyboard.

I love the web interface but I think a few tools could be added:
- possibility to ask the pi to reboot / shutdown / quit the current emulator
- virtual keyboard 

I'm asking this because I was often stuck in an emulator after messing up the button mapping + I can't type in the text inputs (rename game etc..). Would be great to have a virtual keyboard in ES too.

**Comment by Laddyacris** [comment]
Hello
please try to add your request on recalbox manager github https://github.com/recalbox/recalbox-manager

**Comment by daaa57150** [comment]
Thanks, I added the requests there.

**Comment by roba91** [comment]
Please check out this forum post of mine:

https://forum.recalbox.com/topic/3482/virtual-keyboard

It might be of interest for you. I'm working on exactly what you asked for.
