### ISSUE TITLE
Show a star on favorite games, even in the list.

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#900]

**Comment by torra87** [comment]
And maybe remove the duplicate added on top of the list?

**Comment by digitalLumberjack** [comment]
No I like the fact you can find all your favorites for a system at the top
of the list.

**Comment by daaa57150** [comment]
It would effectively be nice to have a visual hint even on the list that a game is a favorite. I would even make them a slightly different color, or the star could be yellow or something. When they are on the top I would also separate them from the other games a bit more with some gap or a horizontal line or something.

**Comment by digitalLumberjack** [comment]
@daaa57150 good idea, you can open a new issue with your ideas please.

**Comment by daaa57150** [comment]
@digitalLumberjack done in issue #977

**Comment by digitalLumberjack** [comment]
thanks :)
