### ISSUE TITLE
[4.0.0 - beta3] [RPI3] N64, sega32x & NeoGeo doesn't work

### ISSUE THREAD

**Issue by andreasmw** [recalbox/recalbox-os#902]
The following emulators doesn't work: N64, sega32x & NeoGeo 
System: 4.0 beta 3 - The same also for V4 beta 2
Also all Bios-ROMs are installed with verified checksum check 

behavior: 
Tried round about 50 different games with the same result.
After starting the screen get´s black for 5 seconds. After that I come back to the Main menu.

I also tried to change the emulator settings to select other cores. But without an effect.

**Comment by rockaddicted** [comment]
These emulators work without problems in my setup.
So if you need support, please use the forum.
