### ISSUE TITLE
 [4.0.0-beta3][ES] back to the menu

### ISSUE THREAD

**Issue by Pitheur** [recalbox/recalbox-os#904]
### What happened

When I lauch a game, the ES menu goes foreground and the game stills run background. I can't go back to the game.

### What should have happened

I'm supposed to enjoy playing video games

### Enumerate your devices

WiiU pro controller with mayflash

### How to reproduce the bug

Simply launch a game...

**Comment by digitalLumberjack** [comment]
lol 
> I'm supposed to enjoy playing video games
You're so right :)

You select a game in ES, then press B, and then how do you know the game is running if es is foreground ?

**Comment by Pitheur** [comment]
Because I hear the music playing :D  I can go back to the game for a short time if I press hotkey+B (retroarch menu) but then after a few seconds ES goes foreground again.
Also ES is foreground and oversized like if it has the same resolution as the game...

**Comment by digitalLumberjack** [comment]
Alright.
Can you give us the rpi model, the installation procedure, what version did you install first, how many updates did you do since, what game you are trying to start, did you tried with an other controller or even a keyboard, did you tried to reinstall ?

**Comment by Pitheur** [comment]
Raspberry Pi 3
Installation procedure : I've copied Recalbox v4.0.0-beta2 on an MicroSDHC SanDisk Ultra 8 Go via an USB device adaptator.
Everything was working just fine till the v4.0.0-beta3 update that I did yesterday
I have this issue on every single game.
I tried with an other controller (wii classic controller via mayflash USB) and I rather not reinstall cause I wanna keep my saved games :P 

Another strange thing that I noticed after a few tests : on the start up i see 2 loading screens one after another... And it looks like I've got 2 ES running at the same time... In fact that explains almost all the wierd things that happen right now, and I don't know how to solve that issue...

**Comment by D1rTyH4rRyGR** [comment]
Same here.
Only common with Pitheur is the installation procedure.
RPi2
Thrustmaster Mini Wireless
Crypto AirMouse Keyboard 2in1
Kingston 16GB c10

Indeed it looks like there are two instances of ES. Actually when I was in the Settings Menu (after finally stopping the game with ESC from Keyboard) when I pressed B to confirm a selection, a game launched from the second ES! :D

**Comment by digitalLumberjack** [comment]
Can you connect through ssh and make some tests? What is `ps fax | grep
emulationstation` returns ?
`ls /etc/init.d ` ?
What happens if you kill one of the two es ?
Le dim. 24 avr. 2016 à 01:22, D1rTyH4rRyGR <notifications@github.com> a
écrit :

**Comment by D1rTyH4rRyGR** [comment]
Hi,

ps fax | grep emulationstation
  233 root     {S31emulationsta} /bin/sh /etc/init.d/S31emulationstation start
  234 root     {emulationstatio} /usr/bin emulationstation
  355 root     {S92emulationsta} /bin/sh /etc/init.d/S92emulationstation start
  356 root     {emulationstatio} /usr/bin emulationstation
  465 root     grep emulationstation

# ls /etc/init.d
S01logging           S30dbus              S92switch
S02splash            S31emulationstation  S92virtualgamepads
S03populate          S31sixad             S94manager
S10udev              S32bluetooth         S95api
S11share             S40network           S98cleanup
S12populateshare     S49ntp               S99custom
S16modprobe          S50avahi-daemon      rcK
S20urandom           S50dropbear          rcS
S25lircd             S91smb
S26recalboxsystem    S92emulationstation

Killing PID 234 seames to fix, the problem (quick test with NES game)

**Comment by Pitheur** [comment]
OK i've got exactly the same results as D1rTyH4rRyGR

**Comment by rockaddicted** [comment]
`/etc/init.d/S92emulationstation`
Didn't edit your init scripts to use a DD or NAS ? Because out of the box there is not this init script.

**Comment by nadenislamarre** [comment]
Yes, this script never existed in v4.0.
@Pitheur @D1rTyH4rRyGR where did you download your recalbox version ?

**Comment by Pitheur** [comment]
Well I never touch init scripts and I downloaded my recalbox from https://github.com/recalbox/recalbox-os/releases ...

**Comment by nadenislamarre** [comment]
digit : do you have an idea about this S92 script (i'm perhaps the faulter
and i don't remember).
However, it looks very strange.

@Pitheur, can you tell use how many upgrade did you do ? which one was your
first one on this card ? beta3 ?

**Comment by Pitheur** [comment]
Beta3 was the first and only update i did on this card.

**Comment by Pitheur** [comment]
Ok, my bad, I DID TOUCH the S31emulationstation script for NAS purpose... I just didn't remember at first...

**Comment by D1rTyH4rRyGR** [comment]
Yeap, S31emulationstation was edited to give access to NAS, which by the way didn't work as expected. An other time maybe...
So... do we remove the S92 (which is the old S31 with the "mount -a" in it)?
