### ISSUE TITLE
[4.0.0 - beta3] [RPI3] LYNX not working

### ISSUE THREAD

**Issue by Duglim** [recalbox/recalbox-os#908]
LYNX games are not working in Recalbox 4.0 b3.

- Bios file lynxboot.img with correct MD5 checksum is present in bios folder and also recognized in the Recalbox web interface.
- All roms are with file extension .lnx (lowercase) and originate from a No-Intro-Set. Region of nearly all ROMs is (USA, Europe) or only (USA).

If I launch a LYNX game, screen goes black and returns to Emulationstation after 4-5 seconds. Happens on all LYNX games.

Any idea?
Thx, Duglim

**Comment by rockaddicted** [comment]
Hello this system work pretty well, but the emulator is very capricious with the ROMs games. I had to try many different romset before find one working. So it is a ROMs problem.
If you need more support please use the irc channel or the forum.
I close this issue.
