### ISSUE TITLE
Add WiringPI - RPI 0 analog sound

### ISSUE THREAD

**Issue by nosfay** [recalbox/recalbox-os#909]
I need to get analog sound thrue rpi0 GPIO but for that I had to put PWM0 on GPIO18 and PWM1 on GPIO13.

May you please install WiringPI?
Here is the link to install it, it sounds pretty simple : http://wiringpi.com/download-and-install/

**Comment by rockaddicted** [comment]
Are you talking about that ? https://github.com/recalbox/recalbox-buildroot/commit/9b0e04711a505add690601404ecc613490edba6d

**Comment by nosfay** [comment]
Yes! DigitaLumberjack just confirm it's already added on 4.1 :)

I just need to wait now, ty !
