### ISSUE TITLE
Change poweroff to halt to allow pi waking up by GPIO

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#91]
The gpio 5 and 6 on the rpi allow wake from halt. If the command used in the frontend for halting the rpi is halt in place of poweroff, one can wake up the pi with a button.

**Comment by digitalLumberjack** [comment]
`halt` does not put the rpi in sleep mode... The screen is on with the message "Shutdown : system halted."
What is it missing in the buildroot ? The watchdog is responsible of the shutdown ?

**Comment by substring** [comment]
done https://github.com/recalbox/recalbox-buildroot/commit/98073572e2fe9f5e7601774282e2033484badd97
