### ISSUE TITLE
[4.0.0-beta3][ES][RECALBOX THEME] many errors in console technical descriptions

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#910]
I don't know where those data came from but there are many errors in console technical descriptions. Maybe you could fix them with wikipedia or retrogaming sites.

**Comment by rockaddicted** [comment]
You have sources in recalbox-themes repo so don't hesitate to fix them. Informations come from zoid theme and wikipedia.

**Comment by bigboo3000** [comment]
OK I will try and maybe have the same informations between systems

**Comment by rockaddicted** [comment]
FYI you can find informations in the `custom.xml` file of each system : https://github.com/recalbox/recalbox-themes/blob/master/themes/recalbox/atarist/custom.xml#L20

**Comment by bigboo3000** [comment]
I think it would be better to make an almost standardized description between systems:
Manufacturer
Year release
unit sold
best selling game

CPU
(CPU2)
RAM + VRAM
VIDEO chip
resolution
SOUND
SUPPORT (cartridge/Disk/CD etc.)

I just tried that for 2600

Where do you want me to PR? "master" or "4.0.X"?

**Comment by rockaddicted** [comment]
nope on the theme repo : https://github.com/recalbox/recalbox-themes

**Comment by bigboo3000** [comment]
I modified custom.xml
It saved a fork
Now I have a screen  "Comparing changes"
and buttons by default : base-fork: recalbox/recalbox-themes and base : master (I can change this one to 4.0.X"
So I leave it all by default and i just click on "create pull request"?
Sorry I never used github

**Comment by mgoulartBR** [comment]
Sorry for using this issue to ask something not related with it. I'm getting Eudora theme to use on Recalbox. Do I need to insert bg music for all systems or it's a optional?
