### ISSUE TITLE
[4.0.0-beta3][ES] slide animation as standard in emulationstation

### ISSUE THREAD

**Issue by CokeGuitarist** [recalbox/recalbox-os#911]
Hello, how about setting the animation in emulationstation to the slide animation as standard?
it looks much more seamless than the the fade animation, especially with the new theme. and on top beeing abled to choose a system by pressing the down button on the dpad would make this feature perfect. so there would be the impression of a seamless interface without interruptions and looking much more fluid.

**Comment by Duglim** [comment]
I also switched to SLIDE animation for the first time ever with the new gorgeous theme. :) Also I would pledge for your Down-Button Idea and would add, to default turn of the Quick-System-Change, as this would break the seamlessness a bit.

Greetings, Dan

**Comment by rockaddicted** [comment]
done
