### ISSUE TITLE
[4.0.0-beta3][FBA LibRetro]Vertical shooters screen ratio

### ISSUE THREAD

**Issue by daaa57150** [recalbox/recalbox-os#913]
### What happened
I'm launching a Vertical shooter in FBA libretro (Esp Ra De is one of them), and the screen is like a letterbox, very small in the screen + cropped.

### What should have happened
The game should better fit on my screen

### Enumerate your devices
RPi 3, Racalbox 4.0.0-Beta3

### How to reproduce the bug
Launch a vertical shooter in FBA LibRetro

### Comments
This can be corrected by going into the retroarch menu, config, screen ratio and choosing 1:1. Choosing 1:1 works also for other standard games, I tried a few.
I think screen ratio 1:1 should be the default, because of course if I quit and relaunch the game I have to redo my changes.

**Comment by rockaddicted** [comment]
Before editing your ratio in retroarch menu, set ratio option in EmulationStation menu on "custom".

**Comment by daaa57150** [comment]
I didn't know there was such an option, I'll look for it when I'm back home.

**Comment by substring** [comment]
@daaa57150 have you been back home since ? :) shall we close ? the fba ratio are fine for me

**Comment by substring** [comment]
Haha no problem man
The ratio should be set on auto, there are hardly any reason to change it, even more for the global.ratio.
Closing it :)
