### ISSUE TITLE
[4.0.0-beta3][Mame]Button mappings are weird/inconsistent

### ISSUE THREAD

**Issue by daaa57150** [recalbox/recalbox-os#914]
### What happened
I'm playing a game in Mame, default core (good examples are Bubble Bobble & Hook).
Bubble Bobble: I shoot with B and jump with Y
Hook: I hit with B and jump with Y

### What should have happened
Bubble Bobble: should shoot with Y and jump with B
Hook: should hit with Y and jump with B

### Enumerate your devices
RPi 3, Recalbox 4.0.0-beta3, PS2 gamepad with smartjoy / smartjoy + adapters

### How to reproduce the bug
Play Hook or Bubble Bobble and probably any game in Mame.

### Comments:
The mapping in Mame is as follows:
(ARCADE -> SNES PAD)
A -> B
B -> Y
C -> X
D -> A
But it should be
A -> Y
B -> B
C -> X
D -> A

I'm pretty sure this is not just a personal preference, because when I try Hook in FBALibRetro, the mappings are OK.

There is a similar problem with NeoGeo but it's messed up a lot more; I have a custom mapping for it so I can't say how I switched the inputs anymore.

**Comment by Dragda** [comment]
The number of games in the 3 romsets is so big that it is impossible to have the control scheme in all of them well without changing  it game by game.
For example, if you change the actual scheme, you wreck all the 6 buttons fighting games, like the SF saga or the mvsc.

**Comment by daaa57150** [comment]
I didn't test any SF game in Mame that's true, but I did in FBALibretro and their mapping is perfect. I played a lot of games in FBALibretro and they all had intuitive controls. 

Now in Mame all the games I've tested have the A & B buttons switched, including Hook which I tested in both cores and is wrong in Mame but right in FBALibretro. 
So my guess is that the SF games won't have the proper mapping in Mame either, but I'll test that to be sure, maybe there's something I don't get.

Did you try any SF game in Mame?
This is the mapping I think is right for a SF game:
Y: SP
X: MP
L: HP
B: SK
A: MK
R: HK
It's true for all the SF games I played up to a point where HK & HP were put on R1 & R2

**Comment by dankcushions** [comment]
This is basically unfixable. Mame's default mappings are inconsistent, so without going through every mame driver and making it right, you're stuck with it. At least you can press tab and do the remapping yourself.

What I did was press tab and change Mame's global input settings to suit street fighter, which makes it right for those games. The rest I don't care too much about mapping.

**Comment by daaa57150** [comment]
I tested Street Fighter in Mame, and the mappings are indeed wrong, much more than I thought, it looks like it's exactly the same mix than the NeoGeo games.
Are you sure we can't find the right mapping and it'll be good for every game? FBALibretro has it right for me up to now on every game, and I tried many of them.

**Comment by dankcushions** [comment]
if you can find one mapping change that works for every game in mame, then sure we can make that the default in the mame code. i thought mame was inconsistent in this regard, though.

**Comment by daaa57150** [comment]
Well I guess you're right, it's such a mess. I configured SF2 and then tested Bubble Bobble and it's not ok. The SF2 config had me mess with L being A and such things it took me sooo long and it's not usable for other games I think.
How do you guys manage this? You can't play SF2 with such a random mapping...

Also I configured both players for SF2, saved my custom config, told recalbox.conf to use it and for SF2 at least it's good... BUT for 2 players only. I launched a game with only one pad connected and I was not player one, I couldn't even open retroarch's menu. I don't know how this can be usable at all.

**Comment by dankcushions** [comment]
you have to reconfigure the controls via the mame tab menu, not retroarch. if you change your retroarch binding, your hotkeys will be all messed up as you've found.

> What I did was press tab and change Mame's global input settings to suit street fighter, which makes it right for those games. The rest I don't care too much about mapping.

**Comment by daaa57150** [comment]
Now I get it, right. I don't have a keyboard so pressing tab doesn't mean anything to me, it's on my R2 button. Thanks I'll try using that.

**Comment by daaa57150** [comment]
So I didn't try Mame yet but I found how to have the good mappings on the NeoGeo at least, without having a custom config:
In the retroarch menu, quick menu, core options, I set:
- Control Scheme: gamepad
- Neo Geo gamepad scheme: newgen
And voilà, everything works like it should, plus it's saved forever it seems.
That makes me happy ^_^

This could be explained on the easy arcade page I think.
