### ISSUE TITLE
[4.0.0-beta3][ES] Make "Favorite Entries" at first entry in ES

### ISSUE THREAD

**Issue by air-sky-one** [recalbox/recalbox-os#919]
### What happened

Making system in Write mode with : mount -o remount, rw /
Stoping ES : /etc/init.d/S31emulationstation stop
Update /recalbox/share_init/system/.emulationstation/es_systems.cfg to make Favroites at first in EmulationStation
Starting ES : /etc/init.d/S31emulationstation start

I'v also tested copying es_system.cfg in /recalbox/share/system/.emulationstation/, but the result is still the same
### What should have happened

The "Favorites" entry should be the first to be displayed in ES. It seems that nothing happened.
### Enumerate your devices

RPi 3, Racalbox 4.0.0-Beta3

**Comment by mgoulartBR** [comment]
+1

**Comment by Duglim** [comment]
+1

**Comment by substring** [comment]
guyz please use the github features for +1 : click on the smiley on the message header bar, and choose the right icon

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0 you can select the default system you reach at start
