### ISSUE TITLE
[4.0.0-beta3] 8bitdo NES30 Pro bluetooth controller won't pair

### ISSUE THREAD

**Issue by bighead734** [recalbox/recalbox-os#920]
I'm very new to Raspberry Pi and Linux in general. I have a Raspberry Pi 3 Model B and an 8bitdo NES30 Pro bluetooth controller. In the ES setting screen I try to Pair the device and it instantly tells me "no controllers found". I've updated the controller's firmware to v1.69, I power on the controller and let the blue lights blink before I try to pair, nothing works. The controller works fine when plugged in(except for the A and B buttons being reversed), what do I have to do to get this paired? I've gone into the command line and I can't figure anything out except how to access the config file. Someone please help!

**Comment by substring** [comment]
Hi

You may not know yet, but the pi3 bluetooth is not supported yet on recalbox

**Comment by bighead734** [comment]
nope, had no idea, thanks for the info.

**Comment by dudo** [comment]
Is Bluetooth supported yet on rPi3?

**Comment by bighead734** [comment]
Last time I checked it out Bluetooth was working, but there's still an issue with the 8bitdo NES controller having input issues.
