### ISSUE TITLE
[4.0.0] manage the themes installation

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-os#926]
- Edit recalbox-themes.mk and only install recalbox theme by default
- Add a way to install the other themes on recalbox-themes repo

**Comment by nadenislamarre** [comment]
i guess you mean : make a script ?
because i guess you already know that you can add easily new themes in ~/.emulationstations/themes

**Comment by digitalLumberjack** [comment]
is https://github.com/recalbox/recalbox-os/issues/927 a duplicate of this one ?
Edit recalbox-themes.mk and only install recalbox theme by default -> https://github.com/recalbox/recalbox-buildroot/issues/340
