### ISSUE TITLE
TP-Link TL-WN725N Driver missing

### ISSUE THREAD

**Issue by ghost** [recalbox/recalbox-os#93]
Drivers can be found here: http://www.raspberrypi.org/forums/viewtopic.php?p=462982

**Comment by DanFaraday** [comment]
Maybe this particular post could be useful: http://www.raspberrypi.org/forums/viewtopic.php?p=675971#p675971

**Comment by boopr** [comment]
I agree, we need it.

**Comment by rockaddicted** [comment]
wget https://github.com/lwfinger/rtl8188eu/raw/master/rtl8188eufw.bin -O /lib/firmware/rtlwifi/rtl8188eufw.bin

**Comment by digitalLumberjack** [comment]
If that works, we add that directly in recalboxOS

**Comment by mxjoe** [comment]
Hi Lumberjack, rockaddicted is right, that works and should be implemented in recalboxOS.
This issue is a duplicate of #230 .

**Comment by rockaddicted** [comment]
firmware ok in recalbox 4.0.0
```
# ls -la /lib/firmware/rtlwifi/rtl8188eufw.bin 
-rw-r--r--    1 root     root         13904 Dec  7 03:17 /lib/firmware/rtlwifi/rtl8188eufw.bin
```
