### ISSUE TITLE
Problem "recalbox rPI-3 error filesystems mounting"

### ISSUE THREAD

**Issue by lilomg** [recalbox/recalbox-os#934]
I have a problem in recalboxos installation on Raspberry Pi 3. I copy the files to the sdcard 64 gb previously formatted in FAT32, it is recognized and the installation starts, however, when they procure reaches 100% shows the seguinta error message " recalbox rPI-3 error filesystems mounting ". I tried to install with versions: recalboxOS-4.0.0-beta2 and recalboxOS-4.0.0-beta3.
How do I RECALBOXOS the work?

**Comment by digitalLumberjack** [comment]
What is you sd card brand ? Did you formatted with gparted on linux or minitool partition wizard on windows ?

**Comment by lilomg** [comment]
SD card Skandisk. In retropie and other operating systems like Ubuntu mate works normal. I have done formatting the gparted on linux and also already used the SD Formatter and Guiformat in Windows 8. The memory card normally recognizes the installation of recalboxos processed normally, but when finalizing the installation of the mentioned error "recalbox rPI-3 error filesystems mounting ". Already deleted the file and baixi again at least 2x and always of the same error in both the version beta2, beta3 and in. Help me please, I do not know q do more. What about the poor English forgive me, is that I am using Google translator.

**Comment by digitalLumberjack** [comment]
try with minitool partition wizard

**Comment by lilomg** [comment]
Did not work! Remains the same.

**Comment by paradadf** [comment]
Your downloaded recalbox zip file might be corrupted. Try downloading it again.

**Comment by lilomg** [comment]
Already have downloaded several times in the official repositories of Recalbox, but did not ccerto. I do not know what to do. Now for example, I redid download and put to reinstall and made the same mistake. And it only happens with recalbox because for retropie for example usually works. Help me here.

**Comment by Laddyacris** [comment]
you need use in minitool partition wizard

create as : primary
file sytem :fat32

**Comment by lilomg** [comment]
Fiz todos esses procedimentos e ainda persiste a mesma mensagem de erro. Como devo proceder?

**Comment by sunsan05** [comment]
where can be download minitool ?

**Comment by Laddyacris** [comment]
https://www.partitionwizard.com/free-partition-manager.html

**Comment by sunsan05** [comment]
3Q Bro!

**Comment by sunsan05** [comment]
Thank you bro!

**Comment by lilomg** [comment]
It worked! In fact it was the sd card 64gb that was not being comatível. Interestingly the same sd card ran for retropie and Ubuntu Mate. Qulquer form of thanks to all!
