### ISSUE TITLE
Searching game on keyword

### ISSUE THREAD

**Issue by jomofcw** [recalbox/recalbox-os#936]
It could be great to be able to search game by keyword on ES.
Using a physical or a virtual keyboard, that enable the user to find all the game related to keyword.
For example, typing "Mario" will return each game about "Mario" like "Mario Kart", "Super Mario Bros" or "Mario Bros" etc.

We could imagine few more stuff about that : 
- looking for a type of game, an editor, ...
- filtering by platform, year, ...

**Comment by MarcDK** [comment]
+1
A virtual keyboard for input via the gamepad would be great. If you scrape a game you are currently stuck if you want to change search query if you don't have a keyboard. I assume that you can input data if a usb keyboard is atteched to the pi.

**Comment by jomofcw** [comment]
That could be nice to be able to search on the number of player possible by game, as, when I've got friend at home, I could search for X players games, and be sure we will be able to play together.

**Comment by rockaddicted** [comment]
A virtualkeyboard has been added in ES, an other one is now available in virtualgamepads application too.
You can now sort games by players numbers or letter in ES, so I close this issue.

**Comment by jomofcw** [comment]
Nice one :D !
Thanks.

__________________________________

*Nicolas VINCENT*
*iDdev* - Développement et stratégie Web
06.25.28.36.42
nicolas.vincent@iddev.fr

2017-01-24 16:34 GMT+01:00 rockaddicted <notifications@github.com>:
