### ISSUE TITLE
[Feature request] Input option for GDB ID to retrieve metadata

### ISSUE THREAD

**Issue by paradadf** [recalbox/recalbox-os#938]
Very often happens that metadata for games on thegamesdb.net isn't found when using the built-in scraper in ES, even if the you look for the exact same name as in the database of TGDB. It would be really useful to have also the possibility to enter the ID of the game to retrieve the medatada instead of having to do it manually on the computer.

**Comment by substring** [comment]
mmmhhhhh tbh, the ES scraper is definitevely not our priority. And that's why there are a few tools developped by the community

**Comment by paradadf** [comment]
Tbh I have no idea how much work adding that feature would be, so it is just a suggestion. As there is already the "input" option to search for a specific name, I thought it would be easy to allow to put the id instead and look for it. But again, maybe I'm naive in in the amount of work for it :D
Thanks anyway for the answer.

**Comment by substring** [comment]
It's not really a question concerning the amount of work for it, but rather priorities. In my opinion, the ES scraper has no future. It's way too monolithic, despite it useful for just a few roms. And there are other ways to solve scraping problems. You could even download + resize the artwork, then add it manually in the gamelist.xml ...

Well, just a question of priority as I said ... i wonder how many people know how to find a game id in tgdb.net (considering they know tgdb.net lol)

**Comment by rockaddicted** [comment]
If we would to invest time in the ES embed scraper, we'd rather to use a hash comparaison as other external scrapers can do (sselph scraper that work very well on rpi) to prevent no answers/false positives.
Some PR has been done upstream, these are mentioned in this issue https://github.com/recalbox/recalbox-os/issues/586

But as said by @substring it is clearly not the priority for the moment.

**Comment by paradadf** [comment]
I'm closing this issue as there are, as you mentioned, better things to do and ways to scrape games.
