### ISSUE TITLE
[4.0.0-beta3]  /etc/init.d/S99custom pass $1 to custom.sh

### ISSUE THREAD

**Issue by matthuisman** [recalbox/recalbox-os#940]
Hi,

Would you consider adding $1 to the line in /etc/init.d/S99custom

`test -e "/recalbox/share/system/custom.sh" && /recalbox/share/system/custom.sh $1`

This would allow custom scripts to do start and stop commands.
eg. mounting a SMB share for roms in start, and unmounting in stop

**Comment by nadenislamarre** [comment]
ok, i'll add it.
note however that it will not help to mount smb share for roms,
while emulation station is started too early, before the network is available, before samba is started and before custom is started.
I've a work to do to allow this and nfs.

**Comment by substring** [comment]
@nadenislamarre it's ok, leave S99 to me, it has to be fully rewritten to look like a normal init script. Gather your energy on some other stuff :)

**Comment by matthuisman** [comment]
I'm just using

/etc/init.d/S*emulationstation restart

after mounting the folder.

Not the prettiest way of doing it as you see the initial screen pop-up, and then restart but it works :)

**Comment by substring** [comment]
@matthuisman dude, i hope you are not bloated with roms ... otherwise it takes ages lol
Anyway, we've already internally talked about adding samba shares like usb keys, @nadenislamarre should do it some day for 4.1 i guess, if he's still ok with this

**Comment by bigboo3000** [comment]
Would it be possible to have multiple mounts for roms? In ES instead of choosing "internal" "usb key" or "samba" (in the future), have a list and tick the ones you want?

**Comment by nadenislamarre** [comment]
@substring : ok

for the mounts, i've not find for the moment what is the best solution.

the current boot actions :
1) mount share (sd card or usb)
2) start emulation station
3) start network (but not wait the wifi is connected, so es restart would not work in the wifi case while it will take too much time)

start network currently requires mount share while the login/password/custom configuration are in share.
so basically, mount share is a prerequisite to start network and start network could be a prerequisite to mount share ;-)
it's why i thought to somethings like this stored in boot-recalbox.conf:

share/roms:nfs:192.168.0.50:/myshare
or 
share/roms:smb:user:password@192.168.0.50:/myshare

or course, not hidden like the wifi password in recalbox 4.1

but none of the solution satisfies me.
one thing could be to allow or avoid nfs/smb mounts via wifi.
and to put s31es after the network in case of mounts
and wait the network to be really availble in s31es (like done in kodilauncher.sh when the mysql database is required).

If you have better ideas, and much more simple, as you'll often have, don't hesitate, not to suggest, but to do then while i let you the action ;-)

**Comment by matthuisman** [comment]
Considered not having the config file in the share partition?
It's easily modified via the web interface / GUI anyway.

You'll simply be cutting off people who edit it via the samba share.
I'm sure it's not hard for them to use the web interface instead.
This sounds familiar - pretty sure I've brought this up before.

Then, you can Read config / start network / start emulation station
