### ISSUE TITLE
recalbox FBA 0.2.97.38 update

### ISSUE THREAD

**Issue by djcyber20018** [recalbox/recalbox-os#943]
como actualizo los binarios al FBA 0.2.97.38
as I update the binaries to FBA 0.2.97.38

**Comment by Laddyacris** [comment]
Core libretro will be updated in recalbox 4.1

**Comment by Voljega** [comment]
maybe not the best idea to upgrade, we will again lose some speed in games, some of them wich work perfectly could lag afer the update.
would be better to add the core as a new one.

**Comment by dankcushions** [comment]
it actually increases speed on rapsberry pi systems for cps3: http://www.fbalpha.com/view/231/

**Comment by Voljega** [comment]
Good but what for other systems which are already the touchy ones with previous versions ?

**Comment by dankcushions** [comment]
it's an incremental upgrade. isn't recalbox running .37 at the moment? it's not like the difference between mame current and mame 0.375b or whatever :)

**Comment by Voljega** [comment]
Well there was a noticeable difference between 0.36 and 0.37... And for this upgrade the romset will go up from 0.167 to 0.173
