### ISSUE TITLE
[4.0.0Beta3] Boot freeze with RPi Zero ver. 1.3

### ISSUE THREAD

**Issue by Astmatic** [recalbox/recalbox-os#945]
Hey,

i recieved my Zero today and tried to install the recent version of RecalBox. Installation works fine but after restart the PI freezes when the Release version is displayed in the left bottom corner.. Tried without plugged in USB Devices with same result. Recovery is working. The Zero is the newest Ver. Including Camera output. Maybe thats the Problem?

hope for Help, thx in advance

**Comment by substring** [comment]
Maybe RPi updated the dtb ... it needs a new recalbox version

**Comment by Astmatic** [comment]
Could be.. SD Card is from Pimoroni Bundle so i would not think that this is the problem

**Comment by kryptalivian** [comment]
I just got my pi zero with camera output as well. I'll test to see if I have the same issue

**Comment by Astmatic** [comment]
Thank you. I'll wait for it

**Comment by kryptalivian** [comment]
Mine booted just fine @Astmatic

**Comment by Astmatic** [comment]
I dont unterstand it.. I will try another sd card tomorrow

**Comment by kryptalivian** [comment]
Did you get it working?

**Comment by Astmatic** [comment]
Sorry been a little busy atm. I'll try today or tomorrow and post my result

**Comment by substring** [comment]
@Astmatic still waiting for your results ;)

**Comment by Astmatic** [comment]
Sorry, i dont have a SD Card that i can use ATM... And i'm ill.. it will take some more time

**Comment by MrWayneBrain** [comment]
Got the same Problem as @Astmatic , with version recalboxOS 4.0.0-beta4 on a raspberry pi 2 model B.
Stucks in loading screen, after a few reboots after installation.
Used a 8Gb SanDisk mSdCard for it.

**Comment by substring** [comment]
then I guess it's not compatible with the rev1.3. No one owns one in the team, can't promise anything before 4.1

**Comment by substring** [comment]
the almighty @Supernature2k had no problem to make it work on a 1.3 pi0

**Comment by substring** [comment]
no answer, closing. And anyway should work with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0
