### ISSUE TITLE
[4.0-beta2] Windows line endings in boot/config.txt

### ISSUE THREAD

**Issue by sixertoy** [recalbox/recalbox-os#946]
Hello :)
No more to say, some trailing ^M in /boot/config.txt.

**Comment by substring** [comment]
The config.txt by default is fine. You must have edited it through a windows text editor that doesn't handle unix file format

**Comment by sixertoy** [comment]
I'll check it and confirm but i work under OSX and edit it with vi has i remember :)

**Comment by substring** [comment]
You can trust us on the right file format ;)
Well, oddly NOOBS adds some ^M terminated lines, but they should be at the bottom and just concern overscan. I personnaly always remove them

**Comment by substring** [comment]
shall we close ths issue ?

**Comment by substring** [comment]
closing. No reply
