### ISSUE TITLE
[4.0.0-beta3][KODI] PS3 controller doesn't work

### ISSUE THREAD

**Issue by zwenny** [recalbox/recalbox-os#948]
Since i've updated from 4.0.0-beta2 to 4.0.0-beta3 (original) on a Raspberry Pi 2 B, ps3 controller don't work in kodi. Neither over bluetooth nor when plugged in with USB connection. The same error occurs, when installing version 4.0.0-beta3 from scratch.

I've reinstalled 4.0.0-beta2 and will wait for the next release to see if the error still occurs.

**Comment by rockaddicted** [comment]
You have just to remap your PS3 controller in ES and that should be ok in Kodi.

**Comment by zwenny** [comment]
Hey, thanks. I've followed your instruction and the controller is working again. Any explanation why this is happening in version beta3?
