### ISSUE TITLE
Add MSX2+ type to bluemsx core options

### ISSUE THREAD

**Issue by Sebbeug** [recalbox/recalbox-os#949]
Actually, blueMSX core option about MSX type is : `bluemsx_msxtype = “MSX”`

It could be more powefull to have `bluemsx_msxtype = “MSX2+”`

> From Libretro wiki about options : 

> bluemsx_msxtype (MSX/MSX2+/MSXturboR): Machine Type (Restart)

File concerned is here : `system\configs\retroarch\cores\retroarch-core-options.cfg`

**Comment by rockaddicted** [comment]
- switch bluemsx as defaut MSX emulator
- add bios informations in readme files

**Comment by rockaddicted** [comment]
done
