### ISSUE TITLE
[Enhancement] AdvanceMame support?

### ISSUE THREAD

**Issue by BestUsername** [recalbox/recalbox-os#950]
Hello,

It looks like the xgaming xarcade tankstick's trackball works in AdvanceMame, but not the Mame distros in recalbox.
Is there any chance AdvanceMame will be supported in a future release?

Cheers,
Marc

**Comment by substring** [comment]
So far there are no plans on adding advance mame unless there is a real advantage to it (emulation speed, rom compatibility)

On which game do you expect the trackball to run ? It's just a mouse for the system, retroarch + mame core may already handle it. I could test on my side

**Comment by Voljega** [comment]
I tried mouse with gun games on mame 78 it's not activated nor used

I think it will work in 4.1 when custom configuration is integrated.

**Comment by BestUsername** [comment]
There are some games like centipede, Golden Tee, etc that would be better with the trackball.
I know Recalbox sees the trackball as a mouse because it works in the scummvm engine. But Mame doesn't seem to be able to use it. When reading online, it sounded as if AdvanceMame was the key (although I haven't tested it yet)

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0
