### ISSUE TITLE
[4.1.0?][ES] Lock and unlock settings features on ES

### ISSUE THREAD

**Issue by mgoulartBR** [recalbox/recalbox-os#960]
Hey guys,

I don't know if it's possible but I like this feature. Using the ES menu you can enable a lock settings options and unlock them using a password or an user-defined buttons sequence.

**Comment by substring** [comment]
hey @mgoulartBR 
What do you want to lock inside ES ? Just using ES itself ?

**Comment by mgoulartBR** [comment]
All the options, leaving just reboot/shutdown menu.

**Comment by substring** [comment]
check your recalbox.conf :
```
## EmulationStation menu style 
## default -> default all options menu
## none -> no menu except the game search menu
## bartop -> less menu, only needed for bartops
system.es.menu=default
```

**Comment by mgoulartBR** [comment]
Is there a way to switch these options on ES menu?
It could be a good idea.

**Comment by substring** [comment]
Nope, because it's just a one way change : you still need to edit the recdalbox.conf to switch back to the full mode. I'm not sure it's worth the pain adding it in ES ;)

**Comment by mgoulartBR** [comment]
I see! I asked for this feature because here in Brazil many guys are
renting arcade machines with RPi + Recalbox for house parties, some of them
are facing "issues" with curious people that mess all the configuration ! :)

**Comment by substring** [comment]
Great ! ask them to donate to recalbox, i think we deserve it ;)

**Comment by mgoulartBR** [comment]
I will do it! :)

**Comment by substring** [comment]
closing the issue as afterall it's not really an issue :)
