### ISSUE TITLE
[ENHANCEMENT] samba add veto files for osx

### ISSUE THREAD

**Issue by MaFL2k** [recalbox/recalbox-os#962]
To prevent osx creating its ._* and .DS_Store files everywhere in the share (and confuse emulationstation) add this to the smb.conf share or global section:

`[share]`
`.....`
`veto files = /._*/.DS_Store/`
`delete veto files = yes`

**Comment by substring** [comment]
@MaFL2k sorry for the late reply. Have you tested it ?

**Comment by gbarre** [comment]
Tested with my macbook under El Capitan, it works.

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.0.0-beta5
