### ISSUE TITLE
[4.0.0-beta3][ES] Moonlight doesn't start streaming, but fades back to ES

### ISSUE THREAD

**Issue by hornerr** [recalbox/recalbox-os#964]
### What happened
When trying to start Steam (or any other game) from the Moonlight section Recalbox opens terminal that says this: http://pastebin.com/fVa4jQzk , then fades back to ES to the Moonlight section where I tried to start Steam from. Also my ethernet connection doesn't work sometimes after I reboot Rpi, but I don't know if these things are related.

### What should have happened
Moonlight should have started streaming Steam in Big picture mode.

### Enumerate your devices
Rpi3,
GeForce Experience 2.10.2.40,
Xbox 360 WIRED controller connected to a USB Hub that is connected to the Rpi,
Wireless keyboard connected straight to Rpis own USB port with the keyboards own usb receiver.

### How to reproduce the bug
I honestly have no idea.. I have xboxdrv enabled, but before when it was disabled same thing happened except terminal didn't show, only black screen with recalbox logo and version number and after that it faded back to ES. Everything in the Moonlight wiki page worked perfectly right until I tried to stream Steam.

**Comment by substring** [comment]
there is a bug in the auto configuration of xbox pads concerning the dpad. But you maybe able to cheat somehow. Want me to dig further this ?

**Comment by substring** [comment]
same kind of issue but with an other gamepad : http://pastebin.com/KFY494sC

**Comment by substring** [comment]
@hornerr do you think you can test a fix ? Worked fine for me, but I don't have any xbox pad

**Comment by substring** [comment]
The issue has been confirmed as solved by some people. Will be shipped with beta5. I'm closing

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.0.0-beta5

**Comment by SigmaticMinor** [comment]
Sorry I see this is closed but I am having the exact same issue, even on the latest beta of Recalbox (downloaded today).
I am using a wired XBOX 360 controller with the xbox driver option enabled in config (and the ps3 one disabled). 
When opening the Steam option in Moonlight, big picture starts on PC, and the noises even play on the TV through recal when going side to side with the controller but the screen is the black screen with the recalbox logo.. Any suggestions? 

Sorry to piggyback off this issue, let me know if you'd prefer I open a new one, cheers!!

**Comment by substring** [comment]
Hi,

You'd better ask on the forum. Most probably you are using GFE 3.0.7 and didn't update Recalbox to 4.0.0-beta6

**Comment by SigmaticMinor** [comment]
Hi there, that was fast!! Cheers! I am on a fresh install of 4.0.0-beta6 (set up the pi today) perhaps I need to manually install GFE 3.0.7? I will check out the forums now! Thank you!

**Comment by SigmaticMinor** [comment]
Hi @substring just wanted to update incase I sent anyone on a goosechase with this issue - sorry but you were correct! I had done a fresh install of beta 6 but I didn't realise that when I did an update it prompted me for on the first boot, that it had put my recal back to the last stable build. My apologies! Updating it back to beta again right now :) hope I didn't waste anyones time!

**Comment by substring** [comment]
Haha believe my intuitions ^^
It's solved, that is the good point
