### ISSUE TITLE
[4.0.0-beta3]snes rom error

### ISSUE THREAD

**Issue by chippettone** [recalbox/recalbox-os#967]
### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

**Comment by chippettone** [comment]
What happened: All' avvio di molte rom snes, appare una schermata dove avvisa che il gioco non supporta le periferiche o il pad collegato.

**Comment by rockaddicted** [comment]
English please ;)

**Comment by Laddyacris** [comment]
@chippettone > 
è necessario cambiare l'emulatore per alcuni Rom
>http://blog.recalbox.com/forums/topic/snes-roms-problem/
http://blog.recalbox.com/forums/topic/this-game-is-designed-only-to-play-with-normal-controller/
http://blog.recalbox.com/forums/topic/kirby-super-star-error-on-start/

**Comment by aloula** [comment]
I don't know Italian as well, but it seems this is the same issue I'm facing. In some SNES games like Kirby's Dream Land 3 the controller is being recognized as some mouse peripheral (snapshot attached):

![retroarch-0619-120505](https://cloud.githubusercontent.com/assets/19810431/16176725/979fc80a-35ec-11e6-8197-52de048b0aa3.png)

I can reproduce it easily, please let me know if I can help with something else.

**Comment by Laddyacris** [comment]
Hello
please read this post on forum : http://blog.recalbox.com/forums/topic/snes-roms-problem/
use forum for your replies.

**Comment by Saccomani** [comment]
the page has not found...what is the solution?!

**Comment by Laddyacris** [comment]
Hello, this issue is closed, please read and search in forum.
