### ISSUE TITLE
save top menu dificult som mk2 etc roms

### ISSUE THREAD

**Issue by stargamesrc** [recalbox/recalbox-os#969]
recalbox unsaved dificult credits after leaving it into the configuration making any change of each rom system ex mk2 mk 3 I enter the menu almento the sound volume but after exit and return back all over again someone knows how this resouver

**Comment by Laddyacris** [comment]
Hello
I have not understand your problem. thank you to be more specific.
version recalbox ? emulator ? what game ?
where ? when ?

> ### Before posting issue 
> - For support go to **IRC** or **forum**. Github is only for development issue/improvement 
> - Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
> - Format your title's issue as follow : 
> - [Full Version][optional : KODI|ES|Buidroot|etc] short desc 
> 
> ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 
> 
> ---
> Please fill the following form :
> 
> ### What happened
> 
> ### What should have happened
> 
> ### Enumerate your devices
> 
> ### How to reproduce the bug

**Comment by mgoulartBR** [comment]
I will try to "translate". I think that he is complaning about the fact that all arcade emulators (Mame and FBA) don't save anything (Hi-scores, in-game configs, etc)

**Comment by giuseking** [comment]
Hi! I´ve got the same problems...I need to manage the Control-Inputs from each Emulator without any global Input-Controls from ES. This would be very good, I like this OS very much and i´ve been building months ago a Bartop-Arcade-Machine with gpio Controls. But everytime I change the controls in MAME for example, they got kicked after a system-restart.

Please fix it on the next version. **Thank you for this nearly perfect OS!!**

**Comment by Laddyacris** [comment]
mame2003 will be upgrade with hiscore, in game configs, dipswitches, samples in recalbox 4.1.0
no date to communicate.

How do you check because you have to activate the options in retroarch?

**Comment by giuseking** [comment]
**Thank you, these are very good news!**

I don´t really checked it, it was simply impossbile to configure the MAME inputs with standard D-PAD Controlls from EmulationStation. I really need to configure the inputs Emulator by Emulator with specific Controls, that would be awesome.

**Comment by Laddyacris** [comment]
Sorry but I dont' understand your problem. Because I have no problem to configure controller in ES.
Do you have try this : https://github.com/recalbox/recalbox-os/wiki/How-to-use-custom-config-for-emulators-%28EN%29
You need configure controller in retroarch with remap per core.
RPI2 ? RPI3 ? RPI0 ? RPI1 ?

**Comment by giuseking** [comment]
Thank you! I will try my best....I hope to see the new Update as soon as possible, it would be great to save some Highscores in MAME.

**Comment by stargamesrc** [comment]
mgoulartBR   todos emuladores neo geo mame fba não salva o dificulti e nem opçoes de alterar creditos e idiomas, no caso de super sider kicks 3 neo geo não tem como salvar e mudar para portugues vc ate consegue alterar mas depois ao sair e voltar volta tudo como estava antes isso acontece com todos emuladores arcade , ja  no retropie funciona os saves , mas não gosto do retropie.

**Comment by mgoulartBR** [comment]
startgamesrc,

Esses problemas que voce está relatando são quando voce entra num jogo e configura todo o jogo ou é no Emulationstation (Interface onde escolhe os jogos)?
Se for dentro dos jogos, a próxima versão do Recalbox (4.1.0) esses recursos serão acrescentados no Mame2003 ou seja as pontuações e configurações internas dos jogos serão preservadas.

---------------------//---------------------//---------------------//---------------------//---------------------//

Translating...

These problems, that you are reporting, are in-game or on Emulationstation?
If it's happening in-game, the next Recalbox version (4.1.0) will update mame2003 with this feature.

**Comment by stargamesrc** [comment]
mgoulartBR ,

no propio jogo ex; numero de vidas, idioma, DIFICULDADE  no caso do mk2, mk2, ultimate mk3 o som
fica muito baixo dai entra neste menu do jogo e almenta aperta save to exisite era pra salvar porem não salva  entendeu e isso ? no retropie essa função salva

**Comment by mgoulartBR** [comment]
Então tem que esperar a versão 4.1.0 mesmo

-----------------//--------------

Translating

So it's necessary to wait for new version (4.1.0)

2016-06-22 20:51 GMT-03:00 walter <notifications@github.com>:

**Comment by stargamesrc** [comment]
vc sabe quando vai sair ?

**Comment by mgoulartBR** [comment]
Sem previsão ainda!

**Comment by substring** [comment]
should be ok with https://github.com/recalbox/recalbox-buildroot/pull/430

**Comment by digitalLumberjack** [comment]
Closing this one for now. May reopen one for libretro if needed
