### ISSUE TITLE
[4.0.0-beta3] [OS] Wi-Fi dongles

### ISSUE THREAD

**Issue by j2k15** [recalbox/recalbox-os#971]
Hi there,

I'm using 4.0.0-beta3 on Rasp Pi 2.
I'm opening this ticket to register 2 wi-fi dongles I have which does not work.

I'll putting here the output of lsusb.

1) This one has been bought as "Raspberry friendly" dongle but is not recognized in Recalbox.

Bus 002 Device 003: ID 0a5c:5800 Broadcom Corp. BCM5880 Secure Applications Processor
Bus 002 Device 005: ID 148f:7601 Ralink Technology, Corp. MT7601U Wireless Adapter
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

2) This is a Maxxter.

Bus 002 Device 003: ID 0a5c:5800 Broadcom Corp. BCM5880 Secure Applications Processor
Bus 002 Device 006: ID 0bda:818b Realtek Semiconductor Corp. 
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

FYI, I run the lsusb on my Ubuntu desktop when these dongles are connected.

**Comment by Laddyacris** [comment]
Hello
need archive of this commande for each wifi dongle.

`/recalbox/scripts/recalbox-support.sh`

**Comment by MikaXII** [comment]
Same reflexion as https://github.com/recalbox/recalbox-os/issues/972#issuecomment-227990973

**Comment by substring** [comment]
@j2k15 must be a firmware problem. Have you found them ? Or do you know which one they require ?

**Comment by kangle66** [comment]
Hi Subsritng I downloaded the lst version of recalbox and I can't install my usb wifi 
Bus 002 Device 006: ID 0bda:818b Realtek Semiconductor Corp. 
It's the 8192eu how can I don?
Thanks

**Comment by kangle66** [comment]
Other thing, I tried to copy rtl9182eu_fw.bin in lib/firmware/rtlwifi but I can't.
Access denied. Note that I do this using the racalbox as an usb storage disc with a raspbian os.

**Comment by Laddyacris** [comment]
you need mount partition as write.

`mount -o remount,rw /`

**Comment by kangle66** [comment]
tried as root with /media/pi/root/ but say that is write protected

**Comment by rockaddicted** [comment]
- On your recalbox, not raspbian, get [an ssh access](https://github.com/recalbox/recalbox-os/wiki/Root-access-on-terminal-%28EN%29), then type this command to remount the root partition with write rights : 

`mount -o remount,rw /`

- Once done, [open winscp](https://github.com/recalbox/recalbox-os/wiki/Network-access-with-WinSCP-%28EN%29), and paste your firmware file on your recalbox.

**Comment by kangle66** [comment]
done thanks.
Now when I activate the wifi on recalbox, I have an error 
I configure my ssid and password on recalbox.conf.

**Comment by nadenislamarre** [comment]
i suggest that we support only hardware officially supported by linux and buildroot.
and that we close that issue.

**Comment by nadenislamarre** [comment]
to be restested in 4.1

**Comment by substring** [comment]
Looks like linux-firmware doesn't copy ALL firmwares, as seen with @ian57 yesterday ... Bummer ...
