### ISSUE TITLE
[4.0.0-beta3] [RetroArch] Snes gamepad clone not working

### ISSUE THREAD

**Issue by j2k15** [recalbox/recalbox-os#972]
Dears,

I'd like to report the fact that one of the cheap Snes clone available on the Internet is not recognized in Recalbox.

Here's the output of lsusb on Linux my Ubuntu laptop where it's working fine.

Bus 002 Device 004: ID 0a5c:5800 Broadcom Corp. BCM5880 Secure Applications Processor
Bus 002 Device 003: ID 0079:0011 DragonRise Inc. Gamepad
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by Laddyacris** [comment]
Hello
please use forum for your request.
create archive and upload it.
`/recalbox/scripts/recalbox-support.sh`

**Comment by MikaXII** [comment]
Hi,
Before buy new pad or other devices check their (compatibility (wiki))[https://github.com/recalbox/recalbox-os/wiki/Compatibility-(EN)#pad-controller] before.

**Comment by substring** [comment]
no feedback from @j2k15 
shall I close ?

**Comment by j2k15** [comment]
Hi, this is fixed in 4.0.1.
Sorry for the delay.
