### ISSUE TITLE
Recalbox not working on my Raspberry pi 2 

### ISSUE THREAD

**Issue by Raspber** [recalbox/recalbox-os#974]
### What happened
 just got my pi 2 and frys electronics store. formatted the sd card and transferred the files. Everything loads fine but at the end it freezes when it reaches 100%. any idea why?

### What should have happened
should have started just fine

### How to reproduce the bug

**Comment by MikaXII** [comment]
Hello,

- Which version of recalbox you used ?
- Did you follow this step https://github.com/recalbox/recalbox-os/wiki/Installation-(EN) ?
- Did you use https://www.sdcard.org/downloads/formatter_4/ or [minitool partition wizard ](http://www.partitionwizard.com/free-partition-manager.html) instead Microsoft native format tools ?

### Please use [forum](http://blog.recalbox.com/forums/forum/english/troubleshooting/) or [IRC](https://kiwiirc.com/client/irc.freenode.net/#recalbox) for this kind of questions

**Comment by Raspber** [comment]
I used recalbox 4-beta 3 the most recent release. I followed the exact direction and got it to boot but when it reaches 100% complete it freezes after a while. Not sure if it because the sd card is exactly 8 gb or what is going on?  i am also on mac.

**Comment by substring** [comment]
What sdcard are you using ? Have you tried with a different one ?

**Comment by Raspber** [comment]
i tried with 2 different sd cards...but they happened to be the same brand. Although they are of "good" brand. They are samsung. Please advice if i should go buy a samdisk sd card...not really sure how that would make a difference. Only conclusion i came up with was maybe it ran out of disk space and froze. i tried retropi and that loads up just fine. i want to get recalbox to work.

**Comment by MikaXII** [comment]
Use sandisk we haven't got any problem with this brand. Samsung doesn't work.
https://github.com/recalbox/recalbox-os/wiki/Compatibility-(EN)#sd-cards

**Comment by substring** [comment]
@raspber is your issue solved ? As said : samsung don't work with noobs.

**Comment by substring** [comment]
@Raspber making .img is in the scope for 4.1. Anyway, this a support problem, not an issue, i'm closing. Join the forum fif you want to discuss come more about this :)
