### ISSUE TITLE
New idea: read a game since server external by "SMB"

### ISSUE THREAD

**Issue by benoitchampougny** [recalbox/recalbox-os#975]
Hello word!! lol 

I think that make a directory share on a "smb server" can open a new viewpoin. The big advantage it is the unlimited stockage for emulator, as psx or nintendo64. And Soon "8BITDO" markets a new pad bluetooth N64 style in bluetooth.

What do you think?

sorry for my bad English.

**Comment by MikaXII** [comment]
There are already this kind of feature : 
- https://github.com/recalbox/recalbox-os/wiki/Mount-a-remote-samba-share-on-system-directory-(EN)
- https://github.com/recalbox/recalbox-os/wiki/Use-an-external-usb-storage-device-on-recalbox-(EN)

For 8Bitdo controllers please use the forum. There are french section ;)

**Comment by substring** [comment]
@benoitchampougny the SMB feature has been added a few days ago to 4.1 and is still under development. For the 8bitdo problem, issues are not made for support :) Can you post your subject on the forum or join IRC ?

I'm closing the issue

**Comment by benoitchampougny** [comment]
perfect thank you for the answer. it would be nice to develop this feature in the user interface.

thank you for the development. it is realy nice.

**Comment by substring** [comment]
the UI should come ;)
