### ISSUE TITLE
[4.0.0-beta3][KODI/ES] System reports invalid value for 2,00 BogoMips to the Components 

### ISSUE THREAD

**Issue by LipkeGu** [recalbox/recalbox-os#976]
### What happened
Kodi "Isengard" shows 2.00 Bogomips, on RPI 1 B+

When i Build KODI 15.2 on OEM Buildroot is shows at least 625,xx BogoMips =(
Test Compiling Kodi 16.1 shows also 2.00 BogoMips, 625 on OEM Buildroot
### What should have happened
Showing at least 600 MogoMips
### Enumerate your devices
Raspberry PI 1 B+
### How to reproduce the bug
Install Recalbox-4.0.0.-R3 and look for the BogoMips

**Comment by Northwave** [comment]
What is this important for ? My Pi 3 shows 76.80 BogoMips on Kodi (in Openelec).
I think over 600 BMips are a bit too much.

Also the BogoMips Value is often discussed as "the number of million times per second a processor can do absolutely nothing" src: https://en.wikipedia.org/wiki/BogoMips

**Comment by nadenislamarre** [comment]
who cares ?

**Comment by Northwave** [comment]
I think this issue can be closed, because it is nothing important for. Thats what I wanted to say in my last comment ;)
