### ISSUE TITLE
[Feature Request]Make favorites stand out more

### ISSUE THREAD

**Issue by daaa57150** [recalbox/recalbox-os#977]
As discussed in issue #900, here are some ideas to make the favorite entries stand out a little bit more:
- make the star in another color, or even the complete line
- separate the block of favorites on the top with a little gap, or a line

It would be nice.

**Comment by substring** [comment]
Another idea : add a small logo representing the system of the favourite rom. It's a nice feature when in the favourites system

**Comment by daaa57150** [comment]
@substring that would be great

**Comment by daaa57150** [comment]
Another thing that could be improved:
I have a few emulators with only 5 or 6 games, and when marking one as a favourite, it looks like it's twice in the list. In fact it is twice in the list I know but in that case it's just weird.
I think the favourites should be duplicated at the top only if there is at least a screen full of games.

Maybe with the separation idea it wouldn't look weird though
