### ISSUE TITLE
[4.0.0-beta4][ES] wired xbox one controller problem buttons

### ISSUE THREAD

**Issue by vinzzz81** [recalbox/recalbox-os#980]
### What happened
I have successfully connected 2 wireless xbox one controllers (but through usb cable, so not wireless anymore :) ). When ingame I press for example the A button, hold it, and press another button, lets say RIGHT, the character in game doesnt move sometimes. Seems like somehow the controller isnt able to send all the correct signals, when pressing too much buttons at the same time. If I want to run in mario and jump over a cliff, I hold a button to run, position right and before the cliff press JUMP. Sometimes it doesnt jump...

### What should have happened
When pressing multiple buttons at once, all signals should be sent.

### Enumerate your devices
RPi3
ES 4.0.0-beta4
2x XBOX one wireless controller (wired connection)

### Other
I've bought 2 NES usb controllers and 2 SNES usb controllers today, so I will check if this problem consists with the new controllers as well.

**Comment by substring** [comment]
Hi @vinzzz81 
Thank you for your feedback ! Would you mind telling us which recalbox version you are using ?
XBOX One wired controllers support is rather new, even in the linux kernel, so i guess everything may not work straight OOtB

Can you SSH to your recalbox, run `evtest` and confirm the issue ? Don't forget to `/etc/init.d/S31emulationstation stop`before

**Comment by vinzzz81** [comment]
Hi there, the version is in the topic name. 4.0.0-beta4. I've added it in the post now. Thanks.
Not familiar with the evtest. 
I'll do the test tonight. Just SSH to the recalbox and first  run "/etc/init.d/S31emulationstation stop" and then "evtest" and post the response in here?

**Comment by substring** [comment]
Yes my good sir :)
evtest is quite talktative, consider a pastebin ;) evtest will show the raw inputs with timestamps. Try the key combinations that are supposed to be faulty, evtest will show if it's an OS problem or not.

**Comment by vinzzz81** [comment]
seems like I can't replicate it. evtest shows every press or release of a button. even if I press multiple buttons. Maybe the game can't handle my quick response on the controller ;)
Is there a rom in which I can test this in a better way perhaps?

**Comment by vinzzz81** [comment]
So I've got my NES usb controllers today and tested it with evtest. Evtest shows no lag whatsoever when pressing buttons. But ingame (mario bros 1) there is some lag, making it hard to jump to the top of the ending flag of each level... anyone who can relate to this?
Even if I press right+b+a at the same time, to do a run + jump, evtest records it, even though ingame mario sometimes doesn't jump. What is causing this?

**Comment by nadenislamarre** [comment]
this is often related to the tv.
do you have a game mode on your tv to disable post image threatméts ?

**Comment by vinzzz81** [comment]
my god, why couldn't I think of this myself :) thanks!

**Comment by substring** [comment]
@vinzzz81 shall we close ?

**Comment by vinzzz81** [comment]
yes! :)
