### ISSUE TITLE
No sound in Pitfall Atari2600

### ISSUE THREAD

**Issue by estivalet** [recalbox/recalbox-os#982]
In version 4.0.0 b4 this problem is happening
---
Please fill the following form :

### What happened
No sound in Pitfall Atari2600

### What should have happened
Sound in Pitfall Atari2600 since other tested roms like enduro, riverraid have sound

### Enumerate your devices
raspberry pi 2 

### How to reproduce the bug
play pitfall atari2600

**Comment by estivalet** [comment]
bump can anyone confirm this is a issue?

**Comment by substring** [comment]
@estivalet no need to bump. We'll reply once we tried :)

**Comment by Nachtgarm** [comment]
@substring @estivalet 
I can't confirm this issue on my PI2 with the latest beta. Both Pitfall Games
1. Pitfall! - Pitfall Harry's Jungle Adventure (1982)Md5 `3e90cf23106f2e08b2781e41299de556`
and
2. Pitfall II - Lost Caverns (1983) MD5 `6d842c96d5a01967be9680080dd5be54`

are running just fine with sounds. Pitfall 1 has only sound when someone jumps, hits something or falls.  In Pitfall 2 is a theme playing in the background.

**Comment by estivalet** [comment]
@substring Sorry for the bump.

@Nachtgarm How do I check the MD5 of my rom? I'm not sure if I have the right one. All other Atari 2600 games have sound, but pitfall does not even when jumping or falling

**Comment by Nachtgarm** [comment]
@estivalet ssh into your PI, or just open the console by pressing F4 (followed by Alt+F2) and enter 
`md5sum <romname>.zip`.make sure that your are in the correct directory or enter the full path to the game `md5sum /recalbox/share/roms/atari2600/<romname>.zip` (or .bin).

Pitfall is not part of the No-Intro Sets and I don't use GoodTools

**Comment by estivalet** [comment]
@Nachtgarm Mine has 96b0ec411bd7b8f6a1aea98c2ce8efaa. Tried to download others, and no one match your MD5. All all others have no sound too. How can I have your rom? Or where did you get it from?

**Comment by substring** [comment]
@estivalet no one asks or provides any rom, please mind the basic rules

**Comment by estivalet** [comment]
ok sorry, I will close this issue and try to find a working one. Pitfall II is with sound and working ok, only pitfall I has the sound issue.
