### ISSUE TITLE
[4.0.0-beta4] Password reset when upgrading from 4.0.0-beta3

### ISSUE THREAD

**Issue by valvolt** [recalbox/recalbox-os#984]
### What happened
I upgraded from 4.0.0-beta3 to 4.0.0-beta4 via the EmulationStation GUI
My (changed) root password was reset to the default password

### What should have happened
My root password should not have changed or I should have been warned it would be reset

### Enumerate your devices
Raspberry 3

### How to reproduce the bug
Update a 4.0.0-beta3 recalbox from the Update menu in EmulationStation

**Comment by substring** [comment]
I'm afraid we can't change that behaviour as the whole system is rewritten, including password files

**Comment by valvolt** [comment]
Just as I thought. In this case, a warning message would be nice (either before the upgrade or right after it) as I discovered this fact the (not so) hard way...

**Comment by nadenislamarre** [comment]
in v4.0, you cannot change the root password.
or you did it in a non supported way.
So, that's normal.
root password can be updated starting with 4.1.

**Comment by valvolt** [comment]
I had to first remount the partition in rw mode in order to change the password.
I guess this is the 'non supported way' ? :)

Thanks for the preview on the 4.1 change password feature. In the meantime, having a default non-changeable root password on a device which (namely) stores wifi password in clear text is kinda... dangerous to say the least.

I would then suggest to also clearly mention on the current documentation that the root password cannot be changed by default, can be altered via the 'workaround', and will be reset with each subsequent update?
Either this or turn ssh off by default?

Just trying to be helpful here in getting these boxes secured

**Comment by nadenislamarre** [comment]
Hi,

fill free to update the wiki with your knownledge.
However note that changing the root password is not enough for the security
:

in 4.1, there is a secure mode available from 1 checkbox in the gui doing :
- changing the root password to a randomized value (visible only from the
gui)
- disabling all non secure services (recalbox manager, virtual pads, ...)
- removing the samba anonymous mode (root password required)

note that in 4.1, the wifi password is no more clearly visible in the
configuration file. It is coded with a key which depends on your rpi
(hardware keys + random values).

Nicolas

**Comment by valvolt** [comment]
Thanks nadenislamarre for pointing out that 4.1 will be a big step-up in securing the box.
I will then update the wiki with my 'knowledge' as you propose ;) and keep looking forward to 4.1.
Kudos to you guys for the work you're putting into Recalbox !
