### ISSUE TITLE
[Feature Request] Add dxx-rebirth support

### ISSUE THREAD

**Issue by kraemera** [recalbox/recalbox-os#985]
I would like to play Decent and Descent2 on the recalbox. Therefore add support for DXX-Rebirth.
See [dxx-rebirth.com](http://www.dxx-rebirth.com/).
There seems to be a built for raspian. See https://www.raspberrypi.org/forums/viewtopic.php?t=14108,

**Comment by MikaXII** [comment]
There are already a lot of request like this : 
https://github.com/recalbox/recalbox-os/issues/358
We will add it to the list but it isn't our priority, we have a lot of work in pending

**Comment by kraemera** [comment]
Thanks for the Information. This issue can be closed.
