### ISSUE TITLE
[4.0.0-beta4] [etc] Missing /etc/printcap errors in /var/log/samba/log.smbd

### ISSUE THREAD

**Issue by rootforce** [recalbox/recalbox-os#988]
### What happened

Logfile /var/log/samba/log.smbd gets filled with missing /etc/printcap file errors:

2016/07/15 01:43:16.185424,  0] ../source3/printing/print_standard.c:69(std_pcap_cache_reload)
  Unable to open printcap file /etc/printcap for read!
 
### What should have happened

Please generate/include an "empty" /etc/printcap file into the image, so errors will disappear

**Comment by nadenislamarre** [comment]
Ok.
I'll check this point.

I suggest we just disable printing in the samba.conf file, something similar to :
https://cmorse.org/blog/archives/142

**Comment by substring** [comment]
tested, works

**Comment by substring** [comment]
Solved with https://github.com/recalbox/recalbox-os/releases/tag/4.0.0-beta5
