### ISSUE TITLE
[4.0.0-beta4][Core] recalbox.conf doesn't remember user changes

### ISSUE THREAD

**Issue by krzystke** [recalbox/recalbox-os#990]
Please fill the following form :

### What happened
I neet to change global.videomode because I am plying on my HDMItoVGA adapter and games display incorrectly. After changing to default eveything is fine, but problem is - when I change this setting, it's ALWAYS resetting after rebooting device or even exitting game (I need to change this option between games). It is not possible to change it permanently.

### What should have happened
When I change CEA X HDMI to other option it should stay till I change it again

### Enumerate your devices
Raspberry Pi Zero

### How to reproduce the bug
Change global.videomode in "recalbox_ip"/config/

**Comment by Laddyacris** [comment]
Hello
very strange.
Can you use notepad++ to edit recalbox.conf or vi / nano in ssh ?
if you use windows notepad, you corrupt may be your recalbox.conf

**Comment by krzystke** [comment]
Hello, before I was editing recalbox.conf via browser, but I will try via nano in ssh (I know how to do it) and report it tomorrow.

**Comment by substring** [comment]
@krzystke tomorrow was 23 days ago, can you report ? Or shall we close ?

**Comment by krzystke** [comment]
Hello, I did not change conf file, only changed ratio to 16:9 and itd working grest (on 4:3 screen, I dont understand it but it works). Sorry I was sure that I responded.
