### ISSUE TITLE
[4.0.0-beta4] Freezes, won't start, resets itself

### ISSUE THREAD

**Issue by bmhm** [recalbox/recalbox-os#991]
### What happened
After starting the 4th game or so, the screen got dissorted (stripes).
Going back to the menu, it also had stripes and was barely readable.
Tried to restart it, but the pi did not power on.
After some time it did turn on again, but froze.
Then it didn't turn on again.
When it did turn on after ~12 Minutes, all games and settings were gone.

### What should have happened
Obviously, nothing of the above should have happened.

### Enumerate your devices
Raspberry Pi 1 B
XBox 360 controller, Saitek 360 Controller
USB 2.0 Hub
HDMI Cable
700mA PSU

### How to reproduce the bug
I really don't know... I don't think I did something odd.

**Comment by bmhm** [comment]
BTW I configured it to have 1000 Mhz, which worked fine on retropie, but after the stripes appeared I changed it to 950 Mhz -- didn't change anything.

**Comment by rockaddicted** [comment]
hummm `700mA PSU`
don't you see a rainbow square on the top right of your screen ?

**Comment by bmhm** [comment]
No, actually not. Only when the Pi starts. Also note that only the Pi **B+** has a square, but I do have a **Pi B** (no plus). I'll try with a more powerful PSU then.

**Comment by bmhm** [comment]
A more powerful PSU (2.5A) is on the way. Sorry for leaving this open for so long. I'll report back if it works. I also ordered a USB-Bus-powered USB-HUB, which I can also attatch to the new PSU (which will supply 2x 2500mA). Not easy to find, but they actually do exist. Most cheap PSUs have 2500mA over all ports.

**Comment by bmhm** [comment]
Actually it turned out to be a problem with my sd card.

The SanDisk Ultra 2 8GiB did not work most of the times.
A cheap SanDisk with 4GiB works all the time.
Both are SDHC.

Anyway, can be closed now. Thanks!
