### ISSUE TITLE
[4.0.0-beta4] Unknown platform errors in es_log.txt

### ISSUE THREAD

**Issue by Supernature2k** [recalbox/recalbox-os#992]
Hi All,

Not really a bug but there are many "unknown" platform showing in es_log:

lvl1:     Unknown platform for system "virtualboy" (platform "virtualboy" from list "virtualboy")
lvl1:     Unknown platform for system "gw" (platform "gw" from list "gw")
lvl1:     Unknown platform for system "pcenginecd" (platform "pcenginecd" from list "pcenginecd")
lvl1:     Unknown platform for system "supergrafx" (platform "supergrafx" from list "supergrafx")
lvl1:     Unknown platform for system "lynx" (platform "lynx" from list "lynx")
lvl1:     Unknown platform for system "wswan" (platform "wswan" from list "wswan")
lvl1:     Unknown platform for system "wswanc" (platform "wswanc" from list "wswanc")
lvl1:     Unknown platform for system "prboom" (platform "prboom" from list "prboom")
lvl1:     Unknown platform for system "vectrex" (platform "vectrex" from list "vectrex")
lvl1:     Unknown platform for system "lutro" (platform "lutro" from list "lutro")
lvl1:     Unknown platform for system "cavestory" (platform "cavestory" from list "cavestory")
lvl1:     Unknown platform for system "msx1" (platform "msx1" from list "msx1")
lvl1:     Unknown platform for system "msx2" (platform "msx2" from list "msx2")
lvl1:     Unknown platform for system "odyssey2" (platform "odyssey2" from list "odyssey2")
lvl1:     Unknown platform for system "zx81" (platform "zx81" from list "zx81")
lvl1:     Unknown platform for system "moonlight" (platform "moonlight" from list "moonlight")
lvl1:     Unknown platform for system "imageviewer" (platform "imageviewer" from list "imageviewer")

I think (but not sure) that it could be easily fixed by adding these in those 2 files:

es-app/src/PlatformId.h
es-app/src/PlatformId.cpp

And also change imageviewer to <platform>ignore</platform> in es_systems.cfg

We could also add systems that will be in 4.1? (Amiga, dreamcast and PSP already exist)

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-emulationstation/pull/145
